// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker (interfaces: BackendService)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	matchmaker "github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker"
	player "github.com/horizon-games/OpenSky/matchmaker/lib/player"
	gomock "go.uber.org/mock/gomock"
)

// MockBackendService is a mock of BackendService interface.
type MockBackendService struct {
	ctrl     *gomock.Controller
	recorder *MockBackendServiceMockRecorder
}

// MockBackendServiceMockRecorder is the mock recorder for MockBackendService.
type MockBackendServiceMockRecorder struct {
	mock *MockBackendService
}

// NewMockBackendService creates a new mock instance.
func NewMockBackendService(ctrl *gomock.Controller) *MockBackendService {
	mock := &MockBackendService{ctrl: ctrl}
	mock.recorder = &MockBackendServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackendService) EXPECT() *MockBackendServiceMockRecorder {
	return m.recorder
}

// FindMatchProposals mocks base method.
func (m *MockBackendService) FindMatchProposals(arg0 context.Context, arg1 *matchmaker.FindMatchesRequest) ([]*matchmaker.MatchProposal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMatchProposals", arg0, arg1)
	ret0, _ := ret[0].([]*matchmaker.MatchProposal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMatchProposals indicates an expected call of FindMatchProposals.
func (mr *MockBackendServiceMockRecorder) FindMatchProposals(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMatchProposals", reflect.TypeOf((*MockBackendService)(nil).FindMatchProposals), arg0, arg1)
}

// MatchFound mocks base method.
func (m *MockBackendService) MatchFound(arg0 context.Context, arg1 matchmaker.MatchProcessedData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MatchFound", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// MatchFound indicates an expected call of MatchFound.
func (mr *MockBackendServiceMockRecorder) MatchFound(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MatchFound", reflect.TypeOf((*MockBackendService)(nil).MatchFound), arg0, arg1)
}

// MatchMade mocks base method.
func (m *MockBackendService) MatchMade(arg0 context.Context, arg1 matchmaker.MatchProcessedData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MatchMade", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// MatchMade indicates an expected call of MatchMade.
func (mr *MockBackendServiceMockRecorder) MatchMade(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MatchMade", reflect.TypeOf((*MockBackendService)(nil).MatchMade), arg0, arg1)
}

// ReleasePlayer mocks base method.
func (m *MockBackendService) ReleasePlayer(arg0 context.Context, arg1 *player.Player) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleasePlayer", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleasePlayer indicates an expected call of ReleasePlayer.
func (mr *MockBackendServiceMockRecorder) ReleasePlayer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleasePlayer", reflect.TypeOf((*MockBackendService)(nil).ReleasePlayer), arg0, arg1)
}
