// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker (interfaces: Matching)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	matchmaker "github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker"
	gomock "go.uber.org/mock/gomock"
)

// MockMatching is a mock of Matching interface.
type MockMatching struct {
	ctrl     *gomock.Controller
	recorder *MockMatchingMockRecorder
}

// MockMatchingMockRecorder is the mock recorder for MockMatching.
type MockMatchingMockRecorder struct {
	mock *MockMatching
}

// NewMockMatching creates a new mock instance.
func NewMockMatching(ctrl *gomock.Controller) *MockMatching {
	mock := &MockMatching{ctrl: ctrl}
	mock.recorder = &MockMatchingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatching) EXPECT() *MockMatchingMockRecorder {
	return m.recorder
}

// FindMatchProposals mocks base method.
func (m *MockMatching) FindMatchProposals(arg0 context.Context, arg1 *matchmaker.FindMatchesRequest) ([]*matchmaker.MatchProposal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMatchProposals", arg0, arg1)
	ret0, _ := ret[0].([]*matchmaker.MatchProposal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMatchProposals indicates an expected call of FindMatchProposals.
func (mr *MockMatchingMockRecorder) FindMatchProposals(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMatchProposals", reflect.TypeOf((*MockMatching)(nil).FindMatchProposals), arg0, arg1)
}
