// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/levels/xp (interfaces: Leveller)
//
// Generated by this command:
//
//	mockgen -destination ./mock/leveller.go -package mock . Leveller
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	data "github.com/horizon-games/OpenSky/api/data"
	proto "github.com/horizon-games/OpenSky/api/proto"
	db "github.com/upper/db/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockLeveller is a mock of Leveller interface.
type MockLeveller struct {
	ctrl     *gomock.Controller
	recorder *MockLevellerMockRecorder
	isgomock struct{}
}

// MockLevellerMockRecorder is the mock recorder for MockLeveller.
type MockLevellerMockRecorder struct {
	mock *MockLeveller
}

// NewMockLeveller creates a new mock instance.
func NewMockLeveller(ctrl *gomock.Controller) *MockLeveller {
	mock := &MockLeveller{ctrl: ctrl}
	mock.recorder = &MockLevellerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLeveller) EXPECT() *MockLevellerMockRecorder {
	return m.recorder
}

// LevelUp mocks base method.
func (m *MockLeveller) LevelUp(arg0 db.Session, arg1 *data.Account) ([]*proto.FeedEvent, []*proto.Reward, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LevelUp", arg0, arg1)
	ret0, _ := ret[0].([]*proto.FeedEvent)
	ret1, _ := ret[1].([]*proto.Reward)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// LevelUp indicates an expected call of LevelUp.
func (mr *MockLevellerMockRecorder) LevelUp(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LevelUp", reflect.TypeOf((*MockLeveller)(nil).LevelUp), arg0, arg1)
}
