// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/levels/xp (interfaces: Promoter)
//
// Generated by this command:
//
//	mockgen -destination ./mock/promoter.go -package mock . Promoter
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	data "github.com/horizon-games/OpenSky/api/data"
	proto "github.com/horizon-games/OpenSky/api/proto"
	db "github.com/upper/db/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockPromoter is a mock of Promoter interface.
type MockPromoter struct {
	ctrl     *gomock.Controller
	recorder *MockPromoterMockRecorder
	isgomock struct{}
}

// MockPromoterMockRecorder is the mock recorder for MockPromoter.
type MockPromoterMockRecorder struct {
	mock *MockPromoter
}

// NewMockPromoter creates a new mock instance.
func NewMockPromoter(ctrl *gomock.Controller) *MockPromoter {
	mock := &MockPromoter{ctrl: ctrl}
	mock.recorder = &MockPromoterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromoter) EXPECT() *MockPromoterMockRecorder {
	return m.recorder
}

// PromoteUnranked mocks base method.
func (m *MockPromoter) PromoteUnranked(sess db.Session, account *data.Account, xp uint64) ([]*proto.FeedEvent, []*proto.Reward, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromoteUnranked", sess, account, xp)
	ret0, _ := ret[0].([]*proto.FeedEvent)
	ret1, _ := ret[1].([]*proto.Reward)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// PromoteUnranked indicates an expected call of PromoteUnranked.
func (mr *MockPromoterMockRecorder) PromoteUnranked(sess, account, xp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromoteUnranked", reflect.TypeOf((*MockPromoter)(nil).PromoteUnranked), sess, account, xp)
}
