// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/analytics (interfaces: PolicyChecker)
//
// Generated by this command:
//
//	mockgen -destination ./mock/policy_checker.go -package mock . PolicyChecker
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockPolicyChecker is a mock of PolicyChecker interface.
type MockPolicyChecker struct {
	ctrl     *gomock.Controller
	recorder *MockPolicyCheckerMockRecorder
	isgomock struct{}
}

// MockPolicyCheckerMockRecorder is the mock recorder for MockPolicyChecker.
type MockPolicyCheckerMockRecorder struct {
	mock *MockPolicyChecker
}

// NewMockPolicyChecker creates a new mock instance.
func NewMockPolicyChecker(ctrl *gomock.Controller) *MockPolicyChecker {
	mock := &MockPolicyChecker{ctrl: ctrl}
	mock.recorder = &MockPolicyCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicyChecker) EXPECT() *MockPolicyCheckerMockRecorder {
	return m.recorder
}

// GetAnalyticsPolicyByAccountID mocks base method.
func (m *MockPolicyChecker) GetAnalyticsPolicyByAccountID(accountID proto.AccountID) (*proto.Account, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnalyticsPolicyByAccountID", accountID)
	ret0, _ := ret[0].(*proto.Account)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAnalyticsPolicyByAccountID indicates an expected call of GetAnalyticsPolicyByAccountID.
func (mr *MockPolicyCheckerMockRecorder) GetAnalyticsPolicyByAccountID(accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnalyticsPolicyByAccountID", reflect.TypeOf((*MockPolicyChecker)(nil).GetAnalyticsPolicyByAccountID), accountID)
}
