// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/analytics (interfaces: Tracker)
//
// Generated by this command:
//
//	mockgen -destination ./mock/tracker.go -package mock . Tracker
//

// Package mock is a generated GoMock package.
package mock

import (
	http "net/http"
	reflect "reflect"

	data "github.com/horizon-games/OpenSky/api/data"
	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockTracker is a mock of Tracker interface.
type MockTracker struct {
	ctrl     *gomock.Controller
	recorder *MockTrackerMockRecorder
	isgomock struct{}
}

// MockTrackerMockRecorder is the mock recorder for MockTracker.
type MockTrackerMockRecorder struct {
	mock *MockTracker
}

// NewMockTracker creates a new mock instance.
func NewMockTracker(ctrl *gomock.Controller) *MockTracker {
	mock := &MockTracker{ctrl: ctrl}
	mock.recorder = &MockTrackerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTracker) EXPECT() *MockTrackerMockRecorder {
	return m.recorder
}

// TrackAccountBanning mocks base method.
func (m *MockTracker) TrackAccountBanning(r *http.Request, accountID proto.AccountID, accountStatus proto.AccountStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackAccountBanning", r, accountID, accountStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackAccountBanning indicates an expected call of TrackAccountBanning.
func (mr *MockTrackerMockRecorder) TrackAccountBanning(r, accountID, accountStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackAccountBanning", reflect.TypeOf((*MockTracker)(nil).TrackAccountBanning), r, accountID, accountStatus)
}

// TrackAccountCreated mocks base method.
func (m *MockTracker) TrackAccountCreated(r *http.Request, accountID proto.AccountID, deviceProperties *proto.DeviceProperties) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackAccountCreated", r, accountID, deviceProperties)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackAccountCreated indicates an expected call of TrackAccountCreated.
func (mr *MockTrackerMockRecorder) TrackAccountCreated(r, accountID, deviceProperties any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackAccountCreated", reflect.TypeOf((*MockTracker)(nil).TrackAccountCreated), r, accountID, deviceProperties)
}

// TrackCompletedQuestClaim mocks base method.
func (m *MockTracker) TrackCompletedQuestClaim(r *http.Request, accountID proto.AccountID, assignment *data.QuestAssignment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackCompletedQuestClaim", r, accountID, assignment)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackCompletedQuestClaim indicates an expected call of TrackCompletedQuestClaim.
func (mr *MockTrackerMockRecorder) TrackCompletedQuestClaim(r, accountID, assignment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackCompletedQuestClaim", reflect.TypeOf((*MockTracker)(nil).TrackCompletedQuestClaim), r, accountID, assignment)
}

// TrackConquestPointsAwarded mocks base method.
func (m *MockTracker) TrackConquestPointsAwarded(r *http.Request, accountID proto.AccountID, treasureProgress *data.ConquestV2TreasureProgress, matchPoints, silverCardPoints, goldCardPoints, heroSkinPoints uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackConquestPointsAwarded", r, accountID, treasureProgress, matchPoints, silverCardPoints, goldCardPoints, heroSkinPoints)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackConquestPointsAwarded indicates an expected call of TrackConquestPointsAwarded.
func (mr *MockTrackerMockRecorder) TrackConquestPointsAwarded(r, accountID, treasureProgress, matchPoints, silverCardPoints, goldCardPoints, heroSkinPoints any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackConquestPointsAwarded", reflect.TypeOf((*MockTracker)(nil).TrackConquestPointsAwarded), r, accountID, treasureProgress, matchPoints, silverCardPoints, goldCardPoints, heroSkinPoints)
}

// TrackEndMatch mocks base method.
func (m *MockTracker) TrackEndMatch(r *http.Request, match *data.Match, matchEnd *proto.MatchEndRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackEndMatch", r, match, matchEnd)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackEndMatch indicates an expected call of TrackEndMatch.
func (mr *MockTrackerMockRecorder) TrackEndMatch(r, match, matchEnd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackEndMatch", reflect.TypeOf((*MockTracker)(nil).TrackEndMatch), r, match, matchEnd)
}

// TrackItemPurchase mocks base method.
func (m *MockTracker) TrackItemPurchase(r *http.Request, itemPurchase *proto.AnalyticsItemPurchase) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackItemPurchase", r, itemPurchase)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackItemPurchase indicates an expected call of TrackItemPurchase.
func (mr *MockTrackerMockRecorder) TrackItemPurchase(r, itemPurchase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackItemPurchase", reflect.TypeOf((*MockTracker)(nil).TrackItemPurchase), r, itemPurchase)
}

// TrackLevelUps mocks base method.
func (m *MockTracker) TrackLevelUps(r *http.Request, accountID proto.AccountID, startLevel, endLevel uint16, gamesPlayed uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackLevelUps", r, accountID, startLevel, endLevel, gamesPlayed)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackLevelUps indicates an expected call of TrackLevelUps.
func (mr *MockTrackerMockRecorder) TrackLevelUps(r, accountID, startLevel, endLevel, gamesPlayed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackLevelUps", reflect.TypeOf((*MockTracker)(nil).TrackLevelUps), r, accountID, startLevel, endLevel, gamesPlayed)
}

// TrackQuestCompletion mocks base method.
func (m *MockTracker) TrackQuestCompletion(r *http.Request, accountID proto.AccountID, assignment *data.QuestAssignment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackQuestCompletion", r, accountID, assignment)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackQuestCompletion indicates an expected call of TrackQuestCompletion.
func (mr *MockTrackerMockRecorder) TrackQuestCompletion(r, accountID, assignment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackQuestCompletion", reflect.TypeOf((*MockTracker)(nil).TrackQuestCompletion), r, accountID, assignment)
}

// TrackRerollQuest mocks base method.
func (m *MockTracker) TrackRerollQuest(r *http.Request, accountID proto.AccountID, assignment *data.QuestAssignment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackRerollQuest", r, accountID, assignment)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackRerollQuest indicates an expected call of TrackRerollQuest.
func (mr *MockTrackerMockRecorder) TrackRerollQuest(r, accountID, assignment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackRerollQuest", reflect.TypeOf((*MockTracker)(nil).TrackRerollQuest), r, accountID, assignment)
}

// TrackRewardMatch mocks base method.
func (m *MockTracker) TrackRewardMatch(r *http.Request, rewards []*proto.Reward, matchEndRequest *proto.MatchEndRequest, match *data.Match) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackRewardMatch", r, rewards, matchEndRequest, match)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackRewardMatch indicates an expected call of TrackRewardMatch.
func (mr *MockTrackerMockRecorder) TrackRewardMatch(r, rewards, matchEndRequest, match any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackRewardMatch", reflect.TypeOf((*MockTracker)(nil).TrackRewardMatch), r, rewards, matchEndRequest, match)
}

// TrackSkypassRewardsClaim mocks base method.
func (m *MockTracker) TrackSkypassRewardsClaim(r *http.Request, accountID proto.AccountID, rewards []*proto.Reward) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackSkypassRewardsClaim", r, accountID, rewards)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackSkypassRewardsClaim indicates an expected call of TrackSkypassRewardsClaim.
func (mr *MockTrackerMockRecorder) TrackSkypassRewardsClaim(r, accountID, rewards any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackSkypassRewardsClaim", reflect.TypeOf((*MockTracker)(nil).TrackSkypassRewardsClaim), r, accountID, rewards)
}

// TrackStartMatch mocks base method.
func (m *MockTracker) TrackStartMatch(r *http.Request, match *proto.Match, matchStartRequest *proto.MatchStartRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackStartMatch", r, match, matchStartRequest)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackStartMatch indicates an expected call of TrackStartMatch.
func (mr *MockTrackerMockRecorder) TrackStartMatch(r, match, matchStartRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackStartMatch", reflect.TypeOf((*MockTracker)(nil).TrackStartMatch), r, match, matchStartRequest)
}

// TrackTreasureRewards mocks base method.
func (m *MockTracker) TrackTreasureRewards(r *http.Request, accountID proto.AccountID, treasureProgress *data.ConquestV2TreasureProgress, usdcAmount float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackTreasureRewards", r, accountID, treasureProgress, usdcAmount)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackTreasureRewards indicates an expected call of TrackTreasureRewards.
func (mr *MockTrackerMockRecorder) TrackTreasureRewards(r, accountID, treasureProgress, usdcAmount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackTreasureRewards", reflect.TypeOf((*MockTracker)(nil).TrackTreasureRewards), r, accountID, treasureProgress, usdcAmount)
}

// TrackTutorialEnd mocks base method.
func (m *MockTracker) TrackTutorialEnd(r *http.Request, accountID proto.AccountID, levels []int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackTutorialEnd", r, accountID, levels)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackTutorialEnd indicates an expected call of TrackTutorialEnd.
func (mr *MockTrackerMockRecorder) TrackTutorialEnd(r, accountID, levels any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackTutorialEnd", reflect.TypeOf((*MockTracker)(nil).TrackTutorialEnd), r, accountID, levels)
}

// TrackTutorialStatus mocks base method.
func (m *MockTracker) TrackTutorialStatus(r *http.Request, accountID proto.AccountID, match *data.Match) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackTutorialStatus", r, accountID, match)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackTutorialStatus indicates an expected call of TrackTutorialStatus.
func (mr *MockTrackerMockRecorder) TrackTutorialStatus(r, accountID, match any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackTutorialStatus", reflect.TypeOf((*MockTracker)(nil).TrackTutorialStatus), r, accountID, match)
}
