// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/director (interfaces: MatchHandler)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMatchHandler is a mock of MatchHandler interface.
type MockMatchHandler struct {
	ctrl     *gomock.Controller
	recorder *MockMatchHandlerMockRecorder
}

// MockMatchHandlerMockRecorder is the mock recorder for MockMatchHandler.
type MockMatchHandlerMockRecorder struct {
	mock *MockMatchHandler
}

// NewMockMatchHandler creates a new mock instance.
func NewMockMatchHandler(ctrl *gomock.Controller) *MockMatchHandler {
	mock := &MockMatchHandler{ctrl: ctrl}
	mock.recorder = &MockMatchHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchHandler) EXPECT() *MockMatchHandlerMockRecorder {
	return m.recorder
}

// HandleMatches mocks base method.
func (m *MockMatchHandler) HandleMatches(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleMatches", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleMatches indicates an expected call of HandleMatches.
func (mr *MockMatchHandlerMockRecorder) HandleMatches(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleMatches", reflect.TypeOf((*MockMatchHandler)(nil).HandleMatches), arg0)
}
