// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/conquest (interfaces: MetricsCollector)
//
// Generated by this command:
//
//	mockgen -destination ./mock/metrics_collector.go -package mock . MetricsCollector
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockMetricsCollector is a mock of MetricsCollector interface.
type MockMetricsCollector struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsCollectorMockRecorder
	isgomock struct{}
}

// MockMetricsCollectorMockRecorder is the mock recorder for MockMetricsCollector.
type MockMetricsCollectorMockRecorder struct {
	mock *MockMetricsCollector
}

// NewMockMetricsCollector creates a new mock instance.
func NewMockMetricsCollector(ctrl *gomock.Controller) *MockMetricsCollector {
	mock := &MockMetricsCollector{ctrl: ctrl}
	mock.recorder = &MockMetricsCollectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsCollector) EXPECT() *MockMetricsCollectorMockRecorder {
	return m.recorder
}

// TrackConquestCompleted mocks base method.
func (m *MockMetricsCollector) TrackConquestCompleted() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackConquestCompleted")
}

// TrackConquestCompleted indicates an expected call of TrackConquestCompleted.
func (mr *MockMetricsCollectorMockRecorder) TrackConquestCompleted() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackConquestCompleted", reflect.TypeOf((*MockMetricsCollector)(nil).TrackConquestCompleted))
}

// TrackConquestEntered mocks base method.
func (m *MockMetricsCollector) TrackConquestEntered(arg0 proto.Hero) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackConquestEntered", arg0)
}

// TrackConquestEntered indicates an expected call of TrackConquestEntered.
func (mr *MockMetricsCollectorMockRecorder) TrackConquestEntered(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackConquestEntered", reflect.TypeOf((*MockMetricsCollector)(nil).TrackConquestEntered), arg0)
}

// TrackConquestExited mocks base method.
func (m *MockMetricsCollector) TrackConquestExited(wins int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackConquestExited", wins)
}

// TrackConquestExited indicates an expected call of TrackConquestExited.
func (mr *MockMetricsCollectorMockRecorder) TrackConquestExited(wins any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackConquestExited", reflect.TypeOf((*MockMetricsCollector)(nil).TrackConquestExited), wins)
}
