// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/conquest (interfaces: ScoreCalculator)
//
// Generated by this command:
//
//	mockgen -destination ./mock/score_calculator.go -package mock . ScoreCalculator
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	data "github.com/horizon-games/OpenSky/api/data"
	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockScoreCalculator is a mock of ScoreCalculator interface.
type MockScoreCalculator struct {
	ctrl     *gomock.Controller
	recorder *MockScoreCalculatorMockRecorder
	isgomock struct{}
}

// MockScoreCalculatorMockRecorder is the mock recorder for MockScoreCalculator.
type MockScoreCalculatorMockRecorder struct {
	mock *MockScoreCalculator
}

// NewMockScoreCalculator creates a new mock instance.
func NewMockScoreCalculator(ctrl *gomock.Controller) *MockScoreCalculator {
	mock := &MockScoreCalculator{ctrl: ctrl}
	mock.recorder = &MockScoreCalculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScoreCalculator) EXPECT() *MockScoreCalculatorMockRecorder {
	return m.recorder
}

// FromPastMatches mocks base method.
func (m *MockScoreCalculator) FromPastMatches(arg0 []*data.Match, arg1 proto.AccountID) int32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FromPastMatches", arg0, arg1)
	ret0, _ := ret[0].(int32)
	return ret0
}

// FromPastMatches indicates an expected call of FromPastMatches.
func (mr *MockScoreCalculatorMockRecorder) FromPastMatches(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FromPastMatches", reflect.TypeOf((*MockScoreCalculator)(nil).FromPastMatches), arg0, arg1)
}
