// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/notification/onetimenotification (interfaces: AccountValidator)
//
// Generated by this command:
//
//	mockgen -destination ./mock/account_validator.go -package mock . AccountValidator
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	data "github.com/horizon-games/OpenSky/api/data"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountValidator is a mock of AccountValidator interface.
type MockAccountValidator struct {
	ctrl     *gomock.Controller
	recorder *MockAccountValidatorMockRecorder
	isgomock struct{}
}

// MockAccountValidatorMockRecorder is the mock recorder for MockAccountValidator.
type MockAccountValidatorMockRecorder struct {
	mock *MockAccountValidator
}

// NewMockAccountValidator creates a new mock instance.
func NewMockAccountValidator(ctrl *gomock.Controller) *MockAccountValidator {
	mock := &MockAccountValidator{ctrl: ctrl}
	mock.recorder = &MockAccountValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountValidator) EXPECT() *MockAccountValidatorMockRecorder {
	return m.recorder
}

// IsValid mocks base method.
func (m *MockAccountValidator) IsValid(rules []byte, account *data.Account) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValid", rules, account)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsValid indicates an expected call of IsValid.
func (mr *MockAccountValidatorMockRecorder) IsValid(rules, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValid", reflect.TypeOf((*MockAccountValidator)(nil).IsValid), rules, account)
}
