use design_data_loader::{filesystem_to_json, get_fs_entries_of_folder_recursive, store_dir};
use inflector::Inflector;
use lazy_static::lazy_static;
use regex::Regex;
use serde::de;
use serde::{Deserialize, Deserializer};
use serde_json::Value;
use std::path::PathBuf;
use std::{
  env,
  error::Error,
  fs::{read_dir, File},
  io::{Read, Write},
  path::Path,
  process,
};
use syn::visit::Visit;

const VERSION_MODULE: &str = "arcadeum_generated_version.rs";
const VERSION_IDENTIFIER: &str = "ARCADEUM_GENERATED_VERSION";

lazy_static! {
  static ref FILENAME_REGEX: Regex = Regex::new(r"c(\d{1,6})\.rs").unwrap();
  static ref TRIGGER_REGEX: Regex = Regex::new(r"\{trigger:(.*?)\}").unwrap();
}

fn main() {
  if let Err(err) = generate_lib() {
    println!("error generating card library: {}", err);
    process::exit(1);
  }

  println!("cargo:rerun-if-changed=src/");
  println!("cargo:rerun-if-changed=../../../../design-data/raw/sheets/card/");

  let module = Path::new(&env::var("OUT_DIR").unwrap()).join(VERSION_MODULE);

  let sheet_cards = get_sheet_cards_dir();
  let version_sources = [
    "Cargo.toml",
    "build.rs",
    "build_components",
    sheet_cards.to_str().unwrap(),
    "src",
  ];

  if let Err(err) =
    card_movement_simulator::arcadeum::tag(module, VERSION_IDENTIFIER, version_sources.iter())
  {
    println!("error versioning sources: {}", err);
    process::exit(1);
  }
}

fn get_active_cardlist() -> Result<Vec<SheetCard>, String> {
  let data_dir = get_sheet_cards_dir();
  let entries = get_fs_entries_of_folder_recursive(data_dir.to_str().unwrap().to_string());
  let json = filesystem_to_json(entries);
  json
    .as_object()
    .unwrap()
    .into_iter()
    .map(|(id, card)| {
      let mut combined_json_val = card.clone();
      combined_json_val["id"] = Value::Number(
        id.parse()
          .map_err(|e| format!("Failed to parse card ID from number: {id} {e:?}"))?,
      );
      let obj = card.as_object().ok_or("card is not an object!")?;
      if !obj.contains_key("power") {
        combined_json_val["power"] = Value::Number(0.into());
      }
      if !obj.contains_key("health") {
        combined_json_val["health"] = Value::Number(0.into());
      }
      let card: SheetCard = serde_json::from_value(combined_json_val)
        .map_err(|e| format!("Error while parsing card {id}: {e:?}"))?;
      Ok(card)
    })
    .collect()
}

fn get_sheet_cards_dir() -> PathBuf {
  let mut data_dir = store_dir();
  data_dir.push("sheets");
  data_dir.push("cards");
  data_dir
}

struct MacroVisitor {
  serializable_filter_enum_members: String,
  serializable_filter_enum_mappings: String,
}
impl MacroVisitor {
  fn push_serializable_filter(&mut self, enum_arm: &str, closure: &str) {
    self
      .serializable_filter_enum_members
      .push_str(&format!("{}, \n", enum_arm));
    self.serializable_filter_enum_mappings.push_str(&format!(
      "Self::{} => {{\nlet func: fn(&CardInfo<SkyWeaver>) -> bool = {}; func(card)\n}}, \n",
      enum_arm, closure
    ));
  }
}

impl<'ast> syn::visit::Visit<'ast> for MacroVisitor {
  fn visit_macro(&mut self, node: &'ast syn::Macro) {
    if node.path.segments.len() == 1 && node.path.segments[0].ident == "serializable_filter" {
      // take until first comma - that's the enum arm.
      // take the rest - that's the closure for the effect.
      let mut enum_arm = String::new();
      let mut closure = String::new();
      let mut done_enum = false;
      let mut seen_colons = false;
      for item in node.tokens.clone() {
        let s = item.to_string();
        if !done_enum {
          if s == "," {
            done_enum = true;
          } else if s == ":" {
            seen_colons = true
          } else if seen_colons {
            enum_arm.push_str(&s);
          }
        } else {
          closure.push_str(&s);
        }
      }
      self.push_serializable_filter(&enum_arm, &closure)
    }
    // Delegate to the default impl to visit any nested functions.
    syn::visit::visit_macro(self, node);
  }
}

fn generate_lib() -> Result<(), Box<dyn Error>> {
  let template_string = read_template_file()?;
  let missing_counter = 0;
  let mut ser_base_card_enum = String::new();
  let mut de_base_card_enum = String::new();
  let mut ts_base_card_enum = String::new();

  let mut base_card_enum = String::new();

  let mut seasons = String::new();
  let mut base_card_consts = String::new();
  let mut base_card_instances = String::new();
  let mut base_card_try_from = String::new();
  let mut base_card_to_u32 = String::new();

  let mut attached_spells = String::new();
  let mut effects = String::new();

  let mut card_effect_mods = "// WARNING: THIS FILE IS AUTO-GENERATED BY build.rs. ANY CHANGES WILL BE OVERWRITTEN ON BUILD.\npub mod effect_helpers;\npub mod hero;\n".to_string();

  let mut card_effect_enum_members = String::new();
  let mut card_effect_enum_mappings = String::new();
  let mut card_effect_source_mappings = String::new();
  let mut enchants_by_name = String::new();

  let mut attack_restriction_enum_members = String::new();
  let mut attack_restriction_enum_mappings = String::new();

  let paths = read_dir("./src/card_effects/").unwrap().map(|u| u.unwrap());
  let cards = get_active_cardlist()?;
  let mut card_effect_paths: Vec<_> = paths
    .filter(|path| {
      let name = path.file_name().into_string().unwrap();
      match name.as_ref() {
        "mod.rs" | "hero.rs" | "effect_helpers.rs" => true,
        name => {
          let id = FILENAME_REGEX
            .captures_iter(name)
            .map(|cap| cap[1].to_string())
            .next();

          if let Some(id) = id {
            if !cards.iter().any(|c| format!("{}", c.id) == id) {
              println!(
                "cargo:warning={} exists, but isn't in the card library.",
                name
              );
            }
            return true;
          }
          panic!("Unexpected file in ./src/card_effects/ {:?}", name);
        }
      }
    })
    .collect();

  // Make sure things happen in a stable order!
  // This should stay consistent across builds with the same set of source files.
  card_effect_paths.sort_by_key(|e| e.file_name());

  let mut macro_visitor = MacroVisitor {
    serializable_filter_enum_mappings: String::new(),
    serializable_filter_enum_members: String::new(),
  };

  let ids_with_effects: Vec<_> = card_effect_paths
    .iter()
    .filter_map(|p| {
      FILENAME_REGEX
        .captures_iter(&p.file_name().into_string().unwrap())
        .map(|cap| cap[1].to_string())
        .next()
    })
    .collect();
  for card_effect_file in card_effect_paths {
    let mut file = File::open(card_effect_file.path()).expect("Unable to open file");
    let filename = &card_effect_file
      .path()
      .file_name()
      .unwrap()
      .to_str()
      .unwrap()
      .to_string();
    let id = FILENAME_REGEX
      .captures_iter(filename)
      .map(|cap| cap[1].to_string())
      .next()
      .unwrap_or_else(|| filename.to_string().replace(".rs", ""));

    let mut src = String::new();
    file
      .read_to_string(&mut src)
      .unwrap_or_else(|_| panic!("Unable to read file {:?}", card_effect_file.path()));

    let syntax = syn::parse_file(&src)
      .unwrap_or_else(|_| panic!("Unable to parse file {:?}", card_effect_file.path()));
    for item in syntax.items {
      macro_visitor.visit_item(&item);

      if let syn::Item::Macro(syn::ItemMacro {
        mac:
          syn::Macro {
            path: syn::Path { segments, .. },
            tokens,
            ..
          },
        ..
      }) = item
      {
        // Magic macro attachable_effect!
        if segments.len() == 1 && segments[0].ident == "attachable_effect" {
          // take until first comma - that's the enum arm.
          // take the next ident - that's the name of the lazy static for the effect.
          let mut enum_arm = String::new();
          let mut static_name = String::new();
          let mut done_enum = false;
          for item in tokens {
            let s = item.to_string();
            if s == ";" {
              continue;
            } else if !done_enum {
              if s == "struct" {
                continue;
              } else if s == "," {
                done_enum = true;
              } else {
                enum_arm.push_str(&s);
              }
            } else if s == "," {
              break;
            } else {
              static_name.push_str(&s);
            }
          }
          let enum_arm_char_type = if enum_arm.contains('{') {
            Some('{')
          } else if enum_arm.contains('(') {
            Some('(')
          } else {
            None
          };
          let enum_arm_pattern = if let Some(enum_arm_char_type) = enum_arm_char_type {
            let pos = enum_arm
              .chars()
              .position(|p| p == enum_arm_char_type)
              .unwrap();
            format!(
              "{} {}..{}",
              &enum_arm[..pos],
              enum_arm_char_type,
              if enum_arm_char_type == '{' { '}' } else { ')' }
            )
          } else {
            enum_arm.clone()
          };
          card_effect_enum_members.push_str(&format!("{}, \n", enum_arm));
          card_effect_enum_mappings.push_str(&format!(
            "Self::{enum_arm_pattern} => &card_effects::{id}::{static_name}, \n",
            enum_arm_pattern = enum_arm_pattern,
            id = if id == "hero" {
              "hero".to_owned()
            } else {
              format!("c{}", id)
            },
            static_name = static_name
          ));
          card_effect_source_mappings.push_str(&format!(
            "Self::{} => BaseCard::{}, \n",
            enum_arm_pattern,
            if id == "hero" {
              "Hero".to_owned()
            } else {
              format!("C{}", id)
            }
          ));
        }
        // Magic macro attack_restriction!
        else if segments.len() == 1 && segments[0].ident == "attack_restriction" {
          // take until first comma - that's the enum arm.
          // take the rest - that's the closure for the effect.
          let mut enum_arm = String::new();
          let mut closure = String::new();
          let mut done_enum = false;
          for item in tokens {
            let s = item.to_string();
            if !done_enum {
              if s == "," {
                done_enum = true;
              } else {
                enum_arm.push_str(&s);
              }
            } else {
              closure.push_str(&s);
            }
          }
          attack_restriction_enum_members.push_str(&format!("{}, \n", enum_arm));
          attack_restriction_enum_mappings.push_str(&format!(
            "Self::{} => ({})(defender, defender_field), \n",
            enum_arm, closure
          ));
        }
      }
    }
  }

  for sheet_card in cards.clone() {
    if sheet_card.r#type != "Type::Unit"
      && (sheet_card.traits.contains(&"Trait::Stealth".to_string())
        || sheet_card.traits.contains(&"Trait::Guard".to_string()))
    {
      panic!("C{} isn't a unit and has Guard/Stealth!", sheet_card.id);
    }

    let has_effect = ids_with_effects.contains(&format!("{}", sheet_card.id));

    base_card_enum += &format!("C{}, ", sheet_card.id);
    ts_base_card_enum += &format!(" | \"{}\"", sheet_card.id);
    ser_base_card_enum += &format!("BaseCard::C{id} => \"{id}\", ", id = sheet_card.id);
    de_base_card_enum += &format!("\"{id}\" => BaseCard::C{id}, ", id = sheet_card.id);
    seasons += &format!(
      "BaseCard::C{id} => {season},\n",
      id = sheet_card.id,
      season = sheet_card.season
    );
    base_card_consts += &format!(
      r#"
        lazy_static! {{
          pub static ref C{id}: CardAttributes = {{
            CardAttributes {{
              power: {power}.into(),
              cost: {cost}.into(),
              element: {element},
              health: {health}.into(),
              prism: {prism},
              r#type: {type},
              traits: indexset![{traits}],
              can_be_played: {can_be_played},
              effects: vec![{effects}],
              is_x_cost: {is_x_cost},
              charges: {start_charges},
              max_charges: {max_charges},
              counters: {start_counters},
              max_counters: {max_counters},
              per_turn: {per_turn},
              ..Default::default()
            }}
          }};
        }}
      "#,
      id = sheet_card.id,
      power = sheet_card.power.to_number(),
      cost = sheet_card.cost.to_number(),
      element = sheet_card.element,
      start_charges = sheet_card
        .start_charges
        .map_or("None".to_string(), |c| format!("Some({c}.into())")),
      max_charges = sheet_card
        .max_charges
        .map_or("None".to_string(), |c| format!("Some({c}.into())")),
      start_counters = sheet_card
        .start_counters
        .map_or("None".to_string(), |c| format!("Some({c}.into())")),
      max_counters = sheet_card
        .max_counters
        .map_or("None".to_string(), |c| format!("Some({c}.into())")),
      per_turn = sheet_card
        .per_turn
        .map_or("None".to_string(), |c| format!("Some({c}.into())")),
      health = sheet_card.health.to_number(),
      prism = sheet_card.prism,
      r#type = sheet_card.r#type,
      traits = sheet_card.traits.join(","),
      can_be_played = sheet_card.cost != StringyCardValue::No,
      is_x_cost = sheet_card.cost == StringyCardValue::X,
      effects = if has_effect {
        format!("CardEffect::Intrinsic(BaseCard::C{})", sheet_card.id)
      } else {
        "".to_string()
      }
    );
    base_card_instances += &format!(
      "BaseCard::C{id} => &*base_card::C{id}, \n",
      id = sheet_card.id
    );

    attached_spells += &format!(
      "BaseCard::C{id} => {spell},",
      id = sheet_card.id,
      spell = sheet_card
        .attached_spell
        .map_or("None".to_string(), |s_id| format!(
          "Some(BaseCard::C{})",
          s_id
        ))
    );

    if has_effect {
      effects += &format!(
        "BaseCard::C{id} => &*card_effects::c{id}::EFFECT,\n",
        id = sheet_card.id,
      );
      card_effect_mods += &format!("pub mod c{id};\n", id = sheet_card.id);
    }

    base_card_try_from += &format!("{id} => Ok(BaseCard::C{id}),\n", id = sheet_card.id);

    base_card_to_u32 += &format!("BaseCard::C{id} => {id},\n", id = sheet_card.id);

    if sheet_card.r#type == "Type::Enchant" {
      let name = sheet_card.name.to_screaming_snake_case();
      enchants_by_name += &format!(
        "pub const {name}: BaseCard = BaseCard::C{id};\n",
        name = name,
        id = sheet_card.id
      );
    }
  }
  let output = template_string
    .replace("{{enumeration}}", &base_card_enum)
    .replace("{{ts_enumeration}}", &ts_base_card_enum)
    .replace("{{serialize_enumeration}}", &ser_base_card_enum)
    .replace("{{deserialize_enumeration}}", &de_base_card_enum)
    .replace("{{consts}}", &base_card_consts)
    .replace("{{instances}}", &base_card_instances)
    .replace("{{try_from}}", &base_card_try_from)
    .replace("{{to_u32}}", &base_card_to_u32)
    .replace("{{attached_spells}}", &attached_spells)
    .replace("{{effects}}", &effects)
    .replace("{{card_effect_enum_members}}", &card_effect_enum_members)
    .replace("{{card_effect_enum_mappings}}", &card_effect_enum_mappings)
    .replace(
      "{{attack_restriction_enum_members}}",
      &attack_restriction_enum_members,
    )
    .replace(
      "{{attack_restriction_enum_mappings}}",
      &attack_restriction_enum_mappings,
    )
    .replace(
      "{{card_effect_source_mappings}}",
      &card_effect_source_mappings,
    )
    .replace("{{enchants_by_name}}", &enchants_by_name)
    .replace(
      "{{serializable_filter_enum_members}}",
      &macro_visitor.serializable_filter_enum_members,
    )
    .replace(
      "{{serializable_filter_enum_mappings}}",
      &macro_visitor.serializable_filter_enum_mappings,
    )
    .replace("{{seasons}}", &seasons);

  let out_dir = env::var("OUT_DIR").unwrap();
  let dest_path = Path::new(&out_dir).join("card_library.rs");
  let mut f = File::create(&dest_path).unwrap();
  f.write_all(output.as_bytes())?;

  let mods_dest_path = Path::new("./src/card_effects/").join("mod.rs");
  let mut f = File::create(&mods_dest_path).unwrap();
  f.write_all(card_effect_mods.as_bytes())?;

  if missing_counter > 0 {
    println!(
      "cargo:warning=Keep coding! Only {} cards to go.",
      missing_counter
    );
  }
  for card in cards {
    let has_text = !card.text.is_empty();
    let has_effect_file = ids_with_effects
      .iter()
      .any(|e| &format!("{}", card.id) == e);
    match (has_text, has_effect_file) {
      (true, false) => {
        println!(
          "cargo:warning=Card {id} has text, but has no file {id}.rs",
          id = card.id
        );
      }
      (false, true) => {
        println!(
          "cargo:warning=Card {id} has no text, but has a file {id}.rs",
          id = card.id
        );
      }
      _ => {
        // effect ok!
      }
    }
  }
  Ok(())
}

fn read_template_file() -> Result<String, Box<dyn Error>> {
  let mut content = String::new();
  File::open("./build_components/card_library.rs.tmpl")?.read_to_string(&mut content)?;
  // swap {} with {{}} - makes this template `format!`-able.
  Ok(content)
}

#[derive(Debug, Deserialize, Clone)]
struct SheetCard {
  id: u32,

  name: String,

  text: String,

  #[serde(deserialize_with = "num_or_no_or_x_or_zero")]
  cost: StringyCardValue,

  #[serde(deserialize_with = "num_or_no_or_x_or_zero")]
  power: StringyCardValue,

  #[serde(deserialize_with = "num_or_no_or_x_or_zero")]
  health: StringyCardValue,

  #[serde(rename = "startCharges")]
  start_charges: Option<u8>,

  #[serde(rename = "maxCharges")]
  max_charges: Option<u8>,

  #[serde(rename = "startCounters")]
  start_counters: Option<u8>,

  #[serde(rename = "maxCounters")]
  max_counters: Option<u8>,

  #[serde(rename = "perTurn")]
  per_turn: Option<u8>,

  #[serde(deserialize_with = "traits")]
  traits: Vec<String>,

  #[serde(deserialize_with = "optional_string_to_num")]
  #[serde(default)]
  #[serde(rename = "attachment")]
  attached_spell: Option<u32>,

  #[serde(deserialize_with = "prism")]
  prism: String,

  #[serde(deserialize_with = "element")]
  element: String,

  #[serde(deserialize_with = "r#type")]
  r#type: String,

  #[serde(rename = "releaseSeason")]
  season: u16,
}

fn optional_string_to_num<'de, D>(deserializer: D) -> Result<Option<u32>, D::Error>
where
  D: Deserializer<'de>,
{
  let value = Option::<String>::deserialize(deserializer)?;
  if let Some(value) = value {
    value
      .parse::<u32>()
      .map_err(|_| de::Error::invalid_value(de::Unexpected::Str(&value), &"an integer."))
      .map(Some)
  } else {
    Ok(None)
  }
}

#[derive(Debug, PartialEq, Eq, Copy, Clone)]
enum StringyCardValue {
  Number(u32),
  X,
  No,
}
impl StringyCardValue {
  pub fn to_number(self) -> u32 {
    match self {
      StringyCardValue::Number(x) => x,
      StringyCardValue::X | StringyCardValue::No => 0,
    }
  }
}

fn num_or_no_or_x_or_zero<'de, D>(deserializer: D) -> Result<StringyCardValue, D::Error>
where
  D: Deserializer<'de>,
{
  let value = Value::deserialize(deserializer)?;
  if let Some(num) = value.as_u64() {
    return Ok(StringyCardValue::Number(num as u32));
  }
  match value
    .as_str()
    .ok_or(de::Error::invalid_type(
      de::Unexpected::Other("&invalid type"),
      &"a string",
    ))?
    .trim()
  {
    "X" => Ok(StringyCardValue::X),
    "no" => Ok(StringyCardValue::No),
    "" => Ok(StringyCardValue::Number(0)),
    v => v
      .trim()
      .parse::<u32>()
      .map_err(|_| {
        de::Error::invalid_value(de::Unexpected::Str(v), &"an integer, X, 'no', or nothing.")
      })
      .map(StringyCardValue::Number),
  }
}

fn prism<'de, D>(deserializer: D) -> Result<String, D::Error>
where
  D: Deserializer<'de>,
{
  let value = String::deserialize(deserializer)?;
  match value.trim() {
    "hrt" => Ok("Prism::Heart"),
    "agy" => Ok("Prism::Agility"),
    "str" => Ok("Prism::Strength"),
    "wis" => Ok("Prism::Wisdom"),
    "int" => Ok("Prism::Intellect"),
    "tok" => Ok("Prism::Token"),
    "tut" => Ok("Prism::Tutorial"),
    _ => Err(de::Error::invalid_value(
      de::Unexpected::Str(&value),
      &r#"one of ["hrt", "agy"m "str", "wis", "tok", "tut"]"#,
    )),
  }
  .map(|s| s.to_string())
}

fn element<'de, D>(deserializer: D) -> Result<String, D::Error>
where
  D: Deserializer<'de>,
{
  let value = String::deserialize(deserializer)?;
  match value.trim() {
    "light" => Ok("Element::Light"),
    "mind" => Ok("Element::Mind"),
    "fire" => Ok("Element::Fire"),
    "air" => Ok("Element::Air"),
    "water" => Ok("Element::Water"),
    "earth" => Ok("Element::Earth"),
    "metal" => Ok("Element::Metal"),
    "dark" => Ok("Element::Dark"),
    "sky" => Ok("Element::Sky"),
    _ => Err(de::Error::invalid_value(
      de::Unexpected::Str(&value),
      &r#"one of ["light", "mind", "fire", "air", "water", "earth", "metal", "dark", "sky"]"#,
    )),
  }
  .map(|s| s.to_string())
}

fn r#type<'de, D>(deserializer: D) -> Result<String, D::Error>
where
  D: Deserializer<'de>,
{
  let value = String::deserialize(deserializer)?;
  match value.trim() {
    "unit" => Ok("Type::Unit"),
    "spell" => Ok("Type::Spell"),
    "enchant" => Ok("Type::Enchant"),
    "heroAbility" => Ok("Type::HeroAbility"),
    _ => Err(de::Error::invalid_value(
      de::Unexpected::Str(&value),
      &r#"one of ["unit", "spell", "enchant", "heroAbility"]"#,
    )),
  }
  .map(|s| s.to_string())
}

fn traits<'de, D>(deserializer: D) -> Result<Vec<String>, D::Error>
where
  D: Deserializer<'de>,
{
  Vec::<String>::deserialize(deserializer)?
    .iter()
    .try_fold(Vec::new(), |mut vec, s| {
      let value = match s.trim() {
        "stealth" => Ok("Trait::Stealth"),
        "wither" => Ok("Trait::Wither"),
        "guard" => Ok("Trait::Guard"),
        "banner" => Ok("Trait::Banner"),
        "lifesteal" => Ok("Trait::Lifesteal"),
        "armor" => Ok("Trait::Armor"),
        "dash" => Ok("Trait::Dash"),
        "" => Ok(""),
        _ => Err(de::Error::invalid_value(
          de::Unexpected::Str(s),
          &r#"one of ["stealth", "wither", "guard", "banner", "lifesteal", "armor", "dash"]"#,
        )),
      }?;
      if !value.is_empty() {
        vec.push(value.to_string());
      }
      Ok(vec)
    })
}
