packages:
  - 'cloudflare'
  - 'game-server-cloudflare'
  - 'matchmaker-ts'
  - 'bot'
  - 'chain'
  - 'cosmetics'
  - 'game'
  - 'game-analytics'
  - 'server'
  - 'migrator'
  - 'lib/parse-card-description'
  - 'state/cards'
  - 'state/js-bindings'
  - 'state/js-bindings/packages/browser-sys'
  - 'state/js-bindings/packages/metadata-sys'
  - 'state/js-bindings/packages/node-sys'
  - 'state/js-bindings/packages/metadata'
  - 'lib/proto'
  - 'lib/language-manager'
  - 'lib/analytics'
  - 'lib/chain-model'
  - 'lib/deck-string-codec'
  - 'lib/shared'
  - 'lib/tools'
  - 'lib/quests'
  - 'webapp'
  - 'sheets'
  - 'design-data'
#  - 'asset-pipeline'
