// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/conquest/conquestv2 (interfaces: CardPointsCalculator)
//
// Generated by this command:
//
//	mockgen -destination ./mock/card_points_calculator.go -package mock . CardPointsCalculator
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	conquestv2 "github.com/horizon-games/OpenSky/api/lib/conquest/conquestv2"
	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockCardPointsCalculator is a mock of CardPointsCalculator interface.
type MockCardPointsCalculator struct {
	ctrl     *gomock.Controller
	recorder *MockCardPointsCalculatorMockRecorder
	isgomock struct{}
}

// MockCardPointsCalculatorMockRecorder is the mock recorder for MockCardPointsCalculator.
type MockCardPointsCalculatorMockRecorder struct {
	mock *MockCardPointsCalculator
}

// NewMockCardPointsCalculator creates a new mock instance.
func NewMockCardPointsCalculator(ctrl *gomock.Controller) *MockCardPointsCalculator {
	mock := &MockCardPointsCalculator{ctrl: ctrl}
	mock.recorder = &MockCardPointsCalculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCardPointsCalculator) EXPECT() *MockCardPointsCalculatorMockRecorder {
	return m.recorder
}

// DetailedFromDeckString mocks base method.
func (m *MockCardPointsCalculator) DetailedFromDeckString(arg0 context.Context, arg1 proto.AccountID, arg2 string) (*conquestv2.DetailedCardPoints, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetailedFromDeckString", arg0, arg1, arg2)
	ret0, _ := ret[0].(*conquestv2.DetailedCardPoints)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetailedFromDeckString indicates an expected call of DetailedFromDeckString.
func (mr *MockCardPointsCalculatorMockRecorder) DetailedFromDeckString(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetailedFromDeckString", reflect.TypeOf((*MockCardPointsCalculator)(nil).DetailedFromDeckString), arg0, arg1, arg2)
}

// FromDeckString mocks base method.
func (m *MockCardPointsCalculator) FromDeckString(arg0 context.Context, arg1 proto.AccountID, arg2 string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FromDeckString", arg0, arg1, arg2)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FromDeckString indicates an expected call of FromDeckString.
func (mr *MockCardPointsCalculatorMockRecorder) FromDeckString(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FromDeckString", reflect.TypeOf((*MockCardPointsCalculator)(nil).FromDeckString), arg0, arg1, arg2)
}
