// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/conquest/conquestv2 (interfaces: ConquestV2PointsCalculator)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	conquestv2 "github.com/horizon-games/OpenSky/api/lib/conquest/conquestv2"
	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockConquestV2PointsCalculator is a mock of ConquestV2PointsCalculator interface.
type MockConquestV2PointsCalculator struct {
	ctrl     *gomock.Controller
	recorder *MockConquestV2PointsCalculatorMockRecorder
}

// MockConquestV2PointsCalculatorMockRecorder is the mock recorder for MockConquestV2PointsCalculator.
type MockConquestV2PointsCalculatorMockRecorder struct {
	mock *MockConquestV2PointsCalculator
}

// NewMockConquestV2PointsCalculator creates a new mock instance.
func NewMockConquestV2PointsCalculator(ctrl *gomock.Controller) *MockConquestV2PointsCalculator {
	mock := &MockConquestV2PointsCalculator{ctrl: ctrl}
	mock.recorder = &MockConquestV2PointsCalculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConquestV2PointsCalculator) EXPECT() *MockConquestV2PointsCalculatorMockRecorder {
	return m.recorder
}

// DetailedFromDeckString mocks base method.
func (m *MockConquestV2PointsCalculator) DetailedFromDeckString(arg0 context.Context, arg1 proto.AccountID, arg2 string) (*conquestv2.DetailedPoints, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetailedFromDeckString", arg0, arg1, arg2)
	ret0, _ := ret[0].(*conquestv2.DetailedPoints)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetailedFromDeckString indicates an expected call of DetailedFromDeckString.
func (mr *MockConquestV2PointsCalculatorMockRecorder) DetailedFromDeckString(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetailedFromDeckString", reflect.TypeOf((*MockConquestV2PointsCalculator)(nil).DetailedFromDeckString), arg0, arg1, arg2)
}
