// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/conquest/conquestv2 (interfaces: HeroSkinFinder)
//
// Generated by this command:
//
//	mockgen -destination ./mock/hero_skin_finder.go -package mock . HeroSkinFinder
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockHeroSkinFinder is a mock of HeroSkinFinder interface.
type MockHeroSkinFinder struct {
	ctrl     *gomock.Controller
	recorder *MockHeroSkinFinderMockRecorder
	isgomock struct{}
}

// MockHeroSkinFinderMockRecorder is the mock recorder for MockHeroSkinFinder.
type MockHeroSkinFinderMockRecorder struct {
	mock *MockHeroSkinFinder
}

// NewMockHeroSkinFinder creates a new mock instance.
func NewMockHeroSkinFinder(ctrl *gomock.Controller) *MockHeroSkinFinder {
	mock := &MockHeroSkinFinder{ctrl: ctrl}
	mock.recorder = &MockHeroSkinFinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHeroSkinFinder) EXPECT() *MockHeroSkinFinderMockRecorder {
	return m.recorder
}

// HasFromDeckString mocks base method.
func (m *MockHeroSkinFinder) HasFromDeckString(arg0 context.Context, arg1 proto.AccountID, arg2 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasFromDeckString", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasFromDeckString indicates an expected call of HasFromDeckString.
func (mr *MockHeroSkinFinderMockRecorder) HasFromDeckString(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasFromDeckString", reflect.TypeOf((*MockHeroSkinFinder)(nil).HasFromDeckString), arg0, arg1, arg2)
}
