// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/conquest/conquestv2 (interfaces: MetricsCollector)
//
// Generated by this command:
//
//	mockgen -destination ./mock/metrics_collector.go -package mock . MetricsCollector
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMetricsCollector is a mock of MetricsCollector interface.
type MockMetricsCollector struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsCollectorMockRecorder
	isgomock struct{}
}

// MockMetricsCollectorMockRecorder is the mock recorder for MockMetricsCollector.
type MockMetricsCollectorMockRecorder struct {
	mock *MockMetricsCollector
}

// NewMockMetricsCollector creates a new mock instance.
func NewMockMetricsCollector(ctrl *gomock.Controller) *MockMetricsCollector {
	mock := &MockMetricsCollector{ctrl: ctrl}
	mock.recorder = &MockMetricsCollectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsCollector) EXPECT() *MockMetricsCollectorMockRecorder {
	return m.recorder
}

// TrackConquestPoolAmount mocks base method.
func (m *MockMetricsCollector) TrackConquestPoolAmount(arg0 uint64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackConquestPoolAmount", arg0)
}

// TrackConquestPoolAmount indicates an expected call of TrackConquestPoolAmount.
func (mr *MockMetricsCollectorMockRecorder) TrackConquestPoolAmount(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackConquestPoolAmount", reflect.TypeOf((*MockMetricsCollector)(nil).TrackConquestPoolAmount), arg0)
}

// TrackConquestTotalWeight mocks base method.
func (m *MockMetricsCollector) TrackConquestTotalWeight(arg0 float32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackConquestTotalWeight", arg0)
}

// TrackConquestTotalWeight indicates an expected call of TrackConquestTotalWeight.
func (mr *MockMetricsCollectorMockRecorder) TrackConquestTotalWeight(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackConquestTotalWeight", reflect.TypeOf((*MockMetricsCollector)(nil).TrackConquestTotalWeight), arg0)
}

// TrackConquestTotalWeightPriceBottom mocks base method.
func (m *MockMetricsCollector) TrackConquestTotalWeightPriceBottom(arg0 uint64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackConquestTotalWeightPriceBottom", arg0)
}

// TrackConquestTotalWeightPriceBottom indicates an expected call of TrackConquestTotalWeightPriceBottom.
func (mr *MockMetricsCollectorMockRecorder) TrackConquestTotalWeightPriceBottom(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackConquestTotalWeightPriceBottom", reflect.TypeOf((*MockMetricsCollector)(nil).TrackConquestTotalWeightPriceBottom), arg0)
}

// TrackConquestTotalWeightPriceTop mocks base method.
func (m *MockMetricsCollector) TrackConquestTotalWeightPriceTop(arg0 uint64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackConquestTotalWeightPriceTop", arg0)
}

// TrackConquestTotalWeightPriceTop indicates an expected call of TrackConquestTotalWeightPriceTop.
func (mr *MockMetricsCollectorMockRecorder) TrackConquestTotalWeightPriceTop(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackConquestTotalWeightPriceTop", reflect.TypeOf((*MockMetricsCollector)(nil).TrackConquestTotalWeightPriceTop), arg0)
}

// TrackConquestWeightUnitPrice mocks base method.
func (m *MockMetricsCollector) TrackConquestWeightUnitPrice(arg0 float32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackConquestWeightUnitPrice", arg0)
}

// TrackConquestWeightUnitPrice indicates an expected call of TrackConquestWeightUnitPrice.
func (mr *MockMetricsCollectorMockRecorder) TrackConquestWeightUnitPrice(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackConquestWeightUnitPrice", reflect.TypeOf((*MockMetricsCollector)(nil).TrackConquestWeightUnitPrice), arg0)
}
