// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/conquest/conquestv2 (interfaces: PointsCalculator)
//
// Generated by this command:
//
//	mockgen -destination ./mock/points_calculator.go -package mock . PointsCalculator
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	conquestv2 "github.com/horizon-games/OpenSky/api/lib/conquest/conquestv2"
	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockPointsCalculator is a mock of PointsCalculator interface.
type MockPointsCalculator struct {
	ctrl     *gomock.Controller
	recorder *MockPointsCalculatorMockRecorder
	isgomock struct{}
}

// MockPointsCalculatorMockRecorder is the mock recorder for MockPointsCalculator.
type MockPointsCalculatorMockRecorder struct {
	mock *MockPointsCalculator
}

// NewMockPointsCalculator creates a new mock instance.
func NewMockPointsCalculator(ctrl *gomock.Controller) *MockPointsCalculator {
	mock := &MockPointsCalculator{ctrl: ctrl}
	mock.recorder = &MockPointsCalculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPointsCalculator) EXPECT() *MockPointsCalculatorMockRecorder {
	return m.recorder
}

// DetailedFromDeckString mocks base method.
func (m *MockPointsCalculator) DetailedFromDeckString(arg0 context.Context, arg1 proto.AccountID, arg2 string) (*conquestv2.DetailedPoints, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetailedFromDeckString", arg0, arg1, arg2)
	ret0, _ := ret[0].(*conquestv2.DetailedPoints)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetailedFromDeckString indicates an expected call of DetailedFromDeckString.
func (mr *MockPointsCalculatorMockRecorder) DetailedFromDeckString(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetailedFromDeckString", reflect.TypeOf((*MockPointsCalculator)(nil).DetailedFromDeckString), arg0, arg1, arg2)
}

// FromDeckString mocks base method.
func (m *MockPointsCalculator) FromDeckString(arg0 context.Context, arg1 proto.AccountID, arg2 string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FromDeckString", arg0, arg1, arg2)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FromDeckString indicates an expected call of FromDeckString.
func (mr *MockPointsCalculatorMockRecorder) FromDeckString(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FromDeckString", reflect.TypeOf((*MockPointsCalculator)(nil).FromDeckString), arg0, arg1, arg2)
}
