// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/conquest/conquestv2 (interfaces: TreasureCalculator)
//
// Generated by this command:
//
//	mockgen -destination ./mock/treasure_calculator.go -package mock . TreasureCalculator
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	data "github.com/horizon-games/OpenSky/api/data"
	gomock "go.uber.org/mock/gomock"
)

// MockTreasureCalculator is a mock of TreasureCalculator interface.
type MockTreasureCalculator struct {
	ctrl     *gomock.Controller
	recorder *MockTreasureCalculatorMockRecorder
	isgomock struct{}
}

// MockTreasureCalculatorMockRecorder is the mock recorder for MockTreasureCalculator.
type MockTreasureCalculatorMockRecorder struct {
	mock *MockTreasureCalculator
}

// NewMockTreasureCalculator creates a new mock instance.
func NewMockTreasureCalculator(ctrl *gomock.Controller) *MockTreasureCalculator {
	mock := &MockTreasureCalculator{ctrl: ctrl}
	mock.recorder = &MockTreasureCalculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTreasureCalculator) EXPECT() *MockTreasureCalculatorMockRecorder {
	return m.recorder
}

// FromConquestPoints mocks base method.
func (m *MockTreasureCalculator) FromConquestPoints(arg0 *data.ConquestPoints) (*data.ConquestV2TreasureProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FromConquestPoints", arg0)
	ret0, _ := ret[0].(*data.ConquestV2TreasureProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FromConquestPoints indicates an expected call of FromConquestPoints.
func (mr *MockTreasureCalculatorMockRecorder) FromConquestPoints(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FromConquestPoints", reflect.TypeOf((*MockTreasureCalculator)(nil).FromConquestPoints), arg0)
}
