export const MOBILE_SECTION_ASPECT_RATIO = '790 / 322'
export const SECTION_ASPECT_RATIO = '1574 / 450.8'

export const SHOP_SECTION_CLASSNAME = 'SHOP_SECTION_CLASSNAME'
export const SHOP_NAV_BUTTON_CLASSNAME = 'SHOP_NAV_BUTTON_CLASSNAME'
