// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/playerstats (interfaces: PlayerStatsManager)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	playerstats "github.com/horizon-games/OpenSky/matchmaker/lib/playerstats"
	gomock "go.uber.org/mock/gomock"
)

// MockPlayerStatsManager is a mock of PlayerStatsManager interface.
type MockPlayerStatsManager struct {
	ctrl     *gomock.Controller
	recorder *MockPlayerStatsManagerMockRecorder
}

// MockPlayerStatsManagerMockRecorder is the mock recorder for MockPlayerStatsManager.
type MockPlayerStatsManagerMockRecorder struct {
	mock *MockPlayerStatsManager
}

// NewMockPlayerStatsManager creates a new mock instance.
func NewMockPlayerStatsManager(ctrl *gomock.Controller) *MockPlayerStatsManager {
	mock := &MockPlayerStatsManager{ctrl: ctrl}
	mock.recorder = &MockPlayerStatsManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlayerStatsManager) EXPECT() *MockPlayerStatsManagerMockRecorder {
	return m.recorder
}

// Push mocks base method.
func (m *MockPlayerStatsManager) Push(arg0 proto.Hash, arg1 *playerstats.Stat) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Push", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Push indicates an expected call of Push.
func (mr *MockPlayerStatsManagerMockRecorder) Push(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*MockPlayerStatsManager)(nil).Push), arg0, arg1)
}

// Retrieve mocks base method.
func (m *MockPlayerStatsManager) Retrieve(arg0 proto.Hash) (*playerstats.StatsSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Retrieve", arg0)
	ret0, _ := ret[0].(*playerstats.StatsSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Retrieve indicates an expected call of Retrieve.
func (mr *MockPlayerStatsManagerMockRecorder) Retrieve(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Retrieve", reflect.TypeOf((*MockPlayerStatsManager)(nil).Retrieve), arg0)
}
