// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/skypass (interfaces: CardIndex)
//
// Generated by this command:
//
//	mockgen -destination ./mock/card_index.go -package mock . CardIndex
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	data "github.com/horizon-games/OpenSky/api/data"
	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockCardIndex is a mock of CardIndex interface.
type MockCardIndex struct {
	ctrl     *gomock.Controller
	recorder *MockCardIndexMockRecorder
	isgomock struct{}
}

// MockCardIndexMockRecorder is the mock recorder for MockCardIndex.
type MockCardIndexMockRecorder struct {
	mock *MockCardIndex
}

// NewMockCardIndex creates a new mock instance.
func NewMockCardIndex(ctrl *gomock.Controller) *MockCardIndex {
	mock := &MockCardIndex{ctrl: ctrl}
	mock.recorder = &MockCardIndexMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCardIndex) EXPECT() *MockCardIndexMockRecorder {
	return m.recorder
}

// CardIDsByCardSets mocks base method.
func (m *MockCardIndex) CardIDsByCardSets(cardSets ...*proto.CardSet) []uint64 {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range cardSets {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CardIDsByCardSets", varargs...)
	ret0, _ := ret[0].([]uint64)
	return ret0
}

// CardIDsByCardSets indicates an expected call of CardIDsByCardSets.
func (mr *MockCardIndexMockRecorder) CardIDsByCardSets(cardSets ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CardIDsByCardSets", reflect.TypeOf((*MockCardIndex)(nil).CardIDsByCardSets), cardSets...)
}

// CardIDsSeasonInvalid mocks base method.
func (m *MockCardIndex) CardIDsSeasonInvalid(season uint16) []uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CardIDsSeasonInvalid", season)
	ret0, _ := ret[0].([]uint64)
	return ret0
}

// CardIDsSeasonInvalid indicates an expected call of CardIDsSeasonInvalid.
func (mr *MockCardIndexMockRecorder) CardIDsSeasonInvalid(season any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CardIDsSeasonInvalid", reflect.TypeOf((*MockCardIndex)(nil).CardIDsSeasonInvalid), season)
}

// GetCardByID mocks base method.
func (m *MockCardIndex) GetCardByID(id uint64) *data.Card {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardByID", id)
	ret0, _ := ret[0].(*data.Card)
	return ret0
}

// GetCardByID indicates an expected call of GetCardByID.
func (mr *MockCardIndexMockRecorder) GetCardByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardByID", reflect.TypeOf((*MockCardIndex)(nil).GetCardByID), id)
}

// GetRandomCard mocks base method.
func (m *MockCardIndex) GetRandomCard(excludeIDs []uint64) *data.Card {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomCard", excludeIDs)
	ret0, _ := ret[0].(*data.Card)
	return ret0
}

// GetRandomCard indicates an expected call of GetRandomCard.
func (mr *MockCardIndexMockRecorder) GetRandomCard(excludeIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomCard", reflect.TypeOf((*MockCardIndex)(nil).GetRandomCard), excludeIDs)
}

// GetRandomCardByCardSets mocks base method.
func (m *MockCardIndex) GetRandomCardByCardSets(sets []*proto.CardSet, excludeIDs []uint64) *data.Card {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomCardByCardSets", sets, excludeIDs)
	ret0, _ := ret[0].(*data.Card)
	return ret0
}

// GetRandomCardByCardSets indicates an expected call of GetRandomCardByCardSets.
func (mr *MockCardIndexMockRecorder) GetRandomCardByCardSets(sets, excludeIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomCardByCardSets", reflect.TypeOf((*MockCardIndex)(nil).GetRandomCardByCardSets), sets, excludeIDs)
}

// GetRandomCardByClasses mocks base method.
func (m *MockCardIndex) GetRandomCardByClasses(classes []proto.CardClass, excludeIDs []uint64) *data.Card {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomCardByClasses", classes, excludeIDs)
	ret0, _ := ret[0].(*data.Card)
	return ret0
}

// GetRandomCardByClasses indicates an expected call of GetRandomCardByClasses.
func (mr *MockCardIndexMockRecorder) GetRandomCardByClasses(classes, excludeIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomCardByClasses", reflect.TypeOf((*MockCardIndex)(nil).GetRandomCardByClasses), classes, excludeIDs)
}
