// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/skypass (interfaces: ListerRuleApplier)
//
// Generated by this command:
//
//	mockgen -destination ./mock/lister_rule_applier.go -package mock . ListerRuleApplier
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	data "github.com/horizon-games/OpenSky/api/data"
	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockListerRuleApplier is a mock of ListerRuleApplier interface.
type MockListerRuleApplier struct {
	ctrl     *gomock.Controller
	recorder *MockListerRuleApplierMockRecorder
	isgomock struct{}
}

// MockListerRuleApplierMockRecorder is the mock recorder for MockListerRuleApplier.
type MockListerRuleApplierMockRecorder struct {
	mock *MockListerRuleApplier
}

// NewMockListerRuleApplier creates a new mock instance.
func NewMockListerRuleApplier(ctrl *gomock.Controller) *MockListerRuleApplier {
	mock := &MockListerRuleApplier{ctrl: ctrl}
	mock.recorder = &MockListerRuleApplierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListerRuleApplier) EXPECT() *MockListerRuleApplierMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockListerRuleApplier) Apply(arg0 context.Context, arg1 proto.AccountID, arg2 []*proto.SkypassLevel, arg3 *data.SkypassSeasonStat) ([]*proto.SkypassLevel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*proto.SkypassLevel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Apply indicates an expected call of Apply.
func (mr *MockListerRuleApplierMockRecorder) Apply(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockListerRuleApplier)(nil).Apply), arg0, arg1, arg2, arg3)
}
