// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/skypass (interfaces: RewardApplier)
//
// Generated by this command:
//
//	mockgen -destination ./mock/reward_applier.go -package mock . RewardApplier
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	data "github.com/horizon-games/OpenSky/api/data"
	proto "github.com/horizon-games/OpenSky/api/proto"
	db "github.com/upper/db/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockRewardApplier is a mock of RewardApplier interface.
type MockRewardApplier struct {
	ctrl     *gomock.Controller
	recorder *MockRewardApplierMockRecorder
	isgomock struct{}
}

// MockRewardApplierMockRecorder is the mock recorder for MockRewardApplier.
type MockRewardApplierMockRecorder struct {
	mock *MockRewardApplier
}

// NewMockRewardApplier creates a new mock instance.
func NewMockRewardApplier(ctrl *gomock.Controller) *MockRewardApplier {
	mock := &MockRewardApplier{ctrl: ctrl}
	mock.recorder = &MockRewardApplierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRewardApplier) EXPECT() *MockRewardApplierMockRecorder {
	return m.recorder
}

// ApplyReward mocks base method.
func (m *MockRewardApplier) ApplyReward(arg0 context.Context, arg1 db.Session, arg2 proto.AccountID, arg3 *data.SkypassReward) ([]*proto.Reward, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyReward", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*proto.Reward)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyReward indicates an expected call of ApplyReward.
func (mr *MockRewardApplierMockRecorder) ApplyReward(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyReward", reflect.TypeOf((*MockRewardApplier)(nil).ApplyReward), arg0, arg1, arg2, arg3)
}
