// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/skypass (interfaces: RewardLister)
//
// Generated by this command:
//
//	mockgen -destination ./mock/reward_lister.go -package mock . RewardLister
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockRewardLister is a mock of RewardLister interface.
type MockRewardLister struct {
	ctrl     *gomock.Controller
	recorder *MockRewardListerMockRecorder
	isgomock struct{}
}

// MockRewardListerMockRecorder is the mock recorder for MockRewardLister.
type MockRewardListerMockRecorder struct {
	mock *MockRewardLister
}

// NewMockRewardLister creates a new mock instance.
func NewMockRewardLister(ctrl *gomock.Controller) *MockRewardLister {
	mock := &MockRewardLister{ctrl: ctrl}
	mock.recorder = &MockRewardListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRewardLister) EXPECT() *MockRewardListerMockRecorder {
	return m.recorder
}

// ListBySeason mocks base method.
func (m *MockRewardLister) ListBySeason(arg0 context.Context, arg1 proto.AccountID, arg2 uint16) ([]*proto.SkypassLevel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBySeason", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*proto.SkypassLevel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBySeason indicates an expected call of ListBySeason.
func (mr *MockRewardListerMockRecorder) ListBySeason(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBySeason", reflect.TypeOf((*MockRewardLister)(nil).ListBySeason), arg0, arg1, arg2)
}
