import {
  getUrlFlag,
  getUrlFloat,
  getUrlInt,
  getUrlParam
} from '@opensky/shared/utils/location'

// prettier-ignore
const queryParams = {
  altMobileUI: getUrlFlag('altMobileUI'),
  disableCanvasAlpha: getUrlFlag('disableCanvasAlpha'),
  assetsDirect: getUrlFlag('assetsDirect'),
  assetsUrl: getUrlParam('assetsUrl'),
  attachmentShadows: getUrlFlag('attachmentShadows'),
  bgFlash: getUrlFlag('bgFlash'),
  botAlias: getUrlParam('botAlias'),
  botDeck: getUrlParam('botDeck'),
  botDifficulty: getUrlFloat('botDifficulty', 0.5, 0, 1),
  botTimer: getUrlFlag('botTimer'),
  botUsesHeroArt: getUrlFlag('botUsesHeroArt'),
  camDamping: getUrlFloat('camDamping', 0, 0, 0.999),
  cards: getUrlParam('cards'), // Sandbox cards to use
  code: getUrlParam('code'), // CrowdIn OAuth return code - we can't choose this param :(
  playOnSpace: getUrlFlag('playOnSpace'),
  customSpeed: getUrlFlag('customSpeed'),
  dayLength: getUrlFloat('dayLength', Number(window.APP_CONFIG.ART_DAY_DURATION_SECONDS)),
  dayPercent: getUrlFloat('dayPercent', 0.85, 0, 1),
  debugArcHelpers: getUrlFlag('debugArcHelpers'),
  debugColliders: getUrlFlag('debugColliders'),
  debugDealer: getUrlFlag('debugDealer'),
  debugLayout: getUrlFlag('debugLayout'),
  debugMenu:getUrlParam('debugMenu'),
  debugRenderOrder: getUrlFlag('debugRenderOrder'),
  debugLights: getUrlFlag('debugLights'),
  debugPerformanceWarning: getUrlFlag('debugPerformanceWarning'),
  debugPreload: getUrlFlag('debugPreload'),
  debugSky: getUrlFlag('debugSky'),
  debugSound: getUrlFlag('debugSound'),
  debugSunMoon: getUrlFlag('debugSunMoon'),
  debugDontSendLoadingProgress: getUrlFlag('debugDontSendLoadingProgress'),
  debugVS: getUrlFlag('debugVS'),
  debugScreenspace: getUrlFlag('debugScreenspace'),
  allowOfflineReporting: getUrlFlag('allowOfflineReporting'),
  allowOfflineSpectating: getUrlFlag('allowOfflineSpectating'),
  deck: getUrlParam('deck'),
  desynchronized: getUrlFlag('desynchronized'),
  disableHighlights: getUrlFlag('disableHighlights'),
  disableCardHoverPopups: getUrlFlag('disableCardHoverPopups'),
  disableText: getUrlFlag('disableText'),
  disableToolTips: getUrlFlag('disableToolTips'),
  editMaterials: getUrlFlag('editMaterials'),
  fakeRanked: getUrlFlag('fakeRanked'),
  fakeConquest: getUrlInt('fakeConquest', -1, -1, 2),
  fakeFindOpponent: getUrlFlag('fakeFindOpponent'),
  fakeRewards: getUrlParam('fakeRewards') || undefined,
  fakeStickers: getUrlParam('fakeStickers') || undefined,
  fakeHeroSkins: getUrlParam('fakeHeroSkins') || undefined,
  fakeCardBacks: getUrlParam('fakeCardBacks') || undefined,
  rewardsPerPage: getUrlFloat('rewardsPerPage', 6),
  fakeStoreData: getUrlFlag('fakeStoreData'),
  fakeWinner: getUrlInt('fakeWinner', 0, -1, 1),
  fakeConcede: getUrlFlag('fakeConcede'),
  foilHero: getUrlFlag('foilHero'),
  forceConcede: getUrlFlag('forceConcede'),
  forceWebGL2: getUrlFlag('forceWebGL2'),
  forceWebGLCommandTracer: getUrlFlag('forceWebGLCommandTracer'),
  fpsCam: getUrlFlag('fpsCam'),
  gameParamsURL: getUrlParam('gameParamsURL'),
  holdUIDuration: getUrlInt('holdUIDuration', 0, 0, 300000),
  instantReconnect: getUrlFlag('instantReconnect'),
  loadTestReplay: getUrlFlag('loadTestReplay'),
  fakeBuggyReconnect: getUrlFlag('fakeBuggyReconnect'),
  openSidebars: getUrlFlag('openSidebars'),
  islandSpin: getUrlFloat('islandSpin', 0),
  gameBoard: getUrlParam('gameBoard'),
  island: getUrlParam('island'),
  isolate: getUrlFlag('isolate'),
  hideZones: getUrlParam('hideZones') || '',
  traits: getUrlParam('traits'),
  logActions: getUrlFlag('logActions'),
  logGameActions: getUrlFlag('logGameActions'),
  logActionHistory: getUrlFlag('logActionHistory'),
  logProof: getUrlFlag('logProof'),
  logStory: getUrlFlag('logStory'),
  lowMem: getUrlFlag('lowMem'),
  midground: getUrlFlag('midground'),
  mode: getUrlParam('mode'),
  noBotDelay: getUrlFlag('noBotDelay'),
  overrideCursor: getUrlParam('overrideCursor'),
  playerAlias: getUrlParam('playerAlias') || 'Player',
  playerIsBot: getUrlFlag('playerIsBot'),
  playerGoesFirst: getUrlFlag('playerGoesFirst'), // player goes first in a local bot game
  preserveDrawingBuffer: getUrlFlag('preserveDrawingBuffer'),
  rarities: getUrlParam('rarities'),
  rarityOverride: getUrlParam('rarityOverride'),
  recordGameForQuestTest: getUrlParam('recordGameForQuestTest'),
  region: getUrlParam('region'),
  renderDefaultLayer: getUrlFlag('renderDefaultLayer'),
  replayMatchID: getUrlParam('replayMatchID'),
  replayID: getUrlParam('replayID'),
  spectateCode: getUrlParam('spectateCode'),
  replayTimestamp: getUrlParam('replayTimestamp'),
  resetSettings: getUrlFlag('resetSettings'),
  resetToolTips: getUrlFlag('resetToolTips'),
  scrollX: getUrlFloat('scrollX', 10),
  scrollY: getUrlFloat('scrollY', 11),
  serializedGamePlayer: () => getUrlParam('serializedGamePlayer') || '0', // needs to be a fn, can change mid-game
  serializedGameURL: getUrlParam('serializedGameURL'),
  serializedGameQuickSlotSelector: () => getUrlInt('serializedGameQuickSlotSelector', -1), // needs to be a fn, can change mid-game
  setPrism: getUrlParam('setPrism'),
  size: getUrlFloat('size', 1),
  skipAuth: getUrlFlag('skipAuth'),
  skipIntro: getUrlFlag('skipIntro'),
  skipCardSelection: getUrlFlag('skipCardSelection'), // Skip card selection
  skipMatchEndContinue: getUrlFlag('skipMatchEndContinue'),
  skipTurnChangeOverlays: getUrlFlag('skipTurnChangeOverlays'),
  skipTutorialTitle: getUrlFlag('skipTutorialTitle'),
  skippedTutorialMessages: getUrlInt('skippedTutorialMessages', -1, 0, 100) || undefined,
  skipVS: getUrlFlag('skipVS'), // Skip versus screen
  speed: getUrlFloat('speed', -1),
  heroAbilityRarity: getUrlParam('heroAbilityRarity') || 'base',
  tavernMode: getUrlParam('tavernMode'),
  test: getUrlParam('test'),
  testBuffIcons: getUrlFlag('testBuffIcons'),
  tutorialJump: getUrlInt('tutorialJump', -1),
  randomRarity: getUrlFlag('randomRarity'),
  forceRarity: getUrlParam('forceRarity'),
  testPingDisplay: getUrlFlag('testPingDisplay'),
  texture: getUrlParam('texture'),
  textureMode: getUrlParam('textureMode'),
  tutorialLevel: getUrlParam('tutorialLevel'),
  timeCutDuration: getUrlFloat('timeCutDuration', 0, 0, 5),
  tweakTitleGlows: getUrlFlag('tweakTitleGlows'),
  type: getUrlParam('type'), // Sandbox entity type to use: 'card', 'character', 'hero'
  uiJump: getUrlParam('uiJump'),
  useWorker: getUrlFlag('useWorker'),
  volleyMax: getUrlInt('volleyMax', 4, 1, 20),
  workerless: getUrlFlag('workerless'),
  fireworkLighting: getUrlFlag('fireworkLighting'),
  previewTriggers: getUrlFlag('previewTriggers'),
  noCatch: getUrlFlag('noCatch'),
  lethalPuzzleURL: getUrlParam('lethalPuzzleURL'),
  language: getUrlParam('language')
}

export default queryParams
