// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker/matching/matchfuncs/matchquality/factorcalculators (interfaces: PlayerStatsRetriever)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	playerstats "github.com/horizon-games/OpenSky/matchmaker/lib/playerstats"
	gomock "go.uber.org/mock/gomock"
)

// MockPlayerStatsRetriever is a mock of PlayerStatsRetriever interface.
type MockPlayerStatsRetriever struct {
	ctrl     *gomock.Controller
	recorder *MockPlayerStatsRetrieverMockRecorder
}

// MockPlayerStatsRetrieverMockRecorder is the mock recorder for MockPlayerStatsRetriever.
type MockPlayerStatsRetrieverMockRecorder struct {
	mock *MockPlayerStatsRetriever
}

// NewMockPlayerStatsRetriever creates a new mock instance.
func NewMockPlayerStatsRetriever(ctrl *gomock.Controller) *MockPlayerStatsRetriever {
	mock := &MockPlayerStatsRetriever{ctrl: ctrl}
	mock.recorder = &MockPlayerStatsRetrieverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlayerStatsRetriever) EXPECT() *MockPlayerStatsRetrieverMockRecorder {
	return m.recorder
}

// Retrieve mocks base method.
func (m *MockPlayerStatsRetriever) Retrieve(arg0 proto.Hash) (*playerstats.StatsSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Retrieve", arg0)
	ret0, _ := ret[0].(*playerstats.StatsSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Retrieve indicates an expected call of Retrieve.
func (mr *MockPlayerStatsRetrieverMockRecorder) Retrieve(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Retrieve", reflect.TypeOf((*MockPlayerStatsRetriever)(nil).Retrieve), arg0)
}
