// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/frontend (interfaces: ClientMessageHandler)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	frontend "github.com/horizon-games/OpenSky/matchmaker/lib/frontend"
	gomock "go.uber.org/mock/gomock"
)

// MockClientMessageHandler is a mock of ClientMessageHandler interface.
type MockClientMessageHandler struct {
	ctrl     *gomock.Controller
	recorder *MockClientMessageHandlerMockRecorder
}

// MockClientMessageHandlerMockRecorder is the mock recorder for MockClientMessageHandler.
type MockClientMessageHandlerMockRecorder struct {
	mock *MockClientMessageHandler
}

// NewMockClientMessageHandler creates a new mock instance.
func NewMockClientMessageHandler(ctrl *gomock.Controller) *MockClientMessageHandler {
	mock := &MockClientMessageHandler{ctrl: ctrl}
	mock.recorder = &MockClientMessageHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientMessageHandler) EXPECT() *MockClientMessageHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockClientMessageHandler) Handle(arg0 context.Context, arg1 *frontend.Client) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockClientMessageHandlerMockRecorder) Handle(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockClientMessageHandler)(nil).Handle), arg0, arg1)
}
