// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/frontend (interfaces: ClientWriter)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClientWriter is a mock of ClientWriter interface.
type MockClientWriter struct {
	ctrl     *gomock.Controller
	recorder *MockClientWriterMockRecorder
}

// MockClientWriterMockRecorder is the mock recorder for MockClientWriter.
type MockClientWriterMockRecorder struct {
	mock *MockClientWriter
}

// NewMockClientWriter creates a new mock instance.
func NewMockClientWriter(ctrl *gomock.Controller) *MockClientWriter {
	mock := &MockClientWriter{ctrl: ctrl}
	mock.recorder = &MockClientWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientWriter) EXPECT() *MockClientWriterMockRecorder {
	return m.recorder
}

// WriteJSON mocks base method.
func (m *MockClientWriter) WriteJSON(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteJSON", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteJSON indicates an expected call of WriteJSON.
func (mr *MockClientWriterMockRecorder) WriteJSON(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteJSON", reflect.TypeOf((*MockClientWriter)(nil).WriteJSON), arg0)
}
