// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/frontend (interfaces: FindMatchMessageHandler)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	frontend "github.com/horizon-games/OpenSky/matchmaker/lib/frontend"
	messages "github.com/horizon-games/OpenSky/matchmaker/lib/messages"
	gomock "go.uber.org/mock/gomock"
)

// MockFindMatchMessageHandler is a mock of FindMatchMessageHandler interface.
type MockFindMatchMessageHandler struct {
	ctrl     *gomock.Controller
	recorder *MockFindMatchMessageHandlerMockRecorder
}

// MockFindMatchMessageHandlerMockRecorder is the mock recorder for MockFindMatchMessageHandler.
type MockFindMatchMessageHandlerMockRecorder struct {
	mock *MockFindMatchMessageHandler
}

// NewMockFindMatchMessageHandler creates a new mock instance.
func NewMockFindMatchMessageHandler(ctrl *gomock.Controller) *MockFindMatchMessageHandler {
	mock := &MockFindMatchMessageHandler{ctrl: ctrl}
	mock.recorder = &MockFindMatchMessageHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFindMatchMessageHandler) EXPECT() *MockFindMatchMessageHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockFindMatchMessageHandler) Handle(arg0 context.Context, arg1 *frontend.Client, arg2 *messages.FindMatchMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockFindMatchMessageHandlerMockRecorder) Handle(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockFindMatchMessageHandler)(nil).Handle), arg0, arg1, arg2)
}
