// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/frontend (interfaces: MessageReceiver)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	frontend "github.com/horizon-games/OpenSky/matchmaker/lib/frontend"
	messages "github.com/horizon-games/OpenSky/matchmaker/lib/messages"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageReceiver is a mock of MessageReceiver interface.
type MockMessageReceiver struct {
	ctrl     *gomock.Controller
	recorder *MockMessageReceiverMockRecorder
}

// MockMessageReceiverMockRecorder is the mock recorder for MockMessageReceiver.
type MockMessageReceiverMockRecorder struct {
	mock *MockMessageReceiver
}

// NewMockMessageReceiver creates a new mock instance.
func NewMockMessageReceiver(ctrl *gomock.Controller) *MockMessageReceiver {
	mock := &MockMessageReceiver{ctrl: ctrl}
	mock.recorder = &MockMessageReceiverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageReceiver) EXPECT() *MockMessageReceiverMockRecorder {
	return m.recorder
}

// Receive mocks base method.
func (m *MockMessageReceiver) Receive(arg0 frontend.ClientReaderCloser) ([]byte, messages.MessageType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Receive", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(messages.MessageType)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Receive indicates an expected call of Receive.
func (mr *MockMessageReceiverMockRecorder) Receive(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Receive", reflect.TypeOf((*MockMessageReceiver)(nil).Receive), arg0)
}
