// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/frontend (interfaces: MessageSender)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	time "time"

	events "github.com/horizon-games/OpenSky/matchmaker/lib/events"
	frontend "github.com/horizon-games/OpenSky/matchmaker/lib/frontend"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageSender is a mock of MessageSender interface.
type MockMessageSender struct {
	ctrl     *gomock.Controller
	recorder *MockMessageSenderMockRecorder
}

// MockMessageSenderMockRecorder is the mock recorder for MockMessageSender.
type MockMessageSenderMockRecorder struct {
	mock *MockMessageSender
}

// NewMockMessageSender creates a new mock instance.
func NewMockMessageSender(ctrl *gomock.Controller) *MockMessageSender {
	mock := &MockMessageSender{ctrl: ctrl}
	mock.recorder = &MockMessageSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageSender) EXPECT() *MockMessageSenderMockRecorder {
	return m.recorder
}

// SendAcceptMatchMessage mocks base method.
func (m *MockMessageSender) SendAcceptedMatchMessage(arg0 frontend.ClientWriter, arg1 events.EventAcceptedMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAcceptedMatchMessage", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAcceptMatchMessage indicates an expected call of SendAcceptMatchMessage.
func (mr *MockMessageSenderMockRecorder) SendAcceptMatchMessage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAcceptedMatchMessage", reflect.TypeOf((*MockMessageSender)(nil).SendAcceptedMatchMessage), arg0, arg1)
}

// SendDeclinedMatchMessage mocks base method.
func (m *MockMessageSender) SendDeclinedMatchMessage(arg0 frontend.ClientWriter, arg1 events.EventDeclinedMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendDeclinedMatchMessage", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendDeclinedMatchMessage indicates an expected call of SendDeclinedMatchMessage.
func (mr *MockMessageSenderMockRecorder) SendDeclinedMatchMessage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendDeclinedMatchMessage", reflect.TypeOf((*MockMessageSender)(nil).SendDeclinedMatchMessage), arg0, arg1)
}

// SendErrorMessage mocks base method.
func (m *MockMessageSender) SendErrorMessage(arg0 frontend.ClientWriter, arg1 events.Error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendErrorMessage", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendErrorMessage indicates an expected call of SendErrorMessage.
func (mr *MockMessageSenderMockRecorder) SendErrorMessage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendErrorMessage", reflect.TypeOf((*MockMessageSender)(nil).SendErrorMessage), arg0, arg1)
}

// SendEvictedMessage mocks base method.
func (m *MockMessageSender) SendEvictedMessage(arg0 frontend.ClientWriter, arg1 events.EventEvictedMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEvictedMessage", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEvictedMessage indicates an expected call of SendEvictedMessage.
func (mr *MockMessageSenderMockRecorder) SendEvictedMessage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEvictedMessage", reflect.TypeOf((*MockMessageSender)(nil).SendEvictedMessage), arg0, arg1)
}

// SendMatchFoundMessage mocks base method.
func (m *MockMessageSender) SendMatchFoundMessage(arg0 frontend.ClientWriter, arg1 events.EventFoundMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMatchFoundMessage", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMatchFoundMessage indicates an expected call of SendMatchFoundMessage.
func (mr *MockMessageSenderMockRecorder) SendMatchFoundMessage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMatchFoundMessage", reflect.TypeOf((*MockMessageSender)(nil).SendMatchFoundMessage), arg0, arg1)
}

// SendMatchedMessage mocks base method.
func (m *MockMessageSender) SendMatchedMessage(arg0 frontend.ClientWriter, arg1 events.EventMadeMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMatchedMessage", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMatchedMessage indicates an expected call of SendMatchedMessage.
func (mr *MockMessageSenderMockRecorder) SendMatchedMessage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMatchedMessage", reflect.TypeOf((*MockMessageSender)(nil).SendMatchedMessage), arg0, arg1)
}

// SendRefusalCooldownMessage mocks base method.
func (m *MockMessageSender) SendRefusalCooldownMessage(arg0 frontend.ClientWriter, arg1 time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendRefusalCooldownMessage", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendRefusalCooldownMessage indicates an expected call of SendRefusalCooldownMessage.
func (mr *MockMessageSenderMockRecorder) SendRefusalCooldownMessage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendRefusalCooldownMessage", reflect.TypeOf((*MockMessageSender)(nil).SendRefusalCooldownMessage), arg0, arg1)
}

// SendTimeoutMessage mocks base method.
func (m *MockMessageSender) SendTimeoutMessage(arg0 frontend.ClientWriter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTimeoutMessage", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendTimeoutMessage indicates an expected call of SendTimeoutMessage.
func (mr *MockMessageSenderMockRecorder) SendTimeoutMessage(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTimeoutMessage", reflect.TypeOf((*MockMessageSender)(nil).SendTimeoutMessage), arg0)
}
