// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/frontend (interfaces: WebsocketHandler)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	websocket "github.com/gorilla/websocket"
	gomock "go.uber.org/mock/gomock"
)

// MockWebsocketHandler is a mock of WebsocketHandler interface.
type MockWebsocketHandler struct {
	ctrl     *gomock.Controller
	recorder *MockWebsocketHandlerMockRecorder
}

// MockWebsocketHandlerMockRecorder is the mock recorder for MockWebsocketHandler.
type MockWebsocketHandlerMockRecorder struct {
	mock *MockWebsocketHandler
}

// NewMockWebsocketHandler creates a new mock instance.
func NewMockWebsocketHandler(ctrl *gomock.Controller) *MockWebsocketHandler {
	mock := &MockWebsocketHandler{ctrl: ctrl}
	mock.recorder = &MockWebsocketHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebsocketHandler) EXPECT() *MockWebsocketHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockWebsocketHandler) Handle(arg0 context.Context, arg1 *websocket.Conn, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockWebsocketHandlerMockRecorder) Handle(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockWebsocketHandler)(nil).Handle), arg0, arg1, arg2)
}
