// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/frontend (interfaces: WebsocketUpgrader)

// Package mock is a generated GoMock package.
package mock

import (
	http "net/http"
	reflect "reflect"

	websocket "github.com/gorilla/websocket"
	gomock "go.uber.org/mock/gomock"
)

// MockWebsocketUpgrader is a mock of WebsocketUpgrader interface.
type MockWebsocketUpgrader struct {
	ctrl     *gomock.Controller
	recorder *MockWebsocketUpgraderMockRecorder
}

// MockWebsocketUpgraderMockRecorder is the mock recorder for MockWebsocketUpgrader.
type MockWebsocketUpgraderMockRecorder struct {
	mock *MockWebsocketUpgrader
}

// NewMockWebsocketUpgrader creates a new mock instance.
func NewMockWebsocketUpgrader(ctrl *gomock.Controller) *MockWebsocketUpgrader {
	mock := &MockWebsocketUpgrader{ctrl: ctrl}
	mock.recorder = &MockWebsocketUpgraderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebsocketUpgrader) EXPECT() *MockWebsocketUpgraderMockRecorder {
	return m.recorder
}

// Upgrade mocks base method.
func (m *MockWebsocketUpgrader) Upgrade(arg0 http.ResponseWriter, arg1 *http.Request, arg2 http.Header) (*websocket.Conn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upgrade", arg0, arg1, arg2)
	ret0, _ := ret[0].(*websocket.Conn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upgrade indicates an expected call of Upgrade.
func (mr *MockWebsocketUpgraderMockRecorder) Upgrade(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upgrade", reflect.TypeOf((*MockWebsocketUpgrader)(nil).Upgrade), arg0, arg1, arg2)
}
