// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker/matching/matchfuncs/matchvalidators/gamemodecriterias (interfaces: WaitTimeScoreCalculator)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	player "github.com/horizon-games/OpenSky/matchmaker/lib/player"
	gomock "go.uber.org/mock/gomock"
)

// MockWaitTimeScoreCalculator is a mock of WaitTimeScoreCalculator interface.
type MockWaitTimeScoreCalculator struct {
	ctrl     *gomock.Controller
	recorder *MockWaitTimeScoreCalculatorMockRecorder
}

// MockWaitTimeScoreCalculatorMockRecorder is the mock recorder for MockWaitTimeScoreCalculator.
type MockWaitTimeScoreCalculatorMockRecorder struct {
	mock *MockWaitTimeScoreCalculator
}

// NewMockWaitTimeScoreCalculator creates a new mock instance.
func NewMockWaitTimeScoreCalculator(ctrl *gomock.Controller) *MockWaitTimeScoreCalculator {
	mock := &MockWaitTimeScoreCalculator{ctrl: ctrl}
	mock.recorder = &MockWaitTimeScoreCalculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWaitTimeScoreCalculator) EXPECT() *MockWaitTimeScoreCalculatorMockRecorder {
	return m.recorder
}

// Calculate mocks base method.
func (m *MockWaitTimeScoreCalculator) Calculate(arg0 *player.Player) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Calculate", arg0)
	ret0, _ := ret[0].(int)
	return ret0
}

// Calculate indicates an expected call of Calculate.
func (mr *MockWaitTimeScoreCalculatorMockRecorder) Calculate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Calculate", reflect.TypeOf((*MockWaitTimeScoreCalculator)(nil).Calculate), arg0)
}
