// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker/matching (interfaces: Matcher)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	matchmaker "github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker"
	gomock "go.uber.org/mock/gomock"
)

// MockMatcher is a mock of Matcher interface.
type MockMatcher struct {
	ctrl     *gomock.Controller
	recorder *MockMatcherMockRecorder
}

// MockMatcherMockRecorder is the mock recorder for MockMatcher.
type MockMatcherMockRecorder struct {
	mock *MockMatcher
}

// NewMockMatcher creates a new mock instance.
func NewMockMatcher(ctrl *gomock.Controller) *MockMatcher {
	mock := &MockMatcher{ctrl: ctrl}
	mock.recorder = &MockMatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatcher) EXPECT() *MockMatcherMockRecorder {
	return m.recorder
}

// FindMatchProposals mocks base method.
func (m *MockMatcher) FindMatchProposals(arg0 context.Context, arg1 *matchmaker.FindMatchesRequest) ([]*matchmaker.MatchProposal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMatchProposals", arg0, arg1)
	ret0, _ := ret[0].([]*matchmaker.MatchProposal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMatchProposals indicates an expected call of FindMatchProposals.
func (mr *MockMatcherMockRecorder) FindMatchProposals(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMatchProposals", reflect.TypeOf((*MockMatcher)(nil).FindMatchProposals), arg0, arg1)
}
