// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/quests (interfaces: Assigner)
//
// Generated by this command:
//
//	mockgen -destination ./mock/assigner.go -package mock . Assigner
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	data "github.com/horizon-games/OpenSky/api/data"
	proto "github.com/horizon-games/OpenSky/api/proto"
	db "github.com/upper/db/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockAssigner is a mock of Assigner interface.
type MockAssigner struct {
	ctrl     *gomock.Controller
	recorder *MockAssignerMockRecorder
	isgomock struct{}
}

// MockAssignerMockRecorder is the mock recorder for MockAssigner.
type MockAssignerMockRecorder struct {
	mock *MockAssigner
}

// NewMockAssigner creates a new mock instance.
func NewMockAssigner(ctrl *gomock.Controller) *MockAssigner {
	mock := &MockAssigner{ctrl: ctrl}
	mock.recorder = &MockAssignerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAssigner) EXPECT() *MockAssignerMockRecorder {
	return m.recorder
}

// CopyToCurrentPeriod mocks base method.
func (m *MockAssigner) CopyToCurrentPeriod(arg0 db.Session, arg1 *data.QuestSpec, arg2 *data.QuestAssignment) (*proto.Quest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyToCurrentPeriod", arg0, arg1, arg2)
	ret0, _ := ret[0].(*proto.Quest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CopyToCurrentPeriod indicates an expected call of CopyToCurrentPeriod.
func (mr *MockAssignerMockRecorder) CopyToCurrentPeriod(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyToCurrentPeriod", reflect.TypeOf((*MockAssigner)(nil).CopyToCurrentPeriod), arg0, arg1, arg2)
}

// MoveUpInEpic mocks base method.
func (m *MockAssigner) MoveUpInEpic(arg0 db.Session, arg1 *data.QuestSpec, arg2 *data.QuestAssignment) (*proto.Quest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveUpInEpic", arg0, arg1, arg2)
	ret0, _ := ret[0].(*proto.Quest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveUpInEpic indicates an expected call of MoveUpInEpic.
func (mr *MockAssignerMockRecorder) MoveUpInEpic(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveUpInEpic", reflect.TypeOf((*MockAssigner)(nil).MoveUpInEpic), arg0, arg1, arg2)
}

// RollNew mocks base method.
func (m *MockAssigner) RollNew(sess db.Session, accountID proto.AccountID, periodicity proto.QuestPeriodicity, position data.QuestPosition, prevSpec *data.QuestSpec, prevAssignment *data.QuestAssignment) (*proto.Quest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollNew", sess, accountID, periodicity, position, prevSpec, prevAssignment)
	ret0, _ := ret[0].(*proto.Quest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RollNew indicates an expected call of RollNew.
func (mr *MockAssignerMockRecorder) RollNew(sess, accountID, periodicity, position, prevSpec, prevAssignment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollNew", reflect.TypeOf((*MockAssigner)(nil).RollNew), sess, accountID, periodicity, position, prevSpec, prevAssignment)
}
