// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/quests (interfaces: DueChecker)
//
// Generated by this command:
//
//	mockgen -destination ./mock/due_checker.go -package mock . DueChecker
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	data "github.com/horizon-games/OpenSky/api/data"
	gomock "go.uber.org/mock/gomock"
)

// MockDueChecker is a mock of DueChecker interface.
type MockDueChecker struct {
	ctrl     *gomock.Controller
	recorder *MockDueCheckerMockRecorder
	isgomock struct{}
}

// MockDueCheckerMockRecorder is the mock recorder for MockDueChecker.
type MockDueCheckerMockRecorder struct {
	mock *MockDueChecker
}

// NewMockDueChecker creates a new mock instance.
func NewMockDueChecker(ctrl *gomock.Controller) *MockDueChecker {
	mock := &MockDueChecker{ctrl: ctrl}
	mock.recorder = &MockDueCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDueChecker) EXPECT() *MockDueCheckerMockRecorder {
	return m.recorder
}

// IsDueToAutoReRoll mocks base method.
func (m *MockDueChecker) IsDueToAutoReRoll(arg0 *data.QuestSpec, arg1 *data.QuestAssignment) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDueToAutoReRoll", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDueToAutoReRoll indicates an expected call of IsDueToAutoReRoll.
func (mr *MockDueCheckerMockRecorder) IsDueToAutoReRoll(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDueToAutoReRoll", reflect.TypeOf((*MockDueChecker)(nil).IsDueToAutoReRoll), arg0, arg1)
}

// IsDueToCopyToCurrentPeriod mocks base method.
func (m *MockDueChecker) IsDueToCopyToCurrentPeriod(arg0 *data.QuestSpec, arg1 *data.QuestAssignment) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDueToCopyToCurrentPeriod", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDueToCopyToCurrentPeriod indicates an expected call of IsDueToCopyToCurrentPeriod.
func (mr *MockDueCheckerMockRecorder) IsDueToCopyToCurrentPeriod(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDueToCopyToCurrentPeriod", reflect.TypeOf((*MockDueChecker)(nil).IsDueToCopyToCurrentPeriod), arg0, arg1)
}
