// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/quests (interfaces: MetricsCollector)
//
// Generated by this command:
//
//	mockgen -destination ./mock/metrics_collector.go -package mock . MetricsCollector
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	data "github.com/horizon-games/OpenSky/api/data"
	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockMetricsCollector is a mock of MetricsCollector interface.
type MockMetricsCollector struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsCollectorMockRecorder
	isgomock struct{}
}

// MockMetricsCollectorMockRecorder is the mock recorder for MockMetricsCollector.
type MockMetricsCollectorMockRecorder struct {
	mock *MockMetricsCollector
}

// NewMockMetricsCollector creates a new mock instance.
func NewMockMetricsCollector(ctrl *gomock.Controller) *MockMetricsCollector {
	mock := &MockMetricsCollector{ctrl: ctrl}
	mock.recorder = &MockMetricsCollectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsCollector) EXPECT() *MockMetricsCollectorMockRecorder {
	return m.recorder
}

// TrackQuestAutoReRoll mocks base method.
func (m *MockMetricsCollector) TrackQuestAutoReRoll(arg0 proto.QuestPeriodicity, arg1 data.QuestPosition) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackQuestAutoReRoll", arg0, arg1)
}

// TrackQuestAutoReRoll indicates an expected call of TrackQuestAutoReRoll.
func (mr *MockMetricsCollectorMockRecorder) TrackQuestAutoReRoll(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackQuestAutoReRoll", reflect.TypeOf((*MockMetricsCollector)(nil).TrackQuestAutoReRoll), arg0, arg1)
}

// TrackQuestCopyToCurrentPeriod mocks base method.
func (m *MockMetricsCollector) TrackQuestCopyToCurrentPeriod(arg0 proto.QuestPeriodicity, arg1 data.QuestPosition) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackQuestCopyToCurrentPeriod", arg0, arg1)
}

// TrackQuestCopyToCurrentPeriod indicates an expected call of TrackQuestCopyToCurrentPeriod.
func (mr *MockMetricsCollectorMockRecorder) TrackQuestCopyToCurrentPeriod(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackQuestCopyToCurrentPeriod", reflect.TypeOf((*MockMetricsCollector)(nil).TrackQuestCopyToCurrentPeriod), arg0, arg1)
}

// TrackQuestManualClaim mocks base method.
func (m *MockMetricsCollector) TrackQuestManualClaim(arg0 proto.QuestPeriodicity) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackQuestManualClaim", arg0)
}

// TrackQuestManualClaim indicates an expected call of TrackQuestManualClaim.
func (mr *MockMetricsCollectorMockRecorder) TrackQuestManualClaim(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackQuestManualClaim", reflect.TypeOf((*MockMetricsCollector)(nil).TrackQuestManualClaim), arg0)
}

// TrackQuestManualReRoll mocks base method.
func (m *MockMetricsCollector) TrackQuestManualReRoll(periodicity proto.QuestPeriodicity, position data.QuestPosition, reroll uint16) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackQuestManualReRoll", periodicity, position, reroll)
}

// TrackQuestManualReRoll indicates an expected call of TrackQuestManualReRoll.
func (mr *MockMetricsCollectorMockRecorder) TrackQuestManualReRoll(periodicity, position, reroll any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackQuestManualReRoll", reflect.TypeOf((*MockMetricsCollector)(nil).TrackQuestManualReRoll), periodicity, position, reroll)
}

// TrackQuestMoveUpInEpic mocks base method.
func (m *MockMetricsCollector) TrackQuestMoveUpInEpic(arg0 proto.QuestPeriodicity, arg1 data.QuestPosition) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackQuestMoveUpInEpic", arg0, arg1)
}

// TrackQuestMoveUpInEpic indicates an expected call of TrackQuestMoveUpInEpic.
func (mr *MockMetricsCollectorMockRecorder) TrackQuestMoveUpInEpic(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackQuestMoveUpInEpic", reflect.TypeOf((*MockMetricsCollector)(nil).TrackQuestMoveUpInEpic), arg0, arg1)
}
