// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/quests (interfaces: ReRoller)
//
// Generated by this command:
//
//	mockgen -destination ./mock/reroller.go -package mock . ReRoller
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	data "github.com/horizon-games/OpenSky/api/data"
	proto "github.com/horizon-games/OpenSky/api/proto"
	db "github.com/upper/db/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockReRoller is a mock of ReRoller interface.
type MockReRoller struct {
	ctrl     *gomock.Controller
	recorder *MockReRollerMockRecorder
	isgomock struct{}
}

// MockReRollerMockRecorder is the mock recorder for MockReRoller.
type MockReRollerMockRecorder struct {
	mock *MockReRoller
}

// NewMockReRoller creates a new mock instance.
func NewMockReRoller(ctrl *gomock.Controller) *MockReRoller {
	mock := &MockReRoller{ctrl: ctrl}
	mock.recorder = &MockReRollerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReRoller) EXPECT() *MockReRollerMockRecorder {
	return m.recorder
}

// AutoReRoll mocks base method.
func (m *MockReRoller) AutoReRoll(arg0 context.Context, arg1 db.Session, arg2 *data.QuestSpec, arg3 *data.QuestAssignment) (*proto.Quest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AutoReRoll", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*proto.Quest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AutoReRoll indicates an expected call of AutoReRoll.
func (mr *MockReRollerMockRecorder) AutoReRoll(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AutoReRoll", reflect.TypeOf((*MockReRoller)(nil).AutoReRoll), arg0, arg1, arg2, arg3)
}
