// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/quests (interfaces: XPUpdater)
//
// Generated by this command:
//
//	mockgen -destination ./mock/xp_updater.go -package mock . XPUpdater
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	db "github.com/upper/db/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockXPUpdater is a mock of XPUpdater interface.
type MockXPUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockXPUpdaterMockRecorder
	isgomock struct{}
}

// MockXPUpdaterMockRecorder is the mock recorder for MockXPUpdater.
type MockXPUpdaterMockRecorder struct {
	mock *MockXPUpdater
}

// NewMockXPUpdater creates a new mock instance.
func NewMockXPUpdater(ctrl *gomock.Controller) *MockXPUpdater {
	mock := &MockXPUpdater{ctrl: ctrl}
	mock.recorder = &MockXPUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockXPUpdater) EXPECT() *MockXPUpdaterMockRecorder {
	return m.recorder
}

// UpdateFromQuest mocks base method.
func (m *MockXPUpdater) UpdateFromQuest(arg0 db.Session, arg1 proto.AccountID, arg2 *proto.QuestReward) ([]*proto.FeedEvent, []*proto.Reward, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFromQuest", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*proto.FeedEvent)
	ret1, _ := ret[1].([]*proto.Reward)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateFromQuest indicates an expected call of UpdateFromQuest.
func (mr *MockXPUpdaterMockRecorder) UpdateFromQuest(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFromQuest", reflect.TypeOf((*MockXPUpdater)(nil).UpdateFromQuest), arg0, arg1, arg2)
}
