// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/rpc (interfaces: AccountAssetTransferer)
//
// Generated by this command:
//
//	mockgen -destination ./mock/account_asset_transferer.go -package mock . AccountAssetTransferer
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountAssetTransferer is a mock of AccountAssetTransferer interface.
type MockAccountAssetTransferer struct {
	ctrl     *gomock.Controller
	recorder *MockAccountAssetTransfererMockRecorder
	isgomock struct{}
}

// MockAccountAssetTransfererMockRecorder is the mock recorder for MockAccountAssetTransferer.
type MockAccountAssetTransfererMockRecorder struct {
	mock *MockAccountAssetTransferer
}

// NewMockAccountAssetTransferer creates a new mock instance.
func NewMockAccountAssetTransferer(ctrl *gomock.Controller) *MockAccountAssetTransferer {
	mock := &MockAccountAssetTransferer{ctrl: ctrl}
	mock.recorder = &MockAccountAssetTransfererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountAssetTransferer) EXPECT() *MockAccountAssetTransfererMockRecorder {
	return m.recorder
}

// ComposeTransactionToTransferFromBurner mocks base method.
func (m *MockAccountAssetTransferer) ComposeTransactionToTransferFromBurner(arg0 context.Context, arg1 proto.AccountID) ([]*proto.OnChainTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComposeTransactionToTransferFromBurner", arg0, arg1)
	ret0, _ := ret[0].([]*proto.OnChainTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ComposeTransactionToTransferFromBurner indicates an expected call of ComposeTransactionToTransferFromBurner.
func (mr *MockAccountAssetTransfererMockRecorder) ComposeTransactionToTransferFromBurner(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComposeTransactionToTransferFromBurner", reflect.TypeOf((*MockAccountAssetTransferer)(nil).ComposeTransactionToTransferFromBurner), arg0, arg1)
}
