// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/rpc (interfaces: AccountRegisterer)
//
// Generated by this command:
//
//	mockgen -destination ./mock/account_registerer.go -package mock . AccountRegisterer
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	data "github.com/horizon-games/OpenSky/api/data"
	proto "github.com/horizon-games/OpenSky/api/proto"
	db "github.com/upper/db/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountRegisterer is a mock of AccountRegisterer interface.
type MockAccountRegisterer struct {
	ctrl     *gomock.Controller
	recorder *MockAccountRegistererMockRecorder
	isgomock struct{}
}

// MockAccountRegistererMockRecorder is the mock recorder for MockAccountRegisterer.
type MockAccountRegistererMockRecorder struct {
	mock *MockAccountRegisterer
}

// NewMockAccountRegisterer creates a new mock instance.
func NewMockAccountRegisterer(ctrl *gomock.Controller) *MockAccountRegisterer {
	mock := &MockAccountRegisterer{ctrl: ctrl}
	mock.recorder = &MockAccountRegistererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountRegisterer) EXPECT() *MockAccountRegistererMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockAccountRegisterer) Register(arg0 context.Context, arg1 db.Session, arg2 *proto.AccountRegistration) (*data.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", arg0, arg1, arg2)
	ret0, _ := ret[0].(*data.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockAccountRegistererMockRecorder) Register(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAccountRegisterer)(nil).Register), arg0, arg1, arg2)
}
