// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/rpc (interfaces: ConquestExiter)
//
// Generated by this command:
//
//	mockgen -destination ./mock/conquest_exiter.go -package mock . ConquestExiter
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	db "github.com/upper/db/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockConquestExiter is a mock of ConquestExiter interface.
type MockConquestExiter struct {
	ctrl     *gomock.Controller
	recorder *MockConquestExiterMockRecorder
	isgomock struct{}
}

// MockConquestExiterMockRecorder is the mock recorder for MockConquestExiter.
type MockConquestExiterMockRecorder struct {
	mock *MockConquestExiter
}

// NewMockConquestExiter creates a new mock instance.
func NewMockConquestExiter(ctrl *gomock.Controller) *MockConquestExiter {
	mock := &MockConquestExiter{ctrl: ctrl}
	mock.recorder = &MockConquestExiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConquestExiter) EXPECT() *MockConquestExiterMockRecorder {
	return m.recorder
}

// Exit mocks base method.
func (m *MockConquestExiter) Exit(arg0 context.Context, arg1 db.Session, arg2 proto.Hash) ([]*proto.FeedEvent, []*proto.Reward, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exit", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*proto.FeedEvent)
	ret1, _ := ret[1].([]*proto.Reward)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Exit indicates an expected call of Exit.
func (mr *MockConquestExiterMockRecorder) Exit(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exit", reflect.TypeOf((*MockConquestExiter)(nil).Exit), arg0, arg1, arg2)
}
