// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/rpc (interfaces: ConquestV2SummaryGetter)
//
// Generated by this command:
//
//	mockgen -destination ./mock/conquest_v2_summary_getter.go -package mock . ConquestV2SummaryGetter
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockConquestV2SummaryGetter is a mock of ConquestV2SummaryGetter interface.
type MockConquestV2SummaryGetter struct {
	ctrl     *gomock.Controller
	recorder *MockConquestV2SummaryGetterMockRecorder
	isgomock struct{}
}

// MockConquestV2SummaryGetterMockRecorder is the mock recorder for MockConquestV2SummaryGetter.
type MockConquestV2SummaryGetterMockRecorder struct {
	mock *MockConquestV2SummaryGetter
}

// NewMockConquestV2SummaryGetter creates a new mock instance.
func NewMockConquestV2SummaryGetter(ctrl *gomock.Controller) *MockConquestV2SummaryGetter {
	mock := &MockConquestV2SummaryGetter{ctrl: ctrl}
	mock.recorder = &MockConquestV2SummaryGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConquestV2SummaryGetter) EXPECT() *MockConquestV2SummaryGetterMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockConquestV2SummaryGetter) Get(arg0 context.Context) (*proto.ConquestV2Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(*proto.ConquestV2Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockConquestV2SummaryGetterMockRecorder) Get(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockConquestV2SummaryGetter)(nil).Get), arg0)
}
