// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/rpc (interfaces: ConquestAccountStatUpdater)
//
// Generated by this command:
//
//	mockgen -destination ./mock/conquest_account_stat_updater.go -package mock . ConquestAccountStatUpdater
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	data "github.com/horizon-games/OpenSky/api/data"
	proto "github.com/horizon-games/OpenSky/api/proto"
	db "github.com/upper/db/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockConquestAccountStatUpdater is a mock of ConquestAccountStatUpdater interface.
type MockConquestAccountStatUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockConquestAccountStatUpdaterMockRecorder
	isgomock struct{}
}

// MockConquestAccountStatUpdaterMockRecorder is the mock recorder for MockConquestAccountStatUpdater.
type MockConquestAccountStatUpdaterMockRecorder struct {
	mock *MockConquestAccountStatUpdater
}

// NewMockConquestAccountStatUpdater creates a new mock instance.
func NewMockConquestAccountStatUpdater(ctrl *gomock.Controller) *MockConquestAccountStatUpdater {
	mock := &MockConquestAccountStatUpdater{ctrl: ctrl}
	mock.recorder = &MockConquestAccountStatUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConquestAccountStatUpdater) EXPECT() *MockConquestAccountStatUpdaterMockRecorder {
	return m.recorder
}

// RecalculateScore mocks base method.
func (m *MockConquestAccountStatUpdater) RecalculateScore(ctx context.Context, sess db.Session, mode proto.GameMode, season uint16, account *data.Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecalculateScore", ctx, sess, mode, season, account)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecalculateScore indicates an expected call of RecalculateScore.
func (mr *MockConquestAccountStatUpdaterMockRecorder) RecalculateScore(ctx, sess, mode, season, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecalculateScore", reflect.TypeOf((*MockConquestAccountStatUpdater)(nil).RecalculateScore), ctx, sess, mode, season, account)
}
