// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/rpc (interfaces: ConquestStateManager)
//
// Generated by this command:
//
//	mockgen -destination ./mock/conquest_state_manager.go -package mock . ConquestStateManager
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	db "github.com/upper/db/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockConquestStateManager is a mock of ConquestStateManager interface.
type MockConquestStateManager struct {
	ctrl     *gomock.Controller
	recorder *MockConquestStateManagerMockRecorder
	isgomock struct{}
}

// MockConquestStateManagerMockRecorder is the mock recorder for MockConquestStateManager.
type MockConquestStateManagerMockRecorder struct {
	mock *MockConquestStateManager
}

// NewMockConquestStateManager creates a new mock instance.
func NewMockConquestStateManager(ctrl *gomock.Controller) *MockConquestStateManager {
	mock := &MockConquestStateManager{ctrl: ctrl}
	mock.recorder = &MockConquestStateManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConquestStateManager) EXPECT() *MockConquestStateManagerMockRecorder {
	return m.recorder
}

// Enter mocks base method.
func (m *MockConquestStateManager) Enter(arg0 context.Context, arg1 proto.AccountID, arg2 proto.Hero) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enter", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enter indicates an expected call of Enter.
func (mr *MockConquestStateManagerMockRecorder) Enter(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enter", reflect.TypeOf((*MockConquestStateManager)(nil).Enter), arg0, arg1, arg2)
}

// UpdateProgress mocks base method.
func (m *MockConquestStateManager) UpdateProgress(arg0 context.Context, arg1 db.Session, arg2 proto.AccountID, arg3 uint64, arg4 proto.ConquestMatchResult) ([]*proto.FeedEvent, []*proto.Reward, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProgress", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*proto.FeedEvent)
	ret1, _ := ret[1].([]*proto.Reward)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateProgress indicates an expected call of UpdateProgress.
func (mr *MockConquestStateManagerMockRecorder) UpdateProgress(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProgress", reflect.TypeOf((*MockConquestStateManager)(nil).UpdateProgress), arg0, arg1, arg2, arg3, arg4)
}
