// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/rpc (interfaces: ConquestV2PointsUpdater)
//
// Generated by this command:
//
//	mockgen -destination ./mock/conquest_v2_points_updater.go -package mock . ConquestV2PointsUpdater
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	data "github.com/horizon-games/OpenSky/api/data"
	proto "github.com/horizon-games/OpenSky/api/proto"
	db "github.com/upper/db/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockConquestV2PointsUpdater is a mock of ConquestV2PointsUpdater interface.
type MockConquestV2PointsUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockConquestV2PointsUpdaterMockRecorder
	isgomock struct{}
}

// MockConquestV2PointsUpdaterMockRecorder is the mock recorder for MockConquestV2PointsUpdater.
type MockConquestV2PointsUpdaterMockRecorder struct {
	mock *MockConquestV2PointsUpdater
}

// NewMockConquestV2PointsUpdater creates a new mock instance.
func NewMockConquestV2PointsUpdater(ctrl *gomock.Controller) *MockConquestV2PointsUpdater {
	mock := &MockConquestV2PointsUpdater{ctrl: ctrl}
	mock.recorder = &MockConquestV2PointsUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConquestV2PointsUpdater) EXPECT() *MockConquestV2PointsUpdaterMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MockConquestV2PointsUpdater) Update(arg0 context.Context, arg1 db.Session, arg2 *data.Match) ([]*proto.FeedEvent, []*proto.Reward, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*proto.FeedEvent)
	ret1, _ := ret[1].([]*proto.Reward)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Update indicates an expected call of Update.
func (mr *MockConquestV2PointsUpdaterMockRecorder) Update(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockConquestV2PointsUpdater)(nil).Update), arg0, arg1, arg2)
}
