// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/rpc (interfaces: DiscordClient)
//
// Generated by this command:
//
//	mockgen -destination ./mock/discord_client.go -package mock . DiscordClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	rpc "github.com/horizon-games/OpenSky/api/rpc"
	gomock "go.uber.org/mock/gomock"
)

// MockDiscordClient is a mock of DiscordClient interface.
type MockDiscordClient struct {
	ctrl     *gomock.Controller
	recorder *MockDiscordClientMockRecorder
	isgomock struct{}
}

// MockDiscordClientMockRecorder is the mock recorder for MockDiscordClient.
type MockDiscordClientMockRecorder struct {
	mock *MockDiscordClient
}

// NewMockDiscordClient creates a new mock instance.
func NewMockDiscordClient(ctrl *gomock.Controller) *MockDiscordClient {
	mock := &MockDiscordClient{ctrl: ctrl}
	mock.recorder = &MockDiscordClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscordClient) EXPECT() *MockDiscordClientMockRecorder {
	return m.recorder
}

// GetServerInfo mocks base method.
func (m *MockDiscordClient) GetServerInfo(arg0 context.Context) (*rpc.DiscordAPIResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerInfo", arg0)
	ret0, _ := ret[0].(*rpc.DiscordAPIResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerInfo indicates an expected call of GetServerInfo.
func (mr *MockDiscordClientMockRecorder) GetServerInfo(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerInfo", reflect.TypeOf((*MockDiscordClient)(nil).GetServerInfo), arg0)
}
