// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/rpc (interfaces: GrandmastersRecalculator)
//
// Generated by this command:
//
//	mockgen -destination ./mock/grandmasters_recalculator.go -package mock . GrandmastersRecalculator
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	db "github.com/upper/db/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockGrandmastersRecalculator is a mock of GrandmastersRecalculator interface.
type MockGrandmastersRecalculator struct {
	ctrl     *gomock.Controller
	recorder *MockGrandmastersRecalculatorMockRecorder
	isgomock struct{}
}

// MockGrandmastersRecalculatorMockRecorder is the mock recorder for MockGrandmastersRecalculator.
type MockGrandmastersRecalculatorMockRecorder struct {
	mock *MockGrandmastersRecalculator
}

// NewMockGrandmastersRecalculator creates a new mock instance.
func NewMockGrandmastersRecalculator(ctrl *gomock.Controller) *MockGrandmastersRecalculator {
	mock := &MockGrandmastersRecalculator{ctrl: ctrl}
	mock.recorder = &MockGrandmastersRecalculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGrandmastersRecalculator) EXPECT() *MockGrandmastersRecalculatorMockRecorder {
	return m.recorder
}

// Recalculate mocks base method.
func (m *MockGrandmastersRecalculator) Recalculate(sess db.Session, season uint16) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recalculate", sess, season)
	ret0, _ := ret[0].(error)
	return ret0
}

// Recalculate indicates an expected call of Recalculate.
func (mr *MockGrandmastersRecalculatorMockRecorder) Recalculate(sess, season any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recalculate", reflect.TypeOf((*MockGrandmastersRecalculator)(nil).Recalculate), sess, season)
}
