// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/rpc (interfaces: MatchRecorder)
//
// Generated by this command:
//
//	mockgen -destination ./mock/match_recorder.go -package mock . MatchRecorder
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockMatchRecorder is a mock of MatchRecorder interface.
type MockMatchRecorder struct {
	ctrl     *gomock.Controller
	recorder *MockMatchRecorderMockRecorder
	isgomock struct{}
}

// MockMatchRecorderMockRecorder is the mock recorder for MockMatchRecorder.
type MockMatchRecorderMockRecorder struct {
	mock *MockMatchRecorder
}

// NewMockMatchRecorder creates a new mock instance.
func NewMockMatchRecorder(ctrl *gomock.Controller) *MockMatchRecorder {
	mock := &MockMatchRecorder{ctrl: ctrl}
	mock.recorder = &MockMatchRecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchRecorder) EXPECT() *MockMatchRecorderMockRecorder {
	return m.recorder
}

// ArchiveURI mocks base method.
func (m *MockMatchRecorder) ArchiveURI(matchID uint64, index int64) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArchiveURI", matchID, index)
	ret0, _ := ret[0].(string)
	return ret0
}

// ArchiveURI indicates an expected call of ArchiveURI.
func (mr *MockMatchRecorderMockRecorder) ArchiveURI(matchID, index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArchiveURI", reflect.TypeOf((*MockMatchRecorder)(nil).ArchiveURI), matchID, index)
}

// GetSignedRecordsURLs mocks base method.
func (m *MockMatchRecorder) GetSignedRecordsURLs(matchID uint64, expiration time.Duration) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSignedRecordsURLs", matchID, expiration)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSignedRecordsURLs indicates an expected call of GetSignedRecordsURLs.
func (mr *MockMatchRecorderMockRecorder) GetSignedRecordsURLs(matchID, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSignedRecordsURLs", reflect.TypeOf((*MockMatchRecorder)(nil).GetSignedRecordsURLs), matchID, expiration)
}

// LiveURI mocks base method.
func (m *MockMatchRecorder) LiveURI(matchID uint64, index int64) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LiveURI", matchID, index)
	ret0, _ := ret[0].(string)
	return ret0
}

// LiveURI indicates an expected call of LiveURI.
func (mr *MockMatchRecorderMockRecorder) LiveURI(matchID, index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LiveURI", reflect.TypeOf((*MockMatchRecorder)(nil).LiveURI), matchID, index)
}

// UploadArchiveRecords mocks base method.
func (m *MockMatchRecorder) UploadArchiveRecords(matchID uint64, index int64, jsonStringData string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadArchiveRecords", matchID, index, jsonStringData)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadArchiveRecords indicates an expected call of UploadArchiveRecords.
func (mr *MockMatchRecorderMockRecorder) UploadArchiveRecords(matchID, index, jsonStringData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadArchiveRecords", reflect.TypeOf((*MockMatchRecorder)(nil).UploadArchiveRecords), matchID, index, jsonStringData)
}
