// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/rpc (interfaces: OnChainTransactionComposer)
//
// Generated by this command:
//
//	mockgen -destination ./mock/onchain_transaction_composer.go -package mock . OnChainTransactionComposer
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockOnChainTransactionComposer is a mock of OnChainTransactionComposer interface.
type MockOnChainTransactionComposer struct {
	ctrl     *gomock.Controller
	recorder *MockOnChainTransactionComposerMockRecorder
	isgomock struct{}
}

// MockOnChainTransactionComposerMockRecorder is the mock recorder for MockOnChainTransactionComposer.
type MockOnChainTransactionComposerMockRecorder struct {
	mock *MockOnChainTransactionComposer
}

// NewMockOnChainTransactionComposer creates a new mock instance.
func NewMockOnChainTransactionComposer(ctrl *gomock.Controller) *MockOnChainTransactionComposer {
	mock := &MockOnChainTransactionComposer{ctrl: ctrl}
	mock.recorder = &MockOnChainTransactionComposerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOnChainTransactionComposer) EXPECT() *MockOnChainTransactionComposerMockRecorder {
	return m.recorder
}

// ComposeERC1155 mocks base method.
func (m *MockOnChainTransactionComposer) ComposeERC1155(ctx context.Context, accountID proto.AccountID, productID string, quantity uint64, tokenIDsToBurn []uint64) ([]*proto.OnChainTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComposeERC1155", ctx, accountID, productID, quantity, tokenIDsToBurn)
	ret0, _ := ret[0].([]*proto.OnChainTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ComposeERC1155 indicates an expected call of ComposeERC1155.
func (mr *MockOnChainTransactionComposerMockRecorder) ComposeERC1155(ctx, accountID, productID, quantity, tokenIDsToBurn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComposeERC1155", reflect.TypeOf((*MockOnChainTransactionComposer)(nil).ComposeERC1155), ctx, accountID, productID, quantity, tokenIDsToBurn)
}

// ComposeERC20 mocks base method.
func (m *MockOnChainTransactionComposer) ComposeERC20(ctx context.Context, accountID proto.AccountID, productID string, quantity uint64) ([]*proto.OnChainTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComposeERC20", ctx, accountID, productID, quantity)
	ret0, _ := ret[0].([]*proto.OnChainTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ComposeERC20 indicates an expected call of ComposeERC20.
func (mr *MockOnChainTransactionComposerMockRecorder) ComposeERC20(ctx, accountID, productID, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComposeERC20", reflect.TypeOf((*MockOnChainTransactionComposer)(nil).ComposeERC20), ctx, accountID, productID, quantity)
}
