// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/rpc (interfaces: OneTimeNotificationChecker)
//
// Generated by this command:
//
//	mockgen -destination ./mock/onetime_notification_checker.go -package mock . OneTimeNotificationChecker
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	data "github.com/horizon-games/OpenSky/api/data"
	gomock "go.uber.org/mock/gomock"
)

// MockOneTimeNotificationChecker is a mock of OneTimeNotificationChecker interface.
type MockOneTimeNotificationChecker struct {
	ctrl     *gomock.Controller
	recorder *MockOneTimeNotificationCheckerMockRecorder
	isgomock struct{}
}

// MockOneTimeNotificationCheckerMockRecorder is the mock recorder for MockOneTimeNotificationChecker.
type MockOneTimeNotificationCheckerMockRecorder struct {
	mock *MockOneTimeNotificationChecker
}

// NewMockOneTimeNotificationChecker creates a new mock instance.
func NewMockOneTimeNotificationChecker(ctrl *gomock.Controller) *MockOneTimeNotificationChecker {
	mock := &MockOneTimeNotificationChecker{ctrl: ctrl}
	mock.recorder = &MockOneTimeNotificationCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOneTimeNotificationChecker) EXPECT() *MockOneTimeNotificationCheckerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockOneTimeNotificationChecker) Check(arg0 *data.Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockOneTimeNotificationCheckerMockRecorder) Check(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockOneTimeNotificationChecker)(nil).Check), arg0)
}
