// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/rpc (interfaces: PaymentProviderResponseVerifier)
//
// Generated by this command:
//
//	mockgen -destination ./mock/payment_provider_response_verifier.go -package mock . PaymentProviderResponseVerifier
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockPaymentProviderResponseVerifier is a mock of PaymentProviderResponseVerifier interface.
type MockPaymentProviderResponseVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentProviderResponseVerifierMockRecorder
	isgomock struct{}
}

// MockPaymentProviderResponseVerifierMockRecorder is the mock recorder for MockPaymentProviderResponseVerifier.
type MockPaymentProviderResponseVerifierMockRecorder struct {
	mock *MockPaymentProviderResponseVerifier
}

// NewMockPaymentProviderResponseVerifier creates a new mock instance.
func NewMockPaymentProviderResponseVerifier(ctrl *gomock.Controller) *MockPaymentProviderResponseVerifier {
	mock := &MockPaymentProviderResponseVerifier{ctrl: ctrl}
	mock.recorder = &MockPaymentProviderResponseVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentProviderResponseVerifier) EXPECT() *MockPaymentProviderResponseVerifierMockRecorder {
	return m.recorder
}

// VerifyAppleAppStorePayment mocks base method.
func (m *MockPaymentProviderResponseVerifier) VerifyAppleAppStorePayment(arg0 context.Context, arg1 proto.AccountID, arg2 *proto.AppleAppStorePaymentResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyAppleAppStorePayment", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyAppleAppStorePayment indicates an expected call of VerifyAppleAppStorePayment.
func (mr *MockPaymentProviderResponseVerifierMockRecorder) VerifyAppleAppStorePayment(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAppleAppStorePayment", reflect.TypeOf((*MockPaymentProviderResponseVerifier)(nil).VerifyAppleAppStorePayment), arg0, arg1, arg2)
}

// VerifyGooglePlayPayment mocks base method.
func (m *MockPaymentProviderResponseVerifier) VerifyGooglePlayPayment(arg0 context.Context, arg1 proto.AccountID, arg2 *proto.GooglePlayPaymentResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyGooglePlayPayment", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyGooglePlayPayment indicates an expected call of VerifyGooglePlayPayment.
func (mr *MockPaymentProviderResponseVerifierMockRecorder) VerifyGooglePlayPayment(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyGooglePlayPayment", reflect.TypeOf((*MockPaymentProviderResponseVerifier)(nil).VerifyGooglePlayPayment), arg0, arg1, arg2)
}

// VerifySamsungGalaxyStorePayment mocks base method.
func (m *MockPaymentProviderResponseVerifier) VerifySamsungGalaxyStorePayment(arg0 context.Context, arg1 proto.AccountID, arg2 *proto.SamsungGalaxyStorePaymentResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifySamsungGalaxyStorePayment", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifySamsungGalaxyStorePayment indicates an expected call of VerifySamsungGalaxyStorePayment.
func (mr *MockPaymentProviderResponseVerifierMockRecorder) VerifySamsungGalaxyStorePayment(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifySamsungGalaxyStorePayment", reflect.TypeOf((*MockPaymentProviderResponseVerifier)(nil).VerifySamsungGalaxyStorePayment), arg0, arg1, arg2)
}
