// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/rpc (interfaces: PaymentIntentCreator)
//
// Generated by this command:
//
//	mockgen -destination ./mock/payment_intent_creator.go -package mock . PaymentIntentCreator
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockPaymentIntentCreator is a mock of PaymentIntentCreator interface.
type MockPaymentIntentCreator struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentIntentCreatorMockRecorder
	isgomock struct{}
}

// MockPaymentIntentCreatorMockRecorder is the mock recorder for MockPaymentIntentCreator.
type MockPaymentIntentCreatorMockRecorder struct {
	mock *MockPaymentIntentCreator
}

// NewMockPaymentIntentCreator creates a new mock instance.
func NewMockPaymentIntentCreator(ctrl *gomock.Controller) *MockPaymentIntentCreator {
	mock := &MockPaymentIntentCreator{ctrl: ctrl}
	mock.recorder = &MockPaymentIntentCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentIntentCreator) EXPECT() *MockPaymentIntentCreatorMockRecorder {
	return m.recorder
}

// CreateStripeIntent mocks base method.
func (m *MockPaymentIntentCreator) CreateStripeIntent(ctx context.Context, accountID proto.AccountID, productID string) (*proto.StripeCheckout, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStripeIntent", ctx, accountID, productID)
	ret0, _ := ret[0].(*proto.StripeCheckout)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStripeIntent indicates an expected call of CreateStripeIntent.
func (mr *MockPaymentIntentCreatorMockRecorder) CreateStripeIntent(ctx, accountID, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStripeIntent", reflect.TypeOf((*MockPaymentIntentCreator)(nil).CreateStripeIntent), ctx, accountID, productID)
}
