// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/rpc (interfaces: QuestsLister)
//
// Generated by this command:
//
//	mockgen -destination ./mock/quests_lister.go -package mock . QuestsLister
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	db "github.com/upper/db/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockQuestsLister is a mock of QuestsLister interface.
type MockQuestsLister struct {
	ctrl     *gomock.Controller
	recorder *MockQuestsListerMockRecorder
	isgomock struct{}
}

// MockQuestsListerMockRecorder is the mock recorder for MockQuestsLister.
type MockQuestsListerMockRecorder struct {
	mock *MockQuestsLister
}

// NewMockQuestsLister creates a new mock instance.
func NewMockQuestsLister(ctrl *gomock.Controller) *MockQuestsLister {
	mock := &MockQuestsLister{ctrl: ctrl}
	mock.recorder = &MockQuestsListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuestsLister) EXPECT() *MockQuestsListerMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockQuestsLister) List(arg0 context.Context, arg1 db.Session, arg2 proto.AccountID) ([]*proto.Quest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*proto.Quest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockQuestsListerMockRecorder) List(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockQuestsLister)(nil).List), arg0, arg1, arg2)
}

// ListEpicChain mocks base method.
func (m *MockQuestsLister) ListEpicChain(arg0 db.Session, arg1 proto.AccountID, arg2 proto.EpicType) ([]*proto.Quest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEpicChain", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*proto.Quest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEpicChain indicates an expected call of ListEpicChain.
func (mr *MockQuestsListerMockRecorder) ListEpicChain(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEpicChain", reflect.TypeOf((*MockQuestsLister)(nil).ListEpicChain), arg0, arg1, arg2)
}
