// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/rpc (interfaces: QuestsReRoller)
//
// Generated by this command:
//
//	mockgen -destination ./mock/quests_reroller.go -package mock . QuestsReRoller
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	db "github.com/upper/db/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockQuestsReRoller is a mock of QuestsReRoller interface.
type MockQuestsReRoller struct {
	ctrl     *gomock.Controller
	recorder *MockQuestsReRollerMockRecorder
	isgomock struct{}
}

// MockQuestsReRollerMockRecorder is the mock recorder for MockQuestsReRoller.
type MockQuestsReRollerMockRecorder struct {
	mock *MockQuestsReRoller
}

// NewMockQuestsReRoller creates a new mock instance.
func NewMockQuestsReRoller(ctrl *gomock.Controller) *MockQuestsReRoller {
	mock := &MockQuestsReRoller{ctrl: ctrl}
	mock.recorder = &MockQuestsReRollerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuestsReRoller) EXPECT() *MockQuestsReRollerMockRecorder {
	return m.recorder
}

// ManualReRoll mocks base method.
func (m *MockQuestsReRoller) ManualReRoll(ctx context.Context, sess db.Session, accountID proto.AccountID, id uint64) ([]*proto.Reward, *proto.Quest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ManualReRoll", ctx, sess, accountID, id)
	ret0, _ := ret[0].([]*proto.Reward)
	ret1, _ := ret[1].(*proto.Quest)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ManualReRoll indicates an expected call of ManualReRoll.
func (mr *MockQuestsReRollerMockRecorder) ManualReRoll(ctx, sess, accountID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ManualReRoll", reflect.TypeOf((*MockQuestsReRoller)(nil).ManualReRoll), ctx, sess, accountID, id)
}
