// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/rpc (interfaces: QuestsClaimer)
//
// Generated by this command:
//
//	mockgen -destination ./mock/quests_claimer.go -package mock . QuestsClaimer
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	db "github.com/upper/db/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockQuestsClaimer is a mock of QuestsClaimer interface.
type MockQuestsClaimer struct {
	ctrl     *gomock.Controller
	recorder *MockQuestsClaimerMockRecorder
	isgomock struct{}
}

// MockQuestsClaimerMockRecorder is the mock recorder for MockQuestsClaimer.
type MockQuestsClaimerMockRecorder struct {
	mock *MockQuestsClaimer
}

// NewMockQuestsClaimer creates a new mock instance.
func NewMockQuestsClaimer(ctrl *gomock.Controller) *MockQuestsClaimer {
	mock := &MockQuestsClaimer{ctrl: ctrl}
	mock.recorder = &MockQuestsClaimerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuestsClaimer) EXPECT() *MockQuestsClaimerMockRecorder {
	return m.recorder
}

// ManualClaim mocks base method.
func (m *MockQuestsClaimer) ManualClaim(ctx context.Context, sess db.Session, accountID proto.AccountID, ids []uint64) ([]*proto.Reward, []*proto.Quest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ManualClaim", ctx, sess, accountID, ids)
	ret0, _ := ret[0].([]*proto.Reward)
	ret1, _ := ret[1].([]*proto.Quest)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ManualClaim indicates an expected call of ManualClaim.
func (mr *MockQuestsClaimerMockRecorder) ManualClaim(ctx, sess, accountID, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ManualClaim", reflect.TypeOf((*MockQuestsClaimer)(nil).ManualClaim), ctx, sess, accountID, ids)
}
