// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/rpc (interfaces: SkypassRewardUpdater)
//
// Generated by this command:
//
//	mockgen -destination ./mock/skypass_reward_updater.go -package mock . SkypassRewardUpdater
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	io "io"
	reflect "reflect"

	data "github.com/horizon-games/OpenSky/api/data"
	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockSkypassRewardUpdater is a mock of SkypassRewardUpdater interface.
type MockSkypassRewardUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockSkypassRewardUpdaterMockRecorder
	isgomock struct{}
}

// MockSkypassRewardUpdaterMockRecorder is the mock recorder for MockSkypassRewardUpdater.
type MockSkypassRewardUpdaterMockRecorder struct {
	mock *MockSkypassRewardUpdater
}

// NewMockSkypassRewardUpdater creates a new mock instance.
func NewMockSkypassRewardUpdater(ctrl *gomock.Controller) *MockSkypassRewardUpdater {
	mock := &MockSkypassRewardUpdater{ctrl: ctrl}
	mock.recorder = &MockSkypassRewardUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSkypassRewardUpdater) EXPECT() *MockSkypassRewardUpdaterMockRecorder {
	return m.recorder
}

// UpdateFromReader mocks base method.
func (m *MockSkypassRewardUpdater) UpdateFromReader(ctx context.Context, accountID proto.AccountID, season uint16, r io.Reader) ([]*data.SkypassReward, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFromReader", ctx, accountID, season, r)
	ret0, _ := ret[0].([]*data.SkypassReward)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFromReader indicates an expected call of UpdateFromReader.
func (mr *MockSkypassRewardUpdaterMockRecorder) UpdateFromReader(ctx, accountID, season, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFromReader", reflect.TypeOf((*MockSkypassRewardUpdater)(nil).UpdateFromReader), ctx, accountID, season, r)
}
