// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/rpc (interfaces: SkypassRewardClaimer)
//
// Generated by this command:
//
//	mockgen -destination ./mock/skypass_reward_claimer.go -package mock . SkypassRewardClaimer
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockSkypassRewardClaimer is a mock of SkypassRewardClaimer interface.
type MockSkypassRewardClaimer struct {
	ctrl     *gomock.Controller
	recorder *MockSkypassRewardClaimerMockRecorder
	isgomock struct{}
}

// MockSkypassRewardClaimerMockRecorder is the mock recorder for MockSkypassRewardClaimer.
type MockSkypassRewardClaimerMockRecorder struct {
	mock *MockSkypassRewardClaimer
}

// NewMockSkypassRewardClaimer creates a new mock instance.
func NewMockSkypassRewardClaimer(ctrl *gomock.Controller) *MockSkypassRewardClaimer {
	mock := &MockSkypassRewardClaimer{ctrl: ctrl}
	mock.recorder = &MockSkypassRewardClaimerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSkypassRewardClaimer) EXPECT() *MockSkypassRewardClaimerMockRecorder {
	return m.recorder
}

// ClaimRewards mocks base method.
func (m *MockSkypassRewardClaimer) ClaimRewards(arg0 context.Context, arg1 proto.AccountID, arg2 []uint64) ([]*proto.Reward, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimRewards", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*proto.Reward)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimRewards indicates an expected call of ClaimRewards.
func (mr *MockSkypassRewardClaimerMockRecorder) ClaimRewards(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimRewards", reflect.TypeOf((*MockSkypassRewardClaimer)(nil).ClaimRewards), arg0, arg1, arg2)
}
