// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/rpc (interfaces: TwitchClient)
//
// Generated by this command:
//
//	mockgen -destination ./mock/twitch_client.go -package mock . TwitchClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	rpc "github.com/horizon-games/OpenSky/api/rpc"
	gomock "go.uber.org/mock/gomock"
)

// MockTwitchClient is a mock of TwitchClient interface.
type MockTwitchClient struct {
	ctrl     *gomock.Controller
	recorder *MockTwitchClientMockRecorder
	isgomock struct{}
}

// MockTwitchClientMockRecorder is the mock recorder for MockTwitchClient.
type MockTwitchClientMockRecorder struct {
	mock *MockTwitchClient
}

// NewMockTwitchClient creates a new mock instance.
func NewMockTwitchClient(ctrl *gomock.Controller) *MockTwitchClient {
	mock := &MockTwitchClient{ctrl: ctrl}
	mock.recorder = &MockTwitchClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTwitchClient) EXPECT() *MockTwitchClientMockRecorder {
	return m.recorder
}

// GetStreams mocks base method.
func (m *MockTwitchClient) GetStreams(ctx context.Context, first, gameID string) (*rpc.TwitchAPIResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStreams", ctx, first, gameID)
	ret0, _ := ret[0].(*rpc.TwitchAPIResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStreams indicates an expected call of GetStreams.
func (mr *MockTwitchClientMockRecorder) GetStreams(ctx, first, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStreams", reflect.TypeOf((*MockTwitchClient)(nil).GetStreams), ctx, first, gameID)
}

// GetVideos mocks base method.
func (m *MockTwitchClient) GetVideos(ctx context.Context, gameID string) (*rpc.TwitchAPIResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVideos", ctx, gameID)
	ret0, _ := ret[0].(*rpc.TwitchAPIResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVideos indicates an expected call of GetVideos.
func (mr *MockTwitchClientMockRecorder) GetVideos(ctx, gameID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideos", reflect.TypeOf((*MockTwitchClient)(nil).GetVideos), ctx, gameID)
}
