
-- +goose Up
-- THIS FILE IS GENERATED BY `yarn gen-card-sql` IN /STATE
-- SQL in this section is executed when the migration is applied.
ALTER TABLE cards ADD COLUMN attributes jsonb;

-- +goose Down
-- SQL in this section is executed when the migration is rolled back.
ALTER TABLE cards DROP COLUMN attributes;
