
-- +goose Up
-- THIS FILE IS GENERATED BY `yarn gen-card-sql` IN /STATE
-- SQL in this section is executed when the migration is applied.
ALTER TABLE accounts ALTER COLUMN region TYPE varchar(8);
-- +goose Down
-- SQL in this section is executed when the migration is rolled back.
ALTER TABLE accounts ALTER COLUMN region TYPE varchar(2);
