
-- +goose Up
-- THIS FILE IS GENERATED BY `yarn gen-card-sql` IN /STATE
-- SQL in this section is executed when the migration is applied.
ALTER TABLE matches ADD COLUMN game_mode smallint NOT NULL DEFAULT 0;

-- +goose Down
-- SQL in this section is executed when the migration is rolled back.
ALTER TABLE matches DROP COLUMN game_mode;
