-- +goose Up
-- THIS FILE IS GENERATED BY \`yarn gen-card-sql\` IN /STATE
-- SQL in this section is executed when the migration is applied.
ALTER TABLE cards
RENAME attack TO power;
DROP INDEX cards_attack;
CREATE INDEX cards_power ON cards(power);

-- +goose Down
-- SQL in this section is executed when the migration is rolled back.
ALTER TABLE cards
RENAME power TO attack;
DROP INDEX cards_power;
CREATE INDEX cards_attack ON cards(attack);
