-- +goose Up
-- SQL in this section is executed when the migration is applied.

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION public.calculate_combined_score(
  player_rank bigint,
  score bigint,
  win_count bigint,
  loss_count bigint,
  abandon_count bigint
) RETURNS bigint
  LANGUAGE SQL IMMUTABLE STRICT
  AS $$
  SELECT
    (player_rank::bigint << 60) + (least(score, 4095)::bigint << 48) + (least(win_count, 65535)::bigint << 32) + ((65535-least(loss_count, 65535))::bigint << 16) + ((65535-least(abandon_count, 65535))) +  (-1::bigint << 63)
$$;
-- +goose StatementEnd

-- This function will raise an error if combined_score differs from the value
-- generated by calculate_combined_score in any row.

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION public.check_score_inconsistencies()
RETURNS VOID
LANGUAGE plpgsql
  AS $$
  BEGIN
    IF EXISTS(
      SELECT * FROM (
        SELECT
          combined_score,
          calculate_combined_score(player_rank, score, win_count, loss_count, abandon_count) AS recalculated_score
        FROM
          account_stats
      ) inconsistencies
      WHERE
        combined_score <> recalculated_score
    ) THEN
      RAISE EXCEPTION 'calculate_combined_score has inconsistencies';
    END IF;
  END;
$$;
-- +goose StatementEnd

-- Make sure recalculation function produces consistent results
SELECT public.check_score_inconsistencies();

-- +goose Down
-- SQL in this section is executed when the migration is rolled back.

-- Clean-up
DROP FUNCTION public.calculate_combined_score;

DROP FUNCTION public.check_score_inconsistencies;