
-- +goose Up
-- THIS FILE IS GENERATED BY `pnpm gen-seasonal-stickers-sql` IN /COSMETICS
-- SQL in this section is executed when the migration is applied.

update tasks set payload = convert_to('{}', 'UTF8') where queue ='balance-sync';