-- +goose Up
-- SQL in this section is executed when the migration is applied.

-- This migration resets Grandweavers back to Masters, then picks the top 100
-- Masters sorted by combined_score DESC and converts them into Grandweavers.
-- Finally, it recalculates the combined_score for all Masters and
-- Grandweavers of the current season.

-- We're going to use a rather long and ugly function to recalculate
-- combined_score, in order to play it safe we'll test that the function is
-- consistent with the value we already calculated and stored in
-- combined_score.

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION public.calculate_combined_score(
  player_rank bigint,
  score bigint,
  win_count bigint,
  loss_count bigint,
  abandon_count bigint
) RETURNS bigint
  LANGUAGE SQL IMMUTABLE STRICT
  AS $$
  SELECT
    (player_rank::bigint << 60) + (least(score, 4095)::bigint << 48) + (least(win_count, 65535)::bigint << 32) + ((65535-least(loss_count, 65535))::bigint << 16) + ((65535-least(abandon_count, 65535))) +  (-1::bigint << 63)
$$;
-- +goose StatementEnd

-- This function will raise an error if combined_score differs from the value
-- generated by calculate_combined_score in any row.

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION public.check_score_inconsistencies()
RETURNS VOID
LANGUAGE plpgsql
  AS $$
  BEGIN
    IF EXISTS(
      SELECT * FROM (
        SELECT
          combined_score,
          calculate_combined_score(player_rank, score, win_count, loss_count, abandon_count) AS recalculated_score
        FROM
          account_stats
      ) inconsistencies
      WHERE
        combined_score <> recalculated_score
    ) THEN
      RAISE EXCEPTION 'calculate_combined_score has inconsistencies';
    END IF;
  END;
$$;
-- +goose StatementEnd

-- Make sure recalculation function produces consistent results
SELECT public.check_score_inconsistencies();

-- Reset all grandweavers and convert them into masters.
UPDATE account_stats
  SET player_rank = 6
  WHERE
    player_rank = 7
    AND status NOT IN (1, 2)
    AND season = 4
    AND game_mode IN (1, 5);

-- Update masters combined scores
-- +goose StatementBegin
UPDATE account_stats
  SET
    combined_score = calculate_combined_score(player_rank, score, win_count, loss_count, abandon_count)
WHERE
  player_rank = 6
  AND season = 4
  AND game_mode IN (1, 5)
  AND player_rank in (6, 7);
-- +goose StatementEnd

-- Pick top 100 masters of the on-going season 4 and convert them into GW (discovery).
-- +goose StatementBegin
WITH grandweavers AS (
  SELECT
    account_address,
    game_mode,
    season
  FROM account_stats
  WHERE
    game_mode = 5 -- GameMode_RANKED_DISCOVERY
    AND player_rank = 6
    AND season = 4
    AND status NOT IN (1, 2) -- AccountStatus_SUSPENDED and AccountStatus_BANNED
  ORDER BY
    calculate_combined_score(player_rank, score, win_count, loss_count, abandon_count) DESC LIMIT 100
) UPDATE
  account_stats AS stats
  SET
    player_rank = 7 -- PlayerRank_GRANDMASTER
  FROM grandweavers
  WHERE
    stats.account_address = grandweavers.account_address
    AND stats.game_mode = grandweavers.game_mode
    AND stats.season = grandweavers.season
;
-- +goose StatementEnd

-- Pick top 100 masters of the on-going season 4 and convert them into GW (constructed).
-- +goose StatementBegin
WITH grandweavers AS (
  SELECT
    account_address,
    game_mode,
    season
  FROM account_stats
  WHERE
    game_mode = 1 -- GameMode_RANKED_CONSTRUCTED
    AND player_rank = 6
    AND season = 4
    AND status NOT IN (1, 2) -- AccountStatus_SUSPENDED and AccountStatus_BANNED
  ORDER BY
    calculate_combined_score(player_rank, score, win_count, loss_count, abandon_count) DESC LIMIT 100
) UPDATE
  account_stats AS stats
  SET
    player_rank = 7 -- PlayerRank_GRANDMASTER
  FROM grandweavers
  WHERE
    stats.account_address = grandweavers.account_address
    AND stats.game_mode = grandweavers.game_mode
    AND stats.season = grandweavers.season
;
-- +goose StatementEnd

-- Recalculate combined_scores for all the affected players
UPDATE account_stats
  SET
    combined_score = calculate_combined_score(player_rank, score, win_count, loss_count, abandon_count)
WHERE
  season = 4
  AND game_mode IN (1, 5)
  AND player_rank in (6, 7)
;

-- Clean-up
DROP FUNCTION public.calculate_combined_score;

DROP FUNCTION public.check_score_inconsistencies;