
-- +goose Up
-- THIS FILE IS GENERATED BY `pnpm gen-seasonal-stickers-sql` IN /COSMETICS
-- SQL in this section is executed when the migration is applied.

TRUNCATE stickers;

INSERT INTO stickers (season, token_id, required_points) VALUES(9, 327688, 25) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(9, 327716, 50) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(9, 327703, 200) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(10, 327690, 25) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(10, 327704, 50) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(10, 327693, 200) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(11, 327687, 25) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(11, 327691, 50) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(11, 327685, 200) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(12, 327712, 25) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(12, 327706, 50) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(12, 327696, 200) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(13, 327682, 25) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(13, 327705, 50) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(13, 327708, 200) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(14, 327692, 25) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(14, 327689, 50) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(14, 327707, 200) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(15, 327713, 25) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(15, 327711, 50) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(15, 327718, 200) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(16, 327710, 50) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(16, 327700, 200) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(17, 327695, 50) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(17, 327686, 200) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(18, 327694, 50) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(18, 327724, 200) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(19, 327684, 75) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(19, 327717, 225) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(20, 327732, 75) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(20, 327722, 225) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(21, 327720, 75) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(21, 327723, 225) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(22, 327770, 75) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(22, 327768, 225) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(23, 327775, 75) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(23, 327773, 225) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(24, 327748, 75) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(24, 327728, 225) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(25, 327780, 75) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(25, 327765, 225) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(26, 327746, 75) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(26, 327702, 225) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(9997, 327774, 0) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(9997, 327749, 0) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(9997, 327736, 0) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(9997, 327747, 0) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(9998, 327729, 0) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(9998, 327721, 0) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(9998, 327701, 0) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(9998, 327735, 0) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(9998, 327771, 0) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(9999, 327726, 0) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(9999, 327730, 0) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(9999, 327719, 0) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(9999, 327699, 0) ON CONFLICT DO NOTHING;
INSERT INTO stickers (season, token_id, required_points) VALUES(9999, 327731, 0) ON CONFLICT DO NOTHING;