
-- +goose Up
-- THIS FILE IS GENERATED BY `yarn gen-weekly-golds-sql` IN /STATE
-- SQL in this section is executed when the migration is applied.
ALTER TABLE reward_pool RENAME TO weekly_golds;
TRUNCATE TABLE weekly_golds;