// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/rankup (interfaces: GrandmasterListerUpdater)
//
// Generated by this command:
//
//	mockgen -destination ./mock/grandmasters_lister_updater.go -package mock . GrandmasterListerUpdater
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	data "github.com/horizon-games/OpenSky/api/data"
	proto "github.com/horizon-games/OpenSky/api/proto"
	db "github.com/upper/db/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockGrandmasterListerUpdater is a mock of GrandmasterListerUpdater interface.
type MockGrandmasterListerUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockGrandmasterListerUpdaterMockRecorder
	isgomock struct{}
}

// MockGrandmasterListerUpdaterMockRecorder is the mock recorder for MockGrandmasterListerUpdater.
type MockGrandmasterListerUpdaterMockRecorder struct {
	mock *MockGrandmasterListerUpdater
}

// NewMockGrandmasterListerUpdater creates a new mock instance.
func NewMockGrandmasterListerUpdater(ctrl *gomock.Controller) *MockGrandmasterListerUpdater {
	mock := &MockGrandmasterListerUpdater{ctrl: ctrl}
	mock.recorder = &MockGrandmasterListerUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGrandmasterListerUpdater) EXPECT() *MockGrandmasterListerUpdaterMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockGrandmasterListerUpdater) List(sess db.Session, gameMode proto.GameMode, season uint16) ([]*data.AccountStat, []*data.AccountStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", sess, gameMode, season)
	ret0, _ := ret[0].([]*data.AccountStat)
	ret1, _ := ret[1].([]*data.AccountStat)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockGrandmasterListerUpdaterMockRecorder) List(sess, gameMode, season any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGrandmasterListerUpdater)(nil).List), sess, gameMode, season)
}

// Update mocks base method.
func (m *MockGrandmasterListerUpdater) Update(sess db.Session, gameMode proto.GameMode, season uint16) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", sess, gameMode, season)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockGrandmasterListerUpdaterMockRecorder) Update(sess, gameMode, season any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGrandmasterListerUpdater)(nil).Update), sess, gameMode, season)
}
