// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker/matching/matchfuncs/matchvalidators (interfaces: GameModeCriteria)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	player "github.com/horizon-games/OpenSky/matchmaker/lib/player"
	gomock "go.uber.org/mock/gomock"
)

// MockGameModeCriteria is a mock of GameModeCriteria interface.
type MockGameModeCriteria struct {
	ctrl     *gomock.Controller
	recorder *MockGameModeCriteriaMockRecorder
}

// MockGameModeCriteriaMockRecorder is the mock recorder for MockGameModeCriteria.
type MockGameModeCriteriaMockRecorder struct {
	mock *MockGameModeCriteria
}

// NewMockGameModeCriteria creates a new mock instance.
func NewMockGameModeCriteria(ctrl *gomock.Controller) *MockGameModeCriteria {
	mock := &MockGameModeCriteria{ctrl: ctrl}
	mock.recorder = &MockGameModeCriteriaMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameModeCriteria) EXPECT() *MockGameModeCriteriaMockRecorder {
	return m.recorder
}

// IsAllowed mocks base method.
func (m *MockGameModeCriteria) IsAllowed(arg0, arg1 *player.Player) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAllowed", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAllowed indicates an expected call of IsAllowed.
func (mr *MockGameModeCriteriaMockRecorder) IsAllowed(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAllowed", reflect.TypeOf((*MockGameModeCriteria)(nil).IsAllowed), arg0, arg1)
}
