// Autogenerated by Nightwatch
// Refer to the online docs for more details: https://nightwatchjs.org/gettingstarted/configuration/
const Services = {}; loadServices();

module.exports = {
  // An array of folders (excluding subfolders) where your tests are located;
  // if this is not specified, the test source must be passed as the second argument to the test runner.
  src_folders: ['test'],

  // See https://nightwatchjs.org/guide/working-with-page-objects/
  page_objects_path: '',

  // See https://nightwatchjs.org/guide/extending-nightwatch/#writing-custom-commands
  custom_commands_path: 'commands',

  // See https://nightwatchjs.org/guide/extending-nightwatch/#writing-custom-assertions
  custom_assertions_path: '',

  // See https://nightwatchjs.org/guide/#external-globals
  globals_path: 'nightwatch.globals.js',

  webdriver: {},

  test_settings: {
    default: {
      disable_error_log: false,
      launch_url: 'https://nightwatchjs.org',

      screenshots: {
        enabled: false,
        path: 'screens',
        on_failure: true
      },

      desiredCapabilities: {
        browserName: 'firefox'
      },

      webdriver: {
        start_process: true,
        server_path: (Services.geckodriver ? Services.geckodriver.path : '')
      }
    },

    firefox: {
      desiredCapabilities: {
        browserName: 'firefox',
        'webdriver.gecko.driver': 'geckodriver',
        alwaysMatch: {
          acceptInsecureCerts: true,
          'moz:firefoxOptions': {
            args: [
              // '-headless',
              // '-verbose'
            ]
          }
        }

      },
      webdriver: {
        start_process: true,
        port: 4444,
        host: '127.0.0.1',
        server_path: (Services.geckodriver ? Services.geckodriver.path : ''),
        cli_args: [
          // very verbose geckodriver logs
          // '-vv'
        ]
      }
    },

    chrome: {
      desiredCapabilities: {
        browserName: 'chrome',
        acceptInsecureCerts: true
      },

      webdriver: {
        start_process: true,
        port: 9515,
        server_path: (Services.chromedriver ? Services.chromedriver.path : ''),
        cli_args: [
          // --verbose
        ]
      }
    },

    'chrome-p2': {
      extends: 'chrome',
      src_folders: ['player2']
    },

    edge: {
      desiredCapabilities: {
        browserName: 'MicrosoftEdge',
        'ms:edgeOptions': {
          w3c: false,
          // More info on EdgeDriver: https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/capabilities-edge-options
          args: [
            // '--headless'
          ]
        }
      },

      webdriver: {
        start_process: true,
        // Download msedgedriver from https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/
        //  and set the location below:
        server_path: '',
        cli_args: [
          // --verbose
        ]
      }
    },

    /// ///////////////////////////////////////////////////////////////////////////////
    // Configuration for when using the browserstack.com cloud service               |
    //                                                                               |
    // Please set the username and access key by setting the environment variables:  |
    // - BROWSERSTACK_USER                                                           |
    // - BROWSERSTACK_KEY                                                            |
    // .env files are supported                                                      |
    /// ///////////////////////////////////////////////////////////////////////////////
    browserstack: {
      selenium: {
        host: 'hub-cloud.browserstack.com',
        port: 443
      },

      globals: {
        waitForConditionTimeout: 50000,
        retryAssertionTimeout: 50000
      },
      // More info on configuring capabilities can be found on:
      // https://www.browserstack.com/automate/capabilities?tag=selenium-4
      desiredCapabilities: {
        'browserstack.selenium_version': '4.1.0',
        'browserstack.idleTimeout': '300',
        'bstack:options': {
          userName: '${BROWSERSTACK_USER}', // eslint-disable-line no-template-curly-in-string
          accessKey: '${BROWSERSTACK_KEY}' // eslint-disable-line no-template-curly-in-string
        }
      },

      disable_error_log: true,
      webdriver: {
        timeout_options: {
          timeout: 60000,
          retry_attempts: 3
        },
        keep_alive: true,
        start_process: false
      }
    },

    'browserstack.local': {
      extends: 'browserstack',
      desiredCapabilities: {
        'browserstack.local': true
      }
    },

    'browserstack.local.chrome': {
      extends: 'browserstack.local',
      desiredCapabilities: {
        browserName: 'chrome',
        chromeOptions: {
          w3c: false
        }
      }
    },

    'browserstack.local.iphone': {
      extends: 'browserstack.local',
      desiredCapabilities: {
        acceptInsecureCerts: true,
        acceptSslCerts: true,
        real_mobile: 'true',
        browserName: 'safari',
        browser: 'iPhone'
      }
    },

    'browserstack.local.android': {
      extends: 'browserstack.local',
      desiredCapabilities: {
        real_mobile: 'true',
        browserName: 'chrome',
        browser: 'Android'
      }
    },

    'browserstack.local.firefox': {
      extends: 'browserstack.local',
      desiredCapabilities: {
        browserName: 'firefox'
      }
    },

    'browserstack.proxy.safari': {
      extends: 'browserstack.local',
      desiredCapabilities: {
        browserName: 'safari',
        browser_version: '15.3',
        os: 'OS X',
        os_version: 'Monterey'
      }
    },

    'browserstack.chrome': {
      extends: 'browserstack',
      desiredCapabilities: {
        browserName: 'chrome',
        chromeOptions: {
          w3c: false
        }
      }
    },

    'browserstack.chrome.win10': {
      extends: 'browserstack.chrome',
      desiredCapabilities: {
        os: 'Windows',
        os_version: '10'
      }
    },

    'browserstack.chrome.osx12': {
      extends: 'browserstack.chrome',
      desiredCapabilities: {
        os: 'OS X',
        os_version: 'Monterey'
      }
    },

    'browserstack.chrome.android11': {
      extends: 'browserstack.chrome',
      desiredCapabilities: {
        os_version: '11.0',
        device: 'Google Pixel 5',
        real_mobile: 'true'
      }
    },

    'browserstack.firefox': {
      extends: 'browserstack',
      desiredCapabilities: {
        browserName: 'firefox'
      }
    },

    'browserstack.firefox.win10': {
      extends: 'browserstack.firefox',
      desiredCapabilities: {
        os: 'Windows',
        os_version: '10'
      }
    },

    'browserstack.firefox.osx12': {
      extends: 'browserstack.firefox',
      desiredCapabilities: {
        os: 'OS X',
        os_version: 'Monterey'
      }
    },

    'browserstack.safari': {
      extends: 'browserstack',
      desiredCapabilities: {
        browserName: 'safari',
        browser_version: '15.3'
      }
    },

    'browserstack.safari.osx12': {
      extends: 'browserstack.safari',
      desiredCapabilities: {
        os: 'OS X',
        os_version: 'Monterey'
      }
    },
    /// ///////////////////////////////////////////////////////////////////////////////
    // Configuration for when using the Selenium service, either locally or remote,  |
    //  like Selenium Grid                                                           |
    /// ///////////////////////////////////////////////////////////////////////////////
    selenium_server: {
      // Selenium Server is running locally and is managed by Nightwatch
      selenium: {
        start_process: true,
        port: 4444,
        server_path: (Services.seleniumServer ? Services.seleniumServer.path : ''),
        cli_args: {
          'webdriver.gecko.driver': (Services.geckodriver ? Services.geckodriver.path : ''),
          'webdriver.chrome.driver': (Services.chromedriver ? Services.chromedriver.path : '')
        }
      }
    },

    'selenium.chrome': {
      extends: 'selenium_server',
      desiredCapabilities: {
        browserName: 'chrome',
        chromeOptions: {
          w3c: false
        }
      }
    },

    'selenium.firefox': {
      extends: 'selenium_server',
      desiredCapabilities: {
        browserName: 'firefox',
        'moz:firefoxOptions': {
          args: [
            // '-headless',
            // '-verbose'
          ]
        }
      }
    }
  }
};

function loadServices() {
  try {
    Services.seleniumServer = require('selenium-server');
  } catch (err) {}

  try {
    Services.chromedriver = require('chromedriver');
  } catch (err) {}

  try {
    Services.geckodriver = require('geckodriver');
  } catch (err) {}
}
