import gameMusic from './gameMusic'
import queryParams from './sharedQueryParams'
import { makeSafetyCheckFromConstStringArray } from './typeHelpers'
import { getRandom } from './utils/arrayUtils'

const BaseAudioSpriteAssetNameStrings = [
  'audioFxTutorial',
  'audioFxCommon',
  'audioFxCards',
  'audioFxMatchEnd'
] as const

export type BaseAudioSpriteAssetName =
  (typeof BaseAudioSpriteAssetNameStrings)[number]

const ValidVariationNameStrings = BaseAudioSpriteAssetNameStrings.map(
  s => `${s}Variations` as const
)

export type ValidVariationName = (typeof ValidVariationNameStrings)[number]

const VariationAudioSpriteAssetNameStrings = [
  'audioFxMatchEndVariations',
  'audioFxCommonVariations'
] as const

export type VariationAudioSpriteAssetName =
  (typeof VariationAudioSpriteAssetNameStrings)[number]

const __dummy: VariationAudioSpriteAssetName = '' as any
const __assertVariationsAreValid: ValidVariationName = __dummy
void __assertVariationsAreValid

const lengthOfVariationsString = 'Variations'.length
export function baseSpriteForVariations<
  T extends ValidVariationName,
  U extends BaseAudioSpriteAssetName
>(variationsSprite: T): T extends `${U}Variations` ? U : never {
  return variationsSprite.slice(0, -lengthOfVariationsString) as any
}

const AudioSpriteAssetNameStrings = [
  ...BaseAudioSpriteAssetNameStrings,
  ...VariationAudioSpriteAssetNameStrings
] as const
export type AudioSpriteAssetName = (typeof AudioSpriteAssetNameStrings)[number]
export const isBaseAudioSpriteAssetName = makeSafetyCheckFromConstStringArray(
  BaseAudioSpriteAssetNameStrings
)
export const isVariationAudioSpriteAssetName =
  makeSafetyCheckFromConstStringArray(VariationAudioSpriteAssetNameStrings)
export const isAudioSpriteAssetName = makeSafetyCheckFromConstStringArray(
  AudioSpriteAssetNameStrings
)

export const Object3DAssetNameStrings = [
  'uiPreloader',
  'gamePiecesPhysical',
  'gameArmorEffect',
  'gameHolographicGlow',
  'gameArrow',
  'fakeCylinderGlow',
  'tutorialCube',
  'manaVial',
  'starterDeckFrame',
  'gameBoardBasicModel',
  'gameBoardConquestModel',
  'islandBasicModel',
  'islandConquest1Model',
  'islandConquest2Model',
  'islandConquest3Model',
  'testLumpModel',
  'gamePiecesGraphical',
  'testCentroids',
  'plaqueVictory',
  'plaqueDefeat',
  'carvedWall',
  'uiSmall',
  'cardBackFairy',
  'cardBackArcadeum',
  'cardBackSkull',
  'cardBackScrappy',
  'cardBackClockwork',
  'cardBackReefus',
  'cardBackVacation',
  'cardBackFunGuy',
  'cardBackStinkyEye',
  'cardBackTreasureMap',
  'cardBackPumpkin',
  'cardBackArmis',
  'cardBackCookie',
  'cardBackWaterfulBalls',
  'cardBackPicnicCake',
  'cardBackMuralLotus',
  'cardBackMuralAri',
  'axel_coin'
] as const
export type Object3DAssetName = (typeof Object3DAssetNameStrings)[number]
export const isObject3DAssetName = makeSafetyCheckFromConstStringArray(
  Object3DAssetNameStrings
)

export const MeshAnimationAssetNameStrings = [
  'meshAnimationAir01',
  'meshAnimationAir02',
  'meshAnimationAir03',
  'meshAnimationAir09',
  'meshAnimationAir11',
  'meshAnimationAir14',
  'meshAnimationAir15',
  'meshAnimationAir16',
  'meshAnimationAir17',
  'meshAnimationAir18',
  'meshAnimationAir19',
  'meshAnimationAir20',
  'meshAnimationAir22',
  'meshAnimationAir23',
  'meshAnimationAir24',
  'meshAnimationAir25',
  'meshAnimationEarth07',
  'meshAnimationEarth09',
  'meshAnimationEarth10',
  'meshAnimationEarth11',
  'meshAnimationEarth13',
  'meshAnimationEnergy00',
  'meshAnimationEnergy02',
  'meshAnimationEnergy04',
  'meshAnimationEnergy05',
  'meshAnimationEnergy06',
  'meshAnimationEnergy07',
  'meshAnimationEnergy08',
  'meshAnimationEnergy10',
  'meshAnimationEnergy11',
  'meshAnimationEnergy12',
  'meshAnimationEnergy13',
  'meshAnimationEnergy14',
  'meshAnimationEnergy15',
  'meshAnimationEnergy16',
  'meshAnimationEnergy17',
  'meshAnimationEnergy18',
  'meshAnimationEnergy19',
  'meshAnimationEnergy20',
  'meshAnimationEnergy21',
  'meshAnimationEnergy22',
  'meshAnimationEnergy23',
  'meshAnimationEnergy24',
  'meshAnimationEnergy27',
  'meshAnimationEnergy28',
  'meshAnimationEnergy29',
  'meshAnimationExplosion01',
  'meshAnimationExplosion02',
  'meshAnimationExplosion03',
  'meshAnimationFire01',
  'meshAnimationFire04',
  'meshAnimationFire08',
  'meshAnimationFire09',
  'meshAnimationFire10',
  'meshAnimationFire11',
  'meshAnimationFire12',
  'meshAnimationFire13',
  'meshAnimationFire14',
  'meshAnimationFire15',
  'meshAnimationFire16',
  'meshAnimationFire17',
  'meshAnimationFire18',
  'meshAnimationFire19',
  'meshAnimationFire20',
  'meshAnimationFire21',
  'meshAnimationFire22',
  'meshAnimationFire23',
  'meshAnimationFire24',
  'meshAnimationFire27',
  'meshAnimationSmoke08',
  'meshAnimationSmoke18',
  'meshAnimationWater01',
  'meshAnimationWater02',
  'meshAnimationWater03',
  'meshAnimationWater04',
  'meshAnimationWater05',
  'meshAnimationWater06',
  'meshAnimationWater07',
  'meshAnimationWater08',
  'meshAnimationWater09',
  'meshAnimationWater12',
  'meshAnimationWater13',
  'meshAnimationWater14',
  'meshAnimationWater15',
  'meshAnimationWater16',
  'meshAnimationWater17',
  'meshAnimationWater18',
  'meshAnimationWater19',
  'meshAnimationWater20',
  'meshAnimationWater21',
  'meshAnimationWater22',
  'meshAnimationWater23',
  'meshAnimationWater24',
  'meshAnimationWater25',
  'meshAnimationWater26',
  'meshAnimationWater27',
  'meshAnimationCrackTest',
  'meshAnimationCrack2Test',
  'meshAnimationShroudTest',
  'meshAnimationShroud2Test',
  'meshAnimationShroud3Test',
  'meshAnimationElectricity015',
  'meshAnimationElectricity043',
  'meshAnimationElectricity048',
  'meshAnimationElectricity049',
  'meshAnimationElectricity051',
  'meshAnimationEnergy008',
  'meshAnimationEnergy015',
  'meshAnimationEnergy020',
  'meshAnimationEnergy021',
  'meshAnimationEnergy025',
  'meshAnimationEnergy027',
  'meshAnimationEnergy031',
  'meshAnimationEnergy060',
  'meshAnimationEnergy064',
  'meshAnimationExplosion019',
  'meshAnimationFire001',
  'meshAnimationFire017',
  'meshAnimationFire026',
  'meshAnimationFire089',
  'meshAnimationFire107',
  'meshAnimationFire116',
  'meshAnimationFire119',
  'meshAnimationLiquid017',
  'meshAnimationLiquid037',
  'meshAnimationLiquid056',
  'meshAnimationSmoke002',
  'meshAnimationSmoke004',
  'meshAnimationSmoke012',
  'meshAnimationSmoke016',
  'meshAnimationSmoke022',
  'meshAnimationSmoke026',
  'meshAnimationSmoke027',
  'meshAnimationSmoke031',
  'meshAnimationSmoke041',
  'meshAnimationSmoke064',
  'meshAnimationSmoke066',
  'meshAnimationSmoke068',
  'ground_crack',
  'fire_fragment_test',
  'fire_vortex_test',
  'fire_vortex2_test',
  'smoke_bomb_test',
  'fire_radial_glow_test',
  'generic_AOE_v1',
  'border_glint_guard',
  'border_glint_unit',
  'border_glint_spell',
  'generic_trigger',
  'water_trigger',
  'light_trigger',
  'fire_trigger',
  'mind_trigger',
  'metal_trigger',
  'earth_trigger',
  'slay_trigger',
  'knives',
  'flames',
  'phoenix_plume_top',
  'debuff_lines',
  'glorious_mane',
  'mad_vibes',
  'glory_trigger',
  'test_death_trigger',
  'death_trigger_high',
  'death_trigger_low',
  'hero_death_small_blast',
  'hero_death_small_smoke',
  'hero_death_big_black_smoke',
  'hero_death_big_points',
  'hero_death_big_ground_ring_3d',
  'hero_death_big_flare',
  'hero_death_big_clouds_A',
  'hero_death_big_clouds_B',
  'arrow',
  'bite',
  'claw',
  'claw_impact',
  'crow',
  'ground_aura',
  'siphon',
  'stomp_impact',
  'stomp_paw',
  'twinkle',
  'cog',
  'hearts',
  'feathers',
  'music_notes',
  'stealth_eye',
  'main_shape',
  'burst_shine',
  'sparks',
  'electricity',
  'glow_bloom',
  'card_flames',

  'charge_up_energy_008',
  'charge_up_energy_051',
  'charge_up_energy_052',
  'charge_up_energy_053',

  'energy_tower_flames_base',
  'energy_tower_flames_bloom',
  'energy_tower_flames_trail',
  'energy_tower_electricity',
  'energy_tower_base_trail',

  'explosion_base',
  'explosion_bloom',
  'explosion_poof',
  'explosion_trace',

  'lava_puddle_bubbles_base',
  'lava_puddle_bubbles_trail',
  'lava_puddle_crack',
  'lava_puddle_embers',
  'lava_puddle_flames_base',
  'lava_puddle_flames_bloom',
  'lava_puddle_flames_trace',
  'lava_puddle_main_bubble',

  'ada_empower_base',
  'ada_empower_bloom',

  'bouran_ritualize_back_flames_base',
  'bouran_ritualize_back_flames_bloom',
  'bouran_ritualize_circle_inner',
  'bouran_ritualize_circle_moon_sun',
  'bouran_ritualize_circle_outer',
  'bouran_ritualize_embers',
  'bouran_ritualize_front_flames_base',
  'bouran_ritualize_front_flames_bloom',
  'bouran_ritualize_glow',

  'samya_teleport_base',
  'samya_teleport_bloom',
  'samya_teleport_dust',
  'samya_teleport_energy',

  'ari_fabricate_base',
  'ari_fabricate_fill',

  'hero_ability_trigger',

  'lotus_petals_1',
  'lotus_petals_2',
  'lotus_petals_3',
  'lotus_petals_4',
  'lotus_petals_5',

  'magma_chasm_base',
  'magma_chasm_bloom',
  'magma_chasm_bubbles',
  'magma_chasm_burst',
  'magma_chasm_smoke',

  'trident_base',
  'trident_bloom',

  'fox_packmaster_buff',
  'fox_packmaster_clash',
  'fox_packmaster_fox',

  'sitti_psychomancy_fire',
  'sitti_psychomancy_skulls',
  'sitti_psychomancy_smoke',

  'horik_vengeance_axe',
  'horik_vengeance_buff',
  'horik_vengeance_impact',
  'horik_vengeance_strike',
  'horik_vengeance_slice',

  'axel_glow_slide',
  'axel_intro_flame',
  'axel_outro_flame',
  'axel_shine',
  'axel_trail',
  'axel_spectral_coins',

  'titus_nurturer_energize',
  'iris_meditation',
  'mai_gadgeteer',
  'zoey_live_fast',
  'banjo_mercurial'
] as const
export type MeshAnimationAssetName =
  (typeof MeshAnimationAssetNameStrings)[number]
export const isMeshAnimationAssetName = makeSafetyCheckFromConstStringArray(
  MeshAnimationAssetNameStrings
)

const TextureAssetNameStrings = [
  'uvTest',
  'lightCacheDaylight',
  'dayNightColorStrip',
  'uiPalette',
  'effectPalette',
  'iconPalette',
  'deckFramePalette',
  'shroudUv',
  'cloudNormals',
  'noise3Map',
  'noise3dNormalizedFullMap',
  'noise3dNormalizedHalfMap',
  'noise3dNormalizedQuarterMap',
  'noiseyTriangles3dNormalizedFullMap',
  'noiseyScales3dNormalizedFullMap',
  'noiseyScales23dNormalizedFullMap',
  'foilStarsMap',
  'fireEffectSourceMap',
  'fogEffectSourceMap',
  'layeredNoise3Map',
  'errorMushroom',
  'optionsBg',
  // Animation sprite sheets
  'keywordArmorAnimation',
  'keywordBannerAnimation',
  'keywordLifestealAnimation',
  'keywordWitherAnimation',
  // Traits & keywords icons
  "keyword-conjure-icon",
"keyword-draw-icon",
"trait-wither-icon",
"trigger-death-icon",
"keyword-dust-icon",
"trait-armor-icon",
"trait-banner-icon",
"trigger-glory-icon",
"trait-guard-icon",
"trait-lifesteal-icon",
"trait-stealth-icon",
"trigger-inspire-icon",
"keyword-mulligan-icon",
"trigger-generic-icon",
"trigger-sunset-icon",
"trigger-sunrise-icon",
"trait-dash-icon",
"trigger-slay-icon",
  // Enchantment sprite sheets
  'enchantmentAnima',
  'enchantmentBarrier',
  'enchantmentBlind',
  'enchantmentChains',
  'enchantmentDazed',
  'enchantmentFate',
  'enchantmentFlames',
  'enchantmentFrozen',
  'enchantmentFury',
  'enchantmentHex',
  'enchantmentLead',
  'enchantmentRoots',
  'enchantmentShield',
  'enchantmentShroud',
  'enchantmentSilence',
  'enchantmentVapors',
  'cardAspectArrow',
  'cardAspectArrowGreen',
  'sleepingAnimation',
  'damageAnimation',
  'damageFatigueAnimation',
  'triggerAnimation',
  'auraTriggerAnimation',
  'buffGenericAnimation',
  'smoke',
  'particle',
  'particle2',
  'witherParticleSpritesheet',
  'fireSpritesheet',
  'brushStroke',
  'uiPreviewDeath',
  'uiPreviewDust',
  'uiPreviewDraw',
  'uiPreviewMulligan',
  'uiPreviewReturnToHand',
  'uiPreviewSendToDeck',
  'uiPreviewSendToGraveyard',
  'uiPreviewSummon',
  'bgLoading',
  'spellLoading',
  'unitLoading'
] as const
export type TextureAssetName = (typeof TextureAssetNameStrings)[number]
export const isTextureAssetName = makeSafetyCheckFromConstStringArray(
  TextureAssetNameStrings
)

const MusicAssetNameStrings = [
  'musicGame',
  'musicVictory',
  'musicDefeat'
] as const
export type MusicAssetName = (typeof MusicAssetNameStrings)[number]
export const isMusicAssetName = makeSafetyCheckFromConstStringArray(
  MusicAssetNameStrings
)

export const AssetNameStrings = [
  ...AudioSpriteAssetNameStrings,
  ...Object3DAssetNameStrings,
  ...MeshAnimationAssetNameStrings,
  ...TextureAssetNameStrings,
  ...MusicAssetNameStrings
] as const

export type AssetName = (typeof AssetNameStrings)[number]

const COMPRESSED_GLTF_SUFFIX = queryParams.gltfFormat
  ? '.' + queryParams.gltfFormat
  : ''

const pathModels = 'game/models'
const pathEffects = 'game/effects'
const pathKeywordIcons = 'game/keyword-icons'
const pathEnchantments = 'game/enchantments'
const pathMeshAnimations = `${pathModels}/meshAnimations`

export const assetUrls: { [K in AssetName]: string } = {
  uiPreloader: `${pathModels}/ui-preloader.gltf`,
  uvTest: `game/models/uvTest.png`,
  lightCacheDaylight: `game/lighting/light-cache-daylight.png`,
  smoke: `${pathEffects}/transparent/smoke.png`,
  gamePiecesGraphical: `${pathModels}/game-pieces-graphical.gltf`,
  testCentroids: `${pathModels}/test-centroids.gltf`,
  plaqueVictory: `${pathModels}/plaque-victory.gltf`,
  plaqueDefeat: `${pathModels}/plaque-defeat.gltf`,
  carvedWall: `${pathModels}/carved-wall.gltf`,
  uiSmall: `${pathModels}/ui-small.gltf`,
  // Cardbacks
  cardBackFairy: `${pathModels}/card-backs/fairy.gltf`,
  cardBackArcadeum: `${pathModels}/card-backs/arcadeum.gltf`,
  cardBackSkull: `${pathModels}/card-backs/skull.gltf`,
  cardBackScrappy: `${pathModels}/card-backs/scrappy.gltf`,
  cardBackClockwork: `${pathModels}/card-backs/clockwork.gltf`,
  cardBackReefus: `${pathModels}/card-backs/reefus.gltf`,
  cardBackVacation: `${pathModels}/card-backs/vacation.gltf`,
  cardBackFunGuy: `${pathModels}/card-backs/funguy.gltf`,
  cardBackStinkyEye: `${pathModels}/card-backs/stinky-eye.gltf`,
  cardBackTreasureMap: `${pathModels}/card-backs/treasure-map.gltf`,
  cardBackPumpkin: `${pathModels}/card-backs/pumpkin.gltf`,
  cardBackArmis: `${pathModels}/card-backs/armis.gltf`,
  cardBackCookie: `${pathModels}/card-backs/cookie.gltf`,
  cardBackWaterfulBalls: `${pathModels}/card-backs/waterful-balls.gltf`,
  cardBackPicnicCake: `${pathModels}/card-backs/picnic-cake.gltf`,
  cardBackMuralLotus: `${pathModels}/card-backs/mural-lotus.gltf`,
  cardBackMuralAri: `${pathModels}/card-backs/mural-ari.gltf`,
  // Game
  axel_coin: `${pathMeshAnimations}/effects/hero_abilities/axel/fates_fortune/coin/coin${COMPRESSED_GLTF_SUFFIX}.gltf`,
  gameArrow: `${pathModels}/game-arrow.gltf`,
  fakeCylinderGlow: `${pathModels}/fake-cylinder-glow.gltf`,
  dayNightColorStrip: `${pathModels}/sky-sun-stars-lights-clouds-day-cycle.png`,
  uiPalette: `game/ui/ui-palette.png`,
  effectPalette: `${pathMeshAnimations}/effect-palette.png`,
  iconPalette: `game/ui/icon-palette.png`,
  deckFramePalette: `game/ui/deck-frame-palette.png`,
  shroudUv: `${pathEffects}/opaque/shroud-uv.png`,
  cloudNormals: `${pathModels}/bg-clouds-sculpted.png`,
  gamePiecesPhysical: `${pathModels}/game-pieces-physical.gltf`,
  gameArmorEffect: `${pathModels}/game-armor-effect.gltf`,
  gameHolographicGlow: `${pathModels}/game-holographic-card-glow.gltf`,
  gameBoardBasicModel: `${pathModels}/game-board-basic.gltf`,
  gameBoardConquestModel: `${pathModels}/game-board-conquest.gltf`,
  manaVial: `${pathModels}/mana-vial.gltf`,
  starterDeckFrame: `${pathModels}/deck-frame.gltf`,
  islandBasicModel: `${pathModels}/island-basic.gltf`,
  islandConquest1Model: `${pathModels}/island-conquest1.gltf`,
  islandConquest2Model: `${pathModels}/island-conquest2.gltf`,
  islandConquest3Model: `${pathModels}/island-conquest3.gltf`,
  testLumpModel: `${pathModels}/test-lump.gltf`,
  errorMushroom: `game/ui/error.png`,
  optionsBg: `game/ui/options-bg.png`,
  bgLoading: `game/cards/art-full/bgs/bg-loading.png`,
  spellLoading: `game/cards/art-full/spells/spell-loading.png`,
  unitLoading: `game/cards/art-full/units/unit-loading.png`,
  // Tutorial
  tutorialCube: `${pathModels}/tutorial-cube.gltf`,
  noise3Map: `${pathEffects}/opaque/simplex-noise.png`,
  noise3dNormalizedFullMap: `${pathEffects}/opaque/noise-3d-normalized-full.png`,
  noiseyTriangles3dNormalizedFullMap: `${pathEffects}/opaque/noisey-triangles-3d-normalized-full.png`,
  noiseyScales3dNormalizedFullMap: `${pathEffects}/opaque/noisey-scales-3d-normalized-full.png`,
  noiseyScales23dNormalizedFullMap: `${pathEffects}/opaque/noisey-scales2-3d-normalized-full.png`,
  foilStarsMap: `${pathEffects}/transparent/foil-stars.png`,
  noise3dNormalizedHalfMap: `${pathEffects}/opaque/noise-3d-normalized-half.png`,
  noise3dNormalizedQuarterMap: `${pathEffects}/opaque/noise-3d-normalized-quarter.png`,
  fireEffectSourceMap: `${pathEffects}/transparent/fire-effect-source.png`,
  fogEffectSourceMap: `${pathEffects}/transparent/fog-effect-source.png`,
  layeredNoise3Map: `${pathEffects}/opaque/layered-perlin-noise.png`,
  particle: `${pathEffects}/transparent/particle2.png`,
  particle2: `${pathEffects}/transparent/particle1.png`,
  witherParticleSpritesheet: `${pathEffects}/transparent/witherParticleSpritesheet.png`,
  fireSpritesheet: `${pathEffects}/opaque/fireSpriteSheet.png`,
  brushStroke: `${pathEffects}/transparent/smoke.png`,
  // Animations - loaded when needed
  keywordArmorAnimation: `${pathEffects}/transparent/keyword-armor-animation.png`,
  keywordBannerAnimation: `${pathEffects}/transparent/aura-animation.png`,
  keywordLifestealAnimation: `${pathEffects}/opaque/keyword-lifesteal-animation.png`,
  keywordWitherAnimation: `${pathEffects}/transparent/keyword-wither-animation.png`,
  sleepingAnimation: `${pathEffects}/transparent/sleeping-animation.png`,
  damageAnimation: `${pathEffects}/opaque/damage-animation.png`,
  damageFatigueAnimation: `${pathEffects}/opaque/damage-fatigue-animation.png`,
  triggerAnimation: `${pathEffects}/opaque/trigger-animation.png`,
  auraTriggerAnimation: `${pathEffects}/opaque/aura-trigger-animation.png`,
  buffGenericAnimation: `${pathEffects}/opaque/buff-animation.png`,
  // keywords
  "keyword-conjure-icon": `${pathKeywordIcons}/conjure.png`,
  "keyword-draw-icon": `${pathKeywordIcons}/draw.png`,
  "trait-wither-icon": `${pathKeywordIcons}/wither.png`,
  "trigger-death-icon": `${pathKeywordIcons}/death.png`,
  "keyword-dust-icon": `${pathKeywordIcons}/dust.png`,
  "trait-armor-icon": `${pathKeywordIcons}/armor.png`,
  "trait-banner-icon": `${pathKeywordIcons}/banner.png`,
  "trigger-glory-icon": `${pathKeywordIcons}/glory.png`,
  "trait-guard-icon": `${pathKeywordIcons}/guard.png`,
  "trait-lifesteal-icon": `${pathKeywordIcons}/lifesteal.png`,
  "trait-stealth-icon": `${pathKeywordIcons}/stealth.png`,
  "trigger-inspire-icon": `${pathKeywordIcons}/inspire.png`,
  "keyword-mulligan-icon": `${pathKeywordIcons}/mulligan.png`,
  "trigger-generic-icon": `${pathKeywordIcons}/trigger.png`,
  "trigger-sunset-icon": `${pathKeywordIcons}/sunset.png`,
  "trigger-sunrise-icon": `${pathKeywordIcons}/sunrise.png`,
  "trait-dash-icon": `${pathKeywordIcons}/dash.png`,
  "trigger-slay-icon": `${pathKeywordIcons}/slay.png`,
  enchantmentAnima: `${pathEnchantments}/anima.png`,
  enchantmentBarrier: `${pathEnchantments}/barrier.png`,
  enchantmentBlind: `${pathEnchantments}/blind.png`,
  enchantmentChains: `${pathEnchantments}/chains.png`,
  enchantmentDazed: `${pathEnchantments}/dazed.png`,
  enchantmentFate: `${pathEnchantments}/fate.png`,
  enchantmentFlames: `${pathEnchantments}/flames.png`,
  enchantmentFrozen: `${pathEnchantments}/ice.png`,
  enchantmentFury: `${pathEnchantments}/fury.png`,
  enchantmentHex: `${pathEnchantments}/hex.png`,
  enchantmentLead: `${pathEnchantments}/lead.png`,
  enchantmentRoots: `${pathEnchantments}/roots.png`,
  enchantmentShield: `${pathEnchantments}/shield.png`,
  enchantmentShroud: `${pathEnchantments}/shroud.png`,
  enchantmentSilence: `${pathEnchantments}/silence.png`,
  enchantmentVapors: `${pathEnchantments}/vapors.png`,
  cardAspectArrow: `game/keyword-icons/arrow.png`,
  cardAspectArrowGreen: `game/keyword-icons/arrow-green.png`,
  // Music
  musicGame: getRandom(gameMusic).url,
  musicVictory: `game/audio/music/OpenSkyVictory.mp3`,
  musicDefeat: `game/audio/music/OpenSkyDefeat.mp3`,
  audioFxCommon: `game/audio/fx/common.json`,
  audioFxTutorial: `game/audio/fx/tutorial.json`,
  audioFxCommonVariations: `game/audio/fx/common_variations.json`,
  audioFxCards: `game/audio/fx/cards.json`,
  audioFxMatchEnd: `game/audio/fx/matchend.json`,
  audioFxMatchEndVariations: `game/audio/fx/matchend_variations.json`,
  // UI
  uiPreviewDeath: `game/ui/preview-icons/death.png`,
  uiPreviewDust: `game/ui/preview-icons/dust.png`,
  uiPreviewDraw: `game/ui/preview-icons/draw.png`,
  uiPreviewMulligan: `game/ui/preview-icons/mulligan.png`,
  uiPreviewReturnToHand: `game/ui/preview-icons/return-to-hand.png`,
  uiPreviewSendToDeck: `game/ui/preview-icons/send-to-deck.png`,
  uiPreviewSendToGraveyard: `game/ui/preview-icons/send-to-graveyard.png`,
  uiPreviewSummon: `game/ui/preview-icons/summon.png`,
  // Mesh Sprite Animations
  meshAnimationAir01: `${pathMeshAnimations}/hive-v1/air_01${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationAir02: `${pathMeshAnimations}/hive-v1/air_02${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationAir03: `${pathMeshAnimations}/hive-v1/air_03${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationAir09: `${pathMeshAnimations}/hive-v1/air_09${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationAir11: `${pathMeshAnimations}/hive-v1/air_11${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationAir14: `${pathMeshAnimations}/hive-v1/air_14${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationAir15: `${pathMeshAnimations}/hive-v1/air_15${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationAir16: `${pathMeshAnimations}/hive-v1/air_16${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationAir17: `${pathMeshAnimations}/hive-v1/air_17${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationAir18: `${pathMeshAnimations}/hive-v1/air_18${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationAir19: `${pathMeshAnimations}/hive-v1/air_19${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationAir20: `${pathMeshAnimations}/hive-v1/air_20${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationAir22: `${pathMeshAnimations}/hive-v1/air_22${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationAir23: `${pathMeshAnimations}/hive-v1/air_23${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationAir24: `${pathMeshAnimations}/hive-v1/air_24${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationAir25: `${pathMeshAnimations}/hive-v1/air_25${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEarth07: `${pathMeshAnimations}/hive-v1/earth_07${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEarth09: `${pathMeshAnimations}/hive-v1/earth_09${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEarth10: `${pathMeshAnimations}/hive-v1/earth_10${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEarth11: `${pathMeshAnimations}/hive-v1/earth_11${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEarth13: `${pathMeshAnimations}/hive-v1/earth_13${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy00: `${pathMeshAnimations}/hive-v1/energy_00${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy02: `${pathMeshAnimations}/hive-v1/energy_02${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy04: `${pathMeshAnimations}/hive-v1/energy_04${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy05: `${pathMeshAnimations}/hive-v1/energy_05${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy06: `${pathMeshAnimations}/hive-v1/energy_06${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy07: `${pathMeshAnimations}/hive-v1/energy_07${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy08: `${pathMeshAnimations}/hive-v1/energy_08${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy10: `${pathMeshAnimations}/hive-v1/energy_10${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy11: `${pathMeshAnimations}/hive-v1/energy_11${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy12: `${pathMeshAnimations}/hive-v1/energy_12${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy13: `${pathMeshAnimations}/hive-v1/energy_13${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy14: `${pathMeshAnimations}/hive-v1/energy_14${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy15: `${pathMeshAnimations}/hive-v1/energy_15${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy16: `${pathMeshAnimations}/hive-v1/energy_16${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy17: `${pathMeshAnimations}/hive-v1/energy_17${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy18: `${pathMeshAnimations}/hive-v1/energy_18${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy19: `${pathMeshAnimations}/hive-v1/energy_19${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy20: `${pathMeshAnimations}/hive-v1/energy_20${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy21: `${pathMeshAnimations}/hive-v1/energy_21${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy22: `${pathMeshAnimations}/hive-v1/energy_22${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy23: `${pathMeshAnimations}/hive-v1/energy_23${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy24: `${pathMeshAnimations}/hive-v1/energy_24${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy27: `${pathMeshAnimations}/hive-v1/energy_27${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy28: `${pathMeshAnimations}/hive-v1/energy_28${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy29: `${pathMeshAnimations}/hive-v1/energy_29${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationExplosion01: `${pathMeshAnimations}/hive-v1/explosion_01${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationExplosion02: `${pathMeshAnimations}/hive-v1/explosion_02${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationExplosion03: `${pathMeshAnimations}/hive-v1/explosion_03${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationFire01: `${pathMeshAnimations}/hive-v1/fire_01${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationFire04: `${pathMeshAnimations}/hive-v1/fire_04${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationFire08: `${pathMeshAnimations}/hive-v1/fire_08${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationFire09: `${pathMeshAnimations}/hive-v1/fire_09${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationFire10: `${pathMeshAnimations}/hive-v1/fire_10${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationFire11: `${pathMeshAnimations}/hive-v1/fire_11${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationFire12: `${pathMeshAnimations}/hive-v1/fire_12${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationFire13: `${pathMeshAnimations}/hive-v1/fire_13${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationFire14: `${pathMeshAnimations}/hive-v1/fire_14${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationFire15: `${pathMeshAnimations}/hive-v1/fire_15${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationFire16: `${pathMeshAnimations}/hive-v1/fire_16${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationFire17: `${pathMeshAnimations}/hive-v1/fire_17${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationFire18: `${pathMeshAnimations}/hive-v1/fire_18${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationFire19: `${pathMeshAnimations}/hive-v1/fire_19${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationFire20: `${pathMeshAnimations}/hive-v1/fire_20${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationFire21: `${pathMeshAnimations}/hive-v1/fire_21${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationFire22: `${pathMeshAnimations}/hive-v1/fire_22${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationFire23: `${pathMeshAnimations}/hive-v1/fire_23${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationFire24: `${pathMeshAnimations}/hive-v1/fire_24${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationFire27: `${pathMeshAnimations}/hive-v1/fire_27${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationSmoke08: `${pathMeshAnimations}/hive-v1/smoke_08${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationSmoke18: `${pathMeshAnimations}/hive-v1/smoke_18${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationWater01: `${pathMeshAnimations}/hive-v1/water_01${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationWater02: `${pathMeshAnimations}/hive-v1/water_02${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationWater03: `${pathMeshAnimations}/hive-v1/water_03${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationWater04: `${pathMeshAnimations}/hive-v1/water_04${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationWater05: `${pathMeshAnimations}/hive-v1/water_05${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationWater06: `${pathMeshAnimations}/hive-v1/water_06${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationWater07: `${pathMeshAnimations}/hive-v1/water_07${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationWater08: `${pathMeshAnimations}/hive-v1/water_08${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationWater09: `${pathMeshAnimations}/hive-v1/water_09${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationWater12: `${pathMeshAnimations}/hive-v1/water_12${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationWater13: `${pathMeshAnimations}/hive-v1/water_13${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationWater14: `${pathMeshAnimations}/hive-v1/water_14${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationWater15: `${pathMeshAnimations}/hive-v1/water_15${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationWater16: `${pathMeshAnimations}/hive-v1/water_16${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationWater17: `${pathMeshAnimations}/hive-v1/water_17${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationWater18: `${pathMeshAnimations}/hive-v1/water_18${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationWater19: `${pathMeshAnimations}/hive-v1/water_19${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationWater20: `${pathMeshAnimations}/hive-v1/water_20${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationWater21: `${pathMeshAnimations}/hive-v1/water_21${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationWater22: `${pathMeshAnimations}/hive-v1/water_22${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationWater23: `${pathMeshAnimations}/hive-v1/water_23${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationWater24: `${pathMeshAnimations}/hive-v1/water_24${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationWater25: `${pathMeshAnimations}/hive-v1/water_25${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationWater26: `${pathMeshAnimations}/hive-v1/water_26${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationWater27: `${pathMeshAnimations}/hive-v1/water_27${COMPRESSED_GLTF_SUFFIX}.gltf`,

  meshAnimationElectricity015: `${pathMeshAnimations}/hive-v2/electricity_015${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationElectricity043: `${pathMeshAnimations}/hive-v2/electricity_043${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationElectricity048: `${pathMeshAnimations}/hive-v2/electricity_048${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationElectricity049: `${pathMeshAnimations}/hive-v2/electricity_049${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationElectricity051: `${pathMeshAnimations}/hive-v2/electricity_051${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy008: `${pathMeshAnimations}/hive-v2/energy_008${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy015: `${pathMeshAnimations}/hive-v2/energy_015${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy020: `${pathMeshAnimations}/hive-v2/energy_020${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy021: `${pathMeshAnimations}/hive-v2/energy_021${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy025: `${pathMeshAnimations}/hive-v2/energy_025${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy027: `${pathMeshAnimations}/hive-v2/energy_027${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy031: `${pathMeshAnimations}/hive-v2/energy_031${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy060: `${pathMeshAnimations}/hive-v2/energy_060${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationEnergy064: `${pathMeshAnimations}/hive-v2/energy_064${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationExplosion019: `${pathMeshAnimations}/hive-v2/explosion_019${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationFire001: `${pathMeshAnimations}/hive-v2/fire_001${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationFire017: `${pathMeshAnimations}/hive-v2/fire_017${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationFire026: `${pathMeshAnimations}/hive-v2/fire_026${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationFire089: `${pathMeshAnimations}/hive-v2/fire_089${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationFire107: `${pathMeshAnimations}/hive-v2/fire_107${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationFire116: `${pathMeshAnimations}/hive-v2/fire_116${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationLiquid017: `${pathMeshAnimations}/hive-v2/liquid_017${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationLiquid037: `${pathMeshAnimations}/hive-v2/liquid_037${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationLiquid056: `${pathMeshAnimations}/hive-v2/liquid_056${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationFire119: `${pathMeshAnimations}/hive-v2/fire_119${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationSmoke002: `${pathMeshAnimations}/hive-v2/smoke_002${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationSmoke004: `${pathMeshAnimations}/hive-v2/smoke_004${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationSmoke012: `${pathMeshAnimations}/hive-v2/smoke_012${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationSmoke016: `${pathMeshAnimations}/hive-v2/smoke_016${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationSmoke022: `${pathMeshAnimations}/hive-v2/smoke_022${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationSmoke026: `${pathMeshAnimations}/hive-v2/smoke_026${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationSmoke027: `${pathMeshAnimations}/hive-v2/smoke_027${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationSmoke031: `${pathMeshAnimations}/hive-v2/smoke_031${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationSmoke041: `${pathMeshAnimations}/hive-v2/smoke_041${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationSmoke064: `${pathMeshAnimations}/hive-v2/smoke_064${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationSmoke066: `${pathMeshAnimations}/hive-v2/smoke_066${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationSmoke068: `${pathMeshAnimations}/hive-v2/smoke_068${COMPRESSED_GLTF_SUFFIX}.gltf`,

  fire_fragment_test: `${pathMeshAnimations}/test/fire_fragment_test${COMPRESSED_GLTF_SUFFIX}.gltf`,
  fire_vortex_test: `${pathMeshAnimations}/test/fire_vortex_test${COMPRESSED_GLTF_SUFFIX}.gltf`,
  fire_vortex2_test: `${pathMeshAnimations}/test/fire_vortex2_test${COMPRESSED_GLTF_SUFFIX}.gltf`,
  smoke_bomb_test: `${pathMeshAnimations}/test/smoke_bomb_test${COMPRESSED_GLTF_SUFFIX}.gltf`,
  fire_radial_glow_test: `${pathMeshAnimations}/test/fire_radial_glow_test${COMPRESSED_GLTF_SUFFIX}.gltf`,
  generic_AOE_v1: `${pathMeshAnimations}/test/generic_AOE_v1${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationCrackTest: `${pathMeshAnimations}/test/crack-test${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationCrack2Test: `${pathMeshAnimations}/test/crack2-test${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationShroudTest: `${pathMeshAnimations}/test/shroud-test${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationShroud2Test: `${pathMeshAnimations}/test/shroud2-test${COMPRESSED_GLTF_SUFFIX}.gltf`,
  meshAnimationShroud3Test: `${pathMeshAnimations}/test/shroud3-test${COMPRESSED_GLTF_SUFFIX}.gltf`,

  ground_crack: `${pathMeshAnimations}/effects/ground_crack${COMPRESSED_GLTF_SUFFIX}.gltf`,

  border_glint_guard: `${pathMeshAnimations}/effects/border_glint_guard${COMPRESSED_GLTF_SUFFIX}.gltf`,
  border_glint_unit: `${pathMeshAnimations}/effects/border_glint_unit${COMPRESSED_GLTF_SUFFIX}.gltf`,
  border_glint_spell: `${pathMeshAnimations}/effects/border_glint_spell${COMPRESSED_GLTF_SUFFIX}.gltf`,

  generic_trigger: `${pathMeshAnimations}/triggers/generic_trigger${COMPRESSED_GLTF_SUFFIX}.gltf`,
  water_trigger: `${pathMeshAnimations}/triggers/water_trigger${COMPRESSED_GLTF_SUFFIX}.gltf`,
  light_trigger: `${pathMeshAnimations}/triggers/light_trigger${COMPRESSED_GLTF_SUFFIX}.gltf`,
  fire_trigger: `${pathMeshAnimations}/triggers/fire_trigger${COMPRESSED_GLTF_SUFFIX}.gltf`,
  mind_trigger: `${pathMeshAnimations}/triggers/mind_trigger${COMPRESSED_GLTF_SUFFIX}.gltf`,
  metal_trigger: `${pathMeshAnimations}/triggers/metal_trigger${COMPRESSED_GLTF_SUFFIX}.gltf`,
  earth_trigger: `${pathMeshAnimations}/test/earth_trigger${COMPRESSED_GLTF_SUFFIX}.gltf`,
  slay_trigger: `${pathMeshAnimations}/triggers/slay_trigger${COMPRESSED_GLTF_SUFFIX}.gltf`,
  glory_trigger: `${pathMeshAnimations}/triggers/glory_trigger${COMPRESSED_GLTF_SUFFIX}.gltf`,
  test_death_trigger: `${pathMeshAnimations}/test/death_trigger${COMPRESSED_GLTF_SUFFIX}.gltf`,
  death_trigger_high: `${pathMeshAnimations}/triggers/death_trigger_high${COMPRESSED_GLTF_SUFFIX}.gltf`,
  death_trigger_low: `${pathMeshAnimations}/triggers/death_trigger_low${COMPRESSED_GLTF_SUFFIX}.gltf`,

  knives: `${pathMeshAnimations}/spells/knives${COMPRESSED_GLTF_SUFFIX}.gltf`,
  flames: `${pathMeshAnimations}/spells/flames${COMPRESSED_GLTF_SUFFIX}.gltf`,
  glorious_mane: `${pathMeshAnimations}/spells/glorious_mane${COMPRESSED_GLTF_SUFFIX}.gltf`,
  mad_vibes: `${pathMeshAnimations}/spells/mad_vibes${COMPRESSED_GLTF_SUFFIX}.gltf`,
  phoenix_plume_top: `${pathMeshAnimations}/spells/phoenix_plume_top${COMPRESSED_GLTF_SUFFIX}.gltf`,
  debuff_lines: `${pathMeshAnimations}/spells/debuff_lines${COMPRESSED_GLTF_SUFFIX}.gltf`,

  hero_death_small_blast: `${pathMeshAnimations}/hero-death/hero_death_small_blast${COMPRESSED_GLTF_SUFFIX}.gltf`,
  hero_death_small_smoke: `${pathMeshAnimations}/hero-death/hero_death_small_smoke${COMPRESSED_GLTF_SUFFIX}.gltf`,
  hero_death_big_black_smoke: `${pathMeshAnimations}/hero-death/hero_death_big_black_smoke${COMPRESSED_GLTF_SUFFIX}.gltf`,
  hero_death_big_points: `${pathMeshAnimations}/hero-death/hero_death_big_points${COMPRESSED_GLTF_SUFFIX}.gltf`,
  hero_death_big_ground_ring_3d: `${pathMeshAnimations}/hero-death/hero_death_big_ground_ring_3d${COMPRESSED_GLTF_SUFFIX}.gltf`,
  hero_death_big_flare: `${pathMeshAnimations}/hero-death/hero_death_big_flare${COMPRESSED_GLTF_SUFFIX}.gltf`,
  hero_death_big_clouds_A: `${pathMeshAnimations}/hero-death/hero_death_big_clouds_A${COMPRESSED_GLTF_SUFFIX}.gltf`,
  hero_death_big_clouds_B: `${pathMeshAnimations}/hero-death/hero_death_big_clouds_B${COMPRESSED_GLTF_SUFFIX}.gltf`,

  arrow: `${pathMeshAnimations}/effects/arrow${COMPRESSED_GLTF_SUFFIX}.gltf`,
  bite: `${pathMeshAnimations}/effects/bite${COMPRESSED_GLTF_SUFFIX}.gltf`,
  claw: `${pathMeshAnimations}/effects/claw${COMPRESSED_GLTF_SUFFIX}.gltf`,
  claw_impact: `${pathMeshAnimations}/effects/claw_impact${COMPRESSED_GLTF_SUFFIX}.gltf`,
  crow: `${pathMeshAnimations}/effects/crow${COMPRESSED_GLTF_SUFFIX}.gltf`,
  ground_aura: `${pathMeshAnimations}/effects/ground_aura${COMPRESSED_GLTF_SUFFIX}.gltf`,
  siphon: `${pathMeshAnimations}/effects/siphon${COMPRESSED_GLTF_SUFFIX}.gltf`,
  stomp_impact: `${pathMeshAnimations}/effects/stomp_impact${COMPRESSED_GLTF_SUFFIX}.gltf`,
  stomp_paw: `${pathMeshAnimations}/effects/stomp_paw${COMPRESSED_GLTF_SUFFIX}.gltf`,
  twinkle: `${pathMeshAnimations}/effects/twinkle${COMPRESSED_GLTF_SUFFIX}.gltf`,
  cog: `${pathMeshAnimations}/effects/cog${COMPRESSED_GLTF_SUFFIX}.gltf`,
  hearts: `${pathMeshAnimations}/effects/hearts${COMPRESSED_GLTF_SUFFIX}.gltf`,
  feathers: `${pathMeshAnimations}/effects/feathers${COMPRESSED_GLTF_SUFFIX}.gltf`,
  music_notes: `${pathMeshAnimations}/effects/music_notes${COMPRESSED_GLTF_SUFFIX}.gltf`,
  stealth_eye: `${pathMeshAnimations}/effects/stealth_eye${COMPRESSED_GLTF_SUFFIX}.gltf`,

  main_shape: `${pathMeshAnimations}/effects/card_casting/main_shape${COMPRESSED_GLTF_SUFFIX}.gltf`,
  burst_shine: `${pathMeshAnimations}/effects/card_casting/burst_shine${COMPRESSED_GLTF_SUFFIX}.gltf`,
  sparks: `${pathMeshAnimations}/effects/card_casting/sparks${COMPRESSED_GLTF_SUFFIX}.gltf`,
  electricity: `${pathMeshAnimations}/effects/card_casting/electricity${COMPRESSED_GLTF_SUFFIX}.gltf`,
  glow_bloom: `${pathMeshAnimations}/effects/card_casting/glow_bloom${COMPRESSED_GLTF_SUFFIX}.gltf`,
  card_flames: `${pathMeshAnimations}/effects/card_casting/flames${COMPRESSED_GLTF_SUFFIX}.gltf`,

  charge_up_energy_008: `${pathMeshAnimations}/effects/charge_up/energy_008${COMPRESSED_GLTF_SUFFIX}.gltf`,
  charge_up_energy_051: `${pathMeshAnimations}/effects/charge_up/energy_051${COMPRESSED_GLTF_SUFFIX}.gltf`,
  charge_up_energy_052: `${pathMeshAnimations}/effects/charge_up/energy_052${COMPRESSED_GLTF_SUFFIX}.gltf`,
  charge_up_energy_053: `${pathMeshAnimations}/effects/charge_up/energy_053${COMPRESSED_GLTF_SUFFIX}.gltf`,

  energy_tower_electricity: `${pathMeshAnimations}/effects/energy_tower/electricity${COMPRESSED_GLTF_SUFFIX}.gltf`,
  energy_tower_base_trail: `${pathMeshAnimations}/effects/energy_tower/base_trail${COMPRESSED_GLTF_SUFFIX}.gltf`,
  energy_tower_flames_base: `${pathMeshAnimations}/effects/energy_tower/flames_base${COMPRESSED_GLTF_SUFFIX}.gltf`,
  energy_tower_flames_bloom: `${pathMeshAnimations}/effects/energy_tower/flames_bloom${COMPRESSED_GLTF_SUFFIX}.gltf`,
  energy_tower_flames_trail: `${pathMeshAnimations}/effects/energy_tower/flames_trail${COMPRESSED_GLTF_SUFFIX}.gltf`,

  explosion_base: `${pathMeshAnimations}/effects/explosion/base${COMPRESSED_GLTF_SUFFIX}.gltf`,
  explosion_bloom: `${pathMeshAnimations}/effects/explosion/bloom${COMPRESSED_GLTF_SUFFIX}.gltf`,
  explosion_poof: `${pathMeshAnimations}/effects/explosion/poof${COMPRESSED_GLTF_SUFFIX}.gltf`,
  explosion_trace: `${pathMeshAnimations}/effects/explosion/trace${COMPRESSED_GLTF_SUFFIX}.gltf`,

  lava_puddle_bubbles_base: `${pathMeshAnimations}/effects/lava_puddle/bubbles_base${COMPRESSED_GLTF_SUFFIX}.gltf`,
  lava_puddle_bubbles_trail: `${pathMeshAnimations}/effects/lava_puddle/bubbles_trail${COMPRESSED_GLTF_SUFFIX}.gltf`,
  lava_puddle_crack: `${pathMeshAnimations}/effects/lava_puddle/crack${COMPRESSED_GLTF_SUFFIX}.gltf`,
  lava_puddle_embers: `${pathMeshAnimations}/effects/lava_puddle/embers${COMPRESSED_GLTF_SUFFIX}.gltf`,
  lava_puddle_flames_base: `${pathMeshAnimations}/effects/lava_puddle/flames_base${COMPRESSED_GLTF_SUFFIX}.gltf`,
  lava_puddle_flames_bloom: `${pathMeshAnimations}/effects/lava_puddle/flames_bloom${COMPRESSED_GLTF_SUFFIX}.gltf`,
  lava_puddle_flames_trace: `${pathMeshAnimations}/effects/lava_puddle/flames_trace${COMPRESSED_GLTF_SUFFIX}.gltf`,
  lava_puddle_main_bubble: `${pathMeshAnimations}/effects/lava_puddle/main_bubble${COMPRESSED_GLTF_SUFFIX}.gltf`,

  ada_empower_base: `${pathMeshAnimations}/effects/hero_abilities/ada/empower_base${COMPRESSED_GLTF_SUFFIX}.gltf`,
  ada_empower_bloom: `${pathMeshAnimations}/effects/hero_abilities/ada/empower_bloom${COMPRESSED_GLTF_SUFFIX}.gltf`,

  bouran_ritualize_back_flames_base: `${pathMeshAnimations}/effects/hero_abilities/bouran/ritualize/back_flames_base${COMPRESSED_GLTF_SUFFIX}.gltf`,
  bouran_ritualize_back_flames_bloom: `${pathMeshAnimations}/effects/hero_abilities/bouran/ritualize/back_flames_bloom${COMPRESSED_GLTF_SUFFIX}.gltf`,
  bouran_ritualize_circle_inner: `${pathMeshAnimations}/effects/hero_abilities/bouran/ritualize/circle_inner${COMPRESSED_GLTF_SUFFIX}.gltf`,
  bouran_ritualize_circle_moon_sun: `${pathMeshAnimations}/effects/hero_abilities/bouran/ritualize/circle_moon_sun${COMPRESSED_GLTF_SUFFIX}.gltf`,
  bouran_ritualize_circle_outer: `${pathMeshAnimations}/effects/hero_abilities/bouran/ritualize/circle_outer${COMPRESSED_GLTF_SUFFIX}.gltf`,
  bouran_ritualize_embers: `${pathMeshAnimations}/effects/hero_abilities/bouran/ritualize/embers${COMPRESSED_GLTF_SUFFIX}.gltf`,
  bouran_ritualize_front_flames_base: `${pathMeshAnimations}/effects/hero_abilities/bouran/ritualize/front_flames_base${COMPRESSED_GLTF_SUFFIX}.gltf`,
  bouran_ritualize_front_flames_bloom: `${pathMeshAnimations}/effects/hero_abilities/bouran/ritualize/front_flames_bloom${COMPRESSED_GLTF_SUFFIX}.gltf`,
  bouran_ritualize_glow: `${pathMeshAnimations}/effects/hero_abilities/bouran/ritualize/glow${COMPRESSED_GLTF_SUFFIX}.gltf`,

  samya_teleport_base: `${pathMeshAnimations}/effects/hero_abilities/samya/teleport/base${COMPRESSED_GLTF_SUFFIX}.gltf`,
  samya_teleport_bloom: `${pathMeshAnimations}/effects/hero_abilities/samya/teleport/bloom${COMPRESSED_GLTF_SUFFIX}.gltf`,
  samya_teleport_dust: `${pathMeshAnimations}/effects/hero_abilities/samya/teleport/dust${COMPRESSED_GLTF_SUFFIX}.gltf`,
  samya_teleport_energy: `${pathMeshAnimations}/effects/hero_abilities/samya/teleport/energy${COMPRESSED_GLTF_SUFFIX}.gltf`,

  ari_fabricate_base: `${pathMeshAnimations}/effects/hero_abilities/ari/fabricate/base${COMPRESSED_GLTF_SUFFIX}.gltf`,
  ari_fabricate_fill: `${pathMeshAnimations}/effects/hero_abilities/ari/fabricate/fill${COMPRESSED_GLTF_SUFFIX}.gltf`,

  hero_ability_trigger: `${pathMeshAnimations}/effects/hero_abilities/trigger${COMPRESSED_GLTF_SUFFIX}.gltf`,

  lotus_petals_1: `${pathMeshAnimations}/effects/hero_abilities/lotus/petals/petals_1${COMPRESSED_GLTF_SUFFIX}.gltf`,
  lotus_petals_2: `${pathMeshAnimations}/effects/hero_abilities/lotus/petals/petals_2${COMPRESSED_GLTF_SUFFIX}.gltf`,
  lotus_petals_3: `${pathMeshAnimations}/effects/hero_abilities/lotus/petals/petals_3${COMPRESSED_GLTF_SUFFIX}.gltf`,
  lotus_petals_4: `${pathMeshAnimations}/effects/hero_abilities/lotus/petals/petals_4${COMPRESSED_GLTF_SUFFIX}.gltf`,
  lotus_petals_5: `${pathMeshAnimations}/effects/hero_abilities/lotus/petals/petals_5${COMPRESSED_GLTF_SUFFIX}.gltf`,

  magma_chasm_base: `${pathMeshAnimations}/effects/magma_chasm/base${COMPRESSED_GLTF_SUFFIX}.gltf`,
  magma_chasm_bloom: `${pathMeshAnimations}/effects/magma_chasm/bloom${COMPRESSED_GLTF_SUFFIX}.gltf`,
  magma_chasm_bubbles: `${pathMeshAnimations}/effects/magma_chasm/bubbles${COMPRESSED_GLTF_SUFFIX}.gltf`,
  magma_chasm_burst: `${pathMeshAnimations}/effects/magma_chasm/burst${COMPRESSED_GLTF_SUFFIX}.gltf`,
  magma_chasm_smoke: `${pathMeshAnimations}/effects/magma_chasm/smoke${COMPRESSED_GLTF_SUFFIX}.gltf`,

  trident_base: `${pathMeshAnimations}/effects/trident/base${COMPRESSED_GLTF_SUFFIX}.gltf`,
  trident_bloom: `${pathMeshAnimations}/effects/trident/bloom${COMPRESSED_GLTF_SUFFIX}.gltf`,

  fox_packmaster_buff: `${pathMeshAnimations}/effects/hero_abilities/fox/packmaster/buff${COMPRESSED_GLTF_SUFFIX}.gltf`,
  fox_packmaster_clash: `${pathMeshAnimations}/effects/hero_abilities/fox/packmaster/clash${COMPRESSED_GLTF_SUFFIX}.gltf`,
  fox_packmaster_fox: `${pathMeshAnimations}/effects/hero_abilities/fox/packmaster/fox${COMPRESSED_GLTF_SUFFIX}.gltf`,

  sitti_psychomancy_fire: `${pathMeshAnimations}/effects/hero_abilities/sitti/psychomancy/fire${COMPRESSED_GLTF_SUFFIX}.gltf`,
  sitti_psychomancy_skulls: `${pathMeshAnimations}/effects/hero_abilities/sitti/psychomancy/skulls${COMPRESSED_GLTF_SUFFIX}.gltf`,
  sitti_psychomancy_smoke: `${pathMeshAnimations}/effects/hero_abilities/sitti/psychomancy/smoke${COMPRESSED_GLTF_SUFFIX}.gltf`,

  horik_vengeance_axe: `${pathMeshAnimations}/effects/hero_abilities/horik/vengeance/axe${COMPRESSED_GLTF_SUFFIX}.gltf`,
  horik_vengeance_buff: `${pathMeshAnimations}/effects/hero_abilities/horik/vengeance/buff${COMPRESSED_GLTF_SUFFIX}.gltf`,
  horik_vengeance_impact: `${pathMeshAnimations}/effects/hero_abilities/horik/vengeance/impact${COMPRESSED_GLTF_SUFFIX}.gltf`,
  horik_vengeance_strike: `${pathMeshAnimations}/effects/hero_abilities/horik/vengeance/strike${COMPRESSED_GLTF_SUFFIX}.gltf`,
  horik_vengeance_slice: `${pathMeshAnimations}/effects/hero_abilities/horik/vengeance/slice${COMPRESSED_GLTF_SUFFIX}.gltf`,

  axel_glow_slide: `${pathMeshAnimations}/effects/hero_abilities/axel/fates_fortune/glow_slide${COMPRESSED_GLTF_SUFFIX}.gltf`,
  axel_intro_flame: `${pathMeshAnimations}/effects/hero_abilities/axel/fates_fortune/intro_flame${COMPRESSED_GLTF_SUFFIX}.gltf`,
  axel_outro_flame: `${pathMeshAnimations}/effects/hero_abilities/axel/fates_fortune/outro_flame${COMPRESSED_GLTF_SUFFIX}.gltf`,
  axel_shine: `${pathMeshAnimations}/effects/hero_abilities/axel/fates_fortune/shine${COMPRESSED_GLTF_SUFFIX}.gltf`,
  axel_trail: `${pathMeshAnimations}/effects/hero_abilities/axel/fates_fortune/trail${COMPRESSED_GLTF_SUFFIX}.gltf`,
  axel_spectral_coins: `${pathMeshAnimations}/effects/hero_abilities/axel/fates_fortune/spectral_coins${COMPRESSED_GLTF_SUFFIX}.gltf`,

  titus_nurturer_energize: `${pathMeshAnimations}/effects/hero_abilities/titus/nurturer/energize${COMPRESSED_GLTF_SUFFIX}.gltf`,
  iris_meditation: `${pathMeshAnimations}/effects/hero_abilities/iris/meditation/meditation${COMPRESSED_GLTF_SUFFIX}.gltf`,
  mai_gadgeteer: `${pathMeshAnimations}/effects/hero_abilities/mai/gadgeteer/gadgeteer${COMPRESSED_GLTF_SUFFIX}.gltf`,
  zoey_live_fast: `${pathMeshAnimations}/effects/hero_abilities/zoey/live_fast/dust${COMPRESSED_GLTF_SUFFIX}.gltf`,
  banjo_mercurial: `${pathMeshAnimations}/effects/hero_abilities/banjo/mercurial/mercurial${COMPRESSED_GLTF_SUFFIX}.gltf`
}

export enum AssetPriority {
  Init,
  PreGame,
  Island,
  Game,
  AfterGameStart,
  EndGame,
  None
}

export const assetPriorities: { [K in AssetName]: AssetPriority } = {
  uiPreloader: AssetPriority.PreGame,
  // Init
  uvTest: AssetPriority.None,
  lightCacheDaylight: AssetPriority.Game,
  smoke: AssetPriority.None,
  gamePiecesGraphical: AssetPriority.PreGame,
  testCentroids: AssetPriority.None,
  plaqueVictory: AssetPriority.None,
  plaqueDefeat: AssetPriority.None,
  carvedWall: AssetPriority.AfterGameStart,
  uiSmall: AssetPriority.PreGame,
  cardBackFairy: AssetPriority.None,
  cardBackArcadeum: AssetPriority.None,
  cardBackSkull: AssetPriority.None,
  cardBackScrappy: AssetPriority.None,
  cardBackClockwork: AssetPriority.None,
  cardBackReefus: AssetPriority.None,
  cardBackVacation: AssetPriority.None,
  cardBackFunGuy: AssetPriority.None,
  cardBackStinkyEye: AssetPriority.None,
  cardBackTreasureMap: AssetPriority.None,
  cardBackPumpkin: AssetPriority.None,
  cardBackArmis: AssetPriority.None,
  cardBackCookie: AssetPriority.None,
  cardBackWaterfulBalls: AssetPriority.None,
  cardBackPicnicCake: AssetPriority.None,
  cardBackMuralLotus: AssetPriority.None,
  cardBackMuralAri: AssetPriority.None,
  // Game
  axel_coin: AssetPriority.None,
  gameArrow: AssetPriority.Game,
  fakeCylinderGlow: AssetPriority.None,
  dayNightColorStrip: AssetPriority.Island,
  uiPalette: AssetPriority.PreGame,
  effectPalette: AssetPriority.PreGame,
  iconPalette: AssetPriority.PreGame,
  deckFramePalette: AssetPriority.None,
  shroudUv: AssetPriority.None,
  cloudNormals: AssetPriority.Island,
  gamePiecesPhysical: AssetPriority.Game,
  gameArmorEffect: AssetPriority.Game,
  gameHolographicGlow: AssetPriority.None,
  gameBoardBasicModel: AssetPriority.None,
  gameBoardConquestModel: AssetPriority.None,
  manaVial: AssetPriority.Game,
  starterDeckFrame: AssetPriority.None,
  islandBasicModel: AssetPriority.None,
  islandConquest1Model: AssetPriority.None,
  islandConquest2Model: AssetPriority.None,
  islandConquest3Model: AssetPriority.None,
  testLumpModel: AssetPriority.None,
  errorMushroom: AssetPriority.Game,
  optionsBg: AssetPriority.Game,
  bgLoading: AssetPriority.Game,
  spellLoading: AssetPriority.Game,
  unitLoading: AssetPriority.Game,
  // Tutorial
  tutorialCube: AssetPriority.None,
  noise3Map: AssetPriority.None,
  noise3dNormalizedFullMap: AssetPriority.None,
  noiseyTriangles3dNormalizedFullMap: AssetPriority.None,
  noiseyScales3dNormalizedFullMap: AssetPriority.None,
  noiseyScales23dNormalizedFullMap: AssetPriority.None,
  foilStarsMap: AssetPriority.None,
  noise3dNormalizedHalfMap: AssetPriority.None,
  noise3dNormalizedQuarterMap: AssetPriority.None,
  fireEffectSourceMap: AssetPriority.Game,
  fogEffectSourceMap: AssetPriority.PreGame,
  layeredNoise3Map: AssetPriority.None,
  particle: AssetPriority.AfterGameStart,
  particle2: AssetPriority.AfterGameStart,
  witherParticleSpritesheet: AssetPriority.AfterGameStart,
  fireSpritesheet: AssetPriority.None,
  brushStroke: AssetPriority.None,
  // Animations - loaded when needed
  keywordArmorAnimation: AssetPriority.AfterGameStart,
  keywordBannerAnimation: AssetPriority.AfterGameStart,
  keywordLifestealAnimation: AssetPriority.AfterGameStart,
  keywordWitherAnimation: AssetPriority.AfterGameStart,
  sleepingAnimation: AssetPriority.AfterGameStart,
  damageAnimation: AssetPriority.AfterGameStart,
  damageFatigueAnimation: AssetPriority.AfterGameStart,
  triggerAnimation: AssetPriority.AfterGameStart,
  auraTriggerAnimation: AssetPriority.AfterGameStart,
  buffGenericAnimation: AssetPriority.AfterGameStart,
  // keywords
  "keyword-conjure-icon": AssetPriority.AfterGameStart,
"keyword-draw-icon": AssetPriority.AfterGameStart,
"trait-wither-icon": AssetPriority.AfterGameStart,
"trigger-death-icon": AssetPriority.AfterGameStart,
"keyword-dust-icon": AssetPriority.AfterGameStart,
"trait-armor-icon": AssetPriority.AfterGameStart,
"trait-banner-icon": AssetPriority.AfterGameStart,
"trigger-glory-icon": AssetPriority.AfterGameStart,
"trait-guard-icon": AssetPriority.AfterGameStart,
"trait-lifesteal-icon": AssetPriority.AfterGameStart,
"trait-stealth-icon": AssetPriority.AfterGameStart,
"trigger-inspire-icon": AssetPriority.AfterGameStart,
"keyword-mulligan-icon": AssetPriority.AfterGameStart,
"trigger-generic-icon": AssetPriority.AfterGameStart,
"trigger-sunset-icon": AssetPriority.AfterGameStart,
"trigger-sunrise-icon": AssetPriority.AfterGameStart,
"trait-dash-icon": AssetPriority.AfterGameStart,
"trigger-slay-icon": AssetPriority.AfterGameStart,
  enchantmentAnima: AssetPriority.AfterGameStart,
  enchantmentBarrier: AssetPriority.AfterGameStart,
  enchantmentBlind: AssetPriority.AfterGameStart,
  enchantmentChains: AssetPriority.AfterGameStart,
  enchantmentDazed: AssetPriority.AfterGameStart,
  enchantmentFate: AssetPriority.AfterGameStart,
  enchantmentFlames: AssetPriority.AfterGameStart,
  enchantmentFrozen: AssetPriority.AfterGameStart,
  enchantmentFury: AssetPriority.AfterGameStart,
  enchantmentHex: AssetPriority.AfterGameStart,
  enchantmentLead: AssetPriority.AfterGameStart,
  enchantmentRoots: AssetPriority.AfterGameStart,
  enchantmentShield: AssetPriority.AfterGameStart,
  enchantmentShroud: AssetPriority.AfterGameStart,
  enchantmentSilence: AssetPriority.AfterGameStart,
  enchantmentVapors: AssetPriority.AfterGameStart,
  cardAspectArrow: AssetPriority.None,
  cardAspectArrowGreen: AssetPriority.None,
  // Music
  musicGame: AssetPriority.None,
  musicVictory: AssetPriority.None,
  musicDefeat: AssetPriority.None,
  audioFxCommon: AssetPriority.Game,
  audioFxTutorial: AssetPriority.None,
  audioFxCommonVariations: AssetPriority.None,
  audioFxCards: AssetPriority.Game,
  audioFxMatchEnd: AssetPriority.None,
  audioFxMatchEndVariations: AssetPriority.None,
  uiPreviewDeath: AssetPriority.Game,
  uiPreviewDust: AssetPriority.Game,
  uiPreviewDraw: AssetPriority.Game,
  uiPreviewMulligan: AssetPriority.Game,
  uiPreviewReturnToHand: AssetPriority.Game,
  uiPreviewSendToDeck: AssetPriority.Game,
  uiPreviewSendToGraveyard: AssetPriority.Game,
  uiPreviewSummon: AssetPriority.Game,
  meshAnimationAir01: AssetPriority.None,
  meshAnimationAir02: AssetPriority.None,
  meshAnimationAir03: AssetPriority.None,
  meshAnimationAir09: AssetPriority.None,
  meshAnimationAir11: AssetPriority.None,
  meshAnimationAir14: AssetPriority.None,
  meshAnimationAir15: AssetPriority.None,
  meshAnimationAir16: AssetPriority.None,
  meshAnimationAir17: AssetPriority.None,
  meshAnimationAir18: AssetPriority.None,
  meshAnimationAir19: AssetPriority.None,
  meshAnimationAir20: AssetPriority.None,
  meshAnimationAir22: AssetPriority.None,
  meshAnimationAir23: AssetPriority.None,
  meshAnimationAir24: AssetPriority.None,
  meshAnimationAir25: AssetPriority.None,
  meshAnimationEarth07: AssetPriority.None,
  meshAnimationEarth09: AssetPriority.None,
  meshAnimationEarth10: AssetPriority.None,
  meshAnimationEarth11: AssetPriority.None,
  meshAnimationEarth13: AssetPriority.None,
  meshAnimationEnergy00: AssetPriority.None,
  meshAnimationEnergy02: AssetPriority.None,
  meshAnimationEnergy04: AssetPriority.None,
  meshAnimationEnergy05: AssetPriority.None,
  meshAnimationEnergy06: AssetPriority.None,
  meshAnimationEnergy07: AssetPriority.None,
  meshAnimationEnergy08: AssetPriority.None,
  meshAnimationEnergy10: AssetPriority.None,
  meshAnimationEnergy11: AssetPriority.None,
  meshAnimationEnergy12: AssetPriority.None,
  meshAnimationEnergy13: AssetPriority.None,
  meshAnimationEnergy14: AssetPriority.None,
  meshAnimationEnergy15: AssetPriority.None,
  meshAnimationEnergy16: AssetPriority.None,
  meshAnimationEnergy17: AssetPriority.None,
  meshAnimationEnergy18: AssetPriority.None,
  meshAnimationEnergy19: AssetPriority.None,
  meshAnimationEnergy20: AssetPriority.None,
  meshAnimationEnergy21: AssetPriority.None,
  meshAnimationEnergy22: AssetPriority.None,
  meshAnimationEnergy23: AssetPriority.None,
  meshAnimationEnergy24: AssetPriority.None,
  meshAnimationEnergy27: AssetPriority.None,
  meshAnimationEnergy28: AssetPriority.None,
  meshAnimationEnergy29: AssetPriority.None,
  meshAnimationExplosion01: AssetPriority.None,
  meshAnimationExplosion02: AssetPriority.None,
  meshAnimationExplosion03: AssetPriority.None,
  meshAnimationFire01: AssetPriority.None,
  meshAnimationFire04: AssetPriority.None,
  meshAnimationFire08: AssetPriority.None,
  meshAnimationFire09: AssetPriority.None,
  meshAnimationFire10: AssetPriority.None,
  meshAnimationFire11: AssetPriority.None,
  meshAnimationFire12: AssetPriority.None,
  meshAnimationFire13: AssetPriority.None,
  meshAnimationFire14: AssetPriority.None,
  meshAnimationFire15: AssetPriority.None,
  meshAnimationFire16: AssetPriority.None,
  meshAnimationFire17: AssetPriority.None,
  meshAnimationFire18: AssetPriority.None,
  meshAnimationFire19: AssetPriority.None,
  meshAnimationFire20: AssetPriority.None,
  meshAnimationFire21: AssetPriority.None,
  meshAnimationFire22: AssetPriority.None,
  meshAnimationFire23: AssetPriority.None,
  meshAnimationFire24: AssetPriority.None,
  meshAnimationFire27: AssetPriority.None,
  meshAnimationSmoke08: AssetPriority.None,
  meshAnimationSmoke18: AssetPriority.None,
  meshAnimationWater01: AssetPriority.None,
  meshAnimationWater02: AssetPriority.None,
  meshAnimationWater03: AssetPriority.None,
  meshAnimationWater04: AssetPriority.None,
  meshAnimationWater05: AssetPriority.None,
  meshAnimationWater06: AssetPriority.None,
  meshAnimationWater07: AssetPriority.None,
  meshAnimationWater08: AssetPriority.None,
  meshAnimationWater09: AssetPriority.None,
  meshAnimationWater12: AssetPriority.None,
  meshAnimationWater13: AssetPriority.None,
  meshAnimationWater14: AssetPriority.None,
  meshAnimationWater15: AssetPriority.None,
  meshAnimationWater16: AssetPriority.None,
  meshAnimationWater17: AssetPriority.None,
  meshAnimationWater18: AssetPriority.None,
  meshAnimationWater19: AssetPriority.None,
  meshAnimationWater20: AssetPriority.None,
  meshAnimationWater21: AssetPriority.None,
  meshAnimationWater22: AssetPriority.None,
  meshAnimationWater23: AssetPriority.None,
  meshAnimationWater24: AssetPriority.None,
  meshAnimationWater25: AssetPriority.None,
  meshAnimationWater26: AssetPriority.None,
  meshAnimationWater27: AssetPriority.None,
  ground_crack: AssetPriority.None,
  meshAnimationCrackTest: AssetPriority.None,
  meshAnimationCrack2Test: AssetPriority.None,
  meshAnimationShroudTest: AssetPriority.None,
  meshAnimationShroud2Test: AssetPriority.None,
  meshAnimationShroud3Test: AssetPriority.None,
  meshAnimationElectricity015: AssetPriority.None,
  meshAnimationElectricity043: AssetPriority.None,
  meshAnimationElectricity048: AssetPriority.None,
  meshAnimationElectricity049: AssetPriority.None,
  meshAnimationElectricity051: AssetPriority.None,
  meshAnimationEnergy008: AssetPriority.None,
  meshAnimationEnergy015: AssetPriority.None,
  meshAnimationEnergy020: AssetPriority.None,
  meshAnimationEnergy021: AssetPriority.None,
  meshAnimationEnergy025: AssetPriority.None,
  meshAnimationEnergy027: AssetPriority.None,
  meshAnimationEnergy031: AssetPriority.None,
  meshAnimationEnergy060: AssetPriority.None,
  meshAnimationEnergy064: AssetPriority.None,
  meshAnimationExplosion019: AssetPriority.None,
  meshAnimationFire001: AssetPriority.None,
  meshAnimationFire017: AssetPriority.None,
  meshAnimationFire026: AssetPriority.None,
  meshAnimationFire089: AssetPriority.None,
  meshAnimationFire107: AssetPriority.None,
  meshAnimationFire116: AssetPriority.None,
  meshAnimationLiquid017: AssetPriority.None,
  meshAnimationLiquid037: AssetPriority.None,
  meshAnimationLiquid056: AssetPriority.None,
  meshAnimationFire119: AssetPriority.None,
  meshAnimationSmoke002: AssetPriority.None,
  meshAnimationSmoke004: AssetPriority.None,
  meshAnimationSmoke012: AssetPriority.None,
  meshAnimationSmoke016: AssetPriority.None,
  meshAnimationSmoke022: AssetPriority.None,
  meshAnimationSmoke026: AssetPriority.None,
  meshAnimationSmoke027: AssetPriority.None,
  meshAnimationSmoke031: AssetPriority.None,
  meshAnimationSmoke041: AssetPriority.None,
  meshAnimationSmoke064: AssetPriority.None,
  meshAnimationSmoke066: AssetPriority.None,
  meshAnimationSmoke068: AssetPriority.None,
  fire_fragment_test: AssetPriority.None,
  fire_vortex_test: AssetPriority.None,
  fire_vortex2_test: AssetPriority.None,
  smoke_bomb_test: AssetPriority.None,
  fire_radial_glow_test: AssetPriority.None,
  generic_AOE_v1: AssetPriority.None,
  border_glint_guard: AssetPriority.AfterGameStart,
  border_glint_unit: AssetPriority.AfterGameStart,
  border_glint_spell: AssetPriority.AfterGameStart,
  generic_trigger: AssetPriority.None,
  water_trigger: AssetPriority.None,
  light_trigger: AssetPriority.None,
  fire_trigger: AssetPriority.None,
  mind_trigger: AssetPriority.None,
  metal_trigger: AssetPriority.None,
  earth_trigger: AssetPriority.None,
  slay_trigger: AssetPriority.None,
  knives: AssetPriority.None,
  flames: AssetPriority.None,
  glorious_mane: AssetPriority.None,
  mad_vibes: AssetPriority.None,
  glory_trigger: AssetPriority.None,
  test_death_trigger: AssetPriority.None,
  death_trigger_high: AssetPriority.None,
  death_trigger_low: AssetPriority.None,
  phoenix_plume_top: AssetPriority.None,
  debuff_lines: AssetPriority.None,
  hero_death_small_blast: AssetPriority.None,
  hero_death_small_smoke: AssetPriority.None,
  hero_death_big_black_smoke: AssetPriority.AfterGameStart,
  hero_death_big_points: AssetPriority.AfterGameStart,
  hero_death_big_ground_ring_3d: AssetPriority.AfterGameStart,
  hero_death_big_flare: AssetPriority.AfterGameStart,
  hero_death_big_clouds_A: AssetPriority.AfterGameStart,
  hero_death_big_clouds_B: AssetPriority.AfterGameStart,

  arrow: AssetPriority.None,
  bite: AssetPriority.None,
  claw: AssetPriority.None,
  claw_impact: AssetPriority.None,
  crow: AssetPriority.None,
  ground_aura: AssetPriority.None,
  siphon: AssetPriority.None,
  stomp_impact: AssetPriority.None,
  stomp_paw: AssetPriority.None,
  twinkle: AssetPriority.None,
  cog: AssetPriority.None,
  hearts: AssetPriority.None,
  feathers: AssetPriority.None,
  music_notes: AssetPriority.None,
  stealth_eye: AssetPriority.None,

  main_shape: AssetPriority.None,
  burst_shine: AssetPriority.None,
  sparks: AssetPriority.None,
  electricity: AssetPriority.None,
  glow_bloom: AssetPriority.None,
  card_flames: AssetPriority.None,

  charge_up_energy_008: AssetPriority.None,
  charge_up_energy_051: AssetPriority.None,
  charge_up_energy_052: AssetPriority.None,
  charge_up_energy_053: AssetPriority.None,

  energy_tower_flames_base: AssetPriority.None,
  energy_tower_flames_bloom: AssetPriority.None,
  energy_tower_flames_trail: AssetPriority.None,
  energy_tower_electricity: AssetPriority.None,
  energy_tower_base_trail: AssetPriority.None,

  explosion_base: AssetPriority.None,
  explosion_bloom: AssetPriority.None,
  explosion_poof: AssetPriority.None,
  explosion_trace: AssetPriority.None,

  lava_puddle_bubbles_base: AssetPriority.None,
  lava_puddle_bubbles_trail: AssetPriority.None,
  lava_puddle_crack: AssetPriority.None,
  lava_puddle_embers: AssetPriority.None,
  lava_puddle_flames_base: AssetPriority.None,
  lava_puddle_flames_bloom: AssetPriority.None,
  lava_puddle_flames_trace: AssetPriority.None,
  lava_puddle_main_bubble: AssetPriority.None,

  // TODO; only load the MSAs for the heroes in the current game (currenlty a maximum of 2 and 1 for mirror matches)

  ada_empower_base: AssetPriority.None,
  ada_empower_bloom: AssetPriority.None,

  bouran_ritualize_back_flames_base: AssetPriority.None,
  bouran_ritualize_back_flames_bloom: AssetPriority.None,
  bouran_ritualize_circle_inner: AssetPriority.None,
  bouran_ritualize_circle_moon_sun: AssetPriority.None,
  bouran_ritualize_circle_outer: AssetPriority.None,
  bouran_ritualize_embers: AssetPriority.None,
  bouran_ritualize_front_flames_base: AssetPriority.None,
  bouran_ritualize_front_flames_bloom: AssetPriority.None,
  bouran_ritualize_glow: AssetPriority.None,

  samya_teleport_base: AssetPriority.None,
  samya_teleport_bloom: AssetPriority.None,
  samya_teleport_dust: AssetPriority.None,
  samya_teleport_energy: AssetPriority.None,

  ari_fabricate_base: AssetPriority.None,
  ari_fabricate_fill: AssetPriority.None,

  hero_ability_trigger: AssetPriority.Game,

  lotus_petals_1: AssetPriority.None,
  lotus_petals_2: AssetPriority.None,
  lotus_petals_3: AssetPriority.None,
  lotus_petals_4: AssetPriority.None,
  lotus_petals_5: AssetPriority.None,

  magma_chasm_base: AssetPriority.None,
  magma_chasm_bloom: AssetPriority.None,
  magma_chasm_bubbles: AssetPriority.None,
  magma_chasm_burst: AssetPriority.None,
  magma_chasm_smoke: AssetPriority.None,

  trident_base: AssetPriority.None,
  trident_bloom: AssetPriority.None,

  fox_packmaster_buff: AssetPriority.None,
  fox_packmaster_clash: AssetPriority.None,
  fox_packmaster_fox: AssetPriority.None,

  sitti_psychomancy_fire: AssetPriority.None,
  sitti_psychomancy_skulls: AssetPriority.None,
  sitti_psychomancy_smoke: AssetPriority.None,

  horik_vengeance_axe: AssetPriority.None,
  horik_vengeance_buff: AssetPriority.None,
  horik_vengeance_impact: AssetPriority.None,
  horik_vengeance_strike: AssetPriority.None,
  horik_vengeance_slice: AssetPriority.None,

  axel_glow_slide: AssetPriority.None,
  axel_intro_flame: AssetPriority.None,
  axel_outro_flame: AssetPriority.None,
  axel_shine: AssetPriority.None,
  axel_trail: AssetPriority.None,
  axel_spectral_coins: AssetPriority.None,

  titus_nurturer_energize: AssetPriority.None,
  iris_meditation: AssetPriority.None,
  mai_gadgeteer: AssetPriority.None,
  zoey_live_fast: AssetPriority.None,
  banjo_mercurial: AssetPriority.None
}

export const assetCacheFlags: { [K in AssetName]: boolean } = {
  uiPreloader: true,
  // Init
  uvTest: false,
  lightCacheDaylight: true,
  smoke: false,
  gamePiecesGraphical: true,
  testCentroids: false,
  plaqueVictory: false,
  plaqueDefeat: false,
  carvedWall: true,
  uiSmall: true,
  // Cardbacks
  cardBackFairy: false,
  cardBackArcadeum: false,
  cardBackSkull: false,
  cardBackScrappy: false,
  cardBackClockwork: false,
  cardBackReefus: false,
  cardBackVacation: false,
  cardBackFunGuy: false,
  cardBackStinkyEye: false,
  cardBackTreasureMap: false,
  cardBackPumpkin: false,
  cardBackArmis: false,
  cardBackCookie: false,
  cardBackWaterfulBalls: false,
  cardBackPicnicCake: false,
  cardBackMuralLotus: false,
  cardBackMuralAri: false,
  // Game
  axel_coin: true,
  gameArrow: true,
  fakeCylinderGlow: true,
  dayNightColorStrip: true,
  uiPalette: true,
  effectPalette: true,
  iconPalette: true,
  deckFramePalette: false,
  shroudUv: false,
  cloudNormals: true,
  gamePiecesPhysical: true,
  gameArmorEffect: true,
  gameHolographicGlow: false,
  gameBoardBasicModel: false,
  gameBoardConquestModel: false,
  manaVial: true,
  starterDeckFrame: false,
  islandBasicModel: false,
  islandConquest1Model: false,
  islandConquest2Model: false,
  islandConquest3Model: false,
  testLumpModel: false,
  errorMushroom: true,
  optionsBg: true,
  bgLoading: true,
  spellLoading: true,
  unitLoading: true,
  // Tutorial
  tutorialCube: false,
  noise3Map: false,
  noise3dNormalizedFullMap: false,
  noiseyTriangles3dNormalizedFullMap: false,
  noiseyScales3dNormalizedFullMap: false,
  noiseyScales23dNormalizedFullMap: false,
  foilStarsMap: false,
  noise3dNormalizedHalfMap: false,
  noise3dNormalizedQuarterMap: false,
  fireEffectSourceMap: true,
  fogEffectSourceMap: false,
  layeredNoise3Map: false,
  particle: true,
  particle2: true,
  witherParticleSpritesheet: true,
  fireSpritesheet: false,
  brushStroke: false,
  // Animations - loaded when needed
  keywordArmorAnimation: true,
  keywordBannerAnimation: true,
  keywordLifestealAnimation: true,
  keywordWitherAnimation: true,
  sleepingAnimation: true,
  damageAnimation: true,
  damageFatigueAnimation: true,
  triggerAnimation: true,
  auraTriggerAnimation: true,
  buffGenericAnimation: true,
  // keywords
"keyword-conjure-icon": true,
"keyword-draw-icon": true,
"trait-wither-icon": true,
"trigger-death-icon": true,
"keyword-dust-icon": true,
"trait-armor-icon": true,
"trait-banner-icon": true,
"trigger-glory-icon": true,
"trait-guard-icon": true,
"trait-lifesteal-icon": true,
"trait-stealth-icon": true,
"trigger-inspire-icon": true,
"keyword-mulligan-icon": true,
"trigger-generic-icon": true,
"trigger-sunset-icon": true,
"trigger-sunrise-icon": true,
"trait-dash-icon": true,
"trigger-slay-icon": true,
  enchantmentAnima: true,
  enchantmentBarrier: true,
  enchantmentBlind: true,
  enchantmentChains: true,
  enchantmentDazed: true,
  enchantmentFate: true,
  enchantmentFlames: true,
  enchantmentFrozen: true,
  enchantmentFury: true,
  enchantmentHex: true,
  enchantmentLead: true,
  enchantmentRoots: true,
  enchantmentShield: true,
  enchantmentShroud: true,
  enchantmentSilence: true,
  enchantmentVapors: true,
  cardAspectArrow: false,
  cardAspectArrowGreen: false,
  // Music
  musicGame: false,
  musicVictory: false,
  musicDefeat: false,
  audioFxCommon: true,
  audioFxTutorial: false,
  audioFxCommonVariations: true,
  audioFxCards: true,
  audioFxMatchEnd: false,
  audioFxMatchEndVariations: false,
  uiPreviewDeath: true,
  uiPreviewDust: true,
  uiPreviewDraw: true,
  uiPreviewMulligan: true,
  uiPreviewReturnToHand: true,
  uiPreviewSendToDeck: true,
  uiPreviewSendToGraveyard: true,
  uiPreviewSummon: true,
  meshAnimationAir01: false,
  meshAnimationAir02: false,
  meshAnimationAir03: false,
  meshAnimationAir09: false,
  meshAnimationAir11: false,
  meshAnimationAir14: false,
  meshAnimationAir15: false,
  meshAnimationAir16: false,
  meshAnimationAir17: false,
  meshAnimationAir18: false,
  meshAnimationAir19: false,
  meshAnimationAir20: false,
  meshAnimationAir22: false,
  meshAnimationAir23: false,
  meshAnimationAir24: false,
  meshAnimationAir25: false,
  meshAnimationEarth07: false,
  meshAnimationEarth09: false,
  meshAnimationEarth10: false,
  meshAnimationEarth11: false,
  meshAnimationEarth13: false,
  meshAnimationEnergy00: false,
  meshAnimationEnergy02: false,
  meshAnimationEnergy04: false,
  meshAnimationEnergy05: false,
  meshAnimationEnergy06: false,
  meshAnimationEnergy07: false,
  meshAnimationEnergy08: false,
  meshAnimationEnergy10: false,
  meshAnimationEnergy11: false,
  meshAnimationEnergy12: false,
  meshAnimationEnergy13: false,
  meshAnimationEnergy14: false,
  meshAnimationEnergy15: false,
  meshAnimationEnergy16: false,
  meshAnimationEnergy17: false,
  meshAnimationEnergy18: false,
  meshAnimationEnergy19: false,
  meshAnimationEnergy20: false,
  meshAnimationEnergy21: false,
  meshAnimationEnergy22: false,
  meshAnimationEnergy23: false,
  meshAnimationEnergy24: false,
  meshAnimationEnergy27: false,
  meshAnimationEnergy28: false,
  meshAnimationEnergy29: false,
  meshAnimationExplosion01: false,
  meshAnimationExplosion02: false,
  meshAnimationExplosion03: false,
  meshAnimationFire01: false,
  meshAnimationFire04: false,
  meshAnimationFire08: false,
  meshAnimationFire09: false,
  meshAnimationFire10: false,
  meshAnimationFire11: false,
  meshAnimationFire12: false,
  meshAnimationFire13: false,
  meshAnimationFire14: false,
  meshAnimationFire15: false,
  meshAnimationFire16: false,
  meshAnimationFire17: false,
  meshAnimationFire18: false,
  meshAnimationFire19: false,
  meshAnimationFire20: false,
  meshAnimationFire21: false,
  meshAnimationFire22: false,
  meshAnimationFire23: false,
  meshAnimationFire24: false,
  meshAnimationFire27: false,
  meshAnimationSmoke08: false,
  meshAnimationSmoke18: false,
  meshAnimationWater01: false,
  meshAnimationWater02: false,
  meshAnimationWater03: false,
  meshAnimationWater04: false,
  meshAnimationWater05: false,
  meshAnimationWater06: false,
  meshAnimationWater07: false,
  meshAnimationWater08: false,
  meshAnimationWater09: false,
  meshAnimationWater12: false,
  meshAnimationWater13: false,
  meshAnimationWater14: false,
  meshAnimationWater15: false,
  meshAnimationWater16: false,
  meshAnimationWater17: false,
  meshAnimationWater18: false,
  meshAnimationWater19: false,
  meshAnimationWater20: false,
  meshAnimationWater21: false,
  meshAnimationWater22: false,
  meshAnimationWater23: false,
  meshAnimationWater24: false,
  meshAnimationWater25: false,
  meshAnimationWater26: false,
  meshAnimationWater27: false,
  ground_crack: true,
  meshAnimationCrackTest: false,
  meshAnimationCrack2Test: false,
  meshAnimationShroudTest: false,
  meshAnimationShroud2Test: false,
  meshAnimationShroud3Test: false,
  meshAnimationElectricity015: false,
  meshAnimationElectricity043: false,
  meshAnimationElectricity048: false,
  meshAnimationElectricity049: false,
  meshAnimationElectricity051: false,
  meshAnimationEnergy008: false,
  meshAnimationEnergy015: false,
  meshAnimationEnergy020: false,
  meshAnimationEnergy021: false,
  meshAnimationEnergy025: false,
  meshAnimationEnergy027: true,
  meshAnimationEnergy031: false,
  meshAnimationEnergy060: false,
  meshAnimationEnergy064: false,
  meshAnimationExplosion019: true,
  meshAnimationFire001: false,
  meshAnimationFire017: false,
  meshAnimationFire026: false,
  meshAnimationFire089: false,
  meshAnimationFire107: false,
  meshAnimationFire116: false,
  meshAnimationLiquid017: false,
  meshAnimationLiquid037: false,
  meshAnimationLiquid056: false,
  meshAnimationFire119: false,
  meshAnimationSmoke002: false,
  meshAnimationSmoke004: false,
  meshAnimationSmoke012: false,
  meshAnimationSmoke016: false,
  meshAnimationSmoke022: false,
  meshAnimationSmoke026: false,
  meshAnimationSmoke027: false,
  meshAnimationSmoke031: false,
  meshAnimationSmoke041: false,
  meshAnimationSmoke064: false,
  meshAnimationSmoke066: false,
  meshAnimationSmoke068: false,
  fire_fragment_test: false,
  fire_vortex_test: false,
  fire_vortex2_test: false,
  smoke_bomb_test: false,
  fire_radial_glow_test: false,
  generic_AOE_v1: false,
  border_glint_guard: true,
  border_glint_unit: true,
  border_glint_spell: true,
  generic_trigger: true,
  water_trigger: true,
  light_trigger: true,
  fire_trigger: true,
  mind_trigger: true,
  metal_trigger: true,
  earth_trigger: false,
  knives: true,
  flames: true,
  glorious_mane: true,
  mad_vibes: true,
  glory_trigger: true,
  slay_trigger: true,
  test_death_trigger: false,
  death_trigger_high: true,
  death_trigger_low: true,
  phoenix_plume_top: true,
  debuff_lines: true,
  hero_death_small_blast: false,
  hero_death_small_smoke: false,
  hero_death_big_black_smoke: true,
  hero_death_big_points: true,
  hero_death_big_ground_ring_3d: true,
  hero_death_big_flare: true,
  hero_death_big_clouds_A: true,
  hero_death_big_clouds_B: true,
  arrow: true,
  bite: true,
  claw: true,
  claw_impact: true,
  crow: true,
  ground_aura: true,
  siphon: true,
  stomp_impact: true,
  stomp_paw: true,
  twinkle: true,
  cog: true,
  hearts: true,
  feathers: true,
  music_notes: true,
  stealth_eye: true,

  main_shape: true,
  burst_shine: true,
  sparks: true,
  electricity: true,
  glow_bloom: true,
  card_flames: true,

  charge_up_energy_008: true,
  charge_up_energy_051: true,
  charge_up_energy_052: true,
  charge_up_energy_053: true,

  energy_tower_flames_base: true,
  energy_tower_flames_bloom: true,
  energy_tower_flames_trail: true,
  energy_tower_electricity: true,
  energy_tower_base_trail: true,

  explosion_base: true,
  explosion_bloom: true,
  explosion_poof: true,
  explosion_trace: true,

  lava_puddle_bubbles_base: true,
  lava_puddle_bubbles_trail: true,
  lava_puddle_crack: true,
  lava_puddle_embers: true,
  lava_puddle_flames_base: true,
  lava_puddle_flames_bloom: true,
  lava_puddle_flames_trace: true,
  lava_puddle_main_bubble: true,

  ada_empower_base: true,
  ada_empower_bloom: true,

  bouran_ritualize_back_flames_base: true,
  bouran_ritualize_back_flames_bloom: true,
  bouran_ritualize_circle_inner: true,
  bouran_ritualize_circle_moon_sun: true,
  bouran_ritualize_circle_outer: true,
  bouran_ritualize_embers: true,
  bouran_ritualize_front_flames_base: true,
  bouran_ritualize_front_flames_bloom: true,
  bouran_ritualize_glow: true,

  samya_teleport_base: true,
  samya_teleport_bloom: true,
  samya_teleport_dust: true,
  samya_teleport_energy: true,

  ari_fabricate_base: true,
  ari_fabricate_fill: true,

  hero_ability_trigger: true,

  lotus_petals_1: true,
  lotus_petals_2: true,
  lotus_petals_3: true,
  lotus_petals_4: true,
  lotus_petals_5: true,

  magma_chasm_base: true,
  magma_chasm_bloom: true,
  magma_chasm_bubbles: true,
  magma_chasm_burst: true,
  magma_chasm_smoke: true,

  trident_base: true,
  trident_bloom: true,

  fox_packmaster_buff: true,
  fox_packmaster_clash: true,
  fox_packmaster_fox: true,

  sitti_psychomancy_fire: true,
  sitti_psychomancy_skulls: true,
  sitti_psychomancy_smoke: true,

  horik_vengeance_axe: true,
  horik_vengeance_buff: true,
  horik_vengeance_impact: true,
  horik_vengeance_strike: true,
  horik_vengeance_slice: true,

  axel_glow_slide: true,
  axel_intro_flame: true,
  axel_outro_flame: true,
  axel_shine: true,
  axel_trail: true,
  axel_spectral_coins: true,

  titus_nurturer_energize: true,
  iris_meditation: true,
  mai_gadgeteer: true,
  zoey_live_fast: true,
  banjo_mercurial: true
}

export const assetTypes = {
  uiPreloader: 'gltf',
  gamePiecesPhysical: 'gltf',
  gameArmorEffect: 'gltf',
  gameHolographicGlow: 'gltf',
  gameArrow: 'gltf',
  fakeCylinderGlow: 'gltf',
  tutorialCube: 'gltf',
  manaVial: 'gltf',
  starterDeckFrame: 'gltf',
  gameBoardBasicModel: 'gltf',
  gameBoardConquestModel: 'gltf',
  islandBasicModel: 'gltf',
  islandConquest1Model: 'gltf',
  islandConquest2Model: 'gltf',
  islandConquest3Model: 'gltf',
  testLumpModel: 'gltf',
  gamePiecesGraphical: 'gltf',
  testCentroids: 'gltf',
  plaqueVictory: 'gltf',
  plaqueDefeat: 'gltf',
  carvedWall: 'gltf',
  uiSmall: 'gltf',
  meshAnimationAir01: 'gltf',
  meshAnimationAir02: 'gltf',
  meshAnimationAir03: 'gltf',
  meshAnimationAir09: 'gltf',
  meshAnimationAir11: 'gltf',
  meshAnimationAir14: 'gltf',
  meshAnimationAir15: 'gltf',
  meshAnimationAir16: 'gltf',
  meshAnimationAir17: 'gltf',
  meshAnimationAir18: 'gltf',
  meshAnimationAir19: 'gltf',
  meshAnimationAir20: 'gltf',
  meshAnimationAir22: 'gltf',
  meshAnimationAir23: 'gltf',
  meshAnimationAir24: 'gltf',
  meshAnimationAir25: 'gltf',
  meshAnimationEarth07: 'gltf',
  meshAnimationEarth09: 'gltf',
  meshAnimationEarth10: 'gltf',
  meshAnimationEarth11: 'gltf',
  meshAnimationEarth13: 'gltf',
  meshAnimationEnergy00: 'gltf',
  meshAnimationEnergy02: 'gltf',
  meshAnimationEnergy04: 'gltf',
  meshAnimationEnergy05: 'gltf',
  meshAnimationEnergy06: 'gltf',
  meshAnimationEnergy07: 'gltf',
  meshAnimationEnergy08: 'gltf',
  meshAnimationEnergy10: 'gltf',
  meshAnimationEnergy11: 'gltf',
  meshAnimationEnergy12: 'gltf',
  meshAnimationEnergy13: 'gltf',
  meshAnimationEnergy14: 'gltf',
  meshAnimationEnergy15: 'gltf',
  meshAnimationEnergy16: 'gltf',
  meshAnimationEnergy17: 'gltf',
  meshAnimationEnergy18: 'gltf',
  meshAnimationEnergy19: 'gltf',
  meshAnimationEnergy20: 'gltf',
  meshAnimationEnergy21: 'gltf',
  meshAnimationEnergy22: 'gltf',
  meshAnimationEnergy23: 'gltf',
  meshAnimationEnergy24: 'gltf',
  meshAnimationEnergy27: 'gltf',
  meshAnimationEnergy28: 'gltf',
  meshAnimationEnergy29: 'gltf',
  meshAnimationExplosion01: 'gltf',
  meshAnimationExplosion02: 'gltf',
  meshAnimationExplosion03: 'gltf',
  meshAnimationFire01: 'gltf',
  meshAnimationFire04: 'gltf',
  meshAnimationFire08: 'gltf',
  meshAnimationFire09: 'gltf',
  meshAnimationFire10: 'gltf',
  meshAnimationFire11: 'gltf',
  meshAnimationFire12: 'gltf',
  meshAnimationFire13: 'gltf',
  meshAnimationFire14: 'gltf',
  meshAnimationFire15: 'gltf',
  meshAnimationFire16: 'gltf',
  meshAnimationFire17: 'gltf',
  meshAnimationFire18: 'gltf',
  meshAnimationFire19: 'gltf',
  meshAnimationFire20: 'gltf',
  meshAnimationFire21: 'gltf',
  meshAnimationFire22: 'gltf',
  meshAnimationFire23: 'gltf',
  meshAnimationFire24: 'gltf',
  meshAnimationFire27: 'gltf',
  meshAnimationSmoke08: 'gltf',
  meshAnimationSmoke18: 'gltf',
  meshAnimationWater01: 'gltf',
  meshAnimationWater02: 'gltf',
  meshAnimationWater03: 'gltf',
  meshAnimationWater04: 'gltf',
  meshAnimationWater05: 'gltf',
  meshAnimationWater06: 'gltf',
  meshAnimationWater07: 'gltf',
  meshAnimationWater08: 'gltf',
  meshAnimationWater09: 'gltf',
  meshAnimationWater12: 'gltf',
  meshAnimationWater13: 'gltf',
  meshAnimationWater14: 'gltf',
  meshAnimationWater15: 'gltf',
  meshAnimationWater16: 'gltf',
  meshAnimationWater17: 'gltf',
  meshAnimationWater18: 'gltf',
  meshAnimationWater19: 'gltf',
  meshAnimationWater20: 'gltf',
  meshAnimationWater21: 'gltf',
  meshAnimationWater22: 'gltf',
  meshAnimationWater23: 'gltf',
  meshAnimationWater24: 'gltf',
  meshAnimationWater25: 'gltf',
  meshAnimationWater26: 'gltf',
  meshAnimationWater27: 'gltf',
  ground_crack: 'gltf',
  meshAnimationCrackTest: 'gltf',
  meshAnimationCrack2Test: 'gltf',
  meshAnimationShroudTest: 'gltf',
  meshAnimationShroud2Test: 'gltf',
  meshAnimationShroud3Test: 'gltf',
  meshAnimationElectricity015: 'gltf',
  meshAnimationElectricity043: 'gltf',
  meshAnimationElectricity048: 'gltf',
  meshAnimationElectricity049: 'gltf',
  meshAnimationElectricity051: 'gltf',
  meshAnimationEnergy008: 'gltf',
  meshAnimationEnergy015: 'gltf',
  meshAnimationEnergy020: 'gltf',
  meshAnimationEnergy021: 'gltf',
  meshAnimationEnergy025: 'gltf',
  meshAnimationEnergy027: 'gltf',
  meshAnimationEnergy031: 'gltf',
  meshAnimationEnergy060: 'gltf',
  meshAnimationEnergy064: 'gltf',
  meshAnimationExplosion019: 'gltf',
  meshAnimationFire001: 'gltf',
  meshAnimationFire017: 'gltf',
  meshAnimationFire026: 'gltf',
  meshAnimationFire089: 'gltf',
  meshAnimationFire107: 'gltf',
  meshAnimationFire116: 'gltf',
  meshAnimationFire119: 'gltf',
  meshAnimationLiquid017: 'gltf',
  meshAnimationLiquid037: 'gltf',
  meshAnimationLiquid056: 'gltf',
  meshAnimationSmoke002: 'gltf',
  meshAnimationSmoke004: 'gltf',
  meshAnimationSmoke012: 'gltf',
  meshAnimationSmoke016: 'gltf',
  meshAnimationSmoke022: 'gltf',
  meshAnimationSmoke026: 'gltf',
  meshAnimationSmoke027: 'gltf',
  meshAnimationSmoke031: 'gltf',
  meshAnimationSmoke041: 'gltf',
  meshAnimationSmoke064: 'gltf',
  meshAnimationSmoke066: 'gltf',
  meshAnimationSmoke068: 'gltf',
  fire_fragment_test: 'gltf',
  fire_vortex_test: 'gltf',
  fire_vortex2_test: 'gltf',
  smoke_bomb_test: 'gltf',
  fire_radial_glow_test: 'gltf',
  generic_AOE_v1: 'gltf',
  border_glint_guard: 'gltf',
  border_glint_unit: 'gltf',
  border_glint_spell: 'gltf',
  generic_trigger: 'gltf',
  water_trigger: 'gltf',
  light_trigger: 'gltf',
  fire_trigger: 'gltf',
  mind_trigger: 'gltf',
  metal_trigger: 'gltf',
  earth_trigger: 'gltf',
  slay_trigger: 'gltf',
  knives: 'gltf',
  flames: 'gltf',
  phoenix_plume_top: 'gltf',
  debuff_lines: 'gltf',
  glorious_mane: 'gltf',
  mad_vibes: 'gltf',
  glory_trigger: 'gltf',
  test_death_trigger: 'gltf',
  death_trigger_high: 'gltf',
  death_trigger_low: 'gltf',
  hero_death_small_blast: 'gltf',
  hero_death_small_smoke: 'gltf',
  hero_death_big_black_smoke: 'gltf',
  hero_death_big_points: 'gltf',
  hero_death_big_ground_ring_3d: 'gltf',
  hero_death_big_flare: 'gltf',
  hero_death_big_clouds_A: 'gltf',
  hero_death_big_clouds_B: 'gltf',
  cardBackFairy: 'gltf',
  cardBackArcadeum: 'gltf',
  cardBackSkull: 'gltf',
  cardBackScrappy: 'gltf',
  cardBackClockwork: 'gltf',
  cardBackReefus: 'gltf',
  cardBackVacation: 'gltf',
  cardBackFunGuy: 'gltf',
  cardBackStinkyEye: 'gltf',
  cardBackTreasureMap: 'gltf',
  cardBackPumpkin: 'gltf',
  cardBackArmis: 'gltf',
  cardBackCookie: 'gltf',
  cardBackWaterfulBalls: 'gltf',
  cardBackPicnicCake: 'gltf',
  cardBackMuralLotus: 'gltf',
  cardBackMuralAri: 'gltf',
  axel_coin: 'gltf',
  arrow: 'gltf',
  bite: 'gltf',
  claw: 'gltf',
  claw_impact: 'gltf',
  crow: 'gltf',
  ground_aura: 'gltf',
  siphon: 'gltf',
  stomp_impact: 'gltf',
  stomp_paw: 'gltf',
  twinkle: 'gltf',
  cog: 'gltf',
  hearts: 'gltf',
  feathers: 'gltf',
  music_notes: 'gltf',
  stealth_eye: 'gltf',

  main_shape: 'gltf',
  burst_shine: 'gltf',
  sparks: 'gltf',
  electricity: 'gltf',
  glow_bloom: 'gltf',
  card_flames: 'gltf',

  charge_up_energy_008: 'gltf',
  charge_up_energy_051: 'gltf',
  charge_up_energy_052: 'gltf',
  charge_up_energy_053: 'gltf',

  energy_tower_flames_base: 'gltf',
  energy_tower_flames_bloom: 'gltf',
  energy_tower_flames_trail: 'gltf',
  energy_tower_electricity: 'gltf',
  energy_tower_base_trail: 'gltf',

  explosion_base: 'gltf',
  explosion_bloom: 'gltf',
  explosion_poof: 'gltf',
  explosion_trace: 'gltf',

  lava_puddle_bubbles_base: 'gltf',
  lava_puddle_bubbles_trail: 'gltf',
  lava_puddle_crack: 'gltf',
  lava_puddle_embers: 'gltf',
  lava_puddle_flames_base: 'gltf',
  lava_puddle_flames_bloom: 'gltf',
  lava_puddle_flames_trace: 'gltf',
  lava_puddle_main_bubble: 'gltf',

  ada_empower_base: 'gltf',
  ada_empower_bloom: 'gltf',

  bouran_ritualize_back_flames_base: 'gltf',
  bouran_ritualize_back_flames_bloom: 'gltf',
  bouran_ritualize_circle_inner: 'gltf',
  bouran_ritualize_circle_moon_sun: 'gltf',
  bouran_ritualize_circle_outer: 'gltf',
  bouran_ritualize_embers: 'gltf',
  bouran_ritualize_front_flames_base: 'gltf',
  bouran_ritualize_front_flames_bloom: 'gltf',
  bouran_ritualize_glow: 'gltf',

  samya_teleport_base: 'gltf',
  samya_teleport_bloom: 'gltf',
  samya_teleport_dust: 'gltf',
  samya_teleport_energy: 'gltf',

  ari_fabricate_base: 'gltf',
  ari_fabricate_fill: 'gltf',

  hero_ability_trigger: 'gltf',

  lotus_petals_1: 'gltf',
  lotus_petals_2: 'gltf',
  lotus_petals_3: 'gltf',
  lotus_petals_4: 'gltf',
  lotus_petals_5: 'gltf',

  magma_chasm_base: 'gltf',
  magma_chasm_bloom: 'gltf',
  magma_chasm_bubbles: 'gltf',
  magma_chasm_burst: 'gltf',
  magma_chasm_smoke: 'gltf',

  trident_base: 'gltf',
  trident_bloom: 'gltf',

  fox_packmaster_buff: 'gltf',
  fox_packmaster_clash: 'gltf',
  fox_packmaster_fox: 'gltf',

  sitti_psychomancy_fire: 'gltf',
  sitti_psychomancy_skulls: 'gltf',
  sitti_psychomancy_smoke: 'gltf',

  horik_vengeance_axe: 'gltf',
  horik_vengeance_buff: 'gltf',
  horik_vengeance_impact: 'gltf',
  horik_vengeance_strike: 'gltf',
  horik_vengeance_slice: 'gltf',

  axel_glow_slide: 'gltf',
  axel_intro_flame: 'gltf',
  axel_outro_flame: 'gltf',
  axel_shine: 'gltf',
  axel_trail: 'gltf',
  axel_spectral_coins: 'gltf',

  titus_nurturer_energize: 'gltf',
  iris_meditation: 'gltf',
  mai_gadgeteer: 'gltf',
  zoey_live_fast: 'gltf',
  banjo_mercurial: 'gltf',

  uvTest: 'texture',
  lightCacheDaylight: 'texture',
  dayNightColorStrip: 'texture',
  uiPalette: 'texture',
  effectPalette: 'texture',
  iconPalette: 'texture',
  deckFramePalette: 'texture',
  shroudUv: 'texture',
  cloudNormals: 'texture',
  noise3Map: 'texture',
  noise3dNormalizedFullMap: 'texture',
  noise3dNormalizedHalfMap: 'texture',
  noise3dNormalizedQuarterMap: 'texture',
  noiseyTriangles3dNormalizedFullMap: 'texture',
  noiseyScales3dNormalizedFullMap: 'texture',
  noiseyScales23dNormalizedFullMap: 'texture',
  foilStarsMap: 'texture',
  fireEffectSourceMap: 'texture',
  fogEffectSourceMap: 'texture',
  layeredNoise3Map: 'texture',
  errorMushroom: 'texture',
  optionsBg: 'texture',
  // Animation sprite sheets
  keywordArmorAnimation: 'texture',
  keywordBannerAnimation: 'texture',
  keywordLifestealAnimation: 'texture',
  keywordWitherAnimation: 'texture',
  // keywords
  "keyword-conjure-icon": 'texture',
"keyword-draw-icon": 'texture',
"trait-wither-icon": 'texture',
"trigger-death-icon": 'texture',
"keyword-dust-icon": 'texture',
"trait-armor-icon": 'texture',
"trait-banner-icon": 'texture',
"trigger-glory-icon": 'texture',
"trait-guard-icon": 'texture',
"trait-lifesteal-icon": 'texture',
"trait-stealth-icon": 'texture',
"trigger-inspire-icon": 'texture',
"keyword-mulligan-icon": 'texture',
"trigger-generic-icon": 'texture',
"trigger-sunset-icon": 'texture',
"trigger-sunrise-icon": 'texture',
"trait-dash-icon": 'texture',
"trigger-slay-icon": 'texture',
  // Enchantment sprite sheets
  enchantmentAnima: 'texture',
  enchantmentBarrier: 'texture',
  enchantmentBlind: 'texture',
  enchantmentChains: 'texture',
  enchantmentDazed: 'texture',
  enchantmentFate: 'texture',
  enchantmentFlames: 'texture',
  enchantmentFrozen: 'texture',
  enchantmentFury: 'texture',
  enchantmentHex: 'texture',
  enchantmentLead: 'texture',
  enchantmentRoots: 'texture',
  enchantmentShield: 'texture',
  enchantmentShroud: 'texture',
  enchantmentSilence: 'texture',
  enchantmentVapors: 'texture',
  cardAspectArrow: 'texture',
  cardAspectArrowGreen: 'texture',
  sleepingAnimation: 'texture',
  damageAnimation: 'texture',
  damageFatigueAnimation: 'texture',
  triggerAnimation: 'texture',
  auraTriggerAnimation: 'texture',
  buffGenericAnimation: 'texture',
  smoke: 'texture',
  particle: 'texture',
  particle2: 'texture',
  witherParticleSpritesheet: 'texture',
  fireSpritesheet: 'texture',
  brushStroke: 'texture',
  uiPreviewDeath: 'texture',
  uiPreviewDust: 'texture',
  uiPreviewDraw: 'texture',
  uiPreviewMulligan: 'texture',
  uiPreviewReturnToHand: 'texture',
  uiPreviewSendToDeck: 'texture',
  uiPreviewSendToGraveyard: 'texture',
  uiPreviewSummon: 'texture',
  bgLoading: 'texture',
  spellLoading: 'texture',
  unitLoading: 'texture',
  musicGame: 'music',
  musicVictory: 'music',
  musicDefeat: 'music',
  audioFxCommon: 'soundSprite',
  audioFxTutorial: 'soundSprite',
  audioFxCards: 'soundSprite',
  audioFxMatchEnd: 'soundSprite',
  audioFxCommonVariations: 'soundSpriteVariations',
  audioFxMatchEndVariations: 'soundSpriteVariations'
} as const satisfies  {
  [K in AssetName]:
    | 'gltf'
    | 'texture'
    | 'music'
    | 'soundSprite'
    | 'soundSpriteVariations'
}

