// This file was generated by "pnpm run generate" in @opensky/design-data
// This file was generated by "pnpm generate" in @opensky/design-data.
import { Hero } from '@opensky/proto'

import type {
  CardBack,
  Crystal,
  HeroSkin,
  SkyTagTitle,
  Sticker
} from '@opensky/shared/constants'

export const stickers: Sticker[] = [
  {
    id: 1,
    artID: 'sticker-dino-01',
    name: 'Star Praise',
    flavorText:
      '"Starfelidae are one of but a few truly benevolent dreambeasts, always seeking to bring cheer and guidance to others."'
  },
  {
    id: 2,
    artID: 'sticker-dino-02',
    name: 'Draco Approves!',
    flavorText:
      '"Dracomantium often dotes on mortals, giving them support and words of encouragement."'
  },
  {
    id: 3,
    artID: 'sticker-dino-03',
    name: 'Fox Help',
    flavorText:
      '"While they can be testy at first, foxes make for incredibly devoted and doting companions when properly befriended."'
  },
  {
    id: 4,
    artID: 'sticker-dino-04',
    name: 'Fun GGuy',
    flavorText:
      '"When they\'re not scrambling in fear of poachers, preadators, loud noises, or their own shadows, fun guys can be remarkably cheerful."'
  },
  {
    id: 5,
    artID: 'sticker-dino-05',
    name: 'Turtor GG',
    flavorText:
      '"To gain the approval of one of the Tortugan philosophers is an incredible honor."'
  },
  {
    id: 6,
    artID: 'sticker-dino-06',
    name: 'Mira Loves It!',
    flavorText:
      '"99% of Mira\'s process is careful planning, testing and research. Doting over her mechanical babies fills the remaining 1%"'
  },
  {
    id: 7,
    artID: 'sticker-dino-07',
    name: 'Titus Woah!',
    flavorText:
      '"Give a squirrel a cookie and suddenly your whole farm is empty!"'
  },
  {
    id: 8,
    artID: 'sticker-dino-08',
    name: 'High Five!',
    flavorText: '"Come here kid, that was a close race!"- Samya'
  },
  {
    id: 9,
    artID: 'sticker-dino-09',
    name: 'WOWW!',
    flavorText:
      '"Fresh faced Cygnets are easily wowed by their older peers martial arts techniques."'
  },
  {
    id: 10,
    artID: 'sticker-dino-10',
    name: 'Mush love',
    flavorText:
      '"Sporekin regard even non-sapient mushrooms as their own kin, nurturing them, singing to them, and even cuddling them."'
  },
  {
    id: 11,
    artID: 'sticker-dino-11',
    name: 'Thinking!',
    flavorText:
      '"Take your time to think. Signing over a sizable chunk of ones lifespan for eldritch power is a decision that shouldn\'t be taken lightly"'
  },
  {
    id: 12,
    artID: 'sticker-dino-12',
    name: 'DISGUSTING!',
    flavorText:
      '"Amongst the Cook Books, scratch and sniff books are seen as abominations."'
  },
  {
    id: 13,
    artID: 'sticker-dino-13',
    name: 'Slow Clap',
    flavorText:
      '"The Lapin have learned that clapping too loud around explosives is not recommended."'
  },
  {
    id: 14,
    artID: 'sticker-dino-14',
    name: 'Sapphire Tears',
    flavorText:
      '"Sapphire seems to have retained much of her mother\'s lost sentimentality..." - Kha Mhet.'
  },
  {
    id: 15,
    artID: 'sticker-dino-15',
    name: 'Uhh...',
    flavorText:
      '"Though they\'re quite knowedgable on chivalry and swordsmanship, Hoplites can become easily confused by new ideas."'
  },
  {
    id: 16,
    artID: 'sticker-dino-16',
    name: 'Superstar!',
    flavorText:
      '"Samya was a celebrity athlete even before taking the mantle of OpenSky. In the time since, her popularity has become unmatchable"'
  },
  {
    id: 19,
    artID: 'sticker-dino-19',
    name: 'Activate Mira XD',
    flavorText: '"XD <3"'
  },
  {
    id: 20,
    artID: 'sticker-dino-20',
    name: 'Live Fast',
    flavorText:
      '"Living among the Mellin taught me that life\'s too short to waste time sitting around!"'
  },
  {
    id: 21,
    artID: 'sticker-dino-21',
    name: 'Take it Easy',
    flavorText: '"Titus always seeks to be \'in-tune\' with nature."'
  },
  {
    id: 22,
    artID: 'sticker-dino-22',
    name: 'Reaper',
    flavorText: '"The mask is honestly for show, and to help keep kids away"'
  },
  {
    id: 23,
    artID: 'sticker-dino-23',
    name: 'Yummy!',
    flavorText:
      '"Banjo has scoured Sky for the most delicious food, that\'s why his belly is so... experienced." - Ari'
  },
  {
    id: 24,
    artID: 'sticker-dino-24',
    name: 'A-Duh!',
    flavorText: '"I gave you my sword and you lost it?..."'
  },
  {
    id: 25,
    artID: 'sticker-dino-25',
    name: 'For You',
    flavorText:
      '"Under his tough guy persona, Fox has a real sentimental side." - Ada'
  },
  {
    id: 26,
    artID: 'sticker-dino-26',
    name: 'Om',
    flavorText:
      '"Meditation is one of many pathways to the light inside of every being."'
  },
  {
    id: 27,
    artID: 'sticker-dino-27',
    name: 'Really?',
    flavorText:
      '"Is that really the best you can do? I honestly expected more from you!"'
  },
  {
    id: 28,
    artID: 'sticker-dino-28',
    name: 'Yeah!',
    flavorText: '"I learned from Ari, the turtle always beats the hare."'
  },
  {
    id: 29,
    artID: 'sticker-dino-29',
    name: 'Wipewipe',
    flavorText:
      '"Oh to wonder of the Secrets small creatures must know, and might tell us if only we would stop to listen." - Snow-Wing, Primalan poet.'
  },
  {
    id: 30,
    artID: 'sticker-dino-30',
    name: 'Wut?',
    flavorText: '"When you realize you left your Electron at home."'
  },
  {
    id: 31,
    artID: 'sticker-dino-31',
    name: 'BAAH!',
    flavorText:
      '"Though Axolotls teeth are too tiny to cause harm, that won\'t stop them from trying to gum you to death."'
  },
  {
    id: 32,
    artID: 'sticker-dino-32',
    name: 'Luv',
    flavorText:
      '"Isn\'t my cubey wooby just the cutest little guy in the whole wide world?"'
  },
  {
    id: 33,
    artID: 'sticker-dino-33',
    name: 'Strength!',
    flavorText: '"Ethera\'s wardens use 100% organic plant protien to bulk up."'
  },
  {
    id: 35,
    artID: 'sticker-dino-35',
    name: 'Gotta go fast',
    flavorText: '"Do you have any idea how fast I really am??"'
  },
  {
    id: 36,
    artID: 'sticker-dino-36',
    name: 'Bzzz!',
    flavorText: '"Bzzzz... Overdrive... Overload..."'
  },
  {
    id: 37,
    artID: 'sticker-dino-37',
    name: 'FASTERRR',
    flavorText: '"Ayo.."'
  },
  {
    id: 38,
    artID: 'sticker-dino-38',
    name: 'Music to my ears',
    flavorText: '"Laaaa de daaaaa"'
  },
  {
    id: 39,
    artID: 'sticker-dino-39',
    name: 'Uncovered Page',
    flavorText: '"Stories lost in time all end up in my pages."'
  },
  {
    id: 40,
    artID: 'sticker-dino-40',
    name: 'Perishing',
    flavorText: '"Ughhhh, I don\'t feel so good..."'
  },
  {
    id: 41,
    artID: 'sticker-dino-41',
    name: 'Shell Love',
    flavorText: '"My shell or yours?"'
  },
  {
    id: 42,
    artID: 'sticker-dino-42',
    name: 'Sleepy bye bye',
    flavorText: '"ZZZZZzzzzz..... Mememememe...... ZZZZzzzz...."'
  },
  {
    id: 43,
    artID: 'sticker-dino-43',
    name: 'Cheeky',
    flavorText: '"Cheeky weeky"'
  },
  {
    id: 44,
    artID: 'sticker-dino-44',
    name: 'I guess so',
    flavorText: '"Hmmmm..."'
  },
  {
    id: 45,
    artID: 'sticker-dino-45',
    name: "Senpai's tea",
    flavorText: '"Sip sip"'
  },
  {
    id: 46,
    artID: 'sticker-dino-46',
    name: 'Eeei',
    flavorText: '"Eh he he he he he"'
  },
  {
    id: 47,
    artID: 'sticker-dino-47',
    name: 'Realization',
    flavorText: '"Ah Ha! I knew it!"'
  },
  {
    id: 48,
    artID: 'sticker-dino-48',
    name: 'Head Pat',
    flavorText: '"Cooo-co-co-cooo"'
  },
  {
    id: 49,
    artID: 'sticker-dino-49',
    name: 'Peace and Love',
    flavorText:
      '"Some of Armis would happily lay down thier life for you." - Rhea, Cygnan Traveller'
  },
  {
    id: 50,
    artID: 'sticker-dino-50',
    name: 'The King',
    flavorText: '"C\'mere boy!"'
  },
  {
    id: 51,
    artID: 'sticker-dino-51',
    name: 'Ded',
    flavorText: '"Out... of.... mana....xxxx"'
  },
  {
    id: 52,
    artID: 'sticker-dino-52',
    name: 'Hush now',
    flavorText: '"Don\'t cry..."'
  },
  {
    id: 55,
    artID: 'sticker-dino-55',
    name: 'Wahooo!',
    flavorText: '"Wahoo Yahoo!"'
  },
  {
    id: 56,
    artID: 'sticker-dino-56',
    name: 'Golden Greed',
    flavorText: '"Back to the Gold Standard!"'
  },
  {
    id: 61,
    artID: 'sticker-dino-61',
    name: 'Golden Ponder',
    flavorText: '“Hmm…"'
  },
  {
    id: 63,
    artID: 'sticker-dino-63',
    name: 'Golden Feed',
    flavorText: '"Well I certainly didn\'t have any cake how dare you."'
  },
  {
    id: 66,
    artID: 'sticker-dino-66',
    name: 'Hallowlight',
    flavorText: '"I feel gourd-geous!"'
  },
  {
    id: 67,
    artID: 'sticker-dino-67',
    name: 'Twek or Tweat',
    flavorText: '"Candy, pwease?"'
  },
  {
    id: 68,
    artID: 'sticker-dino-68',
    name: 'Eya There',
    flavorText: '"Eye see you!"'
  },
  {
    id: 69,
    artID: 'sticker-dino-69',
    name: 'Reading Glass',
    flavorText: '"I\'m really focused on this one."'
  },
  {
    id: 71,
    artID: 'sticker-dino-71',
    name: 'A-Dab',
    flavorText: '“This is quite an honour, I’m thrilled,”'
  },
  {
    id: 72,
    artID: 'sticker-dino-72',
    name: 'A-Wave',
    flavorText: '"Hey guys it\'s yo girl"'
  },
  {
    id: 73,
    artID: 'sticker-dino-73',
    name: "Amaruath's Smile",
    flavorText: '" Fine day to gaze"'
  },
  {
    id: 75,
    artID: 'sticker-dino-75',
    name: 'Sock Kitty',
    flavorText: '"Meow-y Christmas!"'
  },
  {
    id: 76,
    artID: 'sticker-dino-76',
    name: 'Light salute!',
    flavorText: '"Salute!"'
  },
  {
    id: 77,
    artID: 'sticker-dino-77',
    name: 'Green Greeting',
    flavorText: '"Hi!"'
  },
  {
    id: 78,
    artID: 'sticker-dino-78',
    name: 'Nice gesture',
    flavorText: '"Bonjour!"'
  },
  {
    id: 79,
    artID: 'sticker-dino-79',
    name: 'Retro Hi-Fi',
    flavorText: '"Hi!"'
  },
  {
    id: 80,
    artID: 'sticker-dino-80',
    name: 'Yoyo!',
    flavorText: '"Yo!"'
  },
  {
    id: 81,
    artID: 'sticker-dino-81',
    name: 'Holas',
    flavorText: '"Hola!"'
  },
  {
    id: 85,
    artID: 'sticker-dino-85',
    name: 'Foxy Hello!',
    flavorText: '"Fur-tastic!"'
  },
  {
    id: 88,
    artID: 'sticker-dino-88',
    name: 'Saltwater bae',
    flavorText: '"Just a little more sea-soning..."'
  },
  {
    id: 89,
    artID: 'sticker-dino-89',
    name: 'Give it a try',
    flavorText: '"You never know!"'
  },
  {
    id: 90,
    artID: 'sticker-dino-90',
    name: 'Oh I see',
    flavorText: '"I intuited it from the very start *Snort*"'
  },
  {
    id: 91,
    artID: 'sticker-dino-91',
    name: 'Sunbathed',
    flavorText: '"I\'m pond-ering this one hard."'
  },
  {
    id: 93,
    artID: 'sticker-dino-93',
    name: 'Unpearable',
    flavorText: '"Peary surprising!"'
  },
  {
    id: 94,
    artID: 'sticker-dino-94',
    name: 'You rly mean it?',
    flavorText: 'You rly mean it?'
  },
  {
    id: 95,
    artID: 'sticker-dino-95',
    name: 'Mauishroom',
    flavorText: 'The crowd is cap-tivated!'
  },
  {
    id: 99,
    artID: 'sticker-dino-99',
    name: 'Googly eyes',
    flavorText: '"I see, I see"'
  },
  {
    id: 100,
    artID: 'sticker-dino-100',
    name: 'DVW?',
    flavorText: '"Someone\'s flippered this map around!"'
  }
]
export const heroSkins: HeroSkin[] = [
  {
    id: 1,
    artID: 'hero-giaco-13',
    bgID: 'bg-legacy-01',
    flavorText: `"To protect all who call Sky home. That is my Legacy."`,
    grade: 'gold',
    hero: Hero.ADA,
    name: 'Legacy Ada'
  },
  {
    id: 2,
    artID: 'hero-lobogiaco-03',
    bgID: 'bg-legacy-03',
    flavorText: `"To blaze a trail for all those who will follow. That’s my Legacy."`,
    grade: 'gold',
    hero: Hero.SAMYA,
    name: 'Legacy Samya'
  },
  {
    id: 3,
    artID: 'hero-giaco-14',
    bgID: 'bg-legacy-03',
    flavorText: `"To live for myself, free of the chains that once bound me. That is my Legacy."`,
    grade: 'gold',
    hero: Hero.FOX,
    name: 'Legacy Fox'
  },
  {
    id: 4,
    artID: 'hero-xavigiaco-01',
    bgID: 'bg-legacy-03',
    flavorText: `"To preserve the knowledge of this world for future generations. That is my Legacy."`,
    grade: 'gold',
    hero: Hero.LOTUS,
    name: 'Legacy Lotus'
  },
  {
    id: 5,
    artID: 'hero-lobogiaco-04',
    bgID: 'bg-legacy-03',
    flavorText: `"To protect the wild places of this world, and all creatures who call them home. That is my Legacy."`,
    grade: 'gold',
    hero: Hero.TITUS,
    name: 'Legacy Titus'
  },
  {
    id: 6,
    artID: 'hero-delatgiaco-02',
    bgID: 'bg-legacy-02',
    flavorText: `"To learn the lessons of this vast world, and find my place within it. That is my Legacy."`,
    grade: 'gold',
    hero: Hero.IRIS,
    name: 'Legacy Iris'
  },
  {
    id: 7,
    artID: 'hero-xavigiaco-02',
    bgID: 'bg-legacy-03',
    flavorText: `"To maintain the balance of The Cycle that encompasses all. That is my Legacy."`,
    grade: 'gold',
    hero: Hero.BOURAN,
    name: 'Legacy Bouran'
  },
  {
    id: 8,
    artID: 'hero-giaco-15',
    bgID: 'bg-legacy-03',
    flavorText: `"To overcome the will of fate itself. That is my Legacy."`,
    grade: 'gold',
    hero: Hero.HORIK,
    name: 'Legacy Horik'
  },
  {
    id: 9,
    artID: 'hero-lobogiaco-01',
    bgID: 'bg-legacy-02',
    flavorText: `"To free the peoples of this world from tyranny, at any cost. That is my Legacy."`,
    grade: 'gold',
    hero: Hero.ZOEY,
    name: 'Legacy Zoey'
  },
  {
    id: 10,
    artID: 'hero-delatgiaco-01',
    bgID: 'bg-legacy-01',
    flavorText: `"To fade into the past, as all things shall. That is my ‘Legacy.’"`,
    grade: 'gold',
    hero: Hero.AXEL,
    name: 'Legacy Axel'
  },
  {
    id: 11,
    artID: 'hero-xavigiaco-14',
    bgID: 'bg-legacy-01',
    flavorText: `"To uncover the greatest secrets of this world for the good of all. That is my Legacy."`,
    grade: 'gold',
    hero: Hero.ARI,
    name: 'Legacy Ari'
  },
  {
    id: 12,
    artID: 'hero-edgiaco-01',
    bgID: 'bg-legacy-01',
    flavorText: `"To create the means to shelter all from harm. That is my Legacy."`,
    grade: 'gold',
    hero: Hero.MIRA,
    name: 'Legacy Mira'
  },
  {
    id: 13,
    artID: 'hero-lobogiaco-02',
    bgID: 'bg-legacy-01',
    flavorText: `"To challenge the limits of possibilty, and find what lies beyond them. That is my Legacy."`,
    grade: 'gold',
    hero: Hero.MAI,
    name: 'Legacy Mai'
  },
  {
    id: 14,
    artID: 'hero-xavigiaco-04',
    bgID: 'bg-legacy-02',
    flavorText: `"My Legacy? Oh, I think I lost it some time ago. I really should try to remember where I left it."`,
    grade: 'gold',
    hero: Hero.BANJO,
    name: 'Legacy Banjo'
  },
  {
    id: 15,
    artID: 'hero-edgiaco-02',
    bgID: 'bg-legacy-01',
    flavorText: `"To stand above life and death itself. That is my Legacy."`,
    grade: 'gold',
    hero: Hero.SITTI,
    name: 'Legacy Sitti'
  }
]
export const crystals: Crystal[] = [
  {
    id: 1,
    artID: 'opensky-crystal-1',
    name: 'Amethyst Crystal',
    flavorText:
      "Crystals change the color of your username in-game! They reflect how long a player's been part of OpenSky's journey and were distributed for free at Open Beta on February 8, 2022. While the Amethyst Crystal was initially distributed to Horizon staff and friends, it does not mean every owner is currently associated with Horizon.",
    color: '#C867F6'
  },
  {
    id: 2,
    artID: 'opensky-crystal-2',
    name: 'Amber Crystal',
    flavorText:
      'Crystals change the color of your username in-game! The Amber Crystal is distributed to players who join the OpenSky Ambassadors program. Tap here to learn more: https://www.skyweaver.net/community/creators-program/',
    color: '#F1CD01'
  },
  {
    id: 3,
    artID: 'opensky-crystal-3',
    name: 'Sapphire Crystal',
    flavorText:
      'Crystals change the color of your username in-game! The Sapphire Crystal is distributed to players who join the OpenSky Creators program. Tap here to learn more: https://www.skyweaver.net/community/creators-program/',
    color: '#00A3FF'
  },
  {
    id: 4,
    artID: 'opensky-crystal-4',
    name: 'Jade Crystal',
    flavorText:
      "Crystals change the color of your username in-game! They reflect how long a player's been part of OpenSky's journey and were distributed for free at Open Beta on February 8, 2022. The Jade Crystal was distributed to players who joined during the Alpha before March 21, 2020.",
    color: '#46D03B'
  },
  {
    id: 5,
    artID: 'opensky-crystal-5',
    name: 'Jasper Crystal',
    flavorText:
      "Crystals change the color of your username in-game! They reflect how long a player's been part of OpenSky's journey and were distributed for free at Open Beta on February 8, 2022. The Jasper Crystal was distributed to players who joined during Private Beta/Final Test Phase between March 21, 2020 and November 24, 2021.",
    color: '#FF6C28'
  },
  {
    id: 6,
    artID: 'opensky-crystal-6',
    name: 'Topaz Crystal',
    flavorText:
      "Crystals change the color of your username in-game! They reflect how long a player's been part of OpenSky's journey and were distributed for free at Open Beta on February 8, 2022. The Topaz Crystal was distributed to players who joined during Soft Launch between November 25, 2021 and February 7th, 2022 and reached level 5.",
    color: '#08EBDD'
  },
  {
    id: 7,
    artID: 'opensky-crystal-7',
    name: 'Morganite Crystal',
    flavorText:
      'Crystals change the color of your username in-game! The Morganite Crystal is distributed to players who win OpenSky Championships!',
    color: '#FFADDC'
  },
  {
    id: 8,
    artID: 'opensky-crystal-8',
    name: 'Ruby Crystal',
    flavorText: 'Top Secret',
    color: '#FF3535'
  }
]
export const cardBacks: CardBack[] = [
  {
    id: 1,
    artID: 'cardback-pablo-01',
    name: 'Hexed',
    flavorText: 'A hexed skull to celebrate the launch of Hexbound Invasion!',
    releaseSeason: 16
  },
  {
    id: 2,
    artID: 'cardback-pablo-03',
    name: 'Masked',
    flavorText:
      "A Dreamer's mask is fabled to contain their soul... Can you feel it calling?",
    releaseSeason: 17
  },
  {
    id: 3,
    artID: 'cardback-pablo-02',
    name: 'Fairy',
    flavorText:
      'Fae of the Etherwald, lighting the path to any friend of the forest.',
    releaseSeason: 21
  },
  {
    id: 4,
    artID: 'cardback-pablo-04',
    name: 'Clockwork',
    flavorText: 'Time. The intangible force that shapes all things.',
    releaseSeason: 19
  },
  {
    id: 5,
    artID: 'cardback-pablo-05',
    name: 'Deep Sea',
    flavorText:
      'Most of the sea is unknown to land dwellers, what they do know is what we decide to show them.',
    releaseSeason: 20
  },
  {
    id: 6,
    artID: 'cardback-pablo-06',
    name: 'Scrappy',
    flavorText: "One person's scrap is another person's treasure!",
    releaseSeason: 25
  },
  {
    id: 7,
    artID: 'cardback-gname-01',
    name: 'Treasure Map',
    flavorText:
      "People tend to loath X's on papers. But not if you're a Treasure Hunter!",
    releaseSeason: 19
  },
  {
    id: 8,
    artID: 'cardback-pablo-12',
    name: 'Vacation',
    flavorText:
      'And have some fun, with the funk, turn up the bass, and pop the trunk!',
    releaseSeason: 22
  },
  {
    id: 9,
    artID: 'cardback-giaco-01',
    name: 'Funguy',
    flavorText:
      "Funguy needs rest to maintain energy levels. After all, he's only mushroom.",
    releaseSeason: 23
  },
  {
    id: 10,
    artID: 'cardback-pablo-08',
    name: 'Stinky Eye',
    flavorText:
      'Out of sight, out of mind... But not for Stinky Eye... It ceaselessly watches.',
    releaseSeason: 24
  },
  {
    id: 11,
    artID: 'cardback-pablo-07',
    name: 'Pumpkin',
    flavorText:
      'Gnarly ghouls from every tomb are closing in to seal your doom.',
    releaseSeason: 26
  },
  {
    id: 12,
    artID: 'cardback-mara-03',
    name: 'Armis',
    flavorText:
      '“Our shield will protect all of Sky, one day…” - King Altren the 7th',
    releaseSeason: 27
  },
  {
    id: 13,
    artID: 'cardback-mara-02',
    name: 'Cookie',
    flavorText: 'Cookies for me, cookies for you!',
    releaseSeason: 28
  },
  {
    id: 18,
    artID: 'cardback-mara-06',
    name: 'Waterful Balls',
    flavorText:
      'Revisit the whimsical waters of your childhood with each gentle tilt.',
    releaseSeason: 29
  },
  {
    id: 19,
    artID: 'cardback-gname-02',
    name: 'Picnic Cake',
    flavorText: 'A perfect day for a picnic, and an even better day for cake!',
    releaseSeason: 30
  },
  {
    id: 20,
    artID: 'cardback-mara-07',
    name: 'Ode To Lotus',
    flavorText: 'Ode to Lotus',
    releaseSeason: 31
  },
  {
    id: 23,
    artID: 'cardback-mara-09',
    name: 'Ode To Ari',
    flavorText: 'Ode to Ari',
    releaseSeason: 32
  }
]
export const skyTagTitles: SkyTagTitle[] = [
  {
    id: 1,
    asset: '001_purple',
    name: 'Early Songbird',
    glowColor: '#521BEE',
    textColor: '#F9D2FF'
  },
  {
    id: 2,
    asset: '004_purple',
    name: 'Scrappy Supporter',
    glowColor: '#521BEE',
    textColor: '#F9D2FF'
  },
  {
    id: 3,
    asset: '001_red',
    name: 'Guardian',
    glowColor: '#FF0F00',
    textColor: '#FFE5B1'
  },
  {
    id: 4,
    asset: '001_green',
    name: 'Challenger',
    glowColor: '#30D119',
    textColor: '#DAFC51'
  },
  {
    id: 5,
    asset: '001_purple',
    name: 'Shadow',
    glowColor: '#521BEE',
    textColor: '#F9D2FF'
  },
  {
    id: 6,
    asset: '001_blue',
    name: 'Hacker',
    glowColor: '#1A75FD',
    textColor: '#18E5E5'
  },
  {
    id: 7,
    asset: '001_pink',
    name: 'Sage',
    glowColor: '#AF2584',
    textColor: '#FFBCF8'
  },
  {
    id: 8,
    asset: '002_green',
    name: '2023 OG',
    glowColor: '#30D119',
    textColor: '#DAFC51'
  },
  {
    id: 5000,
    asset: '001_silver',
    name: 'Horologist',
    glowColor: '#10787E',
    textColor: '#EFFFF5'
  },
  {
    id: 5001,
    asset: '002_silver',
    name: 'Tooth Hurty',
    glowColor: '#10787E',
    textColor: '#EFFFF5'
  },
  {
    id: 5002,
    asset: '003_silver',
    name: 'Hour Hero',
    glowColor: '#10787E',
    textColor: '#EFFFF5'
  },
  {
    id: 5003,
    asset: '001_blue',
    name: 'Splishy Splashy',
    glowColor: '#1A75FD',
    textColor: '#18E5E5'
  },
  {
    id: 5004,
    asset: '002_blue',
    name: 'Aquanaut',
    glowColor: '#1A75FD',
    textColor: '#18E5E5'
  },
  {
    id: 5005,
    asset: '003_blue',
    name: 'Oceanic Overlord',
    glowColor: '#1A75FD',
    textColor: '#18E5E5'
  },
  {
    id: 5006,
    asset: '001_yellow',
    name: 'Sparkles',
    glowColor: '#FF4D01',
    textColor: '#FFF932'
  },
  {
    id: 5007,
    asset: '002_yellow',
    name: 'Enchanted',
    glowColor: '#FF4D01',
    textColor: '#FFF932'
  },
  {
    id: 5008,
    asset: '003_yellow',
    name: 'Luminary',
    glowColor: '#FF4D01',
    textColor: '#FFF932'
  },
  {
    id: 5009,
    asset: '001_blue',
    name: 'Vacation Virtuoso',
    glowColor: '#1A75FD',
    textColor: '#18E5E5'
  },
  {
    id: 5010,
    asset: '002_blue',
    name: 'Cast Away',
    glowColor: '#1A75FD',
    textColor: '#18E5E5'
  },
  {
    id: 5011,
    asset: '003_blue',
    name: 'Shipwrecked',
    glowColor: '#1A75FD',
    textColor: '#18E5E5'
  },
  {
    id: 5012,
    asset: '001_green',
    name: 'Fun Guy',
    glowColor: '#30D119',
    textColor: '#DAFC51'
  },
  {
    id: 5013,
    asset: '002_green',
    name: 'No Cap',
    glowColor: '#30D119',
    textColor: '#DAFC51'
  },
  {
    id: 5014,
    asset: '003_green',
    name: 'Champignon',
    glowColor: '#30D119',
    textColor: '#DAFC51'
  },
  {
    id: 5015,
    asset: '001_purple',
    name: 'Dreamer',
    glowColor: '#521BEE',
    textColor: '#F9D2FF'
  },
  {
    id: 5016,
    asset: '002_purple',
    name: 'Beholder',
    glowColor: '#521BEE',
    textColor: '#F9D2FF'
  },
  {
    id: 5017,
    asset: '003_purple',
    name: 'Eye Candy',
    glowColor: '#521BEE',
    textColor: '#F9D2FF'
  },
  {
    id: 5018,
    asset: '001_yellow',
    name: 'Adventurer',
    glowColor: '#FF4D01',
    textColor: '#FFF932'
  },
  {
    id: 5019,
    asset: '002_yellow',
    name: 'Landmark',
    glowColor: '#FF4D01',
    textColor: '#FFF932'
  },
  {
    id: 5020,
    asset: '003_yellow',
    name: 'El Dorado',
    glowColor: '#FF4D01',
    textColor: '#FFF932'
  },
  {
    id: 5021,
    asset: '001_purple',
    name: 'Spooky',
    glowColor: '#521BEE',
    textColor: '#F9D2FF'
  },
  {
    id: 5022,
    asset: '002_purple',
    name: 'Scary',
    glowColor: '#521BEE',
    textColor: '#F9D2FF'
  },
  {
    id: 5023,
    asset: '003_purple',
    name: 'Skeletons',
    glowColor: '#521BEE',
    textColor: '#F9D2FF'
  },
  {
    id: 5024,
    asset: '001_teal',
    name: 'Armis Cadet',
    glowColor: '#36ABB2',
    textColor: '#D2FFE4'
  },
  {
    id: 5025,
    asset: '002_teal',
    name: 'Armis Captain',
    glowColor: '#36ABB2',
    textColor: '#D2FFE4'
  },
  {
    id: 5026,
    asset: '003_teal',
    name: 'Armis General',
    glowColor: '#36ABB2',
    textColor: '#D2FFE4'
  },
  {
    id: 5027,
    asset: '001_red',
    name: "It's Edible",
    glowColor: '#FF0F00',
    textColor: '#FFE5B1'
  },
  {
    id: 5028,
    asset: '002_red',
    name: "It's Tasteful",
    glowColor: '#FF0F00',
    textColor: '#FFE5B1'
  },
  {
    id: 5029,
    asset: '003_red',
    name: "It's Decadent",
    glowColor: '#FF0F00',
    textColor: '#FFE5B1'
  },
  {
    id: 5030,
    asset: '001_blue',
    name: 'Aqua Revive',
    glowColor: '#1A75FD',
    textColor: '#18E5E5'
  },
  {
    id: 5031,
    asset: '002_blue',
    name: 'Hydro Quest',
    glowColor: '#1A75FD',
    textColor: '#18E5E5'
  },
  {
    id: 5032,
    asset: '003_blue',
    name: 'Aquatic Odyssey',
    glowColor: '#1A75FD',
    textColor: '#18E5E5'
  },
  {
    id: 5036,
    asset: '001_pink',
    name: 'Cake Sprites',
    glowColor: '#AF2584',
    textColor: '#FFBCF8'
  },
  {
    id: 5037,
    asset: '002_pink',
    name: 'Frosting Fae',
    glowColor: '#AF2584',
    textColor: '#FFBCF8'
  },
  {
    id: 5038,
    asset: '003_pink',
    name: 'Sugared Sages',
    glowColor: '#AF2584',
    textColor: '#FFBCF8'
  },
  {
    id: 5039,
    asset: '001_purple',
    name: 'Sage',
    glowColor: '#521BEE',
    textColor: '#F9D2FF'
  },
  {
    id: 5040,
    asset: '002_purple',
    name: 'Savant',
    glowColor: '#521BEE',
    textColor: '#F9D2FF'
  },
  {
    id: 5041,
    asset: '003_purple',
    name: 'Seer',
    glowColor: '#521BEE',
    textColor: '#F9D2FF'
  },
  {
    id: 5042,
    asset: '001_purple',
    name: 'Hexidecimal',
    glowColor: '#521BEE',
    textColor: '#F9D2FF'
  },
  {
    id: 5043,
    asset: '002_purple',
    name: 'Hexxed',
    glowColor: '#521BEE',
    textColor: '#F9D2FF'
  },
  {
    id: 5044,
    asset: '003_purple',
    name: 'Hexcellency',
    glowColor: '#521BEE',
    textColor: '#F9D2FF'
  },
  {
    id: 5045,
    asset: '001_yellow',
    name: 'Masker Aid',
    glowColor: '#FF4D01',
    textColor: '#FFF932'
  },
  {
    id: 5046,
    asset: '002_yellow',
    name: 'Faceless',
    glowColor: '#FF4D01',
    textColor: '#FFF932'
  },
  {
    id: 5047,
    asset: '003_yellow',
    name: 'Unmasked',
    glowColor: '#FF4D01',
    textColor: '#FFF932'
  },
  {
    id: 5048,
    asset: '004_orange',
    name: 'Rust Bucket',
    glowColor: '#FF4D01',
    textColor: '#FEFB9A'
  },
  {
    id: 5049,
    asset: '004_orange',
    name: 'Junk Dealer',
    glowColor: '#FF4D01',
    textColor: '#FEFB9A'
  },
  {
    id: 5050,
    asset: '004_orange',
    name: 'Rare Find',
    glowColor: '#FF4D01',
    textColor: '#FEFB9A'
  },
  {
    id: 5051,
    asset: '001_blue',
    name: 'Crash Override',
    glowColor: '#1A75FD',
    textColor: '#18E5E5'
  },
  {
    id: 5052,
    asset: '002_blue',
    name: 'Algorithmist',
    glowColor: '#1A75FD',
    textColor: '#18E5E5'
  },
  {
    id: 5053,
    asset: '003_blue',
    name: 'Phriendly Phreak',
    glowColor: '#1A75FD',
    textColor: '#18E5E5'
  }
]
