// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker/matching/matchers (interfaces: BotFactory)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	player "github.com/horizon-games/OpenSky/matchmaker/lib/player"
	gomock "go.uber.org/mock/gomock"
)

// MockBotFactory is a mock of BotFactory interface.
type MockBotFactory struct {
	ctrl     *gomock.Controller
	recorder *MockBotFactoryMockRecorder
}

// MockBotFactoryMockRecorder is the mock recorder for MockBotFactory.
type MockBotFactoryMockRecorder struct {
	mock *MockBotFactory
}

// NewMockBotFactory creates a new mock instance.
func NewMockBotFactory(ctrl *gomock.Controller) *MockBotFactory {
	mock := &MockBotFactory{ctrl: ctrl}
	mock.recorder = &MockBotFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBotFactory) EXPECT() *MockBotFactoryMockRecorder {
	return m.recorder
}

// CreateRegistered mocks base method.
func (m *MockBotFactory) CreateRegistered(arg0 *player.Player) (*player.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRegistered", arg0)
	ret0, _ := ret[0].(*player.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRegistered indicates an expected call of CreateRegistered.
func (mr *MockBotFactoryMockRecorder) CreateRegistered(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRegistered", reflect.TypeOf((*MockBotFactory)(nil).CreateRegistered), arg0)
}

// CreateSimple mocks base method.
func (m *MockBotFactory) CreateSimple(arg0 proto.GameMode) *player.Player {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSimple", arg0)
	ret0, _ := ret[0].(*player.Player)
	return ret0
}

// CreateSimple indicates an expected call of CreateSimple.
func (mr *MockBotFactoryMockRecorder) CreateSimple(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSimple", reflect.TypeOf((*MockBotFactory)(nil).CreateSimple), arg0)
}

// CreateUnregistered mocks base method.
func (m *MockBotFactory) CreateUnregistered(arg0 *player.Player) (*player.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUnregistered", arg0)
	ret0, _ := ret[0].(*player.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUnregistered indicates an expected call of CreateUnregistered.
func (mr *MockBotFactoryMockRecorder) CreateUnregistered(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUnregistered", reflect.TypeOf((*MockBotFactory)(nil).CreateUnregistered), arg0)
}
