// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker/matching/matchfuncs (interfaces: MatchValidator)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	player "github.com/horizon-games/OpenSky/matchmaker/lib/player"
	gomock "go.uber.org/mock/gomock"
)

// MockMatchValidator is a mock of MatchValidator interface.
type MockMatchValidator struct {
	ctrl     *gomock.Controller
	recorder *MockMatchValidatorMockRecorder
}

// MockMatchValidatorMockRecorder is the mock recorder for MockMatchValidator.
type MockMatchValidatorMockRecorder struct {
	mock *MockMatchValidator
}

// NewMockMatchValidator creates a new mock instance.
func NewMockMatchValidator(ctrl *gomock.Controller) *MockMatchValidator {
	mock := &MockMatchValidator{ctrl: ctrl}
	mock.recorder = &MockMatchValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchValidator) EXPECT() *MockMatchValidatorMockRecorder {
	return m.recorder
}

// IsValid mocks base method.
func (m *MockMatchValidator) IsValid(arg0, arg1 *player.Player) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValid", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsValid indicates an expected call of IsValid.
func (mr *MockMatchValidatorMockRecorder) IsValid(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValid", reflect.TypeOf((*MockMatchValidator)(nil).IsValid), arg0, arg1)
}
