// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker/matching/matchers (interfaces: MatchQualitySorter)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	player "github.com/horizon-games/OpenSky/matchmaker/lib/player"
	gomock "go.uber.org/mock/gomock"
)

// MockMatchQualitySorter is a mock of MatchQualitySorter interface.
type MockMatchQualitySorter struct {
	ctrl     *gomock.Controller
	recorder *MockMatchQualitySorterMockRecorder
}

// MockMatchQualitySorterMockRecorder is the mock recorder for MockMatchQualitySorter.
type MockMatchQualitySorterMockRecorder struct {
	mock *MockMatchQualitySorter
}

// NewMockMatchQualitySorter creates a new mock instance.
func NewMockMatchQualitySorter(ctrl *gomock.Controller) *MockMatchQualitySorter {
	mock := &MockMatchQualitySorter{ctrl: ctrl}
	mock.recorder = &MockMatchQualitySorterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchQualitySorter) EXPECT() *MockMatchQualitySorterMockRecorder {
	return m.recorder
}

// Sort mocks base method.
func (m *MockMatchQualitySorter) Sort(arg0 *player.Player, arg1 []*player.Player) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Sort", arg0, arg1)
}

// Sort indicates an expected call of Sort.
func (mr *MockMatchQualitySorterMockRecorder) Sort(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sort", reflect.TypeOf((*MockMatchQualitySorter)(nil).Sort), arg0, arg1)
}
