// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker/matching/matchers (interfaces: PlayerValidator)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	player "github.com/horizon-games/OpenSky/matchmaker/lib/player"
	gomock "go.uber.org/mock/gomock"
)

// MockPlayerValidator is a mock of PlayerValidator interface.
type MockPlayerValidator struct {
	ctrl     *gomock.Controller
	recorder *MockPlayerValidatorMockRecorder
}

// MockPlayerValidatorMockRecorder is the mock recorder for MockPlayerValidator.
type MockPlayerValidatorMockRecorder struct {
	mock *MockPlayerValidator
}

// NewMockPlayerValidator creates a new mock instance.
func NewMockPlayerValidator(ctrl *gomock.Controller) *MockPlayerValidator {
	mock := &MockPlayerValidator{ctrl: ctrl}
	mock.recorder = &MockPlayerValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlayerValidator) EXPECT() *MockPlayerValidatorMockRecorder {
	return m.recorder
}

// IsValid mocks base method.
func (m *MockPlayerValidator) IsValid(arg0 *player.Player) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValid", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsValid indicates an expected call of IsValid.
func (mr *MockPlayerValidatorMockRecorder) IsValid(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValid", reflect.TypeOf((*MockPlayerValidator)(nil).IsValid), arg0)
}
