// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker/matching/matchers (interfaces: PlayerCombinator)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	matchers "github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker/matching/matchers"
	player "github.com/horizon-games/OpenSky/matchmaker/lib/player"
	gomock "go.uber.org/mock/gomock"
)

// MockPlayerCombinator is a mock of PlayerCombinator interface.
type MockPlayerCombinator struct {
	ctrl     *gomock.Controller
	recorder *MockPlayerCombinatorMockRecorder
}

// MockPlayerCombinatorMockRecorder is the mock recorder for MockPlayerCombinator.
type MockPlayerCombinatorMockRecorder struct {
	mock *MockPlayerCombinator
}

// NewMockPlayerCombinator creates a new mock instance.
func NewMockPlayerCombinator(ctrl *gomock.Controller) *MockPlayerCombinator {
	mock := &MockPlayerCombinator{ctrl: ctrl}
	mock.recorder = &MockPlayerCombinatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlayerCombinator) EXPECT() *MockPlayerCombinatorMockRecorder {
	return m.recorder
}

// Combine mocks base method.
func (m *MockPlayerCombinator) Combine(arg0 []*player.Player) (*matchers.PlayerCombinationMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Combine", arg0)
	ret0, _ := ret[0].(*matchers.PlayerCombinationMap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Combine indicates an expected call of Combine.
func (mr *MockPlayerCombinatorMockRecorder) Combine(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Combine", reflect.TypeOf((*MockPlayerCombinator)(nil).Combine), arg0)
}
