// Code generated by MockGen. DO NOT EDIT.
// Source: /home/rev/projects/goware/cachestore/cachestore.go
//
// Generated by this command:
//
//	mockgen -source /home/rev/projects/goware/cachestore/cachestore.go -destination ./cache_store_mock_test.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	cachestore "github.com/goware/cachestore"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore[V any] struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder[V]
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder[V any] struct {
	mock *MockStore[V]
}

// NewMockStore creates a new mock instance.
func NewMockStore[V any](ctrl *gomock.Controller) *MockStore[V] {
	mock := &MockStore[V]{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder[V]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore[V]) EXPECT() *MockStoreMockRecorder[V] {
	return m.recorder
}

// BatchGet mocks base method.
func (m *MockStore[V]) BatchGet(ctx context.Context, keys []string) ([]V, []bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGet", ctx, keys)
	ret0, _ := ret[0].([]V)
	ret1, _ := ret[1].([]bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BatchGet indicates an expected call of BatchGet.
func (mr *MockStoreMockRecorder[V]) BatchGet(ctx, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGet", reflect.TypeOf((*MockStore[V])(nil).BatchGet), ctx, keys)
}

// BatchSet mocks base method.
func (m *MockStore[V]) BatchSet(ctx context.Context, keys []string, values []V) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchSet", ctx, keys, values)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchSet indicates an expected call of BatchSet.
func (mr *MockStoreMockRecorder[V]) BatchSet(ctx, keys, values any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchSet", reflect.TypeOf((*MockStore[V])(nil).BatchSet), ctx, keys, values)
}

// BatchSetEx mocks base method.
func (m *MockStore[V]) BatchSetEx(ctx context.Context, keys []string, values []V, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchSetEx", ctx, keys, values, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchSetEx indicates an expected call of BatchSetEx.
func (mr *MockStoreMockRecorder[V]) BatchSetEx(ctx, keys, values, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchSetEx", reflect.TypeOf((*MockStore[V])(nil).BatchSetEx), ctx, keys, values, ttl)
}

// ClearAll mocks base method.
func (m *MockStore[V]) ClearAll(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearAll", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearAll indicates an expected call of ClearAll.
func (mr *MockStoreMockRecorder[V]) ClearAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearAll", reflect.TypeOf((*MockStore[V])(nil).ClearAll), ctx)
}

// Delete mocks base method.
func (m *MockStore[V]) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStoreMockRecorder[V]) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStore[V])(nil).Delete), ctx, key)
}

// DeletePrefix mocks base method.
func (m *MockStore[V]) DeletePrefix(ctx context.Context, keyPrefix string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePrefix", ctx, keyPrefix)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePrefix indicates an expected call of DeletePrefix.
func (mr *MockStoreMockRecorder[V]) DeletePrefix(ctx, keyPrefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePrefix", reflect.TypeOf((*MockStore[V])(nil).DeletePrefix), ctx, keyPrefix)
}

// Exists mocks base method.
func (m *MockStore[V]) Exists(ctx context.Context, key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockStoreMockRecorder[V]) Exists(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockStore[V])(nil).Exists), ctx, key)
}

// Get mocks base method.
func (m *MockStore[V]) Get(ctx context.Context, key string) (V, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(V)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockStoreMockRecorder[V]) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStore[V])(nil).Get), ctx, key)
}

// GetEx mocks base method.
func (m *MockStore[V]) GetEx(ctx context.Context, key string) (V, *time.Duration, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEx", ctx, key)
	ret0, _ := ret[0].(V)
	ret1, _ := ret[1].(*time.Duration)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetEx indicates an expected call of GetEx.
func (mr *MockStoreMockRecorder[V]) GetEx(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEx", reflect.TypeOf((*MockStore[V])(nil).GetEx), ctx, key)
}

// GetOrSetWithLock mocks base method.
func (m *MockStore[V]) GetOrSetWithLock(ctx context.Context, key string, getter func(context.Context, string) (V, error)) (V, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrSetWithLock", ctx, key, getter)
	ret0, _ := ret[0].(V)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrSetWithLock indicates an expected call of GetOrSetWithLock.
func (mr *MockStoreMockRecorder[V]) GetOrSetWithLock(ctx, key, getter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrSetWithLock", reflect.TypeOf((*MockStore[V])(nil).GetOrSetWithLock), ctx, key, getter)
}

// GetOrSetWithLockEx mocks base method.
func (m *MockStore[V]) GetOrSetWithLockEx(ctx context.Context, key string, getter func(context.Context, string) (V, error), ttl time.Duration) (V, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrSetWithLockEx", ctx, key, getter, ttl)
	ret0, _ := ret[0].(V)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrSetWithLockEx indicates an expected call of GetOrSetWithLockEx.
func (mr *MockStoreMockRecorder[V]) GetOrSetWithLockEx(ctx, key, getter, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrSetWithLockEx", reflect.TypeOf((*MockStore[V])(nil).GetOrSetWithLockEx), ctx, key, getter, ttl)
}

// Set mocks base method.
func (m *MockStore[V]) Set(ctx context.Context, key string, value V) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockStoreMockRecorder[V]) Set(ctx, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockStore[V])(nil).Set), ctx, key, value)
}

// SetEx mocks base method.
func (m *MockStore[V]) SetEx(ctx context.Context, key string, value V, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEx", ctx, key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEx indicates an expected call of SetEx.
func (mr *MockStoreMockRecorder[V]) SetEx(ctx, key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEx", reflect.TypeOf((*MockStore[V])(nil).SetEx), ctx, key, value, ttl)
}

// MockBackend is a mock of Backend interface.
type MockBackend struct {
	ctrl     *gomock.Controller
	recorder *MockBackendMockRecorder
	isgomock struct{}
}

// MockBackendMockRecorder is the mock recorder for MockBackend.
type MockBackendMockRecorder struct {
	mock *MockBackend
}

// NewMockBackend creates a new mock instance.
func NewMockBackend(ctrl *gomock.Controller) *MockBackend {
	mock := &MockBackend{ctrl: ctrl}
	mock.recorder = &MockBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackend) EXPECT() *MockBackendMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockBackend) Apply(arg0 *cachestore.StoreOptions) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Apply", arg0)
}

// Apply indicates an expected call of Apply.
func (mr *MockBackendMockRecorder) Apply(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockBackend)(nil).Apply), arg0)
}
