// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/gamemodechecker (interfaces: SkyWeaverAPI)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockSkyWeaverAPI is a mock of SkyWeaverAPI interface.
type MockSkyWeaverAPI struct {
	ctrl     *gomock.Controller
	recorder *MockSkyWeaverAPIMockRecorder
}

// MockSkyWeaverAPIMockRecorder is the mock recorder for MockSkyWeaverAPI.
type MockSkyWeaverAPIMockRecorder struct {
	mock *MockSkyWeaverAPI
}

// NewMockSkyWeaverAPI creates a new mock instance.
func NewMockSkyWeaverAPI(ctrl *gomock.Controller) *MockSkyWeaverAPI {
	mock := &MockSkyWeaverAPI{ctrl: ctrl}
	mock.recorder = &MockSkyWeaverAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSkyWeaverAPI) EXPECT() *MockSkyWeaverAPIMockRecorder {
	return m.recorder
}

// GetGameModesStatus mocks base method.
func (m *MockSkyWeaverAPI) GetGameModesStatus(arg0 context.Context) (*proto.GameModesStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGameModesStatus", arg0)
	ret0, _ := ret[0].(*proto.GameModesStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGameModesStatus indicates an expected call of GetGameModesStatus.
func (mr *MockSkyWeaverAPIMockRecorder) GetGameModesStatus(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGameModesStatus", reflect.TypeOf((*MockSkyWeaverAPI)(nil).GetGameModesStatus), arg0)
}
