// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker/custommatchmaker (interfaces: AcceptTimeouter)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	matchmaker "github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker"
	gomock "go.uber.org/mock/gomock"
)

// MockAcceptTimeouter is a mock of AcceptTimeouter interface.
type MockAcceptTimeouter struct {
	ctrl     *gomock.Controller
	recorder *MockAcceptTimeouterMockRecorder
}

// MockAcceptTimeouterMockRecorder is the mock recorder for MockAcceptTimeouter.
type MockAcceptTimeouterMockRecorder struct {
	mock *MockAcceptTimeouter
}

// NewMockAcceptTimeouter creates a new mock instance.
func NewMockAcceptTimeouter(ctrl *gomock.Controller) *MockAcceptTimeouter {
	mock := &MockAcceptTimeouter{ctrl: ctrl}
	mock.recorder = &MockAcceptTimeouterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAcceptTimeouter) EXPECT() *MockAcceptTimeouterMockRecorder {
	return m.recorder
}

// Schedule mocks base method.
func (m *MockAcceptTimeouter) Schedule(arg0 *matchmaker.MatchProposal) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Schedule", arg0)
}

// Schedule indicates an expected call of Schedule.
func (mr *MockAcceptTimeouterMockRecorder) Schedule(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Schedule", reflect.TypeOf((*MockAcceptTimeouter)(nil).Schedule), arg0)
}
