// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker/custommatchmaker (interfaces: AcceptedMatchProposalQueue)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	matchmaker "github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker"
	gomock "go.uber.org/mock/gomock"
)

// MockAcceptedMatchProposalQueue is a mock of AcceptedMatchProposalQueue interface.
type MockAcceptedMatchProposalQueue struct {
	ctrl     *gomock.Controller
	recorder *MockAcceptedMatchProposalQueueMockRecorder
}

// MockAcceptedMatchProposalQueueMockRecorder is the mock recorder for MockAcceptedMatchProposalQueue.
type MockAcceptedMatchProposalQueueMockRecorder struct {
	mock *MockAcceptedMatchProposalQueue
}

// NewMockAcceptedMatchProposalQueue creates a new mock instance.
func NewMockAcceptedMatchProposalQueue(ctrl *gomock.Controller) *MockAcceptedMatchProposalQueue {
	mock := &MockAcceptedMatchProposalQueue{ctrl: ctrl}
	mock.recorder = &MockAcceptedMatchProposalQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAcceptedMatchProposalQueue) EXPECT() *MockAcceptedMatchProposalQueueMockRecorder {
	return m.recorder
}

// Items mocks base method.
func (m *MockAcceptedMatchProposalQueue) Items(arg0 proto.GameMode) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Items", arg0)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Items indicates an expected call of Items.
func (mr *MockAcceptedMatchProposalQueueMockRecorder) Items(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Items", reflect.TypeOf((*MockAcceptedMatchProposalQueue)(nil).Items), arg0)
}

// Push mocks base method.
func (m *MockAcceptedMatchProposalQueue) Push(arg0 *matchmaker.MatchProposal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Push", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Push indicates an expected call of Push.
func (mr *MockAcceptedMatchProposalQueueMockRecorder) Push(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*MockAcceptedMatchProposalQueue)(nil).Push), arg0)
}

// Remove mocks base method.
func (m *MockAcceptedMatchProposalQueue) Remove(arg0 string, arg1 proto.GameMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockAcceptedMatchProposalQueueMockRecorder) Remove(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockAcceptedMatchProposalQueue)(nil).Remove), arg0, arg1)
}
