// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker/custommatchmaker (interfaces: AcceptTimeoutPenaltySetter)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	player "github.com/horizon-games/OpenSky/matchmaker/lib/player"
	gomock "go.uber.org/mock/gomock"
)

// MockAcceptTimeoutPenaltySetter is a mock of AcceptTimeoutPenaltySetter interface.
type MockAcceptTimeoutPenaltySetter struct {
	ctrl     *gomock.Controller
	recorder *MockAcceptTimeoutPenaltySetterMockRecorder
}

// MockAcceptTimeoutPenaltySetterMockRecorder is the mock recorder for MockAcceptTimeoutPenaltySetter.
type MockAcceptTimeoutPenaltySetterMockRecorder struct {
	mock *MockAcceptTimeoutPenaltySetter
}

// NewMockAcceptTimeoutPenaltySetter creates a new mock instance.
func NewMockAcceptTimeoutPenaltySetter(ctrl *gomock.Controller) *MockAcceptTimeoutPenaltySetter {
	mock := &MockAcceptTimeoutPenaltySetter{ctrl: ctrl}
	mock.recorder = &MockAcceptTimeoutPenaltySetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAcceptTimeoutPenaltySetter) EXPECT() *MockAcceptTimeoutPenaltySetterMockRecorder {
	return m.recorder
}

// SetAcceptTimeoutPenalty mocks base method.
func (m *MockAcceptTimeoutPenaltySetter) SetAcceptTimeoutPenalty(arg0 *player.Player) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAcceptTimeoutPenalty", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAcceptTimeoutPenalty indicates an expected call of SetAcceptTimeoutPenalty.
func (mr *MockAcceptTimeoutPenaltySetterMockRecorder) SetAcceptTimeoutPenalty(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAcceptTimeoutPenalty", reflect.TypeOf((*MockAcceptTimeoutPenaltySetter)(nil).SetAcceptTimeoutPenalty), arg0)
}
