// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker/custommatchmaker (interfaces: ChannelFactory)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	player "github.com/horizon-games/OpenSky/matchmaker/lib/player"
	playerchannel "github.com/horizon-games/OpenSky/matchmaker/lib/playerchannel"
	gomock "go.uber.org/mock/gomock"
)

// MockChannelFactory is a mock of ChannelFactory interface.
type MockChannelFactory struct {
	ctrl     *gomock.Controller
	recorder *MockChannelFactoryMockRecorder
}

// MockChannelFactoryMockRecorder is the mock recorder for MockChannelFactory.
type MockChannelFactoryMockRecorder struct {
	mock *MockChannelFactory
}

// NewMockChannelFactory creates a new mock instance.
func NewMockChannelFactory(ctrl *gomock.Controller) *MockChannelFactory {
	mock := &MockChannelFactory{ctrl: ctrl}
	mock.recorder = &MockChannelFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannelFactory) EXPECT() *MockChannelFactoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockChannelFactory) Create(arg0 context.Context, arg1 *player.Player) (*playerchannel.PlayerChannel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*playerchannel.PlayerChannel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockChannelFactoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockChannelFactory)(nil).Create), arg0, arg1)
}
