// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker/custommatchmaker (interfaces: Decliner)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockDecliner is a mock of Decliner interface.
type MockDecliner struct {
	ctrl     *gomock.Controller
	recorder *MockDeclinerMockRecorder
}

// MockDeclinerMockRecorder is the mock recorder for MockDecliner.
type MockDeclinerMockRecorder struct {
	mock *MockDecliner
}

// NewMockDecliner creates a new mock instance.
func NewMockDecliner(ctrl *gomock.Controller) *MockDecliner {
	mock := &MockDecliner{ctrl: ctrl}
	mock.recorder = &MockDeclinerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDecliner) EXPECT() *MockDeclinerMockRecorder {
	return m.recorder
}

// DeclineMatch mocks base method.
func (m *MockDecliner) DeclineMatch(arg0 context.Context, arg1 proto.Hash) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeclineMatch", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeclineMatch indicates an expected call of DeclineMatch.
func (mr *MockDeclinerMockRecorder) DeclineMatch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeclineMatch", reflect.TypeOf((*MockDecliner)(nil).DeclineMatch), arg0, arg1)
}
