// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker/custommatchmaker (interfaces: GameServerManager)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gameservers "github.com/horizon-games/OpenSky/matchmaker/lib/gameservers"
	gomock "go.uber.org/mock/gomock"
)

// MockGameServerManager is a mock of GameServerManager interface.
type MockGameServerManager struct {
	ctrl     *gomock.Controller
	recorder *MockGameServerManagerMockRecorder
}

// MockGameServerManagerMockRecorder is the mock recorder for MockGameServerManager.
type MockGameServerManagerMockRecorder struct {
	mock *MockGameServerManager
}

// NewMockGameServerManager creates a new mock instance.
func NewMockGameServerManager(ctrl *gomock.Controller) *MockGameServerManager {
	mock := &MockGameServerManager{ctrl: ctrl}
	mock.recorder = &MockGameServerManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameServerManager) EXPECT() *MockGameServerManagerMockRecorder {
	return m.recorder
}

// ListInfo mocks base method.
func (m *MockGameServerManager) ListInfo() (map[string]*gameservers.GameServerInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInfo")
	ret0, _ := ret[0].(map[string]*gameservers.GameServerInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInfo indicates an expected call of ListInfo.
func (mr *MockGameServerManagerMockRecorder) ListInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInfo", reflect.TypeOf((*MockGameServerManager)(nil).ListInfo))
}
