// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker/custommatchmaker (interfaces: GameModeLocker)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	lock "github.com/horizon-games/OpenSky/matchmaker/lib/lock"
	gomock "go.uber.org/mock/gomock"
)

// MockGameModeLocker is a mock of GameModeLocker interface.
type MockGameModeLocker struct {
	ctrl     *gomock.Controller
	recorder *MockGameModeLockerMockRecorder
}

// MockGameModeLockerMockRecorder is the mock recorder for MockGameModeLocker.
type MockGameModeLockerMockRecorder struct {
	mock *MockGameModeLocker
}

// NewMockGameModeLocker creates a new mock instance.
func NewMockGameModeLocker(ctrl *gomock.Controller) *MockGameModeLocker {
	mock := &MockGameModeLocker{ctrl: ctrl}
	mock.recorder = &MockGameModeLockerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameModeLocker) EXPECT() *MockGameModeLockerMockRecorder {
	return m.recorder
}

// Locker mocks base method.
func (m *MockGameModeLocker) Locker(arg0 proto.GameMode) lock.Mutex {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Locker", arg0)
	ret0, _ := ret[0].(lock.Mutex)
	return ret0
}

// Locker indicates an expected call of Locker.
func (mr *MockGameModeLockerMockRecorder) Locker(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Locker", reflect.TypeOf((*MockGameModeLocker)(nil).Locker), arg0)
}
