// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker/custommatchmaker (interfaces: MatchProposalRepository)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	lock "github.com/horizon-games/OpenSky/matchmaker/lib/lock"
	matchmaker "github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker"
	gomock "go.uber.org/mock/gomock"
)

// MockMatchProposalRepository is a mock of MatchProposalRepository interface.
type MockMatchProposalRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMatchProposalRepositoryMockRecorder
}

// MockMatchProposalRepositoryMockRecorder is the mock recorder for MockMatchProposalRepository.
type MockMatchProposalRepositoryMockRecorder struct {
	mock *MockMatchProposalRepository
}

// NewMockMatchProposalRepository creates a new mock instance.
func NewMockMatchProposalRepository(ctrl *gomock.Controller) *MockMatchProposalRepository {
	mock := &MockMatchProposalRepository{ctrl: ctrl}
	mock.recorder = &MockMatchProposalRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchProposalRepository) EXPECT() *MockMatchProposalRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockMatchProposalRepository) Delete(arg0 *matchmaker.MatchProposal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMatchProposalRepositoryMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMatchProposalRepository)(nil).Delete), arg0)
}

// HasMatchProposal mocks base method.
func (m *MockMatchProposalRepository) HasMatchProposal(arg0 proto.Hash) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasMatchProposal", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasMatchProposal indicates an expected call of HasMatchProposal.
func (mr *MockMatchProposalRepositoryMockRecorder) HasMatchProposal(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasMatchProposal", reflect.TypeOf((*MockMatchProposalRepository)(nil).HasMatchProposal), arg0)
}

// Load mocks base method.
func (m *MockMatchProposalRepository) Load(arg0 string) (*matchmaker.MatchProposal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", arg0)
	ret0, _ := ret[0].(*matchmaker.MatchProposal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockMatchProposalRepositoryMockRecorder) Load(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockMatchProposalRepository)(nil).Load), arg0)
}

// Locker mocks base method.
func (m *MockMatchProposalRepository) Locker(arg0 string) lock.Mutex {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Locker", arg0)
	ret0, _ := ret[0].(lock.Mutex)
	return ret0
}

// Locker indicates an expected call of Locker.
func (mr *MockMatchProposalRepositoryMockRecorder) Locker(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Locker", reflect.TypeOf((*MockMatchProposalRepository)(nil).Locker), arg0)
}

// Save mocks base method.
func (m *MockMatchProposalRepository) Save(arg0 *matchmaker.MatchProposal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockMatchProposalRepositoryMockRecorder) Save(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockMatchProposalRepository)(nil).Save), arg0)
}
