// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker/custommatchmaker (interfaces: PlayerQueue)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	player "github.com/horizon-games/OpenSky/matchmaker/lib/player"
	gomock "go.uber.org/mock/gomock"
)

// MockPlayerQueue is a mock of PlayerQueue interface.
type MockPlayerQueue struct {
	ctrl     *gomock.Controller
	recorder *MockPlayerQueueMockRecorder
}

// MockPlayerQueueMockRecorder is the mock recorder for MockPlayerQueue.
type MockPlayerQueueMockRecorder struct {
	mock *MockPlayerQueue
}

// NewMockPlayerQueue creates a new mock instance.
func NewMockPlayerQueue(ctrl *gomock.Controller) *MockPlayerQueue {
	mock := &MockPlayerQueue{ctrl: ctrl}
	mock.recorder = &MockPlayerQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlayerQueue) EXPECT() *MockPlayerQueueMockRecorder {
	return m.recorder
}

// Items mocks base method.
func (m *MockPlayerQueue) Items(arg0 proto.GameMode) ([]proto.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Items", arg0)
	ret0, _ := ret[0].([]proto.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Items indicates an expected call of Items.
func (mr *MockPlayerQueueMockRecorder) Items(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Items", reflect.TypeOf((*MockPlayerQueue)(nil).Items), arg0)
}

// Push mocks base method.
func (m *MockPlayerQueue) Push(arg0 *player.Player) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Push", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Push indicates an expected call of Push.
func (mr *MockPlayerQueueMockRecorder) Push(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*MockPlayerQueue)(nil).Push), arg0)
}

// Remove mocks base method.
func (m *MockPlayerQueue) Remove(arg0 *player.Player) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockPlayerQueueMockRecorder) Remove(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockPlayerQueue)(nil).Remove), arg0)
}
