// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker/custommatchmaker (interfaces: RefusalPenaltySetter)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	player "github.com/horizon-games/OpenSky/matchmaker/lib/player"
	gomock "go.uber.org/mock/gomock"
)

// MockRefusalPenaltySetter is a mock of RefusalPenaltySetter interface.
type MockRefusalPenaltySetter struct {
	ctrl     *gomock.Controller
	recorder *MockRefusalPenaltySetterMockRecorder
}

// MockRefusalPenaltySetterMockRecorder is the mock recorder for MockRefusalPenaltySetter.
type MockRefusalPenaltySetterMockRecorder struct {
	mock *MockRefusalPenaltySetter
}

// NewMockRefusalPenaltySetter creates a new mock instance.
func NewMockRefusalPenaltySetter(ctrl *gomock.Controller) *MockRefusalPenaltySetter {
	mock := &MockRefusalPenaltySetter{ctrl: ctrl}
	mock.recorder = &MockRefusalPenaltySetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefusalPenaltySetter) EXPECT() *MockRefusalPenaltySetterMockRecorder {
	return m.recorder
}

// SetRefusalPenalty mocks base method.
func (m *MockRefusalPenaltySetter) SetRefusalPenalty(arg0 *player.Player) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRefusalPenalty", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRefusalPenalty indicates an expected call of SetRefusalPenalty.
func (mr *MockRefusalPenaltySetterMockRecorder) SetRefusalPenalty(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRefusalPenalty", reflect.TypeOf((*MockRefusalPenaltySetter)(nil).SetRefusalPenalty), arg0)
}
