/* eslint-disable */
// webserver v0.0.1 ba7250f3f3f32131e8560a1f2b7e2dd9fa2fe5eb
// --
// Code generated by webrpc-gen@v0.10.x-dev with typescript generator. DO NOT EDIT.
//
// webrpc-gen -schema=messages.ridl -target=typescript -client -out=./messages.gen.ts

// WebRPC description and code-gen version
export const WebRPCVersion = "v1"

// Schema version of your RIDL schema
export const WebRPCSchemaVersion = "v0.0.1"

// Schema hash generated from your RIDL schema
export const WebRPCSchemaHash = "ba7250f3f3f32131e8560a1f2b7e2dd9fa2fe5eb"

//
// Types
//


export enum EventType {
  PING = 'PING',
  UPDATE_CHECK = 'UPDATE_CHECK',
  UPDATE_REQUIRED = 'UPDATE_REQUIRED',
  UPDATE_IN_PROGRESS = 'UPDATE_IN_PROGRESS',
  UPDATE_FAILED = 'UPDATE_FAILED',
  UPDATE_SUCEEDED = 'UPDATE_SUCEEDED',
  OK = 'OK'
}

export interface Event {
  type: EventType
  value?: number
}

export interface WebServerAPI {
  getCachedFileHashes(headers?: object): Promise<GetCachedFileHashesReturn>
  invalidateCachedFilesByURL(args: InvalidateCachedFilesByURLArgs, headers?: object): Promise<InvalidateCachedFilesByURLReturn>
  invalidateCachedFilesByHash(args: InvalidateCachedFilesByHashArgs, headers?: object): Promise<InvalidateCachedFilesByHashReturn>
  purgeInvalidCachedFiles(headers?: object): Promise<PurgeInvalidCachedFilesReturn>
  checkForUpdate(headers?: object): Promise<CheckForUpdateReturn>
}

export interface GetCachedFileHashesArgs {
}

export interface GetCachedFileHashesReturn {
  sha256Hashes: Array<string>  
}
export interface InvalidateCachedFilesByURLArgs {
  uris: Array<string>
}

export interface InvalidateCachedFilesByURLReturn {
  ok: boolean  
}
export interface InvalidateCachedFilesByHashArgs {
  sha256Hashes: Array<string>
}

export interface InvalidateCachedFilesByHashReturn {
  ok: boolean  
}
export interface PurgeInvalidCachedFilesArgs {
}

export interface PurgeInvalidCachedFilesReturn {
  ok: boolean  
}
export interface CheckForUpdateArgs {
}

export interface CheckForUpdateReturn {
  done: boolean  
}


  
//
// Client
//
export class WebServerAPI implements WebServerAPI {
  protected hostname: string
  protected fetch: Fetch
  protected path = '/rpc/WebServerAPI/'

  constructor(hostname: string, fetch: Fetch) {
    this.hostname = hostname
    this.fetch = (input: RequestInfo, init?: RequestInit) => fetch(input, init)
  }

  private url(name: string): string {
    return this.hostname + this.path + name
  }
  
  getCachedFileHashes = (headers?: object): Promise<GetCachedFileHashesReturn> => {
    return this.fetch(
      this.url('GetCachedFileHashes'),
      createHTTPRequest({}, headers)
    ).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          sha256Hashes: <Array<string>>(_data.sha256Hashes),
        }
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error.message || ''}` })
    })
  }
  
  invalidateCachedFilesByURL = (args: InvalidateCachedFilesByURLArgs, headers?: object): Promise<InvalidateCachedFilesByURLReturn> => {
    return this.fetch(
      this.url('InvalidateCachedFilesByURL'),
      createHTTPRequest(args, headers)
    ).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          ok: <boolean>(_data.ok),
        }
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error.message || ''}` })
    })
  }
  
  invalidateCachedFilesByHash = (args: InvalidateCachedFilesByHashArgs, headers?: object): Promise<InvalidateCachedFilesByHashReturn> => {
    return this.fetch(
      this.url('InvalidateCachedFilesByHash'),
      createHTTPRequest(args, headers)
    ).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          ok: <boolean>(_data.ok),
        }
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error.message || ''}` })
    })
  }
  
  purgeInvalidCachedFiles = (headers?: object): Promise<PurgeInvalidCachedFilesReturn> => {
    return this.fetch(
      this.url('PurgeInvalidCachedFiles'),
      createHTTPRequest({}, headers)
    ).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          ok: <boolean>(_data.ok),
        }
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error.message || ''}` })
    })
  }
  
  checkForUpdate = (headers?: object): Promise<CheckForUpdateReturn> => {
    return this.fetch(
      this.url('CheckForUpdate'),
      createHTTPRequest({}, headers)
    ).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          done: <boolean>(_data.done),
        }
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error.message || ''}` })
    })
  }
  
}

  const createHTTPRequest = (body: object = {}, headers: object = {}): object => {
  return {
    method: 'POST',
    headers: { ...headers, 'Content-Type': 'application/json' },
    body: JSON.stringify(body || {})
  }
}

const buildResponse = (res: Response): Promise<any> => {
  return res.text().then(text => {
    let data
    try {
      data = JSON.parse(text)
    } catch(error) {
      throw WebrpcBadResponseError.new({
        status: res.status,
        cause: `JSON.parse(): ${error.message || ''}: response text: ${text}`},
      )
    }
    if (!res.ok) {
      const code: number = (typeof data.code === 'number') ? data.code : 0
      throw (webrpcErrorByCode[code] || WebrpcError).new(data)
    }
    return data
  })
}

//
// Errors
//

export class WebrpcError extends Error {
  name: string
  code: number
  message: string
  status: number
  cause?: string

  /** @deprecated Use message instead of msg. Deprecated in webrpc v0.11.0. */
  msg: string

  constructor(name: string, code: number, message: string, status: number, cause?: string) {
    super(message)
    this.name = name || 'WebrpcError'
    this.code = typeof code === 'number' ? code : 0
    this.message = message || `endpoint error ${this.code}`
    this.msg = this.message
    this.status = typeof status === 'number' ? status : 0
    this.cause = cause
    Object.setPrototypeOf(this, WebrpcError.prototype)
  }

  static new(payload: any): WebrpcError {
    return new this(payload.error, payload.code, payload.message || payload.msg, payload.status, payload.cause)
  }
}

// Webrpc errors

export class WebrpcEndpointError extends WebrpcError {
  constructor(
    name: string = 'WebrpcEndpoint',
    code: number = 0,
    message: string = 'endpoint error',
    status: number = 0,
    cause?: string
  ) {
    super(name, code, message, status, cause)
    Object.setPrototypeOf(this, WebrpcEndpointError.prototype)
  }
}

export class WebrpcRequestFailedError extends WebrpcError {
  constructor(
    name: string = 'WebrpcRequestFailed',
    code: number = -1,
    message: string = 'request failed',
    status: number = 0,
    cause?: string
  ) {
    super(name, code, message, status, cause)
    Object.setPrototypeOf(this, WebrpcRequestFailedError.prototype)
  }
}

export class WebrpcBadRouteError extends WebrpcError {
  constructor(
    name: string = 'WebrpcBadRoute',
    code: number = -2,
    message: string = 'bad route',
    status: number = 0,
    cause?: string
  ) {
    super(name, code, message, status, cause)
    Object.setPrototypeOf(this, WebrpcBadRouteError.prototype)
  }
}

export class WebrpcBadMethodError extends WebrpcError {
  constructor(
    name: string = 'WebrpcBadMethod',
    code: number = -3,
    message: string = 'bad method',
    status: number = 0,
    cause?: string
  ) {
    super(name, code, message, status, cause)
    Object.setPrototypeOf(this, WebrpcBadMethodError.prototype)
  }
}

export class WebrpcBadRequestError extends WebrpcError {
  constructor(
    name: string = 'WebrpcBadRequest',
    code: number = -4,
    message: string = 'bad request',
    status: number = 0,
    cause?: string
  ) {
    super(name, code, message, status, cause)
    Object.setPrototypeOf(this, WebrpcBadRequestError.prototype)
  }
}

export class WebrpcBadResponseError extends WebrpcError {
  constructor(
    name: string = 'WebrpcBadResponse',
    code: number = -5,
    message: string = 'bad response',
    status: number = 0,
    cause?: string
  ) {
    super(name, code, message, status, cause)
    Object.setPrototypeOf(this, WebrpcBadResponseError.prototype)
  }
}

export class WebrpcServerPanicError extends WebrpcError {
  constructor(
    name: string = 'WebrpcServerPanic',
    code: number = -6,
    message: string = 'server panic',
    status: number = 0,
    cause?: string
  ) {
    super(name, code, message, status, cause)
    Object.setPrototypeOf(this, WebrpcServerPanicError.prototype)
  }
}


// Schema errors


export enum errors {
  WebrpcEndpoint = 'WebrpcEndpoint',
  WebrpcRequestFailed = 'WebrpcRequestFailed',
  WebrpcBadRoute = 'WebrpcBadRoute',
  WebrpcBadMethod = 'WebrpcBadMethod',
  WebrpcBadRequest = 'WebrpcBadRequest',
  WebrpcBadResponse = 'WebrpcBadResponse',
  WebrpcServerPanic = 'WebrpcServerPanic',
}

const webrpcErrorByCode: { [code: number]: any } = {
  [0]: WebrpcEndpointError,
  [-1]: WebrpcRequestFailedError,
  [-2]: WebrpcBadRouteError,
  [-3]: WebrpcBadMethodError,
  [-4]: WebrpcBadRequestError,
  [-5]: WebrpcBadResponseError,
  [-6]: WebrpcServerPanicError,
}

export type Fetch = (input: RequestInfo, init?: RequestInit) => Promise<Response>
