[service]
  name   = "matchmaker-test"
  listen = "0.0.0.0:8888"
  mode   = "development"

[logging]
  level         = "INFO"
  json          = false
  concise       = false

[auth]
  jwt_secret    = "changemenow"

[redis]
  host = "redis"
  port = 6379

[hcaptcha]
  disabled = true

[honeybadger]
  api_key = ""

[opensky_api]
  uri = "http://opensky-api:1337"
  auth_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlIjoiZ2FtZS1zZXJ2ZXIifQ.pV_Rleoj49So-tyZzeCAxkdXeUjmh4PiNh_4kOd2tuA"
  game_modes_status_cache_ttl_seconds = 0

[game_server]
  auth_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.e30.taDuCwGfO37CntIURTjydC7YEf5C4Mvi9GTFa0ypepQ"

[matchmaker]
  authentication_timeout_seconds = 10.0 

  match_acceptance_timeout_seconds = 30.0
  match_acceptance_penalty_seconds = 2.0

  match_refusal_window_seconds = 30.0
  allow_same_ip_match = true
  direct_balance_fetch = true
  strict_conquest_matching = false
  min_rank_to_play_conquest = 0

  [matchmaker.match_interval]
    default_seconds = 0.2
    make_match_seconds = 0.1
    
    [matchmaker.match_interval.practice]
      bot_seconds = 0.5
      pvp_seconds = 0.5

    [matchmaker.match_interval.conquest]
      discovery_seconds = 0.5
      constructed_seconds = 0.5

    [matchmaker.match_interval.challenge]
      discovery_seconds = 0.5
      constructed_seconds = 0.5

  [matchmaker.relax_matching_rule_interval]
    default_seconds = 1.0

    [matchmaker.relax_matching_rule_interval.conquest]
      discovery_seconds = 1.0
      constructed_seconds = 1.0

    [matchmaker.relax_matching_rule_interval.ranked]
      discovery_seconds = 1.0
      constructed_seconds = 1.0

    [matchmaker.relax_matching_rule_interval.challenge]
      discovery_seconds = 1.0
      constructed_seconds = 1.0

  [matchmaker.match_refusal_penalty]
    default_seconds = [ 0.0, 2.0, 4.0, 6.0, 8.0 ] 

    [matchmaker.match_refusal_penalty.conquest]
      discovery_seconds = [ 0.0, 2.0, 4.0, 6.0, 8.0 ]
      constructed_seconds = [ 0.0, 2.0, 4.0, 6.0, 8.0 ]

[testing]
  authentication_bypass_enabled = true
  captcha_bypass_enabled = true
