// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/frontend/findmatch (interfaces: MatchFinder)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	player "github.com/horizon-games/OpenSky/matchmaker/lib/player"
	playerchannel "github.com/horizon-games/OpenSky/matchmaker/lib/playerchannel"
	gomock "go.uber.org/mock/gomock"
)

// MockMatchFinder is a mock of MatchFinder interface.
type MockMatchFinder struct {
	ctrl     *gomock.Controller
	recorder *MockMatchFinderMockRecorder
}

// MockMatchFinderMockRecorder is the mock recorder for MockMatchFinder.
type MockMatchFinderMockRecorder struct {
	mock *MockMatchFinder
}

// NewMockMatchFinder creates a new mock instance.
func NewMockMatchFinder(ctrl *gomock.Controller) *MockMatchFinder {
	mock := &MockMatchFinder{ctrl: ctrl}
	mock.recorder = &MockMatchFinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchFinder) EXPECT() *MockMatchFinderMockRecorder {
	return m.recorder
}

// FindMatch mocks base method.
func (m *MockMatchFinder) FindMatch(arg0 context.Context, arg1 *player.Player) (*playerchannel.PlayerChannel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMatch", arg0, arg1)
	ret0, _ := ret[0].(*playerchannel.PlayerChannel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMatch indicates an expected call of FindMatch.
func (mr *MockMatchFinderMockRecorder) FindMatch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMatch", reflect.TypeOf((*MockMatchFinder)(nil).FindMatch), arg0, arg1)
}
