// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/frontend/findmatch (interfaces: PlayerFactory)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	messages "github.com/horizon-games/OpenSky/matchmaker/lib/messages"
	player "github.com/horizon-games/OpenSky/matchmaker/lib/player"
	gomock "go.uber.org/mock/gomock"
)

// MockPlayerFactory is a mock of PlayerFactory interface.
type MockPlayerFactory struct {
	ctrl     *gomock.Controller
	recorder *MockPlayerFactoryMockRecorder
}

// MockPlayerFactoryMockRecorder is the mock recorder for MockPlayerFactory.
type MockPlayerFactoryMockRecorder struct {
	mock *MockPlayerFactory
}

// NewMockPlayerFactory creates a new mock instance.
func NewMockPlayerFactory(ctrl *gomock.Controller) *MockPlayerFactory {
	mock := &MockPlayerFactory{ctrl: ctrl}
	mock.recorder = &MockPlayerFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlayerFactory) EXPECT() *MockPlayerFactoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPlayerFactory) Create(arg0 context.Context, arg1 *messages.FindMatchMessage) (*player.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*player.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPlayerFactoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPlayerFactory)(nil).Create), arg0, arg1)
}
