// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/frontend/findmatch (interfaces: SkyWeaverAPI)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	player "github.com/horizon-games/OpenSky/matchmaker/lib/player"
	gomock "go.uber.org/mock/gomock"
)

// MockSkyWeaverAPI is a mock of SkyWeaverAPI interface.
type MockSkyWeaverAPI struct {
	ctrl     *gomock.Controller
	recorder *MockSkyWeaverAPIMockRecorder
}

// MockSkyWeaverAPIMockRecorder is the mock recorder for MockSkyWeaverAPI.
type MockSkyWeaverAPIMockRecorder struct {
	mock *MockSkyWeaverAPI
}

// NewMockSkyWeaverAPI creates a new mock instance.
func NewMockSkyWeaverAPI(ctrl *gomock.Controller) *MockSkyWeaverAPI {
	mock := &MockSkyWeaverAPI{ctrl: ctrl}
	mock.recorder = &MockSkyWeaverAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSkyWeaverAPI) EXPECT() *MockSkyWeaverAPIMockRecorder {
	return m.recorder
}

// GetAccountWithItems mocks base method.
func (m *MockSkyWeaverAPI) GetAccountWithItems(arg0 context.Context, arg1 proto.Hash, arg2 string, arg3 []player.Prism) (*player.AccountWithItems, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountWithItems", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*player.AccountWithItems)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountWithItems indicates an expected call of GetAccountWithItems.
func (mr *MockSkyWeaverAPIMockRecorder) GetAccountWithItems(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountWithItems", reflect.TypeOf((*MockSkyWeaverAPI)(nil).GetAccountWithItems), arg0, arg1, arg2, arg3)
}

// GetConquestInfo mocks base method.
func (m *MockSkyWeaverAPI) GetConquestInfo(arg0 context.Context, arg1 proto.Hash) (*proto.Conquest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConquestInfo", arg0, arg1)
	ret0, _ := ret[0].(*proto.Conquest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConquestInfo indicates an expected call of GetConquestInfo.
func (mr *MockSkyWeaverAPIMockRecorder) GetConquestInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConquestInfo", reflect.TypeOf((*MockSkyWeaverAPI)(nil).GetConquestInfo), arg0, arg1)
}

// ListQuests mocks base method.
func (m *MockSkyWeaverAPI) ListQuests(arg0 context.Context, arg1 proto.Hash) ([]*proto.Quest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListQuests", arg0, arg1)
	ret0, _ := ret[0].([]*proto.Quest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListQuests indicates an expected call of ListQuests.
func (mr *MockSkyWeaverAPIMockRecorder) ListQuests(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListQuests", reflect.TypeOf((*MockSkyWeaverAPI)(nil).ListQuests), arg0, arg1)
}
