// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/frontend/findmatch (interfaces: Validator)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	frontend "github.com/horizon-games/OpenSky/matchmaker/lib/frontend"
	messages "github.com/horizon-games/OpenSky/matchmaker/lib/messages"
	gomock "go.uber.org/mock/gomock"
)

// MockValidator is a mock of Validator interface.
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
}

// MockValidatorMockRecorder is the mock recorder for MockValidator.
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance.
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// IsValid mocks base method.
func (m *MockValidator) IsValid(arg0 context.Context, arg1 *frontend.Client, arg2 *messages.FindMatchMessage) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValid", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsValid indicates an expected call of IsValid.
func (mr *MockValidatorMockRecorder) IsValid(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValid", reflect.TypeOf((*MockValidator)(nil).IsValid), arg0, arg1, arg2)
}
