// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/director/matchhandlers (interfaces: MatchProcessor)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	matchmaker "github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker"
	gomock "go.uber.org/mock/gomock"
)

// MockMatchProcessor is a mock of MatchProcessor interface.
type MockMatchProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockMatchProcessorMockRecorder
}

// MockMatchProcessorMockRecorder is the mock recorder for MockMatchProcessor.
type MockMatchProcessorMockRecorder struct {
	mock *MockMatchProcessor
}

// NewMockMatchProcessor creates a new mock instance.
func NewMockMatchProcessor(ctrl *gomock.Controller) *MockMatchProcessor {
	mock := &MockMatchProcessor{ctrl: ctrl}
	mock.recorder = &MockMatchProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchProcessor) EXPECT() *MockMatchProcessorMockRecorder {
	return m.recorder
}

// ProcessMatch mocks base method.
func (m *MockMatchProcessor) ProcessMatch(arg0 context.Context, arg1 *matchmaker.MatchProposal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessMatch", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessMatch indicates an expected call of ProcessMatch.
func (mr *MockMatchProcessorMockRecorder) ProcessMatch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessMatch", reflect.TypeOf((*MockMatchProcessor)(nil).ProcessMatch), arg0, arg1)
}
