// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/director/matchhandlers (interfaces: PlayerShuffler)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	player "github.com/horizon-games/OpenSky/matchmaker/lib/player"
	gomock "go.uber.org/mock/gomock"
)

// MockPlayerShuffler is a mock of PlayerShuffler interface.
type MockPlayerShuffler struct {
	ctrl     *gomock.Controller
	recorder *MockPlayerShufflerMockRecorder
}

// MockPlayerShufflerMockRecorder is the mock recorder for MockPlayerShuffler.
type MockPlayerShufflerMockRecorder struct {
	mock *MockPlayerShuffler
}

// NewMockPlayerShuffler creates a new mock instance.
func NewMockPlayerShuffler(ctrl *gomock.Controller) *MockPlayerShuffler {
	mock := &MockPlayerShuffler{ctrl: ctrl}
	mock.recorder = &MockPlayerShufflerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlayerShuffler) EXPECT() *MockPlayerShufflerMockRecorder {
	return m.recorder
}

// Shuffle mocks base method.
func (m *MockPlayerShuffler) Shuffle(arg0 []*player.Player) []*player.Player {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shuffle", arg0)
	ret0, _ := ret[0].([]*player.Player)
	return ret0
}

// Shuffle indicates an expected call of Shuffle.
func (mr *MockPlayerShufflerMockRecorder) Shuffle(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shuffle", reflect.TypeOf((*MockPlayerShuffler)(nil).Shuffle), arg0)
}
