// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/director/matchhandlers (interfaces: PlayerStatsPusher)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	playerstats "github.com/horizon-games/OpenSky/matchmaker/lib/playerstats"
	gomock "go.uber.org/mock/gomock"
)

// MockPlayerStatsPusher is a mock of PlayerStatsPusher interface.
type MockPlayerStatsPusher struct {
	ctrl     *gomock.Controller
	recorder *MockPlayerStatsPusherMockRecorder
}

// MockPlayerStatsPusherMockRecorder is the mock recorder for MockPlayerStatsPusher.
type MockPlayerStatsPusherMockRecorder struct {
	mock *MockPlayerStatsPusher
}

// NewMockPlayerStatsPusher creates a new mock instance.
func NewMockPlayerStatsPusher(ctrl *gomock.Controller) *MockPlayerStatsPusher {
	mock := &MockPlayerStatsPusher{ctrl: ctrl}
	mock.recorder = &MockPlayerStatsPusherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlayerStatsPusher) EXPECT() *MockPlayerStatsPusherMockRecorder {
	return m.recorder
}

// Push mocks base method.
func (m *MockPlayerStatsPusher) Push(arg0 proto.Hash, arg1 *playerstats.Stat) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Push", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Push indicates an expected call of Push.
func (mr *MockPlayerStatsPusherMockRecorder) Push(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*MockPlayerStatsPusher)(nil).Push), arg0, arg1)
}
