// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/director/matchhandlers (interfaces: RecentMatchTracker)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockRecentMatchTracker is a mock of RecentMatchTracker interface.
type MockRecentMatchTracker struct {
	ctrl     *gomock.Controller
	recorder *MockRecentMatchTrackerMockRecorder
}

// MockRecentMatchTrackerMockRecorder is the mock recorder for MockRecentMatchTracker.
type MockRecentMatchTrackerMockRecorder struct {
	mock *MockRecentMatchTracker
}

// NewMockRecentMatchTracker creates a new mock instance.
func NewMockRecentMatchTracker(ctrl *gomock.Controller) *MockRecentMatchTracker {
	mock := &MockRecentMatchTracker{ctrl: ctrl}
	mock.recorder = &MockRecentMatchTrackerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecentMatchTracker) EXPECT() *MockRecentMatchTrackerMockRecorder {
	return m.recorder
}

// DeleteMatch mocks base method.
func (m *MockRecentMatchTracker) DeleteMatch(arg0 ...proto.Hash) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteMatch", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMatch indicates an expected call of DeleteMatch.
func (mr *MockRecentMatchTrackerMockRecorder) DeleteMatch(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMatch", reflect.TypeOf((*MockRecentMatchTracker)(nil).DeleteMatch), arg0...)
}
