// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/director/matchhandlers (interfaces: RefusalPenaltyDeleter)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	player "github.com/horizon-games/OpenSky/matchmaker/lib/player"
	gomock "go.uber.org/mock/gomock"
)

// MockRefusalPenaltyDeleter is a mock of RefusalPenaltyDeleter interface.
type MockRefusalPenaltyDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockRefusalPenaltyDeleterMockRecorder
}

// MockRefusalPenaltyDeleterMockRecorder is the mock recorder for MockRefusalPenaltyDeleter.
type MockRefusalPenaltyDeleterMockRecorder struct {
	mock *MockRefusalPenaltyDeleter
}

// NewMockRefusalPenaltyDeleter creates a new mock instance.
func NewMockRefusalPenaltyDeleter(ctrl *gomock.Controller) *MockRefusalPenaltyDeleter {
	mock := &MockRefusalPenaltyDeleter{ctrl: ctrl}
	mock.recorder = &MockRefusalPenaltyDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefusalPenaltyDeleter) EXPECT() *MockRefusalPenaltyDeleterMockRecorder {
	return m.recorder
}

// DeleteRefusalPenalty mocks base method.
func (m *MockRefusalPenaltyDeleter) DeleteRefusalPenalty(arg0 *player.Player) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefusalPenalty", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefusalPenalty indicates an expected call of DeleteRefusalPenalty.
func (mr *MockRefusalPenaltyDeleterMockRecorder) DeleteRefusalPenalty(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefusalPenalty", reflect.TypeOf((*MockRefusalPenaltyDeleter)(nil).DeleteRefusalPenalty), arg0)
}
