// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/director/matchhandlers (interfaces: SkyWeaverAPI)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	player "github.com/horizon-games/OpenSky/matchmaker/lib/player"
	gomock "go.uber.org/mock/gomock"
)

// MockSkyWeaverAPI is a mock of SkyWeaverAPI interface.
type MockSkyWeaverAPI struct {
	ctrl     *gomock.Controller
	recorder *MockSkyWeaverAPIMockRecorder
}

// MockSkyWeaverAPIMockRecorder is the mock recorder for MockSkyWeaverAPI.
type MockSkyWeaverAPIMockRecorder struct {
	mock *MockSkyWeaverAPI
}

// NewMockSkyWeaverAPI creates a new mock instance.
func NewMockSkyWeaverAPI(ctrl *gomock.Controller) *MockSkyWeaverAPI {
	mock := &MockSkyWeaverAPI{ctrl: ctrl}
	mock.recorder = &MockSkyWeaverAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSkyWeaverAPI) EXPECT() *MockSkyWeaverAPIMockRecorder {
	return m.recorder
}

// GetCurrentSeason mocks base method.
func (m *MockSkyWeaverAPI) GetCurrentSeason(arg0 context.Context) (uint16, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentSeason", arg0)
	ret0, _ := ret[0].(uint16)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentSeason indicates an expected call of GetCurrentSeason.
func (mr *MockSkyWeaverAPIMockRecorder) GetCurrentSeason(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentSeason", reflect.TypeOf((*MockSkyWeaverAPI)(nil).GetCurrentSeason), arg0)
}

// MatchStart mocks base method.
func (m *MockSkyWeaverAPI) MatchStart(arg0 context.Context, arg1, arg2 *player.Player) (uint64, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MatchStart", arg0, arg1, arg2)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// MatchStart indicates an expected call of MatchStart.
func (mr *MockSkyWeaverAPIMockRecorder) MatchStart(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MatchStart", reflect.TypeOf((*MockSkyWeaverAPI)(nil).MatchStart), arg0, arg1, arg2)
}
