"use strict";
/* eslint-disable */
// api v0.3.0 34730d4723dccc67a76b11d856510e4517db63fd
// --
// This file has been generated by https://github.com/webrpc/webrpc using gen/typescript
// Do not edit by hand. Update your webrpc schema and re-generate.
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.SkyWeaverAPI = exports.SkypassRewardType = exports.SkypassTier = exports.NotificationType = exports.BannerType = exports.SortOrder = exports.SignalStatus = exports.ActionType = exports.IAPTransactionStatus = exports.PurchaseStateAndroid = exports.ConquestMatchResult = exports.ConquestStatus = exports.TaskStatus = exports.DeckType = exports.RewardType = exports.MatchStatus = exports.GameMode = exports.CardSet = exports.CardClass = exports.CardStatus = exports.CardElement = exports.CardKeyword = exports.CardType = exports.DeckClass = exports.Hero = exports.FeedEventType = exports.ItemType = exports.ContractType = exports.CookiePolicyOption = exports.PlayerRankStage = exports.PlayerRank = exports.AccountStatus = exports.WebRPCSchemaHash = exports.WebRPCSchemaVersion = exports.WebRPCVersion = void 0;
// WebRPC description and code-gen version
exports.WebRPCVersion = "v1";
// Schema version of your RIDL schema
exports.WebRPCSchemaVersion = "v0.3.0";
// Schema hash generated from your RIDL schema
exports.WebRPCSchemaHash = "34730d4723dccc67a76b11d856510e4517db63fd";
//
// Types
//
var AccountStatus;
(function (AccountStatus) {
    AccountStatus["ACTIVE"] = "ACTIVE";
    AccountStatus["SUSPENDED"] = "SUSPENDED";
    AccountStatus["BANNED"] = "BANNED";
    AccountStatus["VIP"] = "VIP";
    AccountStatus["FLAGGED"] = "FLAGGED";
    AccountStatus["TO_DELETE"] = "TO_DELETE";
    AccountStatus["DELETED"] = "DELETED";
})(AccountStatus = exports.AccountStatus || (exports.AccountStatus = {}));
var PlayerRank;
(function (PlayerRank) {
    PlayerRank["UNKNOWN"] = "UNKNOWN";
    PlayerRank["UNRANKED"] = "UNRANKED";
    PlayerRank["WANDERER"] = "WANDERER";
    PlayerRank["TRAINEE"] = "TRAINEE";
    PlayerRank["APPRENTICE"] = "APPRENTICE";
    PlayerRank["EXPERT"] = "EXPERT";
    PlayerRank["MASTER"] = "MASTER";
    PlayerRank["GRANDWEAVER"] = "GRANDWEAVER";
})(PlayerRank = exports.PlayerRank || (exports.PlayerRank = {}));
var PlayerRankStage;
(function (PlayerRankStage) {
    PlayerRankStage["STAGE_NONE"] = "STAGE_NONE";
    PlayerRankStage["STAGE_I"] = "STAGE_I";
    PlayerRankStage["STAGE_II"] = "STAGE_II";
    PlayerRankStage["STAGE_III"] = "STAGE_III";
})(PlayerRankStage = exports.PlayerRankStage || (exports.PlayerRankStage = {}));
var CookiePolicyOption;
(function (CookiePolicyOption) {
    CookiePolicyOption["AUTHENTICATION"] = "AUTHENTICATION";
    CookiePolicyOption["MARKETPLACE"] = "MARKETPLACE";
    CookiePolicyOption["GEO_BLOCKING"] = "GEO_BLOCKING";
    CookiePolicyOption["PRODUCT_ANALYTICS"] = "PRODUCT_ANALYTICS";
})(CookiePolicyOption = exports.CookiePolicyOption || (exports.CookiePolicyOption = {}));
var ContractType;
(function (ContractType) {
    ContractType["UNKNOWN"] = "UNKNOWN";
    ContractType["SKYWEAVER_ASSETS"] = "SKYWEAVER_ASSETS";
})(ContractType = exports.ContractType || (exports.ContractType = {}));
var ItemType;
(function (ItemType) {
    ItemType["UNKNOWN"] = "UNKNOWN";
    ItemType["USDC"] = "USDC";
    ItemType["SW_BASE_CARDS"] = "SW_BASE_CARDS";
    ItemType["SW_SILVER_DUST"] = "SW_SILVER_DUST";
    ItemType["SW_SILVER_CARDS"] = "SW_SILVER_CARDS";
    ItemType["SW_GOLD_CARDS"] = "SW_GOLD_CARDS";
    ItemType["SW_CONQUEST_TICKET"] = "SW_CONQUEST_TICKET";
    ItemType["SW_CRYSTALS"] = "SW_CRYSTALS";
    ItemType["SW_STICKERS"] = "SW_STICKERS";
    ItemType["SW_HERO_SKINS"] = "SW_HERO_SKINS";
    ItemType["SW_CARD_BACKS"] = "SW_CARD_BACKS";
    ItemType["SW_HERO"] = "SW_HERO";
})(ItemType = exports.ItemType || (exports.ItemType = {}));
var FeedEventType;
(function (FeedEventType) {
    FeedEventType["LEVELUP"] = "LEVELUP";
    FeedEventType["MATCH"] = "MATCH";
    FeedEventType["REWARD"] = "REWARD";
    FeedEventType["TRADE"] = "TRADE";
    FeedEventType["RANKUP"] = "RANKUP";
    FeedEventType["LEADERBOARD_REWARD"] = "LEADERBOARD_REWARD";
    FeedEventType["HERO_UNLOCK"] = "HERO_UNLOCK";
    FeedEventType["IAP_CONQUEST_MINTING"] = "IAP_CONQUEST_MINTING";
    FeedEventType["DELAYED_REWARD"] = "DELAYED_REWARD";
    FeedEventType["DELAYED_REWARD_MINTED"] = "DELAYED_REWARD_MINTED";
    FeedEventType["STARTED_DECK_UNLOCK"] = "STARTED_DECK_UNLOCK";
    FeedEventType["CONQUEST_V2_REWARD"] = "CONQUEST_V2_REWARD";
})(FeedEventType = exports.FeedEventType || (exports.FeedEventType = {}));
var Hero;
(function (Hero) {
    Hero["UNKNOWN"] = "UNKNOWN";
    Hero["ADA"] = "ADA";
    Hero["SAMYA"] = "SAMYA";
    Hero["FOX"] = "FOX";
    Hero["LOTUS"] = "LOTUS";
    Hero["TITUS"] = "TITUS";
    Hero["IRIS"] = "IRIS";
    Hero["BOURAN"] = "BOURAN";
    Hero["HORIK"] = "HORIK";
    Hero["ZOEY"] = "ZOEY";
    Hero["AXEL"] = "AXEL";
    Hero["ARI"] = "ARI";
    Hero["MIRA"] = "MIRA";
    Hero["MAI"] = "MAI";
    Hero["BANJO"] = "BANJO";
    Hero["SITTI"] = "SITTI";
})(Hero = exports.Hero || (exports.Hero = {}));
var DeckClass;
(function (DeckClass) {
    DeckClass["UNKNOWN_CLASS"] = "UNKNOWN_CLASS";
    DeckClass["STR"] = "STR";
    DeckClass["HRT"] = "HRT";
    DeckClass["AGY"] = "AGY";
    DeckClass["INT"] = "INT";
    DeckClass["WIS"] = "WIS";
    DeckClass["STH"] = "STH";
    DeckClass["STA"] = "STA";
    DeckClass["STI"] = "STI";
    DeckClass["STW"] = "STW";
    DeckClass["HRA"] = "HRA";
    DeckClass["HRI"] = "HRI";
    DeckClass["HRW"] = "HRW";
    DeckClass["AGI"] = "AGI";
    DeckClass["AGW"] = "AGW";
    DeckClass["INW"] = "INW";
})(DeckClass = exports.DeckClass || (exports.DeckClass = {}));
var CardType;
(function (CardType) {
    CardType["UNIT"] = "UNIT";
    CardType["SPELL"] = "SPELL";
})(CardType = exports.CardType || (exports.CardType = {}));
var CardKeyword;
(function (CardKeyword) {
    CardKeyword["ARMOR"] = "ARMOR";
    CardKeyword["STEALTH"] = "STEALTH";
    CardKeyword["GUARD"] = "GUARD";
    CardKeyword["BANNER"] = "BANNER";
    CardKeyword["WITHER"] = "WITHER";
    CardKeyword["DEATH"] = "DEATH";
})(CardKeyword = exports.CardKeyword || (exports.CardKeyword = {}));
var CardElement;
(function (CardElement) {
    CardElement["WATER"] = "WATER";
    CardElement["FIRE"] = "FIRE";
    CardElement["EARTH"] = "EARTH";
    CardElement["AIR"] = "AIR";
    CardElement["MIND"] = "MIND";
    CardElement["METAL"] = "METAL";
    CardElement["LIGHT"] = "LIGHT";
    CardElement["DARK"] = "DARK";
})(CardElement = exports.CardElement || (exports.CardElement = {}));
var CardStatus;
(function (CardStatus) {
    CardStatus["PLAY"] = "PLAY";
    CardStatus["BLOCKED"] = "BLOCKED";
    CardStatus["CODE"] = "CODE";
})(CardStatus = exports.CardStatus || (exports.CardStatus = {}));
var CardClass;
(function (CardClass) {
    CardClass["STR"] = "STR";
    CardClass["HRT"] = "HRT";
    CardClass["AGY"] = "AGY";
    CardClass["INT"] = "INT";
    CardClass["WIS"] = "WIS";
    CardClass["TOK"] = "TOK";
})(CardClass = exports.CardClass || (exports.CardClass = {}));
var CardSet;
(function (CardSet) {
    CardSet["UNKNOWN"] = "UNKNOWN";
    CardSet["CORE_SET"] = "CORE_SET";
    CardSet["CORE_EXPANSION"] = "CORE_EXPANSION";
    CardSet["CLASH_OF_INVENTORS"] = "CLASH_OF_INVENTORS";
    CardSet["HEXBOUND_INVASION"] = "HEXBOUND_INVASION";
})(CardSet = exports.CardSet || (exports.CardSet = {}));
var GameMode;
(function (GameMode) {
    GameMode["UNKNOWN"] = "UNKNOWN";
    GameMode["RANKED_CONSTRUCTED"] = "RANKED_CONSTRUCTED";
    GameMode["CHALLENGE_CONSTRUCTED"] = "CHALLENGE_CONSTRUCTED";
    GameMode["TUTORIAL"] = "TUTORIAL";
    GameMode["PRACTICE_BOT"] = "PRACTICE_BOT";
    GameMode["RANKED_DISCOVERY"] = "RANKED_DISCOVERY";
    GameMode["CONQUEST_CONSTRUCTED"] = "CONQUEST_CONSTRUCTED";
    GameMode["CONQUEST_DISCOVERY"] = "CONQUEST_DISCOVERY";
    GameMode["WARM_UP"] = "WARM_UP";
    GameMode["CHALLENGE_DISCOVERY"] = "CHALLENGE_DISCOVERY";
    GameMode["PRACTICE_PVP"] = "PRACTICE_PVP";
})(GameMode = exports.GameMode || (exports.GameMode = {}));
var MatchStatus;
(function (MatchStatus) {
    MatchStatus["UNKNOWN"] = "UNKNOWN";
    MatchStatus["COMPLETED"] = "COMPLETED";
    MatchStatus["ABANDONED"] = "ABANDONED";
    MatchStatus["FORFEITED"] = "FORFEITED";
    MatchStatus["IN_PROGRESS"] = "IN_PROGRESS";
    MatchStatus["CRASHED"] = "CRASHED";
})(MatchStatus = exports.MatchStatus || (exports.MatchStatus = {}));
var RewardType;
(function (RewardType) {
    RewardType["EXP"] = "EXP";
    RewardType["CARD"] = "CARD";
    RewardType["RANK"] = "RANK";
    RewardType["PRISM"] = "PRISM";
    RewardType["HERO"] = "HERO";
    RewardType["HERO_SKIN"] = "HERO_SKIN";
    RewardType["DECK"] = "DECK";
    RewardType["CONQUEST_POINTS"] = "CONQUEST_POINTS";
})(RewardType = exports.RewardType || (exports.RewardType = {}));
var DeckType;
(function (DeckType) {
    DeckType["RANDOM"] = "RANDOM";
    DeckType["CUSTOM"] = "CUSTOM";
    DeckType["LOCKED_STARTER"] = "LOCKED_STARTER";
    DeckType["UNLOCKED_STARTER"] = "UNLOCKED_STARTER";
})(DeckType = exports.DeckType || (exports.DeckType = {}));
var TaskStatus;
(function (TaskStatus) {
    TaskStatus["PENDING"] = "PENDING";
    TaskStatus["PAUSED"] = "PAUSED";
    TaskStatus["FAILED"] = "FAILED";
    TaskStatus["COMPLETED"] = "COMPLETED";
    TaskStatus["DISABLED"] = "DISABLED";
})(TaskStatus = exports.TaskStatus || (exports.TaskStatus = {}));
var ConquestStatus;
(function (ConquestStatus) {
    ConquestStatus["UNKNOWN"] = "UNKNOWN";
    ConquestStatus["IN_PROGRESS"] = "IN_PROGRESS";
    ConquestStatus["REWARDS_PENDING"] = "REWARDS_PENDING";
    ConquestStatus["COMPLETED"] = "COMPLETED";
})(ConquestStatus = exports.ConquestStatus || (exports.ConquestStatus = {}));
var ConquestMatchResult;
(function (ConquestMatchResult) {
    ConquestMatchResult["UNKNOWN"] = "UNKNOWN";
    ConquestMatchResult["WIN"] = "WIN";
    ConquestMatchResult["LOSS"] = "LOSS";
    ConquestMatchResult["DRAW"] = "DRAW";
})(ConquestMatchResult = exports.ConquestMatchResult || (exports.ConquestMatchResult = {}));
var PurchaseStateAndroid;
(function (PurchaseStateAndroid) {
    PurchaseStateAndroid["UNSPECIFIED_STATE"] = "UNSPECIFIED_STATE";
    PurchaseStateAndroid["PURCHASED"] = "PURCHASED";
    PurchaseStateAndroid["PENDING"] = "PENDING";
})(PurchaseStateAndroid = exports.PurchaseStateAndroid || (exports.PurchaseStateAndroid = {}));
var IAPTransactionStatus;
(function (IAPTransactionStatus) {
    IAPTransactionStatus["UNKNOWN"] = "UNKNOWN";
    IAPTransactionStatus["MINTING_FAILED"] = "MINTING_FAILED";
    IAPTransactionStatus["MINTING_PENDING"] = "MINTING_PENDING";
    IAPTransactionStatus["MINTING_SUCCESS"] = "MINTING_SUCCESS";
    IAPTransactionStatus["PAYMENT_FAILED"] = "PAYMENT_FAILED";
})(IAPTransactionStatus = exports.IAPTransactionStatus || (exports.IAPTransactionStatus = {}));
var ActionType;
(function (ActionType) {
    ActionType["MOD_BAN"] = "MOD_BAN";
    ActionType["MOD_SUSPENSION"] = "MOD_SUSPENSION";
    ActionType["AUTO_BAN"] = "AUTO_BAN";
    ActionType["AUTO_SUSPENSION"] = "AUTO_SUSPENSION";
    ActionType["DELAYED_MOD_BAN"] = "DELAYED_MOD_BAN";
    ActionType["DELAYED_MOD_SUSPENSION"] = "DELAYED_MOD_SUSPENSION";
    ActionType["DELAYED_AUTO_BAN"] = "DELAYED_AUTO_BAN";
    ActionType["DELAYED_AUTO_SUSPENSION"] = "DELAYED_AUTO_SUSPENSION";
    ActionType["MOD_FLAG"] = "MOD_FLAG";
    ActionType["AUTO_FLAG"] = "AUTO_FLAG";
    ActionType["MOD_VET"] = "MOD_VET";
})(ActionType = exports.ActionType || (exports.ActionType = {}));
var SignalStatus;
(function (SignalStatus) {
    SignalStatus["PENDING"] = "PENDING";
    SignalStatus["ACTED_UPON"] = "ACTED_UPON";
    SignalStatus["NOT_ACTIONABLE"] = "NOT_ACTIONABLE";
})(SignalStatus = exports.SignalStatus || (exports.SignalStatus = {}));
var SortOrder;
(function (SortOrder) {
    SortOrder["DESC"] = "DESC";
    SortOrder["ASC"] = "ASC";
})(SortOrder = exports.SortOrder || (exports.SortOrder = {}));
var BannerType;
(function (BannerType) {
    BannerType["INFO"] = "INFO";
    BannerType["WARNING"] = "WARNING";
    BannerType["EMERGENCY"] = "EMERGENCY";
})(BannerType = exports.BannerType || (exports.BannerType = {}));
var NotificationType;
(function (NotificationType) {
    NotificationType["LEADERBOARD_REWARD"] = "LEADERBOARD_REWARD";
    NotificationType["CONQUEST_V2_REWARD"] = "CONQUEST_V2_REWARD";
    NotificationType["SKYPASS_LEVEL_INTRODUCTION"] = "SKYPASS_LEVEL_INTRODUCTION";
    NotificationType["SEASON_START"] = "SEASON_START";
})(NotificationType = exports.NotificationType || (exports.NotificationType = {}));
var SkypassTier;
(function (SkypassTier) {
    SkypassTier["FREE"] = "FREE";
    SkypassTier["PREMIUM"] = "PREMIUM";
})(SkypassTier = exports.SkypassTier || (exports.SkypassTier = {}));
var SkypassRewardType;
(function (SkypassRewardType) {
    SkypassRewardType["XP_BOOST"] = "XP_BOOST";
    SkypassRewardType["CONQUEST_TICKET"] = "CONQUEST_TICKET";
    SkypassRewardType["STICKER_POINT"] = "STICKER_POINT";
    SkypassRewardType["STICKER"] = "STICKER";
    SkypassRewardType["HERO"] = "HERO";
    SkypassRewardType["HERO_SKIN"] = "HERO_SKIN";
    SkypassRewardType["BASE_CARD"] = "BASE_CARD";
    SkypassRewardType["SILVER_CARD"] = "SILVER_CARD";
    SkypassRewardType["CARD_BACK"] = "CARD_BACK";
})(SkypassRewardType = exports.SkypassRewardType || (exports.SkypassRewardType = {}));
//
// Client
//
var SkyWeaverAPI = /** @class */ (function () {
    function SkyWeaverAPI(hostname, fetch) {
        var _this = this;
        this.path = '/rpc/SkyWeaverAPI/';
        this.getAuthToken = function (args, headers) {
            return _this.fetch(_this.url('GetAuthToken'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        status: (_data.status),
                        jwtToken: (_data.jwtToken),
                        address: (_data.address),
                        account: (_data.account)
                    };
                });
            });
        };
        this.getSession = function (headers) {
            return _this.fetch(_this.url('GetSession'), createHTTPRequest({}, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        address: (_data.address),
                        account: (_data.account)
                    };
                });
            });
        };
        this.migrateAccount = function (args, headers) {
            return _this.fetch(_this.url('MigrateAccount'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        ok: (_data.ok)
                    };
                });
            });
        };
        this.registerAccount = function (args, headers) {
            return _this.fetch(_this.url('RegisterAccount'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        status: (_data.status),
                        account: (_data.account)
                    };
                });
            });
        };
        this.getAccount = function (args, headers) {
            return _this.fetch(_this.url('GetAccount'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        account: (_data.account)
                    };
                });
            });
        };
        this.getAccountByUsername = function (args, headers) {
            return _this.fetch(_this.url('GetAccountByUsername'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        account: (_data.account)
                    };
                });
            });
        };
        this.getAccountStats = function (args, headers) {
            return _this.fetch(_this.url('GetAccountStats'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        constructedStats: (_data.constructedStats),
                        discoveryStats: (_data.discoveryStats)
                    };
                });
            });
        };
        this.accountExists = function (args, headers) {
            return _this.fetch(_this.url('AccountExists'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        exists: (_data.exists),
                        pending_migration: (_data.pending_migration)
                    };
                });
            });
        };
        this.accountExistsByName = function (args, headers) {
            return _this.fetch(_this.url('AccountExistsByName'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        exists: (_data.exists),
                        pending_migration: (_data.pending_migration)
                    };
                });
            });
        };
        this.updateAccount = function (args, headers) {
            return _this.fetch(_this.url('UpdateAccount'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        account: (_data.account)
                    };
                });
            });
        };
        this.requestAccountDeletion = function (args, headers) {
            return _this.fetch(_this.url('RequestAccountDeletion'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        status: (_data.status)
                    };
                });
            });
        };
        this.requestMoreInvites = function (headers) {
            return _this.fetch(_this.url('RequestMoreInvites'), createHTTPRequest({}, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        status: (_data.status)
                    };
                });
            });
        };
        this.setInvitedBy = function (args, headers) {
            return _this.fetch(_this.url('SetInvitedBy'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        ok: (_data.ok)
                    };
                });
            });
        };
        this.getPrivateSpectateCode = function (args, headers) {
            return _this.fetch(_this.url('GetPrivateSpectateCode'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        code: (_data.code)
                    };
                });
            });
        };
        this.listNotifications = function (headers) {
            return _this.fetch(_this.url('ListNotifications'), createHTTPRequest({}, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        notifications: (_data.notifications)
                    };
                });
            });
        };
        this.setNotificationsAsSeen = function (args, headers) {
            return _this.fetch(_this.url('SetNotificationsAsSeen'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        status: (_data.status)
                    };
                });
            });
        };
        this.getFriendPoints = function (args, headers) {
            return _this.fetch(_this.url('GetFriendPoints'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        total: (_data.total),
                        friends: (_data.friends)
                    };
                });
            });
        };
        this.getFriendPointsBySeason = function (args, headers) {
            return _this.fetch(_this.url('GetFriendPointsBySeason'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        total: (_data.total),
                        friends: (_data.friends)
                    };
                });
            });
        };
        this.getPointsGifted = function (args, headers) {
            return _this.fetch(_this.url('GetPointsGifted'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        total: (_data.total),
                        inviter: (_data.inviter)
                    };
                });
            });
        };
        this.getStickers = function (headers) {
            return _this.fetch(_this.url('GetStickers'), createHTTPRequest({}, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        stickers: (_data.stickers)
                    };
                });
            });
        };
        this.getStickersBySeason = function (args, headers) {
            return _this.fetch(_this.url('GetStickersBySeason'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        stickers: (_data.stickers)
                    };
                });
            });
        };
        this.getStickerOwnership = function (args, headers) {
            return _this.fetch(_this.url('GetStickerOwnership'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        res: (_data.res)
                    };
                });
            });
        };
        this.userStorageFetch = function (args, headers) {
            return _this.fetch(_this.url('UserStorageFetch'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        object: (_data.object)
                    };
                });
            });
        };
        this.userStorageSave = function (args, headers) {
            return _this.fetch(_this.url('UserStorageSave'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        ok: (_data.ok)
                    };
                });
            });
        };
        this.userStorageDelete = function (args, headers) {
            return _this.fetch(_this.url('UserStorageDelete'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        ok: (_data.ok)
                    };
                });
            });
        };
        this.userStorageFetchAll = function (args, headers) {
            return _this.fetch(_this.url('UserStorageFetchAll'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        objects: (_data.objects)
                    };
                });
            });
        };
        this.getFeed = function (args, headers) {
            return _this.fetch(_this.url('GetFeed'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        page: (_data.page),
                        res: (_data.res)
                    };
                });
            });
        };
        this.getItemSummary = function (args, headers) {
            return _this.fetch(_this.url('GetItemSummary'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        summary: (_data.summary)
                    };
                });
            });
        };
        this.getItemSupply = function (args, headers) {
            return _this.fetch(_this.url('GetItemSupply'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        summary: (_data.summary)
                    };
                });
            });
        };
        this.getBatchItemSupply = function (args, headers) {
            return _this.fetch(_this.url('GetBatchItemSupply'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        summary: (_data.summary)
                    };
                });
            });
        };
        this.getItemSuppliesByType = function (args, headers) {
            return _this.fetch(_this.url('GetItemSuppliesByType'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        summary: (_data.summary)
                    };
                });
            });
        };
        this.getItemOwnershipByType = function (args, headers) {
            return _this.fetch(_this.url('GetItemOwnershipByType'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        items: (_data.items)
                    };
                });
            });
        };
        this.markItemsNotNew = function (args, headers) {
            return _this.fetch(_this.url('MarkItemsNotNew'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        ok: (_data.ok)
                    };
                });
            });
        };
        this.getCardLibrary = function (args, headers) {
            return _this.fetch(_this.url('GetCardLibrary'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        cards: (_data.cards)
                    };
                });
            });
        };
        this.getCardsByID = function (args, headers) {
            return _this.fetch(_this.url('GetCardsByID'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        cards: (_data.cards)
                    };
                });
            });
        };
        this.getCardsByDeckString = function (args, headers) {
            return _this.fetch(_this.url('GetCardsByDeckString'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        cards: (_data.cards)
                    };
                });
            });
        };
        this.searchCards = function (args, headers) {
            return _this.fetch(_this.url('SearchCards'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        page: (_data.page),
                        res: (_data.res)
                    };
                });
            });
        };
        this.getCardOwnership = function (args, headers) {
            return _this.fetch(_this.url('GetCardOwnership'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        res: (_data.res)
                    };
                });
            });
        };
        this.getPendingCards = function (headers) {
            return _this.fetch(_this.url('GetPendingCards'), createHTTPRequest({}, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        res: (_data.res)
                    };
                });
            });
        };
        this.listDecks = function (args, headers) {
            return _this.fetch(_this.url('ListDecks'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        page: (_data.page),
                        res: (_data.res)
                    };
                });
            });
        };
        this.searchDecks = function (args, headers) {
            return _this.fetch(_this.url('SearchDecks'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        page: (_data.page),
                        res: (_data.res)
                    };
                });
            });
        };
        this.createDeck = function (args, headers) {
            return _this.fetch(_this.url('CreateDeck'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        res: (_data.res)
                    };
                });
            });
        };
        this.updateDeck = function (args, headers) {
            return _this.fetch(_this.url('UpdateDeck'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        res: (_data.res)
                    };
                });
            });
        };
        this.favoriteDeck = function (args, headers) {
            return _this.fetch(_this.url('FavoriteDeck'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        ok: (_data.ok)
                    };
                });
            });
        };
        this.unfavoriteDeck = function (args, headers) {
            return _this.fetch(_this.url('UnfavoriteDeck'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        ok: (_data.ok)
                    };
                });
            });
        };
        this.toggleDeckFavorite = function (args, headers) {
            return _this.fetch(_this.url('ToggleDeckFavorite'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        isFavorite: (_data.isFavorite)
                    };
                });
            });
        };
        this.getDeck = function (args, headers) {
            return _this.fetch(_this.url('GetDeck'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        res: (_data.res)
                    };
                });
            });
        };
        this.checkDeck = function (args, headers) {
            return _this.fetch(_this.url('CheckDeck'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        res: (_data.res)
                    };
                });
            });
        };
        this.deleteDeck = function (args, headers) {
            return _this.fetch(_this.url('DeleteDeck'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        ok: (_data.ok)
                    };
                });
            });
        };
        this.searchDeckRanks = function (args, headers) {
            return _this.fetch(_this.url('SearchDeckRanks'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        page: (_data.page),
                        res: (_data.res)
                    };
                });
            });
        };
        this.listDeckRanks = function (args, headers) {
            return _this.fetch(_this.url('ListDeckRanks'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        page: (_data.page),
                        res: (_data.res)
                    };
                });
            });
        };
        this.markDeckNotNew = function (args, headers) {
            return _this.fetch(_this.url('MarkDeckNotNew'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        ok: (_data.ok)
                    };
                });
            });
        };
        this.listLeaderboard = function (args, headers) {
            return _this.fetch(_this.url('ListLeaderboard'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        page: (_data.page),
                        res: (_data.res)
                    };
                });
            });
        };
        this.listMatches = function (args, headers) {
            return _this.fetch(_this.url('ListMatches'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        page: (_data.page),
                        res: (_data.res)
                    };
                });
            });
        };
        this.getMatch = function (args, headers) {
            return _this.fetch(_this.url('GetMatch'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        match: (_data.match)
                    };
                });
            });
        };
        this.getCurrentSeason = function (headers) {
            return _this.fetch(_this.url('GetCurrentSeason'), createHTTPRequest({}, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        res: (_data.res)
                    };
                });
            });
        };
        this.getNextRewardsTime = function (headers) {
            return _this.fetch(_this.url('GetNextRewardsTime'), createHTTPRequest({}, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        res: (_data.res)
                    };
                });
            });
        };
        this.getNextSeasonTime = function (headers) {
            return _this.fetch(_this.url('GetNextSeasonTime'), createHTTPRequest({}, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        res: (_data.res)
                    };
                });
            });
        };
        this.getCurrentSeasonStartTime = function (headers) {
            return _this.fetch(_this.url('GetCurrentSeasonStartTime'), createHTTPRequest({}, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        res: (_data.res)
                    };
                });
            });
        };
        this.accountLeaderboard = function (args, headers) {
            return _this.fetch(_this.url('AccountLeaderboard'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        page: (_data.page),
                        res: (_data.res)
                    };
                });
            });
        };
        this.getMatchArchiveRecordsURI = function (args, headers) {
            return _this.fetch(_this.url('GetMatchArchiveRecordsURI'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        ok: (_data.ok),
                        match: (_data.match),
                        archiveIndexURI: (_data.archiveIndexURI),
                        recordURIs: (_data.recordURIs)
                    };
                });
            });
        };
        this.getMatchLiveRecordsURI = function (args, headers) {
            return _this.fetch(_this.url('GetMatchLiveRecordsURI'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        ok: (_data.ok),
                        match: (_data.match),
                        liveIndexURI: (_data.liveIndexURI)
                    };
                });
            });
        };
        this.botMatchEnd = function (args, headers) {
            return _this.fetch(_this.url('BotMatchEnd'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        rewards: (_data.rewards)
                    };
                });
            });
        };
        this.internalMatchStart = function (args, headers) {
            return _this.fetch(_this.url('InternalMatchStart'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        matchID: (_data.matchID),
                        replayID: (_data.replayID)
                    };
                });
            });
        };
        this.internalMatchEnd = function (args, headers) {
            return _this.fetch(_this.url('InternalMatchEnd'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        rewards: (_data.rewards)
                    };
                });
            });
        };
        this.internalAppendMatchArchiveRecords = function (args, headers) {
            return _this.fetch(_this.url('InternalAppendMatchArchiveRecords'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        status: (_data.status),
                        uri: (_data.uri)
                    };
                });
            });
        };
        this.internalAppendMatchLiveRecords = function (args, headers) {
            return _this.fetch(_this.url('InternalAppendMatchLiveRecords'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        status: (_data.status),
                        uri: (_data.uri)
                    };
                });
            });
        };
        this.internalConquestStatus = function (args, headers) {
            return _this.fetch(_this.url('InternalConquestStatus'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        conquest: (_data.conquest)
                    };
                });
            });
        };
        this.internalGetAccount = function (args, headers) {
            return _this.fetch(_this.url('InternalGetAccount'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        account: (_data.account)
                    };
                });
            });
        };
        this.internalGetPrivateSpectateCode = function (args, headers) {
            return _this.fetch(_this.url('InternalGetPrivateSpectateCode'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        code: (_data.code)
                    };
                });
            });
        };
        this.enterConquest = function (args, headers) {
            return _this.fetch(_this.url('EnterConquest'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        status: (_data.status)
                    };
                });
            });
        };
        this.conquestStatus = function (headers) {
            return _this.fetch(_this.url('ConquestStatus'), createHTTPRequest({}, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        conquest: (_data.conquest)
                    };
                });
            });
        };
        this.conquestStats = function (headers) {
            return _this.fetch(_this.url('ConquestStats'), createHTTPRequest({}, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        stats: (_data.stats)
                    };
                });
            });
        };
        this.conquestRewards = function (headers) {
            return _this.fetch(_this.url('ConquestRewards'), createHTTPRequest({}, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        weeklyGolds: (_data.weeklyGolds)
                    };
                });
            });
        };
        this.conquestPoints = function (headers) {
            return _this.fetch(_this.url('ConquestPoints'), createHTTPRequest({}, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        points: (_data.points),
                        nedeed: (_data.nedeed)
                    };
                });
            });
        };
        this.conquestV2Pool = function (headers) {
            return _this.fetch(_this.url('ConquestV2Pool'), createHTTPRequest({}, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        pool: (_data.pool)
                    };
                });
            });
        };
        this.conquestV2Progress = function (headers) {
            return _this.fetch(_this.url('ConquestV2Progress'), createHTTPRequest({}, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        progress: (_data.progress)
                    };
                });
            });
        };
        this.listSkypassRewards = function (args, headers) {
            return _this.fetch(_this.url('ListSkypassRewards'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        res: (_data.res)
                    };
                });
            });
        };
        this.claimSkypassRewards = function (args, headers) {
            return _this.fetch(_this.url('ClaimSkypassRewards'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        status: (_data.status)
                    };
                });
            });
        };
        this.iAPVerifyGoogleProducts = function (args, headers) {
            return _this.fetch(_this.url('IAPVerifyGoogleProducts'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        productPurchase: (_data.productPurchase)
                    };
                });
            });
        };
        this.iAPVerifyAppleProducts = function (args, headers) {
            return _this.fetch(_this.url('IAPVerifyAppleProducts'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        applePurchase: (_data.applePurchase)
                    };
                });
            });
        };
        this.iAPVerifyGoogleProducts2 = function (args, headers) {
            return _this.fetch(_this.url('IAPVerifyGoogleProducts2'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        productPurchase: (_data.productPurchase)
                    };
                });
            });
        };
        this.iAPVerifyAppleProducts2 = function (args, headers) {
            return _this.fetch(_this.url('IAPVerifyAppleProducts2'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        applePurchase: (_data.applePurchase)
                    };
                });
            });
        };
        this.joinEarlyAccessList = function (args, headers) {
            return _this.fetch(_this.url('JoinEarlyAccessList'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        status: (_data.status),
                        serviceError: (_data.serviceError)
                    };
                });
            });
        };
        this.recordGameClientFeedback = function (args, headers) {
            return _this.fetch(_this.url('RecordGameClientFeedback'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        status: (_data.status)
                    };
                });
            });
        };
        this.heroUnlockLevels = function (headers) {
            return _this.fetch(_this.url('HeroUnlockLevels'), createHTTPRequest({}, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        res: (_data.res)
                    };
                });
            });
        };
        this.deckClassUnlockLevels = function (headers) {
            return _this.fetch(_this.url('DeckClassUnlockLevels'), createHTTPRequest({}, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        res: (_data.res)
                    };
                });
            });
        };
        this.availableXPBonuses = function (headers) {
            return _this.fetch(_this.url('AvailableXPBonuses'), createHTTPRequest({}, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        res: (_data.res)
                    };
                });
            });
        };
        this.reportAccount = function (args, headers) {
            return _this.fetch(_this.url('ReportAccount'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        ok: (_data.ok)
                    };
                });
            });
        };
        this.saveCookiePolicy = function (args, headers) {
            return _this.fetch(_this.url('SaveCookiePolicy'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        status: (_data.status)
                    };
                });
            });
        };
        this.getCookiePolicy = function (headers) {
            return _this.fetch(_this.url('GetCookiePolicy'), createHTTPRequest({}, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        res: (_data.res)
                    };
                });
            });
        };
        this.getDiscordInfo = function (headers) {
            return _this.fetch(_this.url('GetDiscordInfo'), createHTTPRequest({}, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        data: (_data.data)
                    };
                });
            });
        };
        this.getTwitchInfo = function (headers) {
            return _this.fetch(_this.url('GetTwitchInfo'), createHTTPRequest({}, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        data: (_data.data)
                    };
                });
            });
        };
        this.getFeaturedStreamers = function (headers) {
            return _this.fetch(_this.url('GetFeaturedStreamers'), createHTTPRequest({}, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        streamers: (_data.streamers)
                    };
                });
            });
        };
        this.gMAddFeaturedStreamer = function (args, headers) {
            return _this.fetch(_this.url('GMAddFeaturedStreamer'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        status: (_data.status)
                    };
                });
            });
        };
        this.gMRemoveFeaturedStreamer = function (args, headers) {
            return _this.fetch(_this.url('GMRemoveFeaturedStreamer'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        status: (_data.status)
                    };
                });
            });
        };
        this.getBanners = function (headers) {
            return _this.fetch(_this.url('GetBanners'), createHTTPRequest({}, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        banners: (_data.banners)
                    };
                });
            });
        };
        this.gMListBanners = function (headers) {
            return _this.fetch(_this.url('GMListBanners'), createHTTPRequest({}, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        banners: (_data.banners)
                    };
                });
            });
        };
        this.gMAddBanner = function (args, headers) {
            return _this.fetch(_this.url('GMAddBanner'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        status: (_data.status)
                    };
                });
            });
        };
        this.gMModifyBanner = function (args, headers) {
            return _this.fetch(_this.url('GMModifyBanner'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        status: (_data.status)
                    };
                });
            });
        };
        this.gMRemoveBanner = function (args, headers) {
            return _this.fetch(_this.url('GMRemoveBanner'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        status: (_data.status)
                    };
                });
            });
        };
        this.getGameModesStatus = function (headers) {
            return _this.fetch(_this.url('GetGameModesStatus'), createHTTPRequest({}, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        status: (_data.status)
                    };
                });
            });
        };
        this.adminListAccounts = function (args, headers) {
            return _this.fetch(_this.url('AdminListAccounts'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        page: (_data.page),
                        accounts: (_data.accounts)
                    };
                });
            });
        };
        this.adminSearchAccounts = function (args, headers) {
            return _this.fetch(_this.url('AdminSearchAccounts'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        page: (_data.page),
                        accounts: (_data.accounts)
                    };
                });
            });
        };
        this.gMFindAccount = function (args, headers) {
            return _this.fetch(_this.url('GMFindAccount'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        account: (_data.account)
                    };
                });
            });
        };
        this.gMRenameAccount = function (args, headers) {
            return _this.fetch(_this.url('GMRenameAccount'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        account: (_data.account)
                    };
                });
            });
        };
        this.gMUnlockAllBaseCards = function (args, headers) {
            return _this.fetch(_this.url('GMUnlockAllBaseCards'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        ok: (_data.ok)
                    };
                });
            });
        };
        this.gMGiveLevels = function (args, headers) {
            return _this.fetch(_this.url('GMGiveLevels'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        ok: (_data.ok)
                    };
                });
            });
        };
        this.gMSetRP = function (args, headers) {
            return _this.fetch(_this.url('GMSetRP'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        ok: (_data.ok)
                    };
                });
            });
        };
        this.gMSetWarmupGamesCompleted = function (args, headers) {
            return _this.fetch(_this.url('GMSetWarmupGamesCompleted'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        ok: (_data.ok)
                    };
                });
            });
        };
        this.gMListAccountActions = function (args, headers) {
            return _this.fetch(_this.url('GMListAccountActions'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        page: (_data.page),
                        accountActions: (_data.accountActions)
                    };
                });
            });
        };
        this.gMCreateAccountAction = function (args, headers) {
            return _this.fetch(_this.url('GMCreateAccountAction'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        action: (_data.action)
                    };
                });
            });
        };
        this.gMIsAccountBanned = function (args, headers) {
            return _this.fetch(_this.url('GMIsAccountBanned'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        banned: (_data.banned),
                        status: (_data.status),
                        accountActions: (_data.accountActions)
                    };
                });
            });
        };
        this.gMListAccountSignals = function (args, headers) {
            return _this.fetch(_this.url('GMListAccountSignals'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        signal: (_data.signal)
                    };
                });
            });
        };
        this.gMAccountSignalSummaries = function (args, headers) {
            return _this.fetch(_this.url('GMAccountSignalSummaries'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        page: (_data.page),
                        signals: (_data.signals)
                    };
                });
            });
        };
        this.gMListAccounts = function (args, headers) {
            return _this.fetch(_this.url('GMListAccounts'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        page: (_data.page),
                        accounts: (_data.accounts)
                    };
                });
            });
        };
        this.gMListMatches = function (args, headers) {
            return _this.fetch(_this.url('GMListMatches'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        page: (_data.page),
                        res: (_data.res)
                    };
                });
            });
        };
        this.gMSetReviewed = function (args, headers) {
            return _this.fetch(_this.url('GMSetReviewed'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        ok: (_data.ok)
                    };
                });
            });
        };
        this.gMListPendingCards = function (args, headers) {
            return _this.fetch(_this.url('GMListPendingCards'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        page: (_data.page),
                        response: (_data.response)
                    };
                });
            });
        };
        this.gMStats = function (headers) {
            return _this.fetch(_this.url('GMStats'), createHTTPRequest({}, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        stats: (_data.stats)
                    };
                });
            });
        };
        this.gMGameModeSet = function (args, headers) {
            return _this.fetch(_this.url('GMGameModeSet'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        ok: (_data.ok)
                    };
                });
            });
        };
        this.gMGameModeStatusHistory = function (args, headers) {
            return _this.fetch(_this.url('GMGameModeStatusHistory'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        page: (_data.page),
                        statusHistory: (_data.statusHistory)
                    };
                });
            });
        };
        this.gMSetConquestV2PoolConfig = function (args, headers) {
            return _this.fetch(_this.url('GMSetConquestV2PoolConfig'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        ok: (_data.ok)
                    };
                });
            });
        };
        this.gMGetConquestV2PoolConfig = function (headers) {
            return _this.fetch(_this.url('GMGetConquestV2PoolConfig'), createHTTPRequest({}, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        config: (_data.config)
                    };
                });
            });
        };
        this.gMGetConquestV2Summary = function (headers) {
            return _this.fetch(_this.url('GMGetConquestV2Summary'), createHTTPRequest({}, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        summary: (_data.summary)
                    };
                });
            });
        };
        this.gMListConquestV2AccountTreasureProgress = function (args, headers) {
            return _this.fetch(_this.url('GMListConquestV2AccountTreasureProgress'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        page: (_data.page),
                        data: (_data.data)
                    };
                });
            });
        };
        this.gMAppDevKeyCreate = function (args, headers) {
            return _this.fetch(_this.url('GMAppDevKeyCreate'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        appDevKey: (_data.appDevKey)
                    };
                });
            });
        };
        this.gMAppDevKeyFind = function (args, headers) {
            return _this.fetch(_this.url('GMAppDevKeyFind'), createHTTPRequest(args, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        appDevKey: (_data.appDevKey),
                        jwtToken: (_data.jwtToken)
                    };
                });
            });
        };
        this.ping = function (headers) {
            return _this.fetch(_this.url('Ping'), createHTTPRequest({}, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        status: (_data.status)
                    };
                });
            });
        };
        this.version = function (headers) {
            return _this.fetch(_this.url('Version'), createHTTPRequest({}, headers)).then(function (res) {
                return buildResponse(res).then(function (_data) {
                    return {
                        version: (_data.version)
                    };
                });
            });
        };
        this.hostname = hostname;
        this.fetch = fetch;
    }
    SkyWeaverAPI.prototype.url = function (name) {
        return this.hostname + this.path + name;
    };
    return SkyWeaverAPI;
}());
exports.SkyWeaverAPI = SkyWeaverAPI;
var createHTTPRequest = function (body, headers) {
    if (body === void 0) { body = {}; }
    if (headers === void 0) { headers = {}; }
    return {
        method: 'POST',
        headers: __assign(__assign({}, headers), { 'Content-Type': 'application/json' }),
        body: JSON.stringify(body || {})
    };
};
var buildResponse = function (res) {
    return res.text().then(function (text) {
        var data;
        try {
            data = JSON.parse(text);
        }
        catch (err) {
            throw { code: 'unknown', msg: "expecting JSON, got: ".concat(text), status: res.status };
        }
        if (!res.ok) {
            throw data; // webrpc error response
        }
        return data;
    });
};
