// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/payments (interfaces: AppleAppStoreVerifier)
//
// Generated by this command:
//
//	mockgen -destination ./mock/apple_app_store_verifier.go -package mock . AppleAppStoreVerifier
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	appleappstore "github.com/horizon-games/OpenSky/api/lib/payments/appleappstore"
	gomock "go.uber.org/mock/gomock"
)

// MockAppleAppStoreVerifier is a mock of AppleAppStoreVerifier interface.
type MockAppleAppStoreVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockAppleAppStoreVerifierMockRecorder
	isgomock struct{}
}

// MockAppleAppStoreVerifierMockRecorder is the mock recorder for MockAppleAppStoreVerifier.
type MockAppleAppStoreVerifierMockRecorder struct {
	mock *MockAppleAppStoreVerifier
}

// NewMockAppleAppStoreVerifier creates a new mock instance.
func NewMockAppleAppStoreVerifier(ctrl *gomock.Controller) *MockAppleAppStoreVerifier {
	mock := &MockAppleAppStoreVerifier{ctrl: ctrl}
	mock.recorder = &MockAppleAppStoreVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppleAppStoreVerifier) EXPECT() *MockAppleAppStoreVerifierMockRecorder {
	return m.recorder
}

// Verify mocks base method.
func (m *MockAppleAppStoreVerifier) Verify(ctx context.Context, receiptData string) (*appleappstore.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, receiptData)
	ret0, _ := ret[0].(*appleappstore.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockAppleAppStoreVerifierMockRecorder) Verify(ctx, receiptData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockAppleAppStoreVerifier)(nil).Verify), ctx, receiptData)
}
