// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/payments (interfaces: ContractUSDC)
//
// Generated by this command:
//
//	mockgen -destination ./mock/contract_usdc.go -package mock . ContractUSDC
//

// Package mock is a generated GoMock package.
package mock

import (
	big "math/big"
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockContractUSDC is a mock of ContractUSDC interface.
type MockContractUSDC struct {
	ctrl     *gomock.Controller
	recorder *MockContractUSDCMockRecorder
	isgomock struct{}
}

// MockContractUSDCMockRecorder is the mock recorder for MockContractUSDC.
type MockContractUSDCMockRecorder struct {
	mock *MockContractUSDC
}

// NewMockContractUSDC creates a new mock instance.
func NewMockContractUSDC(ctrl *gomock.Controller) *MockContractUSDC {
	mock := &MockContractUSDC{ctrl: ctrl}
	mock.recorder = &MockContractUSDCMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContractUSDC) EXPECT() *MockContractUSDCMockRecorder {
	return m.recorder
}

// Address mocks base method.
func (m *MockContractUSDC) Address() proto.Hash {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Address")
	ret0, _ := ret[0].(proto.Hash)
	return ret0
}

// Address indicates an expected call of Address.
func (mr *MockContractUSDCMockRecorder) Address() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Address", reflect.TypeOf((*MockContractUSDC)(nil).Address))
}

// ComposeApprove mocks base method.
func (m *MockContractUSDC) ComposeApprove(spender proto.Hash, value *big.Int) (*proto.OnChainTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComposeApprove", spender, value)
	ret0, _ := ret[0].(*proto.OnChainTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ComposeApprove indicates an expected call of ComposeApprove.
func (mr *MockContractUSDCMockRecorder) ComposeApprove(spender, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComposeApprove", reflect.TypeOf((*MockContractUSDC)(nil).ComposeApprove), spender, value)
}
