// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/payments (interfaces: ContractPaymentProxy)
//
// Generated by this command:
//
//	mockgen -destination ./mock/contract_payment_proxy.go -package mock . ContractPaymentProxy
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	big "math/big"
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockContractPaymentProxy is a mock of ContractPaymentProxy interface.
type MockContractPaymentProxy struct {
	ctrl     *gomock.Controller
	recorder *MockContractPaymentProxyMockRecorder
	isgomock struct{}
}

// MockContractPaymentProxyMockRecorder is the mock recorder for MockContractPaymentProxy.
type MockContractPaymentProxyMockRecorder struct {
	mock *MockContractPaymentProxy
}

// NewMockContractPaymentProxy creates a new mock instance.
func NewMockContractPaymentProxy(ctrl *gomock.Controller) *MockContractPaymentProxy {
	mock := &MockContractPaymentProxy{ctrl: ctrl}
	mock.recorder = &MockContractPaymentProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContractPaymentProxy) EXPECT() *MockContractPaymentProxyMockRecorder {
	return m.recorder
}

// Address mocks base method.
func (m *MockContractPaymentProxy) Address() proto.Hash {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Address")
	ret0, _ := ret[0].(proto.Hash)
	return ret0
}

// Address indicates an expected call of Address.
func (mr *MockContractPaymentProxyMockRecorder) Address() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Address", reflect.TypeOf((*MockContractPaymentProxy)(nil).Address))
}

// CallNonces mocks base method.
func (m *MockContractPaymentProxy) CallNonces(ctx context.Context, address proto.Hash) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CallNonces", ctx, address)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CallNonces indicates an expected call of CallNonces.
func (mr *MockContractPaymentProxyMockRecorder) CallNonces(ctx, address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallNonces", reflect.TypeOf((*MockContractPaymentProxy)(nil).CallNonces), ctx, address)
}

// ComposePurchaseItems mocks base method.
func (m *MockContractPaymentProxy) ComposePurchaseItems(currencyAddress proto.Hash, currencyAmount, nonce *big.Int, itemIDsPurchased []uint64, recipient proto.Hash) (*proto.OnChainTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComposePurchaseItems", currencyAddress, currencyAmount, nonce, itemIDsPurchased, recipient)
	ret0, _ := ret[0].(*proto.OnChainTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ComposePurchaseItems indicates an expected call of ComposePurchaseItems.
func (mr *MockContractPaymentProxyMockRecorder) ComposePurchaseItems(currencyAddress, currencyAmount, nonce, itemIDsPurchased, recipient any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComposePurchaseItems", reflect.TypeOf((*MockContractPaymentProxy)(nil).ComposePurchaseItems), currencyAddress, currencyAmount, nonce, itemIDsPurchased, recipient)
}

// EncodeBurnOrderData mocks base method.
func (m *MockContractPaymentProxy) EncodeBurnOrderData(itemRecipient proto.Hash, nonce *big.Int, itemIDsPurchased []uint64) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncodeBurnOrderData", itemRecipient, nonce, itemIDsPurchased)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncodeBurnOrderData indicates an expected call of EncodeBurnOrderData.
func (mr *MockContractPaymentProxyMockRecorder) EncodeBurnOrderData(itemRecipient, nonce, itemIDsPurchased any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncodeBurnOrderData", reflect.TypeOf((*MockContractPaymentProxy)(nil).EncodeBurnOrderData), itemRecipient, nonce, itemIDsPurchased)
}
