// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/payments (interfaces: ContractOpenSkyAssets)
//
// Generated by this command:
//
//	mockgen -destination ./mock/contract_opensky_assets.go -package mock . ContractOpenSkyAssets
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockContractOpenSkyAssets is a mock of ContractOpenSkyAssets interface.
type MockContractOpenSkyAssets struct {
	ctrl     *gomock.Controller
	recorder *MockContractOpenSkyAssetsMockRecorder
	isgomock struct{}
}

// MockContractOpenSkyAssetsMockRecorder is the mock recorder for MockContractOpenSkyAssets.
type MockContractOpenSkyAssetsMockRecorder struct {
	mock *MockContractOpenSkyAssets
}

// NewMockContractOpenSkyAssets creates a new mock instance.
func NewMockContractOpenSkyAssets(ctrl *gomock.Controller) *MockContractOpenSkyAssets {
	mock := &MockContractOpenSkyAssets{ctrl: ctrl}
	mock.recorder = &MockContractOpenSkyAssetsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContractOpenSkyAssets) EXPECT() *MockContractOpenSkyAssetsMockRecorder {
	return m.recorder
}

// ComposeSafeBatchTransferFrom mocks base method.
func (m *MockContractOpenSkyAssets) ComposeSafeBatchTransferFrom(from, to proto.Hash, tokens map[uint64]uint64, data []byte) (*proto.OnChainTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComposeSafeBatchTransferFrom", from, to, tokens, data)
	ret0, _ := ret[0].(*proto.OnChainTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ComposeSafeBatchTransferFrom indicates an expected call of ComposeSafeBatchTransferFrom.
func (mr *MockContractOpenSkyAssetsMockRecorder) ComposeSafeBatchTransferFrom(from, to, tokens, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComposeSafeBatchTransferFrom", reflect.TypeOf((*MockContractOpenSkyAssets)(nil).ComposeSafeBatchTransferFrom), from, to, tokens, data)
}
