// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/payments (interfaces: GooglePlayVerifier)
//
// Generated by this command:
//
//	mockgen -destination ./mock/google_play_verifier.go -package mock . GooglePlayVerifier
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	androidpublisher "google.golang.org/api/androidpublisher/v3"
)

// MockGooglePlayVerifier is a mock of GooglePlayVerifier interface.
type MockGooglePlayVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockGooglePlayVerifierMockRecorder
	isgomock struct{}
}

// MockGooglePlayVerifierMockRecorder is the mock recorder for MockGooglePlayVerifier.
type MockGooglePlayVerifierMockRecorder struct {
	mock *MockGooglePlayVerifier
}

// NewMockGooglePlayVerifier creates a new mock instance.
func NewMockGooglePlayVerifier(ctrl *gomock.Controller) *MockGooglePlayVerifier {
	mock := &MockGooglePlayVerifier{ctrl: ctrl}
	mock.recorder = &MockGooglePlayVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGooglePlayVerifier) EXPECT() *MockGooglePlayVerifierMockRecorder {
	return m.recorder
}

// Verify mocks base method.
func (m *MockGooglePlayVerifier) Verify(ctx context.Context, packageName, productID, token string) (*androidpublisher.ProductPurchase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, packageName, productID, token)
	ret0, _ := ret[0].(*androidpublisher.ProductPurchase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockGooglePlayVerifierMockRecorder) Verify(ctx, packageName, productID, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockGooglePlayVerifier)(nil).Verify), ctx, packageName, productID, token)
}
