// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/payments (interfaces: ItemTokenGetter)
//
// Generated by this command:
//
//	mockgen -destination ./mock/item_token_getter.go -package mock . ItemTokenGetter
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockItemTokenGetter is a mock of ItemTokenGetter interface.
type MockItemTokenGetter struct {
	ctrl     *gomock.Controller
	recorder *MockItemTokenGetterMockRecorder
	isgomock struct{}
}

// MockItemTokenGetterMockRecorder is the mock recorder for MockItemTokenGetter.
type MockItemTokenGetterMockRecorder struct {
	mock *MockItemTokenGetter
}

// NewMockItemTokenGetter creates a new mock instance.
func NewMockItemTokenGetter(ctrl *gomock.Controller) *MockItemTokenGetter {
	mock := &MockItemTokenGetter{ctrl: ctrl}
	mock.recorder = &MockItemTokenGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockItemTokenGetter) EXPECT() *MockItemTokenGetterMockRecorder {
	return m.recorder
}

// GetToken mocks base method.
func (m *MockItemTokenGetter) GetToken(arg0 proto.ItemType) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToken", arg0)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetToken indicates an expected call of GetToken.
func (mr *MockItemTokenGetterMockRecorder) GetToken(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToken", reflect.TypeOf((*MockItemTokenGetter)(nil).GetToken), arg0)
}
