// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/payments (interfaces: ItemGainer)
//
// Generated by this command:
//
//	mockgen -destination ./mock/item_gainer.go -package mock . ItemGainer
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	data "github.com/horizon-games/OpenSky/api/data"
	db "github.com/upper/db/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockItemGainer is a mock of ItemGainer interface.
type MockItemGainer struct {
	ctrl     *gomock.Controller
	recorder *MockItemGainerMockRecorder
	isgomock struct{}
}

// MockItemGainerMockRecorder is the mock recorder for MockItemGainer.
type MockItemGainerMockRecorder struct {
	mock *MockItemGainer
}

// NewMockItemGainer creates a new mock instance.
func NewMockItemGainer(ctrl *gomock.Controller) *MockItemGainer {
	mock := &MockItemGainer{ctrl: ctrl}
	mock.recorder = &MockItemGainerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockItemGainer) EXPECT() *MockItemGainerMockRecorder {
	return m.recorder
}

// Gain mocks base method.
func (m *MockItemGainer) Gain(sess db.Session, payment *data.Payment, tokenID uint64, amount int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Gain", sess, payment, tokenID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// Gain indicates an expected call of Gain.
func (mr *MockItemGainerMockRecorder) Gain(sess, payment, tokenID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gain", reflect.TypeOf((*MockItemGainer)(nil).Gain), sess, payment, tokenID, amount)
}
