// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/payments (interfaces: MetricsCollector)
//
// Generated by this command:
//
//	mockgen -destination ./mock/metrics_collector.go -package mock . MetricsCollector
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockMetricsCollector is a mock of MetricsCollector interface.
type MockMetricsCollector struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsCollectorMockRecorder
	isgomock struct{}
}

// MockMetricsCollectorMockRecorder is the mock recorder for MockMetricsCollector.
type MockMetricsCollectorMockRecorder struct {
	mock *MockMetricsCollector
}

// NewMockMetricsCollector creates a new mock instance.
func NewMockMetricsCollector(ctrl *gomock.Controller) *MockMetricsCollector {
	mock := &MockMetricsCollector{ctrl: ctrl}
	mock.recorder = &MockMetricsCollectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsCollector) EXPECT() *MockMetricsCollectorMockRecorder {
	return m.recorder
}

// TrackPayment mocks base method.
func (m *MockMetricsCollector) TrackPayment(provider proto.PaymentProvider, status proto.PaymentStatus, productCode string, quantity uint64, paidIn proto.ItemType) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackPayment", provider, status, productCode, quantity, paidIn)
}

// TrackPayment indicates an expected call of TrackPayment.
func (mr *MockMetricsCollectorMockRecorder) TrackPayment(provider, status, productCode, quantity, paidIn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackPayment", reflect.TypeOf((*MockMetricsCollector)(nil).TrackPayment), provider, status, productCode, quantity, paidIn)
}
