// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/payments (interfaces: ProductConverter)
//
// Generated by this command:
//
//	mockgen -destination ./mock/product_converter.go -package mock . ProductConverter
//

// Package mock is a generated GoMock package.
package mock

import (
	big "math/big"
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockProductConverter is a mock of ProductConverter interface.
type MockProductConverter struct {
	ctrl     *gomock.Controller
	recorder *MockProductConverterMockRecorder
	isgomock struct{}
}

// MockProductConverterMockRecorder is the mock recorder for MockProductConverter.
type MockProductConverterMockRecorder struct {
	mock *MockProductConverter
}

// NewMockProductConverter creates a new mock instance.
func NewMockProductConverter(ctrl *gomock.Controller) *MockProductConverter {
	mock := &MockProductConverter{ctrl: ctrl}
	mock.recorder = &MockProductConverterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductConverter) EXPECT() *MockProductConverterMockRecorder {
	return m.recorder
}

// ToAmount mocks base method.
func (m *MockProductConverter) ToAmount(targetProduct string) int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToAmount", targetProduct)
	ret0, _ := ret[0].(int64)
	return ret0
}

// ToAmount indicates an expected call of ToAmount.
func (mr *MockProductConverterMockRecorder) ToAmount(targetProduct any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToAmount", reflect.TypeOf((*MockProductConverter)(nil).ToAmount), targetProduct)
}

// ToItemType mocks base method.
func (m *MockProductConverter) ToItemType(provider proto.PaymentProvider, targetProduct string) (*proto.ItemType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToItemType", provider, targetProduct)
	ret0, _ := ret[0].(*proto.ItemType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToItemType indicates an expected call of ToItemType.
func (mr *MockProductConverterMockRecorder) ToItemType(provider, targetProduct any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToItemType", reflect.TypeOf((*MockProductConverter)(nil).ToItemType), provider, targetProduct)
}

// ToPrice mocks base method.
func (m *MockProductConverter) ToPrice(provider proto.PaymentProvider, targetProduct string, priceItemType proto.ItemType) (*big.Float, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToPrice", provider, targetProduct, priceItemType)
	ret0, _ := ret[0].(*big.Float)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToPrice indicates an expected call of ToPrice.
func (mr *MockProductConverterMockRecorder) ToPrice(provider, targetProduct, priceItemType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToPrice", reflect.TypeOf((*MockProductConverter)(nil).ToPrice), provider, targetProduct, priceItemType)
}

// ToProductID mocks base method.
func (m *MockProductConverter) ToProductID(provider proto.PaymentProvider, itemType *proto.ItemType, amount int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToProductID", provider, itemType, amount)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToProductID indicates an expected call of ToProductID.
func (mr *MockProductConverterMockRecorder) ToProductID(provider, itemType, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToProductID", reflect.TypeOf((*MockProductConverter)(nil).ToProductID), provider, itemType, amount)
}
