// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/payments (interfaces: SamsungGalaxyStoreVerifier)
//
// Generated by this command:
//
//	mockgen -destination ./mock/samsung_galaxy_store_verifier.go -package mock . SamsungGalaxyStoreVerifier
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	samsunggalaxystore "github.com/horizon-games/OpenSky/api/lib/payments/samsunggalaxystore"
	gomock "go.uber.org/mock/gomock"
)

// MockSamsungGalaxyStoreVerifier is a mock of SamsungGalaxyStoreVerifier interface.
type MockSamsungGalaxyStoreVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockSamsungGalaxyStoreVerifierMockRecorder
	isgomock struct{}
}

// MockSamsungGalaxyStoreVerifierMockRecorder is the mock recorder for MockSamsungGalaxyStoreVerifier.
type MockSamsungGalaxyStoreVerifierMockRecorder struct {
	mock *MockSamsungGalaxyStoreVerifier
}

// NewMockSamsungGalaxyStoreVerifier creates a new mock instance.
func NewMockSamsungGalaxyStoreVerifier(ctrl *gomock.Controller) *MockSamsungGalaxyStoreVerifier {
	mock := &MockSamsungGalaxyStoreVerifier{ctrl: ctrl}
	mock.recorder = &MockSamsungGalaxyStoreVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSamsungGalaxyStoreVerifier) EXPECT() *MockSamsungGalaxyStoreVerifierMockRecorder {
	return m.recorder
}

// Verify mocks base method.
func (m *MockSamsungGalaxyStoreVerifier) Verify(ctx context.Context, purchaseID string) (*samsunggalaxystore.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, purchaseID)
	ret0, _ := ret[0].(*samsunggalaxystore.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockSamsungGalaxyStoreVerifierMockRecorder) Verify(ctx, purchaseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockSamsungGalaxyStoreVerifier)(nil).Verify), ctx, purchaseID)
}
