// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/payments (interfaces: StripeEventGetter)
//
// Generated by this command:
//
//	mockgen -destination ./mock/stripe_event_getter.go -package mock . StripeEventGetter
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	stripe "github.com/stripe/stripe-go/v74"
	gomock "go.uber.org/mock/gomock"
)

// MockStripeEventGetter is a mock of StripeEventGetter interface.
type MockStripeEventGetter struct {
	ctrl     *gomock.Controller
	recorder *MockStripeEventGetterMockRecorder
	isgomock struct{}
}

// MockStripeEventGetterMockRecorder is the mock recorder for MockStripeEventGetter.
type MockStripeEventGetterMockRecorder struct {
	mock *MockStripeEventGetter
}

// NewMockStripeEventGetter creates a new mock instance.
func NewMockStripeEventGetter(ctrl *gomock.Controller) *MockStripeEventGetter {
	mock := &MockStripeEventGetter{ctrl: ctrl}
	mock.recorder = &MockStripeEventGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStripeEventGetter) EXPECT() *MockStripeEventGetterMockRecorder {
	return m.recorder
}

// GetEvent mocks base method.
func (m *MockStripeEventGetter) GetEvent(ctx context.Context, eventID string) (*stripe.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvent", ctx, eventID)
	ret0, _ := ret[0].(*stripe.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvent indicates an expected call of GetEvent.
func (mr *MockStripeEventGetterMockRecorder) GetEvent(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvent", reflect.TypeOf((*MockStripeEventGetter)(nil).GetEvent), ctx, eventID)
}
