// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/payments (interfaces: StripeIntentCreator)
//
// Generated by this command:
//
//	mockgen -destination ./mock/stripe_intent_creator.go -package mock . StripeIntentCreator
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	stripe "github.com/stripe/stripe-go/v74"
	gomock "go.uber.org/mock/gomock"
)

// MockStripeIntentCreator is a mock of StripeIntentCreator interface.
type MockStripeIntentCreator struct {
	ctrl     *gomock.Controller
	recorder *MockStripeIntentCreatorMockRecorder
	isgomock struct{}
}

// MockStripeIntentCreatorMockRecorder is the mock recorder for MockStripeIntentCreator.
type MockStripeIntentCreatorMockRecorder struct {
	mock *MockStripeIntentCreator
}

// NewMockStripeIntentCreator creates a new mock instance.
func NewMockStripeIntentCreator(ctrl *gomock.Controller) *MockStripeIntentCreator {
	mock := &MockStripeIntentCreator{ctrl: ctrl}
	mock.recorder = &MockStripeIntentCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStripeIntentCreator) EXPECT() *MockStripeIntentCreatorMockRecorder {
	return m.recorder
}

// CreateIntent mocks base method.
func (m *MockStripeIntentCreator) CreateIntent(ctx context.Context, productID string, amount uint64) (*stripe.CheckoutSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIntent", ctx, productID, amount)
	ret0, _ := ret[0].(*stripe.CheckoutSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIntent indicates an expected call of CreateIntent.
func (mr *MockStripeIntentCreatorMockRecorder) CreateIntent(ctx, productID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIntent", reflect.TypeOf((*MockStripeIntentCreator)(nil).CreateIntent), ctx, productID, amount)
}
