// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/frontend/findmatch/validators (interfaces: GameModeStatusChecker)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockGameModeStatusChecker is a mock of GameModeStatusChecker interface.
type MockGameModeStatusChecker struct {
	ctrl     *gomock.Controller
	recorder *MockGameModeStatusCheckerMockRecorder
}

// MockGameModeStatusCheckerMockRecorder is the mock recorder for MockGameModeStatusChecker.
type MockGameModeStatusCheckerMockRecorder struct {
	mock *MockGameModeStatusChecker
}

// NewMockGameModeStatusChecker creates a new mock instance.
func NewMockGameModeStatusChecker(ctrl *gomock.Controller) *MockGameModeStatusChecker {
	mock := &MockGameModeStatusChecker{ctrl: ctrl}
	mock.recorder = &MockGameModeStatusCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameModeStatusChecker) EXPECT() *MockGameModeStatusCheckerMockRecorder {
	return m.recorder
}

// IsEnabled mocks base method.
func (m *MockGameModeStatusChecker) IsEnabled(arg0 context.Context, arg1 proto.GameMode) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEnabled", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsEnabled indicates an expected call of IsEnabled.
func (mr *MockGameModeStatusCheckerMockRecorder) IsEnabled(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEnabled", reflect.TypeOf((*MockGameModeStatusChecker)(nil).IsEnabled), arg0, arg1)
}
