// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/frontend/findmatch/validators (interfaces: MatchInProgressChecker)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	messages "github.com/horizon-games/OpenSky/matchmaker/lib/messages"
	gomock "go.uber.org/mock/gomock"
)

// MockMatchInProgressChecker is a mock of MatchInProgressChecker interface.
type MockMatchInProgressChecker struct {
	ctrl     *gomock.Controller
	recorder *MockMatchInProgressCheckerMockRecorder
}

// MockMatchInProgressCheckerMockRecorder is the mock recorder for MockMatchInProgressChecker.
type MockMatchInProgressCheckerMockRecorder struct {
	mock *MockMatchInProgressChecker
}

// NewMockMatchInProgressChecker creates a new mock instance.
func NewMockMatchInProgressChecker(ctrl *gomock.Controller) *MockMatchInProgressChecker {
	mock := &MockMatchInProgressChecker{ctrl: ctrl}
	mock.recorder = &MockMatchInProgressCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchInProgressChecker) EXPECT() *MockMatchInProgressCheckerMockRecorder {
	return m.recorder
}

// GetMatch mocks base method.
func (m *MockMatchInProgressChecker) GetMatch(arg0 proto.Hash) (*messages.InProgressMatchInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMatch", arg0)
	ret0, _ := ret[0].(*messages.InProgressMatchInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMatch indicates an expected call of GetMatch.
func (mr *MockMatchInProgressCheckerMockRecorder) GetMatch(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMatch", reflect.TypeOf((*MockMatchInProgressChecker)(nil).GetMatch), arg0)
}
