// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/frontend/findmatch/validators (interfaces: PenaltyGetter)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	time "time"

	player "github.com/horizon-games/OpenSky/matchmaker/lib/player"
	gomock "go.uber.org/mock/gomock"
)

// MockPenaltyGetter is a mock of PenaltyGetter interface.
type MockPenaltyGetter struct {
	ctrl     *gomock.Controller
	recorder *MockPenaltyGetterMockRecorder
}

// MockPenaltyGetterMockRecorder is the mock recorder for MockPenaltyGetter.
type MockPenaltyGetterMockRecorder struct {
	mock *MockPenaltyGetter
}

// NewMockPenaltyGetter creates a new mock instance.
func NewMockPenaltyGetter(ctrl *gomock.Controller) *MockPenaltyGetter {
	mock := &MockPenaltyGetter{ctrl: ctrl}
	mock.recorder = &MockPenaltyGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPenaltyGetter) EXPECT() *MockPenaltyGetterMockRecorder {
	return m.recorder
}

// GetPenalty mocks base method.
func (m *MockPenaltyGetter) GetPenalty(arg0 *player.Player) (time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPenalty", arg0)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPenalty indicates an expected call of GetPenalty.
func (mr *MockPenaltyGetterMockRecorder) GetPenalty(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPenalty", reflect.TypeOf((*MockPenaltyGetter)(nil).GetPenalty), arg0)
}
