// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/frontend/findmatch/validators (interfaces: PendingMatchChecker)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockPendingMatchChecker is a mock of PendingMatchChecker interface.
type MockPendingMatchChecker struct {
	ctrl     *gomock.Controller
	recorder *MockPendingMatchCheckerMockRecorder
}

// MockPendingMatchCheckerMockRecorder is the mock recorder for MockPendingMatchChecker.
type MockPendingMatchCheckerMockRecorder struct {
	mock *MockPendingMatchChecker
}

// NewMockPendingMatchChecker creates a new mock instance.
func NewMockPendingMatchChecker(ctrl *gomock.Controller) *MockPendingMatchChecker {
	mock := &MockPendingMatchChecker{ctrl: ctrl}
	mock.recorder = &MockPendingMatchCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPendingMatchChecker) EXPECT() *MockPendingMatchCheckerMockRecorder {
	return m.recorder
}

// HasMatchProposal mocks base method.
func (m *MockPendingMatchChecker) HasMatchProposal(arg0 proto.Hash) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasMatchProposal", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasMatchProposal indicates an expected call of HasMatchProposal.
func (mr *MockPendingMatchCheckerMockRecorder) HasMatchProposal(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasMatchProposal", reflect.TypeOf((*MockPendingMatchChecker)(nil).HasMatchProposal), arg0)
}
