// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/frontend/findmatch/validators (interfaces: SkyWeaverAPI)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockSkyWeaverAPI is a mock of SkyWeaverAPI interface.
type MockSkyWeaverAPI struct {
	ctrl     *gomock.Controller
	recorder *MockSkyWeaverAPIMockRecorder
}

// MockSkyWeaverAPIMockRecorder is the mock recorder for MockSkyWeaverAPI.
type MockSkyWeaverAPIMockRecorder struct {
	mock *MockSkyWeaverAPI
}

// NewMockSkyWeaverAPI creates a new mock instance.
func NewMockSkyWeaverAPI(ctrl *gomock.Controller) *MockSkyWeaverAPI {
	mock := &MockSkyWeaverAPI{ctrl: ctrl}
	mock.recorder = &MockSkyWeaverAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSkyWeaverAPI) EXPECT() *MockSkyWeaverAPIMockRecorder {
	return m.recorder
}

// CheckDeck mocks base method.
func (m *MockSkyWeaverAPI) CheckDeck(arg0 context.Context, arg1 proto.Hash, arg2 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckDeck", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckDeck indicates an expected call of CheckDeck.
func (mr *MockSkyWeaverAPIMockRecorder) CheckDeck(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckDeck", reflect.TypeOf((*MockSkyWeaverAPI)(nil).CheckDeck), arg0, arg1, arg2)
}
