// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker/matching/matchfuncs/matchquality (interfaces: FactorCalculator)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	matchquality "github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker/matching/matchers/matchquality"
	player "github.com/horizon-games/OpenSky/matchmaker/lib/player"
	gomock "go.uber.org/mock/gomock"
)

// MockFactorCalculator is a mock of FactorCalculator interface.
type MockFactorCalculator struct {
	ctrl     *gomock.Controller
	recorder *MockFactorCalculatorMockRecorder
}

// MockFactorCalculatorMockRecorder is the mock recorder for MockFactorCalculator.
type MockFactorCalculatorMockRecorder struct {
	mock *MockFactorCalculator
}

// NewMockFactorCalculator creates a new mock instance.
func NewMockFactorCalculator(ctrl *gomock.Controller) *MockFactorCalculator {
	mock := &MockFactorCalculator{ctrl: ctrl}
	mock.recorder = &MockFactorCalculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactorCalculator) EXPECT() *MockFactorCalculatorMockRecorder {
	return m.recorder
}

// Calculate mocks base method.
func (m *MockFactorCalculator) Calculate(arg0, arg1 *player.Player) matchquality.Factor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Calculate", arg0, arg1)
	ret0, _ := ret[0].(matchquality.Factor)
	return ret0
}

// Calculate indicates an expected call of Calculate.
func (mr *MockFactorCalculatorMockRecorder) Calculate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Calculate", reflect.TypeOf((*MockFactorCalculator)(nil).Calculate), arg0, arg1)
}
