// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/matchmaker/matching/matchfuncs/matchquality (interfaces: QualityCalculator)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	player "github.com/horizon-games/OpenSky/matchmaker/lib/player"
	gomock "go.uber.org/mock/gomock"
)

// MockQualityCalculator is a mock of QualityCalculator interface.
type MockQualityCalculator struct {
	ctrl     *gomock.Controller
	recorder *MockQualityCalculatorMockRecorder
}

// MockQualityCalculatorMockRecorder is the mock recorder for MockQualityCalculator.
type MockQualityCalculatorMockRecorder struct {
	mock *MockQualityCalculator
}

// NewMockQualityCalculator creates a new mock instance.
func NewMockQualityCalculator(ctrl *gomock.Controller) *MockQualityCalculator {
	mock := &MockQualityCalculator{ctrl: ctrl}
	mock.recorder = &MockQualityCalculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQualityCalculator) EXPECT() *MockQualityCalculatorMockRecorder {
	return m.recorder
}

// Calculate mocks base method.
func (m *MockQualityCalculator) Calculate(arg0, arg1 *player.Player) float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Calculate", arg0, arg1)
	ret0, _ := ret[0].(float64)
	return ret0
}

// Calculate indicates an expected call of Calculate.
func (mr *MockQualityCalculatorMockRecorder) Calculate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Calculate", reflect.TypeOf((*MockQualityCalculator)(nil).Calculate), arg0, arg1)
}
