// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/frontend/declinematch (interfaces: MatchDecliner)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockMatchDecliner is a mock of MatchDecliner interface.
type MockMatchDecliner struct {
	ctrl     *gomock.Controller
	recorder *MockMatchDeclinerMockRecorder
}

// MockMatchDeclinerMockRecorder is the mock recorder for MockMatchDecliner.
type MockMatchDeclinerMockRecorder struct {
	mock *MockMatchDecliner
}

// NewMockMatchDecliner creates a new mock instance.
func NewMockMatchDecliner(ctrl *gomock.Controller) *MockMatchDecliner {
	mock := &MockMatchDecliner{ctrl: ctrl}
	mock.recorder = &MockMatchDeclinerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchDecliner) EXPECT() *MockMatchDeclinerMockRecorder {
	return m.recorder
}

// DeclineMatch mocks base method.
func (m *MockMatchDecliner) DeclineMatch(arg0 context.Context, arg1 proto.Hash) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeclineMatch", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeclineMatch indicates an expected call of DeclineMatch.
func (mr *MockMatchDeclinerMockRecorder) DeclineMatch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeclineMatch", reflect.TypeOf((*MockMatchDecliner)(nil).DeclineMatch), arg0, arg1)
}
