export enum DECK_SORTING_OPTIONS {
  LAST_MODIFIED_DESCENDING = 'LAST_MODIFIED_DESCENDING',
  ALPHABETICAL_ASCENDING = 'ALPHABETICAL_ASCENDING',
  ALPHABETICAL_DESCENDING = 'ALPHABETICAL_DESCENDING'
}
