/* eslint-disable */
// opensky-analytics v0.0.1 488e06c4857e980c70ec8180ffc9a8403e95a57f
// --
// This file has been generated by https://github.com/webrpc/webrpc using gen/typescript
// Do not edit by hand. Update your webrpc schema and re-generate.

// WebRPC description and code-gen version
export const WebRPCVersion = "v1"

// Schema version of your RIDL schema
export const WebRPCSchemaVersion = "v0.0.1"

// Schema hash generated from your RIDL schema
export const WebRPCSchemaHash = "488e06c4857e980c70ec8180ffc9a8403e95a57f"


//
// Types
//
export enum EventType {
  INIT = 'INIT',
  VIEW = 'VIEW',
  ACCOUNT_CREATED = 'ACCOUNT_CREATED',
  ACCOUNT_LEVELED_UP = 'ACCOUNT_LEVELED_UP',
  ACCOUNT_STATUS_UPDATED = 'ACCOUNT_STATUS_UPDATED',
  CONQUEST_TICKET_MINTED = 'CONQUEST_TICKET_MINTED',
  GOT_CONQUEST_POINTS = 'GOT_CONQUEST_POINTS',
  GOT_TREASURE_REWARD = 'GOT_TREASURE_REWARD',
  MATCH_ENDED = 'MATCH_ENDED',
  MATCH_GOT_REWARD = 'MATCH_GOT_REWARD',
  MATCH_STARTED = 'MATCH_STARTED',
  QUEST_COMPLETED = 'QUEST_COMPLETED',
  QUEST_COMPLETION_CLAIMED = 'QUEST_COMPLETION_CLAIMED',
  QUEST_REROLLED = 'QUEST_REROLLED',
  SKYPASS_PURCHASED = 'SKYPASS_PURCHASED',
  SKYPASS_REWARD_CLAIMED = 'SKYPASS_REWARD_CLAIMED',
  TUTORIAL_ENDED = 'TUTORIAL_ENDED',
  TUTORIAL_STATUS_UPDATED = 'TUTORIAL_STATUS_UPDATED',
  CLIENT_ATTEMPTING_NEW_ACCOUNT = 'CLIENT_ATTEMPTING_NEW_ACCOUNT'
}

  
  
export interface WebRPCError extends Error {
  code: string
  msg: string
	status: number
}

const createHTTPRequest = (body: object = {}, headers: object = {}): object => {
  return {
    method: 'POST',
    headers: { ...headers, 'Content-Type': 'application/json' },
    body: JSON.stringify(body || {})
  }
}

const buildResponse = (res: Response): Promise<any> => {
  return res.text().then(text => {
    let data
    try {
      data = JSON.parse(text)
    } catch(err) {
      throw { code: 'unknown', msg: `expecting JSON, got: ${text}`, status: res.status } as WebRPCError
    }
    if (!res.ok) {
      throw data // webrpc error response
    }
    return data
  })
}

export type Fetch = (input: RequestInfo, init?: RequestInit) => Promise<Response>
