// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/jobqueue (interfaces: ConquestV2PoolManager)
//
// Generated by this command:
//
//	mockgen -destination ./mock/conquest_v2_pool_manager.go -package mock . ConquestV2PoolManager
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockConquestV2PoolManager is a mock of ConquestV2PoolManager interface.
type MockConquestV2PoolManager struct {
	ctrl     *gomock.Controller
	recorder *MockConquestV2PoolManagerMockRecorder
	isgomock struct{}
}

// MockConquestV2PoolManagerMockRecorder is the mock recorder for MockConquestV2PoolManager.
type MockConquestV2PoolManagerMockRecorder struct {
	mock *MockConquestV2PoolManager
}

// NewMockConquestV2PoolManager creates a new mock instance.
func NewMockConquestV2PoolManager(ctrl *gomock.Controller) *MockConquestV2PoolManager {
	mock := &MockConquestV2PoolManager{ctrl: ctrl}
	mock.recorder = &MockConquestV2PoolManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConquestV2PoolManager) EXPECT() *MockConquestV2PoolManagerMockRecorder {
	return m.recorder
}

// GetConfig mocks base method.
func (m *MockConquestV2PoolManager) GetConfig(arg0 context.Context) (*proto.ConquestV2PoolConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", arg0)
	ret0, _ := ret[0].(*proto.ConquestV2PoolConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockConquestV2PoolManagerMockRecorder) GetConfig(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockConquestV2PoolManager)(nil).GetConfig), arg0)
}

// GetPool mocks base method.
func (m *MockConquestV2PoolManager) GetPool(arg0 context.Context) (*proto.ConquestV2Pool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPool", arg0)
	ret0, _ := ret[0].(*proto.ConquestV2Pool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPool indicates an expected call of GetPool.
func (mr *MockConquestV2PoolManagerMockRecorder) GetPool(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPool", reflect.TypeOf((*MockConquestV2PoolManager)(nil).GetPool), arg0)
}

// RecalculatePool mocks base method.
func (m *MockConquestV2PoolManager) RecalculatePool(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecalculatePool", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecalculatePool indicates an expected call of RecalculatePool.
func (mr *MockConquestV2PoolManagerMockRecorder) RecalculatePool(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecalculatePool", reflect.TypeOf((*MockConquestV2PoolManager)(nil).RecalculatePool), arg0)
}
