// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/jobqueue (interfaces: ConquestV2AnalyticsTracker)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	data "github.com/horizon-games/OpenSky/api/data"
	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockConquestV2AnalyticsTracker is a mock of ConquestV2AnalyticsTracker interface.
type MockConquestV2AnalyticsTracker struct {
	ctrl     *gomock.Controller
	recorder *MockConquestV2AnalyticsTrackerMockRecorder
}

// MockConquestV2AnalyticsTrackerMockRecorder is the mock recorder for MockConquestV2AnalyticsTracker.
type MockConquestV2AnalyticsTrackerMockRecorder struct {
	mock *MockConquestV2AnalyticsTracker
}

// NewMockConquestV2AnalyticsTracker creates a new mock instance.
func NewMockConquestV2AnalyticsTracker(ctrl *gomock.Controller) *MockConquestV2AnalyticsTracker {
	mock := &MockConquestV2AnalyticsTracker{ctrl: ctrl}
	mock.recorder = &MockConquestV2AnalyticsTrackerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConquestV2AnalyticsTracker) EXPECT() *MockConquestV2AnalyticsTrackerMockRecorder {
	return m.recorder
}

// TrackTreasureRewards mocks base method.
func (m *MockConquestV2AnalyticsTracker) TrackTreasureRewards(arg0 context.Context, arg1 proto.AccountID, arg2 *data.ConquestV2TreasureProgress, arg3 float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackTreasureRewards", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackTreasureRewards indicates an expected call of TrackTreasureRewards.
func (mr *MockConquestV2AnalyticsTrackerMockRecorder) TrackTreasureRewards(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackTreasureRewards", reflect.TypeOf((*MockConquestV2AnalyticsTracker)(nil).TrackTreasureRewards), arg0, arg1, arg2, arg3)
}
