// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/jobqueue (interfaces: DeckRankUpdater)
//
// Generated by this command:
//
//	mockgen -destination ./mock/deck_rank_updater.go -package mock . DeckRankUpdater
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	data "github.com/horizon-games/OpenSky/api/data"
	db "github.com/upper/db/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockDeckRankUpdater is a mock of DeckRankUpdater interface.
type MockDeckRankUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockDeckRankUpdaterMockRecorder
	isgomock struct{}
}

// MockDeckRankUpdaterMockRecorder is the mock recorder for MockDeckRankUpdater.
type MockDeckRankUpdaterMockRecorder struct {
	mock *MockDeckRankUpdater
}

// NewMockDeckRankUpdater creates a new mock instance.
func NewMockDeckRankUpdater(ctrl *gomock.Controller) *MockDeckRankUpdater {
	mock := &MockDeckRankUpdater{ctrl: ctrl}
	mock.recorder = &MockDeckRankUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeckRankUpdater) EXPECT() *MockDeckRankUpdaterMockRecorder {
	return m.recorder
}

// UpdateFromMatch mocks base method.
func (m *MockDeckRankUpdater) UpdateFromMatch(sess db.Session, match *data.Match, season uint16) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFromMatch", sess, match, season)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFromMatch indicates an expected call of UpdateFromMatch.
func (mr *MockDeckRankUpdaterMockRecorder) UpdateFromMatch(sess, match, season any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFromMatch", reflect.TypeOf((*MockDeckRankUpdater)(nil).UpdateFromMatch), sess, match, season)
}
