// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/jobqueue (interfaces: MetricsCollector)
//
// Generated by this command:
//
//	mockgen -destination ./mock/metrics_collector.go -package mock . MetricsCollector
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	time "time"

	data "github.com/horizon-games/OpenSky/api/data"
	jobqueue "github.com/horizon-games/OpenSky/api/lib/jobqueue"
	gomock "go.uber.org/mock/gomock"
)

// MockMetricsCollector is a mock of MetricsCollector interface.
type MockMetricsCollector struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsCollectorMockRecorder
	isgomock struct{}
}

// MockMetricsCollectorMockRecorder is the mock recorder for MockMetricsCollector.
type MockMetricsCollectorMockRecorder struct {
	mock *MockMetricsCollector
}

// NewMockMetricsCollector creates a new mock instance.
func NewMockMetricsCollector(ctrl *gomock.Controller) *MockMetricsCollector {
	mock := &MockMetricsCollector{ctrl: ctrl}
	mock.recorder = &MockMetricsCollectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsCollector) EXPECT() *MockMetricsCollectorMockRecorder {
	return m.recorder
}

// TrackLastBlockNumber mocks base method.
func (m *MockMetricsCollector) TrackLastBlockNumber(process string, blockNumber uint64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackLastBlockNumber", process, blockNumber)
}

// TrackLastBlockNumber indicates an expected call of TrackLastBlockNumber.
func (mr *MockMetricsCollectorMockRecorder) TrackLastBlockNumber(process, blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackLastBlockNumber", reflect.TypeOf((*MockMetricsCollector)(nil).TrackLastBlockNumber), process, blockNumber)
}

// TrackTaskDuration mocks base method.
func (m *MockMetricsCollector) TrackTaskDuration(runner jobqueue.Runner, task *data.Task) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackTaskDuration", runner, task)
}

// TrackTaskDuration indicates an expected call of TrackTaskDuration.
func (mr *MockMetricsCollectorMockRecorder) TrackTaskDuration(runner, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackTaskDuration", reflect.TypeOf((*MockMetricsCollector)(nil).TrackTaskDuration), runner, task)
}

// TrackTasksAttempt mocks base method.
func (m *MockMetricsCollector) TrackTasksAttempt(runner jobqueue.Runner, tasks []*data.Task) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackTasksAttempt", runner, tasks)
}

// TrackTasksAttempt indicates an expected call of TrackTasksAttempt.
func (mr *MockMetricsCollectorMockRecorder) TrackTasksAttempt(runner, tasks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackTasksAttempt", reflect.TypeOf((*MockMetricsCollector)(nil).TrackTasksAttempt), runner, tasks)
}

// TrackTxMintingDuration mocks base method.
func (m *MockMetricsCollector) TrackTxMintingDuration(status string, submittedAt time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TrackTxMintingDuration", status, submittedAt)
}

// TrackTxMintingDuration indicates an expected call of TrackTxMintingDuration.
func (mr *MockMetricsCollectorMockRecorder) TrackTxMintingDuration(status, submittedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackTxMintingDuration", reflect.TypeOf((*MockMetricsCollector)(nil).TrackTxMintingDuration), status, submittedAt)
}
