// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/jobqueue (interfaces: PaymentEventHandler)
//
// Generated by this command:
//
//	mockgen -destination ./mock/payment_event_handler.go -package mock . PaymentEventHandler
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	contracts "github.com/horizon-games/OpenSky/api/lib/contracts"
	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockPaymentEventHandler is a mock of PaymentEventHandler interface.
type MockPaymentEventHandler struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentEventHandlerMockRecorder
	isgomock struct{}
}

// MockPaymentEventHandlerMockRecorder is the mock recorder for MockPaymentEventHandler.
type MockPaymentEventHandlerMockRecorder struct {
	mock *MockPaymentEventHandler
}

// NewMockPaymentEventHandler creates a new mock instance.
func NewMockPaymentEventHandler(ctrl *gomock.Controller) *MockPaymentEventHandler {
	mock := &MockPaymentEventHandler{ctrl: ctrl}
	mock.recorder = &MockPaymentEventHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentEventHandler) EXPECT() *MockPaymentEventHandlerMockRecorder {
	return m.recorder
}

// HandleOnChainItemBurnEvent mocks base method.
func (m *MockPaymentEventHandler) HandleOnChainItemBurnEvent(ctx context.Context, txHash proto.Hash, transferBatchEvent *contracts.ERC1155TransferBatchEvent, itemBurnEvent *contracts.PaymentProxyItemBurnEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleOnChainItemBurnEvent", ctx, txHash, transferBatchEvent, itemBurnEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleOnChainItemBurnEvent indicates an expected call of HandleOnChainItemBurnEvent.
func (mr *MockPaymentEventHandlerMockRecorder) HandleOnChainItemBurnEvent(ctx, txHash, transferBatchEvent, itemBurnEvent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleOnChainItemBurnEvent", reflect.TypeOf((*MockPaymentEventHandler)(nil).HandleOnChainItemBurnEvent), ctx, txHash, transferBatchEvent, itemBurnEvent)
}

// HandleOnChainItemPurchaseEvent mocks base method.
func (m *MockPaymentEventHandler) HandleOnChainItemPurchaseEvent(ctx context.Context, txHash proto.Hash, transferEvent *contracts.ERC20TransferEvent, itemPurchaseEvent *contracts.PaymentProxyItemPurchaseEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleOnChainItemPurchaseEvent", ctx, txHash, transferEvent, itemPurchaseEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleOnChainItemPurchaseEvent indicates an expected call of HandleOnChainItemPurchaseEvent.
func (mr *MockPaymentEventHandlerMockRecorder) HandleOnChainItemPurchaseEvent(ctx, txHash, transferEvent, itemPurchaseEvent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleOnChainItemPurchaseEvent", reflect.TypeOf((*MockPaymentEventHandler)(nil).HandleOnChainItemPurchaseEvent), ctx, txHash, transferEvent, itemPurchaseEvent)
}

// HandleStripeEvent mocks base method.
func (m *MockPaymentEventHandler) HandleStripeEvent(ctx context.Context, eventID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleStripeEvent", ctx, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleStripeEvent indicates an expected call of HandleStripeEvent.
func (mr *MockPaymentEventHandlerMockRecorder) HandleStripeEvent(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleStripeEvent", reflect.TypeOf((*MockPaymentEventHandler)(nil).HandleStripeEvent), ctx, eventID)
}
