// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/jobqueue (interfaces: PushNotifier)
//
// Generated by this command:
//
//	mockgen -destination ./mock/push_notifier.go -package mock . PushNotifier
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockPushNotifier is a mock of PushNotifier interface.
type MockPushNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockPushNotifierMockRecorder
	isgomock struct{}
}

// MockPushNotifierMockRecorder is the mock recorder for MockPushNotifier.
type MockPushNotifierMockRecorder struct {
	mock *MockPushNotifier
}

// NewMockPushNotifier creates a new mock instance.
func NewMockPushNotifier(ctrl *gomock.Controller) *MockPushNotifier {
	mock := &MockPushNotifier{ctrl: ctrl}
	mock.recorder = &MockPushNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPushNotifier) EXPECT() *MockPushNotifierMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockPushNotifier) Send(arg0 context.Context, arg1 []proto.AccountID, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockPushNotifierMockRecorder) Send(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockPushNotifier)(nil).Send), arg0, arg1, arg2)
}
