// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/jobqueue (interfaces: Runner)
//
// Generated by this command:
//
//	mockgen -destination ./mock/runner.go -package mock . Runner
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	data "github.com/horizon-games/OpenSky/api/data"
	db "github.com/upper/db/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockRunner is a mock of Runner interface.
type MockRunner struct {
	ctrl     *gomock.Controller
	recorder *MockRunnerMockRecorder
	isgomock struct{}
}

// MockRunnerMockRecorder is the mock recorder for MockRunner.
type MockRunnerMockRecorder struct {
	mock *MockRunner
}

// NewMockRunner creates a new mock instance.
func NewMockRunner(ctrl *gomock.Controller) *MockRunner {
	mock := &MockRunner{ctrl: ctrl}
	mock.recorder = &MockRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunner) EXPECT() *MockRunnerMockRecorder {
	return m.recorder
}

// MaxBatchSize mocks base method.
func (m *MockRunner) MaxBatchSize() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxBatchSize")
	ret0, _ := ret[0].(int)
	return ret0
}

// MaxBatchSize indicates an expected call of MaxBatchSize.
func (mr *MockRunnerMockRecorder) MaxBatchSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxBatchSize", reflect.TypeOf((*MockRunner)(nil).MaxBatchSize))
}

// Queues mocks base method.
func (m *MockRunner) Queues() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Queues")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Queues indicates an expected call of Queues.
func (mr *MockRunnerMockRecorder) Queues() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Queues", reflect.TypeOf((*MockRunner)(nil).Queues))
}

// RunTasks mocks base method.
func (m *MockRunner) RunTasks(arg0 context.Context, arg1 db.Session, arg2 []*data.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunTasks", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunTasks indicates an expected call of RunTasks.
func (mr *MockRunnerMockRecorder) RunTasks(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunTasks", reflect.TypeOf((*MockRunner)(nil).RunTasks), arg0, arg1, arg2)
}

// Tick mocks base method.
func (m *MockRunner) Tick() <-chan time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tick")
	ret0, _ := ret[0].(<-chan time.Time)
	return ret0
}

// Tick indicates an expected call of Tick.
func (mr *MockRunnerMockRecorder) Tick() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tick", reflect.TypeOf((*MockRunner)(nil).Tick))
}

// WorkGroup mocks base method.
func (m *MockRunner) WorkGroup() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkGroup")
	ret0, _ := ret[0].(string)
	return ret0
}

// WorkGroup indicates an expected call of WorkGroup.
func (mr *MockRunnerMockRecorder) WorkGroup() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkGroup", reflect.TypeOf((*MockRunner)(nil).WorkGroup))
}
