// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/jobqueue (interfaces: SkypassRewardLister)
//
// Generated by this command:
//
//	mockgen -destination ./mock/skypass_reward_lister.go -package mock . SkypassRewardLister
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockSkypassRewardLister is a mock of SkypassRewardLister interface.
type MockSkypassRewardLister struct {
	ctrl     *gomock.Controller
	recorder *MockSkypassRewardListerMockRecorder
	isgomock struct{}
}

// MockSkypassRewardListerMockRecorder is the mock recorder for MockSkypassRewardLister.
type MockSkypassRewardListerMockRecorder struct {
	mock *MockSkypassRewardLister
}

// NewMockSkypassRewardLister creates a new mock instance.
func NewMockSkypassRewardLister(ctrl *gomock.Controller) *MockSkypassRewardLister {
	mock := &MockSkypassRewardLister{ctrl: ctrl}
	mock.recorder = &MockSkypassRewardListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSkypassRewardLister) EXPECT() *MockSkypassRewardListerMockRecorder {
	return m.recorder
}

// ListBySeason mocks base method.
func (m *MockSkypassRewardLister) ListBySeason(arg0 context.Context, arg1 proto.AccountID, arg2 uint16) ([]*proto.SkypassLevel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBySeason", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*proto.SkypassLevel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBySeason indicates an expected call of ListBySeason.
func (mr *MockSkypassRewardListerMockRecorder) ListBySeason(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBySeason", reflect.TypeOf((*MockSkypassRewardLister)(nil).ListBySeason), arg0, arg1, arg2)
}
