// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/gameservers (interfaces: Manager)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gameservers "github.com/horizon-games/OpenSky/matchmaker/lib/gameservers"
	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockManager) Find(arg0 context.Context, arg1 string) (*gameservers.GameServerInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1)
	ret0, _ := ret[0].(*gameservers.GameServerInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockManagerMockRecorder) Find(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockManager)(nil).Find), arg0, arg1)
}

// InitiateMatch mocks base method.
func (m *MockManager) InitiateMatch(arg0 context.Context, arg1 *gameservers.GameServerInfo, arg2 gameservers.MatchRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiateMatch", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitiateMatch indicates an expected call of InitiateMatch.
func (mr *MockManagerMockRecorder) InitiateMatch(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiateMatch", reflect.TypeOf((*MockManager)(nil).InitiateMatch), arg0, arg1, arg2)
}
