// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/accounts (interfaces: ContractUSDC)
//
// Generated by this command:
//
//	mockgen -destination ./mock/contract_usdc.go -package mock . ContractUSDC
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	big "math/big"
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockContractUSDC is a mock of ContractUSDC interface.
type MockContractUSDC struct {
	ctrl     *gomock.Controller
	recorder *MockContractUSDCMockRecorder
	isgomock struct{}
}

// MockContractUSDCMockRecorder is the mock recorder for MockContractUSDC.
type MockContractUSDCMockRecorder struct {
	mock *MockContractUSDC
}

// NewMockContractUSDC creates a new mock instance.
func NewMockContractUSDC(ctrl *gomock.Controller) *MockContractUSDC {
	mock := &MockContractUSDC{ctrl: ctrl}
	mock.recorder = &MockContractUSDCMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContractUSDC) EXPECT() *MockContractUSDCMockRecorder {
	return m.recorder
}

// CallBalanceOf mocks base method.
func (m *MockContractUSDC) CallBalanceOf(ctx context.Context, owner proto.Hash) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CallBalanceOf", ctx, owner)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CallBalanceOf indicates an expected call of CallBalanceOf.
func (mr *MockContractUSDCMockRecorder) CallBalanceOf(ctx, owner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallBalanceOf", reflect.TypeOf((*MockContractUSDC)(nil).CallBalanceOf), ctx, owner)
}

// ComposeTransfer mocks base method.
func (m *MockContractUSDC) ComposeTransfer(to proto.Hash, value *big.Int) (*proto.OnChainTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComposeTransfer", to, value)
	ret0, _ := ret[0].(*proto.OnChainTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ComposeTransfer indicates an expected call of ComposeTransfer.
func (mr *MockContractUSDCMockRecorder) ComposeTransfer(to, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComposeTransfer", reflect.TypeOf((*MockContractUSDC)(nil).ComposeTransfer), to, value)
}
