// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/accounts (interfaces: ContractBalanceGetter)
//
// Generated by this command:
//
//	mockgen -destination ./mock/contract_balance_getter.go -package mock . ContractBalanceGetter
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	prototyp "github.com/0xsequence/go-sequence/lib/prototyp"
	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockContractBalanceGetter is a mock of ContractBalanceGetter interface.
type MockContractBalanceGetter struct {
	ctrl     *gomock.Controller
	recorder *MockContractBalanceGetterMockRecorder
	isgomock struct{}
}

// MockContractBalanceGetterMockRecorder is the mock recorder for MockContractBalanceGetter.
type MockContractBalanceGetterMockRecorder struct {
	mock *MockContractBalanceGetter
}

// NewMockContractBalanceGetter creates a new mock instance.
func NewMockContractBalanceGetter(ctrl *gomock.Controller) *MockContractBalanceGetter {
	mock := &MockContractBalanceGetter{ctrl: ctrl}
	mock.recorder = &MockContractBalanceGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContractBalanceGetter) EXPECT() *MockContractBalanceGetterMockRecorder {
	return m.recorder
}

// GetCurrencyBalance mocks base method.
func (m *MockContractBalanceGetter) GetCurrencyBalance(ctx context.Context, accountAddress proto.Hash) (prototyp.BigInt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrencyBalance", ctx, accountAddress)
	ret0, _ := ret[0].(prototyp.BigInt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrencyBalance indicates an expected call of GetCurrencyBalance.
func (mr *MockContractBalanceGetterMockRecorder) GetCurrencyBalance(ctx, accountAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrencyBalance", reflect.TypeOf((*MockContractBalanceGetter)(nil).GetCurrencyBalance), ctx, accountAddress)
}
