// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/api/lib/accounts (interfaces: NameGenerator)
//
// Generated by this command:
//
//	mockgen -destination ./mock/name_generator.go -package mock . NameGenerator
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	db "github.com/upper/db/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockNameGenerator is a mock of NameGenerator interface.
type MockNameGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockNameGeneratorMockRecorder
	isgomock struct{}
}

// MockNameGeneratorMockRecorder is the mock recorder for MockNameGenerator.
type MockNameGeneratorMockRecorder struct {
	mock *MockNameGenerator
}

// NewMockNameGenerator creates a new mock instance.
func NewMockNameGenerator(ctrl *gomock.Controller) *MockNameGenerator {
	mock := &MockNameGenerator{ctrl: ctrl}
	mock.recorder = &MockNameGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNameGenerator) EXPECT() *MockNameGeneratorMockRecorder {
	return m.recorder
}

// GenerateFromAddress mocks base method.
func (m *MockNameGenerator) GenerateFromAddress(arg0 db.Session, arg1 proto.Hash) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateFromAddress", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateFromAddress indicates an expected call of GenerateFromAddress.
func (mr *MockNameGeneratorMockRecorder) GenerateFromAddress(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateFromAddress", reflect.TypeOf((*MockNameGenerator)(nil).GenerateFromAddress), arg0, arg1)
}
