// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horizon-games/OpenSky/matchmaker/lib/frontend/acceptmatch (interfaces: MatchAccepter)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	proto "github.com/horizon-games/OpenSky/api/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockMatchAccepter is a mock of MatchAccepter interface.
type MockMatchAccepter struct {
	ctrl     *gomock.Controller
	recorder *MockMatchAccepterMockRecorder
}

// MockMatchAccepterMockRecorder is the mock recorder for MockMatchAccepter.
type MockMatchAccepterMockRecorder struct {
	mock *MockMatchAccepter
}

// NewMockMatchAccepter creates a new mock instance.
func NewMockMatchAccepter(ctrl *gomock.Controller) *MockMatchAccepter {
	mock := &MockMatchAccepter{ctrl: ctrl}
	mock.recorder = &MockMatchAccepterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchAccepter) EXPECT() *MockMatchAccepterMockRecorder {
	return m.recorder
}

// AcceptMatch mocks base method.
func (m *MockMatchAccepter) AcceptMatch(arg0 context.Context, arg1 proto.Hash) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptMatch", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcceptMatch indicates an expected call of AcceptMatch.
func (mr *MockMatchAccepterMockRecorder) AcceptMatch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptMatch", reflect.TypeOf((*MockMatchAccepter)(nil).AcceptMatch), arg0, arg1)
}
